- Documentation/INSTALL
> this is a test

- acknowledge_license_cert.html
This seems like a good idea, and I found this on the following OpenMRS website:
http://openmrs.org/license/
> Added a Healthcare Disclaimer to licensing

- interface/globals.php
- interface/super/edit_globals.php
- library/log.inc
- Added missing $ to variables
- Added array_key_exists to check arrays prior to attempted access
- Removed trailing whitespace
**REBASED** to current master branch
**Fixed Bug:** mentioned by @bradymiller [(#49)](https://github.com/openemr/openemr/pull/49#commitcomment-10448445) showing all settings instead of the user specific settings; due to inversion of boolean check
> General BUG cleanup to decrease time to save globals:

- interface/modules/zend_modules/module/Application/view/error/404.phtml
- interface/modules/zend_modules/module/Application/view/error/index.phtml
Adding missing views to zend system
*view for response 404
*view for display error
Without those files php throw fatal error when occur error in the development in the zend system.
> Adding missing files to zend system

- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- interface/themes/ajax_calendar.css
Fixed : http://oi64.tinypic.com/k3t00k.jpg
> fix calendar css

- interface/main/tabs/css/menu.css
- interface/main/tabs/css/tabs.css
- interface/main/tabs/templates/menu_template.php
- interface/main/tabs/templates/patient_data_template.php
- interface/main/tabs/templates/tabs_template.php
Lots of UI improvements for the menus on the tab interface.
> Improved menu styling

- library/appointments.inc.php
Hi Brady,
I added the days of week pattern interpretation to the appointment recurrence widget. Now if a 'days of week' recurrence exists, it will now show up in the widget.
> added days of week to reccurence widget

- interface/forms/newpatient/common.php
- interface/main/calendar/add_edit_event.php
- interface/new/new_comprehensive.php
- interface/patient_file/history/history_full.php
- interface/patient_file/summary/demographics_full.php
- interface/usergroup/facilities_add.php
- interface/usergroup/facility_admin.php
- interface/usergroup/user_admin.php
- interface/usergroup/usergroup_admin_add.php
- library/validation/validate_core.php
- library/validation/validation_script.js.php
Brady, we fixed the validation bugs according your comments, please let us know if its acceptable or there is something else to do
> Added flag for validation validate js

- interface/main/tabs/js/tabs_view_model.js
- interface/main/tabs/templates/patient_data_template.php
- interface/main/tabs/templates/user_data_template.php
- interface/themes/tabs_style_compact.css
- interface/themes/tabs_style_full.css
- version.php
Associated with following Issue:
https://github.com/openemr/openemr/issues/300
> make the current encounter on top an active link in the tab layout

- interface/usergroup/addrbook_edit.php
- sql/4_2_2-to-5_0_0_upgrade.sql
- sql/database.sql
Here we added an optional validation for the address book.
Currently the validation for this page (in the Page Validation list) is empty because there weren't validations previous to this addition.
Validation can be added by adding validation rules to the json in the Page Validation.
> Address Book validation

- interface/themes/tabs_style_full.css
Made changes in the css file
added --  overflow:auto;
> Tabs overflow #253.

- interface/main/tabs/js/user_data_view_model.js
- interface/main/tabs/main.php
- interface/main/tabs/templates/patient_data_template.php
- interface/themes/style_babyblu.css
- interface/themes/style_metal.css
- interface/themes/style_oemr.css
- interface/themes/style_purple.css
- interface/themes/style_sky_blue.css
- interface/themes/tabs_style_compact.css
- interface/themes/tabs_style_full.css
- version.php
The demo for this code is here:
http://www.open-emr.org/wiki/index.php/Development_Demo#192.168.1.131
Also integrated several tab layout changes by MDSupport from:
https://github.com/openemr/openemr/pull/277
Also updated legacy themes with Ray's buttons from the tan theme.
> Show message indicator and several tab layout changes

- contrib/forms/scanned_notes/new.php
- contrib/forms/specialist_notes/new.php
- contrib/forms/specialist_notes/view.php
- interface/main/calendar/find_patient.php
- interface/main/calendar/modules/PostCalendar/pntemplates/default/user/ajax_search.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/orig_default.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/global/fancy_navigation.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
- interface/patient_file/summary/demographics.php
- interface/patient_file/summary/summary_title.php
- interface/reports/appointments_report.php
- library/dialog.js
- version.php
This looks nice on the Frames layout.
However on the Tabs layout, it seems a bit too big now.
Thoughts?
> fixed size of the appt edit/add popup

- interface/globals.php
- interface/login/login.php
- interface/main/about_page.php
- interface/main/exceptions/invalid_email_exception.php
- interface/main/utils/http_response_helper.php
- interface/product_registration/exceptions/duplicate_registration_exception.php
- interface/product_registration/exceptions/generic_product_registration_exception.php
- interface/product_registration/product_registration_controller.js
- interface/product_registration/product_registration_controller.php
- interface/product_registration/product_registration_service.js
- interface/product_registration/product_registration_service.php
- interface/themes/login.css
- sql/4_2_2-to-5_0_0_upgrade.sql
- sql/database.sql
> [WIP] Product Registration

- interface/login/login.php
- interface/main/about_page.php
- interface/product_registration/product_registration_controller.js
> translations for product registration dialog close

- interface/globals.php
- library/classes/Controller.class.php
- library/clinical_rules.php
- library/options.inc.php
Below is a list of errors we were getting in our system and these are the changes that were made to clear up the error messages. 
[error_cleanup.txt](https://github.com/openemr/openemr/files/578080/error_cleanup.txt)
> PHP error fixes

- interface/usergroup/addrbook_edit.php
Hi ,
Wrapped divs around elements so that when using page validation in the address book validation error messages show up properly without messing up view
> fixed addrbook validation style

- interface/forms/note/print.php
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day_print/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day_print/outlook_ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month_print/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month_print/outlook_ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week_print/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week_print/outlook_ajax_template.html
Revision 2 of following PR:
https://github.com/openemr/openemr/pull/345
> Revision 2 of fixed bug: print window would open and close right away.

- interface/forms/note/print.php
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day_print/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day_print/outlook_ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month_print/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month_print/outlook_ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week_print/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week_print/outlook_ajax_template.html
> Revert to correct the author info of "Revision 2 of fixed bug: print window would open and close right away."

- interface/patient_file/history/history.php
- interface/patient_file/history/history_full.php
- interface/patient_file/reminder/clinical_reminders.php
- interface/patient_file/reminder/patient_reminders.php
- interface/patient_file/summary/pnotes_full.php
- interface/themes/rtl.css
Hi all, 
This is a minor fix to RTL. 
1. I added div id and class to some elements for better control.
2. On RTL mod pushes the patient name to the right in the screen 
PATIENT/CLIENT->some patient name->Edit (Clinical Reminders)
Thanks,
Eyal
> Changes for RTL and addind ids classes to divs

- library/ESign/Form/Signable.php
- sql/patch.sql
Ability to ESign encounters with physical exam form.
> ESign non-standard tables

- interface/main/onotes/office_comments.php
- interface/main/onotes/office_comments_full.php
> whitespace fixes

- library/options.inc.php
> whitespace cleanup

- interface/usergroup/facility_admin.php
When you add a  new facility/clinic, there is an address field, which is required to complete the form.
However, the field is not marked as required and there is no visible sign indicating that.
for the other required fields, there is an asterisks next to them to indicate this. those asterisks are hard-coded in the form.
this branch removes the asterisks from the form and instead mark required fields dynamically with JS depending if the field defined as required  on validation rules.
> removed asterisks on new facility form

- interface/patient_file/problem_encounter.php
- interface/patient_file/summary/add_edit_issue.php
- interface/patient_file/summary/stats_full.php
Hi.
Here have 2 fixes in patient issues.
1. Disabling a option of writing duplicate coding at interface/patient_file/summary/add_edit_issue.php.
Prevent this situation - 
2. Refresh issues screen after adding/updating encounter connection to get right result.
(This is the single solution that I've found.. I open to another suggestions.. )
Thanks 
Amiel
> Some minor fixes at patient issues

- interface/main/calendar/add_edit_event.php
This pull request comes to solve the following issue:
[issue 344 link](https://github.com/openemr/openemr/issues/344)
> major bug fix for recurrent event deletion when no provider chosen

- interface/super/edit_globals.php
Uses bootstrap's mark tag to highlight field(s) and related tab(s).
> Search for globals editing

- library/globals.inc.php
Changed word in text for an Appointment Display Style global option to mirror Add New Event / Edit Event window
> Changed word in text for an Appointment Display Style global option to mirror Add Event / Edit Event window

- interface/main/calendar/add_edit_event.php
Hi brady.
Here I send  fix in the validation of add event screen.
The problem occurs when multi provider is turned on.
Thank you!
amiel
> bug in multi select validation (missing event)

- interface/main/tabs/js/user_data_view_model.js
- interface/main/tabs/templates/patient_data_template.php
Adds direct access to patient finder from patient data block of tabs interface.
> Access patient list from patient data block

- interface/batchcom/batch_navigation.php
- interface/batchcom/batchcom.php
- interface/code_systems/dataloads_ajax.php
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/header.html
- interface/main/main_info.php
- interface/main/tabs/js/custom_bindings.js
- interface/patient_file/encounter/superbill_custom_full.php
- interface/patient_file/summary/labdata.php
Fixed Calendar tab label translation bug in tab layout along with a couple other tab label bugs
> Fixed Calendar tab label translation bug.

- interface/patient_file/report/custom_report.php
- interface/patient_file/report/patient_report.php
Hi,
I have added the functionality to view the recurring days on the report.
Can you please have a look at it.
thanks
Dror G.
> add new feature to the report - view recurring days.

- interface/patient_file/encounter/new_form.php
Fix for the following Issue:
https://github.com/openemr/openemr/issues/402
> forms menu link fix

- interface/patient_file/encounter/new_form.php
bug was reported in following issue:
https://github.com/openemr/openemr/issues/402
> fix Encounter Summary link in tab layout ui

- interface/themes/tabs_style_full.css
- version.php
1. Stop scroll of tabs 
2. Do not show bottom border of active tab
> full tab user interface fixes

- library/clinical_rules.php
Adds ability to use pattern searches in CDR target values.
> Wildcard matching in CDR

- interface/main/tabs/js/tabs_view_model.js
Brought in a function body that handles hover clicks.
> Force menu collapse after click

- interface/patient_file/summary/demographics.php
- library/appointments.inc.php
Hi.
Here I fixed  the widget that show recurrence events, now it shows the category name correctly instead the description field.    
Thanks.
Amiel
> Minor fix in widget that shows recurrences for appointments

- interface/forms/newpatient/report.php
Hi.
Here fix in the report of encounters. I take the currently facility name from 'facility' table according facility id.
Thanks.
Amiel
> Show currently facility name in the encounter report

- interface/reports/collections_report.php
Hi ,
I have created this feature to view only those patients who have debt.
can you please review this code.
thanks
Dror G.
> Create a feature for selecting only those who has debt

- interface/patient_file/summary/pnotes_full_add.php
a fix according to this
https://github.com/openemr/openemr/issues/366#issuecomment-272338606
> fix patient notes

- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
Hi all 
This small fix is just to translate the date in the calendar weekly display 
Thanks
> Fix calendar week translation

- interface/new/new_comprehensive.php
- interface/patient_file/summary/demographics_full.php
- interface/super/edit_layout.php
Hi,
I have added the abillity to differentiate between edit patient and new patient in the patient validation hook logic. can you please review it.
thanks
Dror G.
> addon to zend patient validation hook :

- interface/main/messages/messages.php
Hi,
Small translation fixes. While I was at it, updated the other escaping methods in the block to the new short methods.
thanks,
shachar
> translation fixes

- interface/main/left_nav.php
- library/globals.inc.php
Hi,
Here we added more globals to add more control on what the payments tab in left nav shows.
> left nav globals

- sql/5_0_0-to-5_0_1_upgrade.sql
- sql/database.sql
Added timestamp column to list options with default current datetime as default value.
We need to track the changes by timedate
> Added date time to list_options for modification control

- interface/product_registration/product_registration_controller.js
Addresses https://github.com/openemr/openemr/issues/461
Sorry about the bug!
> "No thanks" registration button bug fix

- interface/logview/logview.php
- interface/reports/amc_tracking.php
- interface/reports/appointments_report.php
- interface/reports/appt_encounter_report.php
- interface/reports/cdr_log.php
- interface/reports/clinical_reports.php
- interface/reports/cqm.php
- interface/reports/custom_report_range.php
- interface/reports/daily_summary_report.php
- interface/reports/edi_270.php
- interface/reports/encounters_report.php
- interface/reports/immunization_report.php
- interface/reports/non_reported.php
- interface/reports/patient_flow_board_report.php
- interface/reports/patient_list.php
- interface/reports/patient_list_creation.php
- interface/reports/prescriptions_report.php
- interface/reports/referrals_report.php
- interface/reports/report_results.php
- library/js/xl/jquery-datetimepicker-2-5-4.js.php
Can see the date picker at:
Reports->Visits->Appointments
Can see the date/time picker at:
Administration->Other->Logs
It also supports translations via OpenEMR and supports RTL.
Date picker screenshot:
Date and time picker screenshot:
> new datetimepicker

- interface/forms/LBF/new.php
- interface/forms/LBF/printable.php
- interface/forms/LBF/report.php
- interface/main/left_nav.php
- interface/main/tabs/menu/menu_updates.php
- interface/patient_file/encounter/forms.php
- interface/patient_file/encounter/new_form.php
- interface/super/edit_layout_props.php
- interface/super/edit_list.php
This branch will contain a number of commits for enhancing access control features.
The first commit relates to layout-based visit forms. It allows you to choose an ACO for each LBF form type.  In Administration -> Lists -> Layout_based Visit Forms you can click in the Notes column to set some attributes for the form, one of which is the ACO selection.  If you assign an ACO then users with that level of access will be allowed to access forms of that type, otherwise not.
More to come. Comments appreciated. Thanks!
> Access Control Improvements

- controllers/C_Document.class.php
(Adding my tasks to the top of the PR so they don't get lost -matthew)
> Update document class to check for relocated documents folder

- interface/themes/rtl.css
Hi, I just fix the rtl of the date picker, month and years are now in rtl current direction.
thanks oshri.
> fix support of rtl on datepicker openemr

- interface/main/finder/dynamic_finder.php
- library/js/xl/datatables-net.js.php
Centralizing this since plan to also use this in the Groups code that Matrix is currently working on.
> centralized translations for the datatables asset

- interface/themes/rtl.css
Hi 
This is a minor CSS , RTL related fix regarding opening a new encounter 
Thanks,
Eyal
>  Rtl css fix for new encounter

- interface/billing/era_payments.php
- interface/billing/new_payment.php
- interface/billing/payment_master.inc.php
- interface/billing/search_payments.php
- interface/reports/patient_list.php
- interface/reports/patient_list_creation.php
1. integrated datepicker into batch payment gui
2. internationalized datepicker input field in interface/reports/patient_list.php report
3. some minor code cleanup in patient_list_creation.php
> Modern datepicker project

- controllers/C_Document.class.php
hi, we add xl to option val xl(text($row_result_docs['pc_catname']))
> add lang option

- library/classes/Document.class.php
Addresses my user error in https://github.com/openemr/openemr/issues/482 and https://github.com/openemr/openemr/issues/481
> Disallow doc uploads with no file extension

- interface/main/calendar/add_edit_event.php
Hi, i add new lang to add and edit event form.
> add new lang to "add and edit event"

- interface/forms/vitals/report.php
- interface/patient_file/report/custom_report.php
Hi,
Fixed rtl issues in the patient report for vitals
> rtl issues in patient vitals report

- library/globals.inc.php
- library/translation.inc.php
- version.php
added option to disable safe apostrophes for translations
this was inspired by the prior PR here:
https://github.com/openemr/openemr/pull/505
> added option to disable safe apostrophes for translations

- interface/forms/care_plan/new.php
- interface/forms/care_plan/view.php
- interface/forms/functional_cognitive_status/new.php
- interface/forms/functional_cognitive_status/view.php
- interface/forms/observation/new.php
- interface/forms/observation/view.php
- interface/patient_file/summary/immunizations.php
> ongoing datepicker work

- interface/super/rules/controllers/browse/view/list.php
- interface/super/rules/www/css/rules.css
Hi, this is the fix for the issues
> fix responsive rule list

- interface/forms/aftercare_plan/new.php
- interface/forms/misc_billing_options/new.php
- interface/forms/note/new.php
- interface/forms/note/view.php
- interface/forms/transfer_summary/new.php
- interface/forms/treatment_plan/new.php
- interface/forms/vitals/templates/vitals/general_new.html
- interface/patient_file/encounter/trend_form.php
added the new datepicker in the standard forms
> added the new datepicker in the standard forms

- acl_setup.php
- acl_upgrade.php
- interface/main/left_nav.php
- interface/main/tabs/js/menu_analysis.js
- interface/main/tabs/menu/menu_data.php
- interface/main/tabs/menu/menu_json.php
- interface/main/tabs/menu/menu_updates.php
- interface/patient_file/summary/demographics.php
- interface/patient_file/summary/disc_fragment.php
- interface/patient_file/summary/pnotes_fragment.php
- library/acl.inc
- version.php
This continues work to fill in access control omissions.
Added these ACOs in the "patients" section:
reminder    Patient Reminders (write,addonly optional)
alert       Clinical Reminders/Alerts (write,addonly optional)
disclosure  Disclosures (write,addonly optional)
rx          Prescriptions (write,addonly optional)
amendment   Amendments (write,addonly optional)
lab         Lab Results (write,addonly optional)
Also added code, mostly in the demographics summary, to enforce these and some others.
Also modified acl.inc to always give the superuser access to everything.
Also updated menu code to disable items that the user does not have permission for.
> Access control improvements.

- interface/billing/sl_eob_search.php
Hi,
like in billing report there is no way to view only patient with debt .
so I have added this filter.
also it will be nice to have the pid in the table . I have added this also .
thanks
Dror G.
> add patient with debt filter and patient pid to the table.

- interface/forms/LBF/new.php
- interface/new/new.php
- interface/new/new_comprehensive.php
- interface/orders/orders_results.php
- interface/patient_file/history/history_full.php
- interface/patient_file/summary/demographics_full.php
- interface/patient_file/transaction/add_transaction.php
- interface/usergroup/facility_user_admin.php
- library/options.inc.php
added modern datepicker to layouts engine
> added modern datepicker to layouts engine

- library/edihistory/test_edih_835_accounting.php
- library/edihistory/test_edih_sftp_files.php
Fixed - missing logical operators, brackets, semicolons.
> Fixed few typos

- library/options.inc.php
- sql/5_0_0-to-5_0_1_upgrade.sql
- sql/database.sql
- version.php
Title pretty much says it all. :)  This relates to layout based visit forms with the Image Canvas data type.
> Some fixes for drawable images with larger image sizes.

- interface/billing/edih_view.php
- interface/forms/group_attendance/new.php
- interface/therapy_groups/therapy_groups_views/groupDetailsParticipants.php
- interface/therapy_groups/therapy_groups_views/listGroups.php
incorporated centralized translations into DataTable js
> incorporated centralized translations into DataTable js

- interface/forms/ros/report.php
Simplified code for ros form display using array.
> ros display update

- interface/forms/eye_mag/SpectacleRx.php
- interface/forms/eye_mag/a_issue.php
- interface/forms/eye_mag/css/style.css
- interface/forms/eye_mag/help.php
- interface/forms/eye_mag/js/eye_base.php
Spectacle Rx fix.
JS,Help.php and styling.
> Several minor bug fixes

- interface/themes/tabs_style_compact.css
- interface/themes/tabs_style_full.css
- version.php
Removed left and right borders on the main frame display, not sure why they were even in the code. @bradymiller is there anything I need to do to bump the CSS version on these two files? If not this is an easy PR
> Removing useless main frame borders

- interface/main/messages/messages.php
> Bug fix for message center broken links

- interface/billing/billing_report.php
- interface/reports/criteria.tab.php
> new calendar widget to billing report

- CONTRIBUTING.md
Example of what this will look like:
The idea is to keep this limited to just 5 items forever. No exceptions.
> CONTRIBUTING.md guidelines w/ some very light process

- interface/forms/procedure_order/new.php
- interface/reports/patient_list.php
- interface/reports/prescriptions_report.php
- library/js/report_helper.js
- library/options.inc.php
- library/templates/standard_header_template.php
New report converted is Reports->Clients->Rx
This is part of the following code walk through project:
> Work on standard header and conversion of another report

- bower.json
- controllers/C_PracticeSettings.class.php
- interface/themes/style_babyblu.css
- interface/themes/style_light.css
- interface/themes/style_metal.css
- interface/themes/style_oemr.css
- interface/themes/style_purple.css
- interface/themes/style_radiant.css
- interface/themes/style_sky_blue.css
- interface/themes/style_tan.css
- public/assets/bootstrap-sidebar-0-2-2/.bower.json
- public/assets/bootstrap-sidebar-0-2-2/README.md
- public/assets/bootstrap-sidebar-0-2-2/bower.json
- public/assets/bootstrap-sidebar-0-2-2/demo.html
- public/assets/bootstrap-sidebar-0-2-2/dist/css/sidebar.css
- public/assets/bootstrap-sidebar-0-2-2/dist/js/sidebar.js
- public/assets/bootstrap-sidebar-0-2-2/index.html
- public/assets/bootstrap-sidebar-0-2-2/style.css
- templates/insurance_companies/general_list.html
- templates/insurance_numbers/general_list.html
- templates/pharmacies/general_list.html
- templates/practice_settings/general_list.html
- templates/x12_partners/general_list.html
- version.php
Quick little update to the Practice Settings page
I get easily distracted when doing things like adding a pharmacy for testing and start updating the UI. This is just about ready to go, just.... where is the tab title defined? Obviously it's not correct. Just gotta fix that and this should be good.
It's super straight forward, just added the sidebar and added some classes to the tables
> Modernizing Practice Settings page

- interface/billing/payment_pat_sel.inc.php
change ICD9 to ICD10 thanks to community forum tip
> fix to ICD10 codes in post payments

- interface/billing/sl_eob_search.php
- portal/home.php
- portal/lib/portal_mail.inc
- portal/messaging/handle_note.php
- portal/messaging/messages.php
- sql/5_0_0-to-5_0_1_upgrade.sql
- sql/database.sql
Fix for duplicate and misdirection of messages. Also cleaned up forwarding to pnotes and added a mass delete of selected messages. Changed individual message delete to delete message chain.
> Onsite portal messaging fix. 

- interface/billing/sl_eob_invoice.php
can't figure out why opener.document.forms[0] is undefined when called from encounters.php but this steps around it for now
> fix to issue #647

- interface/reports/patient_list_creation.php
note removed fancybox, jquery-ui, and common.js includes since were not being used in this report
This is part of the following code walk through project:
> added standard header and bootstrap light to another report

- interface/reports/clinical_reports.php
- interface/reports/immunization_report.php
- interface/reports/referrals_report.php
> standard header and bootstrap light continued

- interface/login/login.php
> incorporate standard header template into login screen

- interface/patient_file/summary/pnotes_full_add.php
see here for details:
https://community.open-emr.org/t/new-problem-since-installing-5-0-0-concerning-patient-notes/8432/
> added back the close patient note shortcut

- interface/reports/amc_tracking.php
- interface/reports/cdr_log.php
- interface/reports/cqm.php
- interface/reports/report_results.php
> standard header and bootstrap light continued - 2

- interface/patient_file/report/custom_report.php
- library/ajax/document_helpers.php
- portal/import_template_ui.php
- portal/lib/download_template.php
- portal/messaging/secure_chat.php
- portal/patient/templates/OnsiteDocumentListView.tpl.php
- portal/patient/templates/OnsitePortalActivityListView.tpl.php
- templates/documents/general_list.html
- templates/documents/general_view.html
Allows user to change patient in New documents. This is meant to make dealing with more than one patients document maintenance easier by doing them all in one place. Also added a selection toggle to expand the document viewer into entire frame. Always bugged me.
Improved custom report to allow either a gif,png or jpg image for practice logo along with improved error reporting of html to pdf errors.
Some portal changes for templates and chat.
> Enhancements for New Document.

- bower.json
- interface/forms/procedure_order/new.php
- interface/themes/style_babyblu.css
- interface/themes/style_blue.css
- interface/themes/style_light.css
- interface/themes/style_metal.css
- interface/themes/style_oemr.css
- interface/themes/style_purple.css
- interface/themes/style_radiant.css
- interface/themes/style_sky_blue.css
- interface/themes/style_tan.css
@juggernautsei @bradymiller New PR fixing the weird merge issues.
Some notes (That I think were lost)
`Save` and `Save and Transmit` are now working as expected.
`Add Procedure` is still not working as expected, but I know why and am working on it. Basically the `addProcLine()` function was manipulating the `table` DOM element, since there are no more tables in this DOM that function gets angry. Easy enough to fix.
> Moving procedure order form to bootstrap

- interface/patient_file/encounter/forms.php
Adding standards to help me visualize some errors I'm trying to fix on a separate PR. This commit is *ONLY* the auto-applied changes to code formatting
> Auto fix applied to form.php

- interface/patient_file/encounter/Services/ViewHelper.php
- interface/patient_file/encounter/forms.php
- interface/patient_file/encounter/new_form.php
- interface/themes/style_light.css
> Move encounter menu to sidebar

- interface/reports/appointments_report.php
- interface/reports/appt_encounter_report.php
- interface/reports/chart_location_activity.php
- interface/reports/charts_checked_out.php
- interface/reports/daily_summary_report.php
- interface/reports/edi_270.php
- interface/reports/encounters_report.php
- interface/reports/non_reported.php
- interface/reports/patient_flow_board_report.php
- interface/reports/services_by_category.php
more details in following issue:
> more standard template/bootstrap header ongoing work

- interface/patient_file/encounter/Services/ViewHelper.php
- interface/patient_file/encounter/forms.php
Hi.
The new side menu of the encounter screen doesn't support rtl languages. so I fixed it..
Thanks
Amiel
> Improve new encounter menu  to support RTL langauges

- interface/patient_file/encounter/forms.php
- interface/patient_file/encounter/new_form.php
This is temporary until we get the bootstrap menu working well.
Copied in the interface/patient_file/encounter/forms.php and interface/patient_file/encounter/new_form.php before any changes were made.
(so can just revert this in the branch to continue work on bootstrap menu)
> revert encounter gui (while complete the bootstrap improvements)

- interface/main/calendar/add_edit_event.php
- library/globals.inc.php
Hi.
Here I added new validation to prevent changing status to 'Arrive' before the appointment's time.
Thanks
Amiel
> Additional validation to add/edit event screen

- interface/main/calendar/add_edit_event.php
Hi all , 
This is a bug fix that shows an alert : 
"On this date there is a holiday, use it anyway?" 
This is needed when the user is trying to schedule an appointment in holiday day and 
he Global  Support Multi-Provider Events is turned true
note:
This alert already exist in OpenEMR in case of the Global  Support Multi-Provider Events is turned false
> A fix for calendar alert of holidays

- controllers/C_Document.class.php
- templates/documents/general_view.html
We have fixed this issue.
Thanks
[Visolve](http:hc.visolve.com)
> Bug Fix for Can’t untag a document / encounter pair

- interface/forms/soap/templates/general_new.html
- library/templates/standard_header_template.php
> converted SOAP form to bootstrap

- interface/forms/soap/templates/general_new.html
- interface/patient_file/encounter/superbill_custom_full.php
- library/templates/standard_header_template.php
Hi 
This is a security permission fix for the codes screen 
(We need to consider applying additional fixes to other screens related to the  superbill  permission )
Today users that have superbill permission can edit the data in the codes screen
regardless to the view/edit state of the permission!
Now after the fix ,  users that have superbill view permission can not edit the data in that screen
Thanks
Eyal
> Add permissions

- interface/modules/zend_modules/module/Multipledb/view/multipledb/multipledb/index.phtml
Hi.
Here I adding full url to links in the view of multiDB.
Thanks 
Amiel
> MultiDB zend module - Change links to absolute path

- interface/therapy_groups/therapy_groups_controllers/participants_controller.php
- interface/therapy_groups/therapy_groups_controllers/therapy_groups_controller.php
- interface/therapy_groups/therapy_groups_views/groupDetailsGeneralData.php
- interface/therapy_groups/therapy_groups_views/groupDetailsParticipants.php
Hi.
Here I complete the issue of the format date in the all screens of therapy groups.
Now it's working correctly.
Thanks 
Amiel
> Local date format in all the therapy group screens

- interface/main/about_page.php
> use new buttons in about page

- interface/billing/sl_eob_search.php
Hello Brady,
Here is the code that emails the patient statement to patients who allow emails and has a valid email address. It also shows that if the user has an email and allows email in the "EOB Posting - Search" page.
Please let me know if there are any changes that needs to be done.
Thank you
Venkat Ambati
> email pdf statement to patients with email address

- interface/patient_file/deleter.php
- library/templates/standard_header_template.php
> Styling of buttons on delete gui

- interface/patient_file/letter.php
- library/templates/standard_header_template.php
> converted letter script (Popups->Letter) to bootstrap light and new calendar widget

- interface/therapy_groups/therapy_groups_controllers/participants_controller.php
- interface/therapy_groups/therapy_groups_views/groupDetailsParticipants.php
Hi.
Here I sort the list of therapy group participants with php instead datatable that not work correctly.
Now in the head of the list shows the active participants and in the end inactive.  
Thanks
Amiel
> Order participants list with php

- interface/themes/core.css
- interface/themes/style_light.css
- library/options.inc.php
> Options.inc.php to bootstrap

- interface/patient_file/letter.php
testing well. plan to bring into codebase is passes travis-ci.
> several improvements to letter gui

- interface/patient_file/transaction/add_transaction.php
- interface/patient_file/transaction/transactions.php
- interface/patient_file/transaction/transactions_full.php
> Add new button styles to transactions

- interface/forms/eye_mag/view.php
Changed 'Alert' to 'Alert{{Mental Status}}'
> Add comment to Alert constant

- interface/patient_file/history/history.php
- interface/patient_file/history/history_full.php
- interface/themes/core.css
- interface/themes/style_light.css
> Updating history page

- interface/main/tabs/main.php
- interface/main/tabs/templates/patient_data_template.php
- interface/main/tabs/templates/therapy_group_template.php
- library/templates/standard_header_template.php
This is really nice styling work by Robert of the main stuff in the main top panel of the tabs user interface.
I added a little integration work to it.
Note also need to add it to the Administration->Appearance->Enable Group Therapy module
(this is basically the same gui as interface/main/tabs/templates/patient_data_template.php, but is the interface/main/tabs/templates/therapy_group_template.php script)
> Improved style of tabs layout by Robert

- library/templates/standard_header_template.php
- templates/practice_settings/general_list.html
https://github.com/openemr/openemr/issues/799
After some more quick testing, will bring this into the codebase.
> removed pure php in templates/practice_settings/general_list.html

- library/gen_hcfa_1500.inc.php
from hamd's troubles reported through the forum
> simple fix for box 32b

- interface/themes/core.css
- templates/documents/general_queue.html
- templates/hl7/general_parse.html
> Minor fixes to brady's work

- interface/main/tabs/templates/patient_data_template.php
Added comments to constant "None" to ease translation
> Add comments to constants

- interface/themes/tabs_style_full.css
- version.php
Just some minor changes to tone down the text size a little bit on the menu and tab titles.
(tested it on all the global text sizes)
> minor styling adjustments to top panel

- interface/themes/style_light.css
- interface/themes/tabs_style_full.css
- version.php
Work in progress to bring back pertinent font-sizes in light style that were removed:
https://github.com/openemr/openemr/commit/015259540048911657930c1e698777a6953957db
@robertdown , Does it make sense to bring back the font-size setting that were removed previously but as percentage (or em if you prefer) ?
> interim styling font size fixes

- common/compatibility/Checker.php
see here for reason why:
https://github.com/robertogagliotta/openemr/commit/6989b55aea7674524d39de8a133b812a41b986cb#commitcomment-22393359
> proposing increasing minimum php version to 5.6.0

- interface/patient_file/encounter/superbill_custom_full.php
This will also go in next 5.0.0 patch
> bug fix when modifying external codes

- interface/forms/group_attendance/new.php
- interface/forms/group_attendance/save.php
Here we embedded permissions into the groups attendance forms
> attendance form permissions fix

- interface/patient_file/summary/demographics_full.php
bug fixes when values contain quotes in insurance form
> bug fixes when values contain quotes in insurance form

- interface/super/edit_layout_props.php
Allow optional specification of the "Category" property for layout forms.  This property can be combined with similar setting in registry based forms.
Also makes the form fields mapping to JSON string generic.
> Category option for layouts.

- templates/documents/general_view.html
Also includes minor layout adjustments.
> Document view template default set to show contents

- interface/forms/fee_sheet/new.php
- interface/forms/group_attendance/new.php
> Permission fixes 06 08 17

- interface/forms/track_anything/history.php
- interface/forms/track_anything/report.php
- interface/forms/vitals/templates/vitals/general_new.html
- interface/patient_file/summary/labdata.php
- interface/themes/core.css
- version.php
https://github.com/openemr/openemr/issues/583
> some dygraphs changes for 5.0.1

- interface/patient_file/encounter/forms.php
continued from https://github.com/openemr/openemr/pull/859
> incorporated sensitivity acl into encounter gui

- interface/patient_file/encounter/forms.php
1. remove libraries not used in forms.php
2. made forms.php compatible with modern jquery
> Encounter gui work 1

- library/globals.inc.php
> simple fix for hylafax

- interface/patient_tracker/patient_tracker.php
- interface/themes/style_babyblu.css
- interface/themes/style_blue.css
- interface/themes/style_light.css
- interface/themes/style_metal.css
- interface/themes/style_oemr.css
- interface/themes/style_purple.css
- interface/themes/style_radiant.css
- interface/themes/style_sky_blue.css
- interface/themes/style_tan.css
- library/appointments.inc.php
- library/patient_tracker.inc.php
Hi brady,
Added a filter by name or Id to patient flowboard.
Changed the style so fits well into screen.
> Flowboard pid filter

- interface/forms/misc_billing_options/new.php
- interface/forms/misc_billing_options/report.php
- interface/forms/misc_billing_options/save.php
- library/Claim.class.php
- library/gen_hcfa_1500.inc.php
- library/gen_x12_837.inc.php
- sql/5_0_0-to-5_0_1_upgrade.sql
- sql/database.sql
- version.php
> More misc billing

- interface/forms/misc_billing_options/date_qualifier_options.php
- interface/forms/misc_billing_options/new.php
- interface/forms/misc_billing_options/report.php
- library/Claim.class.php
- library/gen_hcfa_1500.inc.php
- sql/5_0_0-to-5_0_1_upgrade.sql
- sql/database.sql
> fixed sql errors, form tag, cleaned up report

- interface/reports/patient_edu_web_lookup.php
@robertdown  @bradymiller  script Ready for review
> Patient education  bootstrap convertion

- .gitignore
- interface/patient_file/ccr_import.php
Shouldn't cause any regressions. Additionally now preventing git from tracking compiled calendar artifacts.
> Migrating ccr_import to bootstrap

- interface/main/messages/messages.php
- interface/super/edit_globals.php
- library/globals.inc.php
This is a fix to the Message and Reminder Center in order to adapt it to RTL 
I will add pictures in the comment below
Thanks
Eyal
> Add translation and fix rtl

- sql/database.sql
this seems somewhat silly but was there a reason there was a space in column 4?
> minor fix to separator

- interface/forms/eye_mag/save.php
- interface/new/new_comprehensive_save.php
- interface/patient_file/history/history_save.php
- interface/patient_file/summary/demographics_save.php
Hi.
I've found that if you define field as disabled in the LBF with option - 0 (http://www.open-emr.org/wiki/index.php/LBV_Forms) for static data from database.
In the saving of such form all the disabled fields saved with empty value because field with disabled status isn't sent by form and the generator saves it as empty value.  
With my fix a disabled field never will saved in the database.
Thanks
Amiel
> fix for disabled filed in the LBF

- interface/new/new_comprehensive_save.php
Hi.
This bug has happened because my[ PR](https://github.com/openemr/openemr/pull/907) that enable saving of form with disabled field.
The correction caused to pubpid to be empty in the new patient.
so I've fixed it..
Thanks 
Amiel
> Fix bug of default value of pubpid

- interface/main/calendar/add_edit_event.php
just a couple quick code changes towards full psr2
> fully psr2 compatible in interface/main/calendar/add_edit_event.php

- interface/patient_file/encounter/forms.php
Hey,
Just a small fix, otherwise even admin would be locked out of therapy group encounters
> fixed therapy groups permissions

- interface/patient_file/reminder/active_reminder_popup.php
Removes unused script from popup.
> Unused scripts

- interface/patient_file/encounter/search_code.php
- interface/themes/style.css
- interface/themes/style_babyblu.css
- interface/themes/style_blue.css
- interface/themes/style_flat_red.css
- interface/themes/style_light.css
- interface/themes/style_metal.css
- interface/themes/style_oemr.css
- interface/themes/style_pdf.css
- interface/themes/style_purple.css
- interface/themes/style_sky_blue.css
- interface/themes/style_tan.css
- interface/usergroup/user_info.php
- interface/usergroup/user_info_ajax.php
- library/dated_reminder_functions.php
continued from the following PR:
https://github.com/openemr/openemr/pull/936
> Roberto's Password Change script bootstrap conversion

- library/api.inc
Hi.
This continuation of the fix from PR  [959](https://github.com/openemr/openemr/pull/959).
The problem occurs also in the save of forms and in the cancel of addition forms.
Amiel
> Fix in the saving of forms

- ci/ci.sh
Quick improvement to `ci.sh` to display more details about errors. I wonder if it would be desirable to display warnings as well?
> Using a more thorough report for CI

- controllers/C_InsuranceNumbers.class.php
- templates/hl7/general_parse.html
- templates/insurance_companies/general_edit.html
- templates/insurance_numbers/general_edit.html
- templates/pharmacies/general_edit.html
- templates/practice_settings/general_list.html
- templates/x12_partners/general_edit.html
work in progress so can get early feedback
> bootstrap practice settings gui

- controllers/C_Document.class.php
- interface/forms/eye_mag/report.php
- interface/patient_file/encounter/cash_receipt.php
- interface/patient_file/report/custom_report.php
- library/classes/Document.class.php
- library/classes/Note.class.php
- portal/report/portal_custom_report.php
Code improvement by @mdsupport  taken from following PR:
https://github.com/openemr/openemr/pull/970
> mdsupport Notes rebase

- custom/chart_tracker.php
@bradymiller @robertdown  Unit Testing Ok. script ready for code review.
> chart_tracker.php bootstrap convertion

- interface/usergroup/facilities.php
- services/FacilityService.php
Added new function to FacilityService class to allow updating users facility name after facility edit.
> Missing rx address after facility edit.

- interface/forms/LBF/new.php
- interface/new/new_comprehensive.php
- interface/patient_file/summary/demographics_full.php
- interface/themes/core.css
new/search patient
edit patient demographics
lbf forms
> incorporated bootstrap into several layouts

- contrib/forms/evaluation/FormEvaluation.class.php
- contrib/forms/hand/FormHand.class.php
- contrib/forms/hp_tje_primary/FormHpTjePrimary.class.php
not sure which contrib form (evaluation) this equates to under encounter, misc->? or clinical->?
also tried to fix missing parent constructor message in php storm, and removed code references to unused variable
> fix deprecated class named construct

- interface/billing/sl_eob_search.php
- sites/default/statement.inc.php
Added CVV to statements credit return tear off.
> Behavior change for eob print.

- interface/logview/logview.php
- interface/patient_tracker/patient_tracker.php
- library/encounter_events.inc.php
- library/formatting.inc.php
Added a new function to return the date formatted with hours and minutes according the global
> Added new function to format the complete date according the global

- interface/patient_file/summary/demographics_full.php
Hi.
I removed the line that add "type=button" to submit button It causes js error.
Because this error the client side validation also not working and the form saved anyway.
Thanks
Amiel
> Fix demographics validation

- interface/batchcom/batch_phone_notification.php
- library/allow_cronjobs.php
Standard checks before running a script as cronjob.
Including batchcom script just to illustrate use of this library.
> cronjob hdr v1

- interface/patient_file/summary/demographics.php
Hi.
We've found that jquery funcybox is not support multi instance together so when there is patient reminders and birthday popup the second not opened.
I fixed it so reminder popup is opened after birthday popup is closed.
Thanks
Amiel
> Fix birthday popup and reminder popup to working together

- interface/main/tabs/templates/patient_data_template.php
- library/js/xl/jquery-datetimepicker-2-5-4.js.php
- sites/default/statement.inc.php
Couple bug fixes. Please leave open for a few days in case I have more. Just wanted to get the PR up in case anyone comes across these problems.
> Misc fixes version 5.0.1

- config/config.yaml
Switch order of base and bootstrap add-on theme for select2
Details .. #1009
> Fix bootstrap theme order for select2

- controllers/C_Document.class.php
- library/smarty/plugins/function.datetimepickerSupport.php
- library/smarty/plugins/function.headerShow.php
- templates/documents/general_list.html
- templates/documents/general_upload.html
- templates/documents/general_view.html
related to this issue:
https://github.com/openemr/openemr/issues/799
> future proofing smarty - ongoing project

- contrib/forms/hpi/FormHPI.class.php
- contrib/forms/leg_length/FormLegLength.class.php
- contrib/forms/nursing_notes/FormNursingNotes.class.php
hi @bradymiller , what do you think of the `__toString` use?
> fix travis deprecated constructor

- contrib/forms/prior_auth/FormPriorAuth.class.php
- contrib/forms/prosthesis/FormProsthesis.class.php
- contrib/forms/review_of_systems/FormReviewOfSystems.class.php
- contrib/forms/rom/FormROM.class.php
- contrib/forms/ros2/FormROS2.class.php
- contrib/forms/snellen/FormSnellen.class.php
- custom/BillingExport.csv.php
- interface/clickmap/AbstractClickmapModel.php
- interface/forms/painmap/FormPainMap.php
- interface/forms/prior_auth/FormPriorAuth.class.php
- interface/main/calendar/includes/pnHTML.php
- library/classes/ORDataObject.class.php
- library/classes/class.Handler_HL7v2.php
- library/custom_template/ckeditor/ckeditor_php4.php
- library/xmltoarray_parser_htmlfix.php
- modules/sms_email_reminder/sms_clickatell.php
- modules/sms_email_reminder/sms_tmb4.php
- portal/patient/fwk/libs/util/Mime_Types.php
- portal/patient/fwk/libs/util/parsecsv.lib.php
- portal/patient/fwk/libs/verysimple/Email/Pop3Client.php
also added toString for painmap
> constructor deprecated fix

- controllers/C_Document.class.php
https://github.com/openemr/openemr/issues/1029
> fix to open separate window when open ccr/ccd in documents gui

- custom/zutil.cli.doc_import.php
Utility script for importing documents in a directory
Useful for faxes, scans and other files that require a document record that can be processed using standard documents functions.
> Batch import of documents

- interface/super/edit_list.php
> fix undef var

- controllers/C_Document.class.php
- controllers/C_InsuranceCompany.class.php
- controllers/C_InsuranceNumbers.class.php
- controllers/C_PatientFinder.class.php
- controllers/C_Pharmacy.class.php
- controllers/C_PracticeSettings.class.php
- controllers/C_Prescription.class.php
- controllers/C_X12Partner.class.php
- library/classes/Controller.class.php
- library/classes/Prescription.class.php
- templates/document_categories/general_list.html
- templates/documents/general_list.html
- templates/documents/general_upload.html
- templates/prescription/general_block.html
- templates/prescription/general_edit.html
- templates/prescription/general_fragment.html
- templates/prescription/general_list.html
- templates/prescription/general_lookup.html
- templates/prescription/general_send.html
-also cleaned out and consolidated several unused/redundant global variables
Need to test this a bit before bringing into codebase.
> prescription smarty code escaped and made pure

- interface/billing/billing_process.php
- interface/billing/ub04_helpers.php
- interface/patient_file/deleter.php
- interface/patient_file/front_payment.php
- interface/reports/pat_ledger.php
- library/globals.inc.php
First in a series of billing fixes.
> Various Billing Fixes

- interface/billing/sl_eob_search.php
- sites/default/statement.inc.php
Bug fix to prevent appending file size to statement PDF. Reformat of statement footer to center and justify better.
@bradymiller Wouldn't hurt to leave open a couple days as may be others.
> Invoice Statement Fixes and others

- interface/super/edit_layout.php
This fixes renames of LBF fields so that if table columns must also be renamed (demographics and history) that happens properly.
> Fix for layout field renames in demographics and history.

- interface/forms/newpatient/common.php
This corrects the problem with the encounter not defaulting to the billing facility
> POS default selection for encounter

- setup.php
made the setup script theme consistent
> bug fix - made the setup script theme consistent

- interface/patient_file/history/history.php
- interface/patient_file/history/history_full.php
- interface/patient_file/summary/demographics_full.php
> minor title changes

- controllers/C_BillingContact.class.php
- controllers/C_Document.class.php
- controllers/C_DocumentCategory.class.php
- controllers/C_InsuranceCompany.class.php
- controllers/C_InsuranceNumbers.class.php
- controllers/C_PatientFinder.class.php
- controllers/C_Pharmacy.class.php
- controllers/C_PracticeSettings.class.php
- controllers/C_Prescription.class.php
- controllers/C_X12Partner.class.php
- interface/forms/fee_sheet/new.php
- interface/main/calendar/includes/pnMod.php
- interface/main/finder/patient_select.php
- interface/orders/load_compendium.php
- interface/orders/pending_orders.php
- interface/patient_file/deleter.php
- interface/patient_file/encounter/encounter_top.php
- interface/patient_file/printed_fee_sheet.php
- interface/patient_file/reminder/patient_reminders.php
- interface/patient_file/report/custom_report.php
- interface/patient_file/summary/add_edit_issue.php
- interface/patient_file/summary/pnotes_full.php
- library/encounter.inc
- library/patient.inc
Hi.
We received security report from professional company with all the problems they found in the system.
I've began to resolved them and this the first PR.
I added comments with explanation in the some places.
We on holiday in the next days so we'll be in touch next week.
Thanks.
Good year! (Hebrew year..)  
Amiel
Matrix
> FIx XSS attack issues

- library/options.inc.php
- sites/default/statement.inc.php
Remove returned nation note escaping so edit field can render any returned html.
Restyle of postings statement/invoice tear-off to prevent form feed.
Thank you @sunsetsystems for the LBF nation notes fixes.
> Give LBF nation note field in form a width.

- interface/forms/LBF/new.php
- interface/patient_file/encounter/find_code_dynamic_ajax.php
- library/ajax/code_attributes_ajax.php
o Possible JavaScript errors using Diagnosis section in LBF.
o For codes, finder was failing to set start and limit for returned rows.
o JavaScript error from failing to strip carriage returns from code descriptions.
I think this is ready to go, going through the PR process since it's not quite trivial.
> Fixed some bugs related to the Dynamic Code Finder.

- interface/forms/LBF/report.php
- interface/patient_file/encounter/find_code_dynamic_ajax.php
- interface/super/edit_layout.php
- library/options.inc.php
- sites/default/statement.inc.php
Added a new date time picker field type to lbf editor.
demo is here:
http://www.open-emr.org/wiki/index.php/Development_Demo#Mu_-_Up_For_Grabs_Demo
> Fix lbf nation note field type having no width in form.

- interface/main/finder/patient_select.php
not sure how travis missed this?
> minor php syntax fix

- interface/reports/unique_seen_patients_report.php
Bug reported by Visolve whom also contributed to this fix.
> Bug fix in unique seen patient reports.

- library/patient.inc
fixed so should only return 1 row if 1 provider
> fixed empty row added in getProviders

- library/globals.inc.php
> fix concatentation 

- interface/patient_file/encounter/forms.php
Puts forms in order of date (after ordering according to name etc).
> forms ordered also according to date

- interface/themes/style.css
- interface/usergroup/addrbook_list.php
Restyle to make responsive and full screen.
> Add header class and fancy box dependencies.

- interface/main/tabs/js/tabs_view_model.js
- interface/main/tabs/templates/patient_data_template.php
Added new icon next to new encounter to open visit history page.
> Add visit history function and icon to patient data header.

- interface/patient_file/summary/pnotes_full.php
Added a Status column to notes editing screen so can see status in that screen as well
> added status column

- interface/globals.php
- interface/main/left_nav.php
- interface/main/main_title.php
- interface/themes/style_ash_blue.css
- interface/themes/style_burgundy.css
- interface/themes/style_cadmium_yellow.css
- interface/themes/style_chocolate.css
- interface/themes/style_cobalt_blue.css
- interface/themes/style_coral.css
- interface/themes/style_deep_purple.css
- interface/themes/style_dune.css
- interface/themes/style_emerald.css
- interface/themes/style_forest_green.css
- interface/themes/style_light.css
- interface/themes/style_manila.css
- interface/themes/style_mauve.css
- interface/themes/style_mustard_green.css
- interface/themes/style_olive.css
- interface/themes/style_pink.css
- interface/themes/style_powder_blue.css
- interface/themes/style_red.css
- interface/themes/style_sienna.css
- interface/themes/style_tangerine.css
- library/globals.inc.php
added icon to patient dashdoard menu item in left nav, main title in frame view
has font-awesome icons on top right. Made suitable adjustments to all
stylesheets
> zbig1 integration of left nav and main title

- interface/super/edit_layout.php
- library/options.inc.php
Prevent null save to table and change modifier qualified logic.
> LBF isOption Fix

- sql/database.sql
got a little carried away after i went in to add drop table command to each create table :)
> added drop table command and some formatting cleanup

- interface/forms/care_plan/new.php
- interface/forms/clinical_instructions/new.php
- interface/forms/dictation/new.php
- interface/forms/dictation/report.php
- interface/forms/dictation/view.php
- interface/forms/functional_cognitive_status/new.php
- interface/forms/observation/new.php
- interface/forms/reviewofs/new.php
- interface/forms/reviewofs/view.php
- interface/forms/ros/FormROS.class.php
- interface/forms/ros/templates/ros/general_new.html
integration PR for some code from following PR:
https://github.com/openemr/openemr/pull/1115
> responsive and bootstrap to some forms

- library/options.inc.php
Hi.
The conditions in the LBF haven't  worked in multi select element since last updating.
I fixed it.
Thanks
Amiel
> Fix LBF conditions in multi select element

- interface/super/edit_layout.php
fix of javascript error on select datatype reported in pr https://github.com/openemr/openemr/pull/1152
> Fix null error caused by certain elements called before they exist.

- interface/main/finder/dynamic_finder_ajax.php
- library/options.inc.php
Hi.
I added 'xls'  function to results that fill a patients list using AJAX.
Needed for all data in 'patient data' table that saved from lists.
Thanks
Amiel
> Translation of values in the patient list

- interface/super/edit_layout.php
I was going for cross browser support with checking dom content but forgot to add element. sorry guys.
> try3- does element exist in DOM

- interface/patient_file/encounter/forms.php
bug fix for issue #1184 , fix was reported by Rod
> bug fix for issue #1184 , fix was reported by Rod

- interface/main/calendar/modules/PostCalendar/pnadmin.php
Proposed fix for PHP 7.1 issue at https://github.com/openemr/openemr/issues/1177
> bug fix for issue #1177

- interface/main/calendar/modules/PostCalendar/pnadmin.php
To fix following issue: https://github.com/openemr/openemr/issues/1176
> fix issue #1176

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CcdController.php
Fix for issue: https://github.com/openemr/openemr/issues/1163
Demo on php 7.1 is here:
http://www.open-emr.org/wiki/index.php/Development_Demo#Nu_-_Up_For_Grabs_Demo
> fix issue #1163

- interface/patient_file/encounter/forms.php
- interface/themes/rtl.css
Hi.
Here 2 minor fixes in encounters list.
1. Missing translation.
2. Style for RTL languages.
Thanks
Amiel
> Translation and rtl style in the encounters list screen

- interface/main/messages/messages.php
@brady.miller,
[Removing the accidentally added recipients in Messages](https://community.open-emr.org/t/removing-the-accidentally-added-recipients-in-messages/9177) bug has been fixed and the following is the 
[Commit Link](https://github.com/visolve-openemr/Openemr_features_enhancements/commit/3b4eed78670669ec5784b597ced4254b3330cde2)
Please check this and share your views.
Thanks,
[ViSolve](http://www.visolve.com/hc/openemr)
> clear button in messages screen to remove selected users

- interface/orders/types_edit.php
@brady.miller,
[Order Catalog Deletion](https://community.open-emr.org/t/order-catalog-deletion/9129) bug has been fixed and the following is the commit link 
[Commit Link](https://github.com/visolve-openemr/Openemr_features_enhancements/commit/85ab6e9d17cf08d2e8c81c8c0cf5087e7d27083b)
Please check and share your views
Regards,
[Visolve](http://www.visolve.com/hc/openemr)
> order catalog deletion

- interface/reports/prescriptions_report.php
https://github.com/openemr/openemr/issues/499
> prescriptions_report cleanup

- interface/patient_file/deleter.php
Delete cancel button always selected a fancybox popup close. Leaving popup open if called from dialog.
> Deleter cancel fix

- interface/forms/aftercare_plan/new.php
- interface/forms/care_plan/new.php
- interface/forms/clinical_instructions/new.php
- interface/forms/functional_cognitive_status/new.php
- interface/forms/misc_billing_options/new.php
- interface/forms/observation/new.php
- interface/forms/procedure_order/new.php
- interface/forms/transfer_summary/new.php
- interface/forms/treatment_plan/new.php
- interface/patient_file/encounter/forms.php
Fixed those listed plus couple others.
Refer: https://github.com/openemr/openemr/issues/1185
> Resolve type warning errors. Issue #1185

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Form/ModuleconfigForm.php
Refer issue: https://github.com/openemr/openemr/issues/1162
Wanted to get this out of the way. Narrowing in on the main issue dealing with CarecoordinationController issue.
> Instantiate a listener for translations.

- interface/main/calendar/add_edit_event.php
- interface/main/calendar/find_appt_popup.php
- interface/main/finder/patient_select.php
- interface/main/tabs/js/include_opener.js
- interface/main/tabs/main.php
- interface/patient_file/encounter/find_code_dynamic.php
- interface/super/edit_layout.php
- interface/super/edit_layout_props.php
- interface/themes/tabs_style_compact.css
- interface/themes/tabs_style_full.css
- interface/usergroup/addrbook_list.php
- library/dialog.js
Stage 1. Rework tabs dlgopen modal function for the following:
* Made into a  bootstrap modal with bootstrap classes.
* Automatic size to content on open.
* Maintain legacy function call by sizing to existing dimensions.
* Four responsive sizes: sm,md,lg,xl.
* Resize and drag.
Demo for this PR is at: http://www.open-emr.org/wiki/index.php/Development_Demo#Epsilon_-_Up_For_Grabs_Demo
> Rework mainstay dialog to be responsive, resizeable and able to drag.

- portal/patient/templates/_FormsHeader.tpl.php
- portal/patient/templates/_ProviderHeader.tpl.php
Think this solves. Missed it from last go around.
> Remove setting a base url.

- interface/billing/indigent_patients_report.php
- interface/billing/new_payment.php
- interface/orders/orders_results.php
- interface/orders/types.php
- interface/patient_file/encounter/superbill_custom_full.php
- interface/reports/daily_summary_report.php
- interface/reports/external_data.php
Should resolve following issue's: #1164, #1165, #1178, #1179, #1180 and #1182.
> Minor changes for PHP7 warnings.

- interface/patient_file/summary/pnotes_fragment.php
- interface/themes/style_ash_blue.css
- interface/themes/style_burgundy.css
- interface/themes/style_cadmium_yellow.css
- interface/themes/style_chocolate.css
- interface/themes/style_cobalt_blue.css
- interface/themes/style_coral.css
- interface/themes/style_deep_purple.css
- interface/themes/style_dune.css
- interface/themes/style_emerald.css
- interface/themes/style_forest_green.css
- interface/themes/style_light.css
- interface/themes/style_manila.css
- interface/themes/style_mauve.css
- interface/themes/style_mustard_green.css
- interface/themes/style_olive.css
- interface/themes/style_pdf.css
- interface/themes/style_pink.css
- interface/themes/style_powder_blue.css
- interface/themes/style_red.css
- interface/themes/style_sienna.css
- interface/themes/style_tangerine.css
- library/globals.inc.php
Created another type of notes widget, can choose between them in Globals.
New type contains:
- ajax button to update message status to complete
- added 'To' column
- 'Content' contains only content itself without date or users
Up For Grabs demo is here:
http://www.open-emr.org/wiki/index.php/Development_Demo#Mu_-_Up_For_Grabs_Demo
> New notes widget

- interface/main/calendar/includes/pnMod.php
Likely winner for proposed strategy for the following issue/PR: #1222
> calendar xss take 4

- interface/patient_file/reminder/patient_reminders.php
- interface/super/edit_globals.php
- interface/usergroup/adminacl.php
- interface/usergroup/adminacl_help.php
- interface/usergroup/usergroup_admin.php
- library/ajax/adminacl_ajax.php
- templates/practice_settings/general_list.html
Several script from following PR:
https://github.com/openemr/openemr/pull/1235
> Zbig01 changes ui 1

- interface/forms/eye_mag/css/style.css
- interface/forms/eye_mag/php/eye_mag_functions.php
- interface/forms/eye_mag/php/taskman_functions.php
- interface/forms/eye_mag/save.php
- interface/forms/eye_mag/view.php
Convert to mPDF library.
Fix for pdf generation.
Style changes.
demo is here: http://www.open-emr.org/wiki/index.php/Development_Demo#Epsilon_-_Up_For_Grabs_Demo
> Eye Module Changes Issue #1233 and Issue #1159

- templates/prescription/general_list.html
Initialize drug list correctly when weno enabled.
New function to simplify drug build submit list.
Track all drug select checkbox's when weno enabled.
> Changes to allow for print/faxing prescriptions when weno is enabled.

- interface/forms/newpatient/common.php
In the patient encounters, there is no need to bring the provider categories.
> Don't bring the categories that are related to the provider

- interface/patient_file/report/custom_report.php
CCM uses zend frameworks glob class which handles recursive incompatibilities.
> GLOB_BRACE recursive compatibility fix.

- gacl/gacl_api.class.php
- library/ajax/adminacl_ajax.php
proposed fixes for issue #1166
(still need to test and ensure I didn't do anything stupid in the gacl class logic)
> php 7.1 fix for issue #1166

- interface/main/calendar/add_edit_event.php
We've found problematic scenario when you replace between providers in the groups's event (with multi providers feature). 
Every encounter that's created automatic is connected to event with 'appt_id' column in 'form_groups_encounter' table. 
When replacing provider in the calendar the current logic deletes a old event ande creates new event for new provider, so the encounter id disconnected from the event.
This code should save on the event and encounter connected (necessary for group attendance form)
Thanks.
Amiel
> Auto create event with multi providers for therapy group

- library/dialog.js
Universal dialog mainly as phase one to replace fancybox dialogs.
Populate content via ajax (normal modal), iframe or html string.
Stackable, resizable and draggable.
Dynamic auto size to iframe content.
Assigns opener and close().
> Add new dialog modal for frames or tabs U.I.

- interface/forms/newpatient/common.php
There was a condition by cat id, not it's irrelevant as we are checking by category type, only display patient and group categories
> Removed condition by cat id as we added by type (only patient and group)

- interface/main/calendar/add_edit_event.php
- interface/main/calendar/find_appt_popup.php
- interface/main/calendar/find_patient_popup.php
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/header.html
- interface/main/main_screen.php
- interface/main/tabs/js/include_opener.js
- interface/patient_file/summary/demographics.php
- interface/patient_file/summary/stats.php
- interface/patient_tracker/patient_tracker.php
- interface/patient_tracker/patient_tracker_status.php
- interface/themes/core.css
- library/dialog.js
- templates/prescription/general_edit.html
Consolidation of dlgopen dialog into one function. oeModal is rolled into dlgopen. Universal modal for both frames and tabs interfaces. Called same as legacy tabs dialog and should be a seamless  transition from window dialogs to new in frames ui.
demo is at: http://www.open-emr.org/wiki/index.php/Development_Demo#Eta_-_Up_For_Grabs_Demo
> Universal Replacement Dialog for Tabs and Frames U.I's

- library/dialog.js
- templates/documents/general_list.html
- templates/documents/general_view.html
1. Added new button to right panel top action button group to open current viewers document, full screen.
2. Added double click on left panels documents icon to open to near full screen static modal where document can be viewed or opened to full screen window.
(below added by bradymiller):
demo at: http://www.open-emr.org/wiki/index.php/Development_Demo#Eta_-_Up_For_Grabs_Demo
> Documents view enhancements.

- interface/main/calendar/add_edit_event.php
- interface/main/calendar/find_appt_popup.php
- interface/patient_file/reminder/active_reminder_popup.php
- interface/patient_file/reminder/clinical_reminders.php
- interface/patient_file/rules/patient_data.php
- interface/patient_file/summary/create_portallogin.php
- interface/patient_file/summary/demographics.php
- library/dialog.js
Most are replaced. I believe still have some in insurance etc.
(below by bradymiller)
demo is here: http://www.open-emr.org/wiki/index.php/Development_Demo#Eta_-_Up_For_Grabs_Demo
> Replace fancybox dialogs within demographics.

- interface/patient_file/birthday_alert/birthday_pop.php
- interface/patient_file/summary/pnotes_full.php
- interface/super/edit_globals.php
Added escaping of characters and minor security fixes
> More security fixes Sc/security fixes

- interface/patient_file/deleter.php
- interface/patient_file/summary/disclosure_full.php
Hi all
this branch is intended to address the following problems 
URL: openemr/interface/patient_file/deleter.php
Entity: offset (Parameter)
problem : openemr/interface/patient_file/deleter.php?patient=&encounterid=%27%3B
URL:openemr/interface/patient_file/summary/disclosure_full.php
Entity: encounterid (Parameter)
problem : openemr/interface/patient_file/summary/disclosure_full.php?active=&offset=15%27%3B&leftrecords=635
> sql injection fix

- interface/patient_file/birthday_alert/birthday_pop.php
- interface/patient_file/summary/demographics.php
Hi.
Thanks you @sjpadgett about great improvement in the popups of demographics.
I've just pushed minor changes in the style of birthday popup to make it nicer.
Thanks.
Amiel
> Beautify birthday popup

- contrib/util/docker/README.md
> Must cd into repo for docker

- common/database/Connector.php
- gacl/gacl.class.php
- gacl/setup.php
- interface/globals.php
- interface/main/calendar/config.php
- interface/main/calendar/includes/pnAPI.php
- interface/modules/zend_modules/config/autoload/global.php
- interface/modules/zend_modules/module/Application/src/Application/Model/ApplicationTable.php
- library/ADODB_mysqli_log.php
- library/ADODB_mysqli_mod.php
- library/sql.inc
- portal/patient/fwk/libs/verysimple/DB/DataDriver/MySQLi.php
- sites/default/documents/certificates/README.md
Am testing with the following mysql docker:
`docker run --detach --name mysql --env "MYSQL_ROOT_PASSWORD=root" -v ~/git/newcerts:/etc/newcertsfake:ro --net mynet mysql --character-set-server=utf8 --ssl-key=/etc/newcertsfake/server-key.pem --ssl-cert=/etc/newcertsfake/server-cert.pem --ssl-ca=/etc/newcertsfake/ca.pem`
Part of this issue:
https://github.com/openemr/openemr/issues/1113
demo is here:
http://www.open-emr.org/wiki/index.php/Development_Demo#Lambda_-_Up_For_Grabs_Demo
> Support mysql ssl connection

- interface/forms/painmap/FormPainMap.php
https://github.com/openemr/openemr/issues/1291
> pain map form fix, reported by Arnab

- interface/forms/group_attendance/new.php
> fix can not add user to group attendance report 

- interface/main/left_nav.php
- interface/patient_file/summary/pnotes_full.php
- interface/patient_file/summary/pnotes_full_add.php
- interface/usergroup/facilities.php
- interface/usergroup/facilities_add.php
- interface/usergroup/facility_admin.php
- library/dialog.js
@bradymiller Example of replace a form target with ajax promise using dialog callback for refresh.
> bug fix for note save return after fancybox replace.

- interface/patient_tracker/patient_tracker_status.php
https://github.com/openemr/openemr/issues/1317
> removed unused fancybox and bootstrapped the patient_tracker_status.php script

- interface/main/tabs/js/frame_proxies.js
- interface/patient_file/deleter.php
- interface/patient_file/encounter/forms.php
- library/dialog.js
Added left navs encounter util functions to tabs left_nav proxy object. It certainly is never a dull moment in OpenEMR codebase. Knockout is sure to get your left and right brain talking to each other!
I want to add some restyle of new encounter screen as it is looking ragged between the different browser's.
> Encounter delete cleanup issue #1321

- library/billing.inc
See https://github.com/openemr/openemr/issues/685
> Fix for issue 685: reopening encounter through void on fee sheet fails

- interface/forms/newpatient/common.php
- interface/patient_file/deleter.php
- interface/patient_file/encounter/forms.php
Also made form appearance consistent by adding class styles to selects and inputs.
> bug-fix: new encounter cancel not returning in tabs ui.

- interface/patient_file/summary/demographics.php
- interface/weno/confirm.php
- library/dialog.js
- templates/prescription/general_edit.html
- templates/prescription/general_lookup.html
Restyle weno confirm.
Restyle prescription and adjust dialog size for weno.
Restyle drug search.
Fix bug window popup search by removing.
> Prescriptions Fix up.

- config/config.yaml
- interface/main/dated_reminders/dated_reminders_add.php
- interface/patient_file/encounter/forms.php
- interface/patient_file/summary/demographics_full.php
- interface/patient_file/summary/disclosure_full.php
- interface/practice/ins_search.php
- templates/prescription/general_edit.html
- templates/prescription/general_lookup.html
Just some low hanging fruit for the headers. I need to test this a bit.
> some header work

- library/dialog.js
dlgclose local steps on opener dlgclose if stacked.
> Minor bug fix for when dialogs are stacked cancel action intermittent.

- interface/super/edit_globals.php
This is step 1 from a prior PR here (https://github.com/openemr/openemr/pull/971) that is responsive and testing well. Will plan to get this into the codebase and then work on step 2 in the future (per the above PR link).
> Globals bootstrap responsive - step 1

- interface/billing/edit_payment.php
- interface/billing/search_payments.php
- interface/patient_file/merge_patients.php
- library/custom_template/custom_template.php
@bradymiller After the user stuff, I think this is it. However, fancybox knows we are after it so there are a lot of nooks and crannies to hide in OpenEMR. :)
> fancybox replace edit payments

- interface/usergroup/user_admin.php
- interface/usergroup/usergroup_admin.php
- interface/usergroup/usergroup_admin_add.php
- library/menu/src/MainMenuRole.php
Still need to work out a bug when save (it takes over the entire browser). And the algorithm on the receiving script is a bit complicated and needs to be able to throw a popup if an issue arises (not as simple to do an ajax call and then refresh like in other examples).
> update admin users gui

- interface/usergroup/user_admin.php
- interface/usergroup/usergroup_admin.php
- interface/usergroup/usergroup_admin_add.php
- library/dialog.js
@bradymiller I guess there are lots of ways to do this but I think for future modernization this method may prove more useful. Maybe docker so we can test heck out of and not mess up my dev database:)
> Finish up users fancybox replace.

- interface/patient_file/front_payment.php
- interface/reports/front_receipts_report.php
Form restyle.
Fix receipt exit handling after delete.
Fix refresh after receipt delete in front rec report.
Some code cleanup.
> Fix cancel front payment. #1340

- interface/patient_file/front_payment.php
Fix for create/goto encounter both tabs/frames UI.
issue #1345
> Stop generate invoice when form empty(no payment).

- interface/billing/sl_eob_invoice.php
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/header.html
- interface/orders/single_order_results.inc.php
- interface/patient_file/front_payment.php
- interface/patient_file/summary/pnotes_full.php
Update calendar jquery to v3-1-1.
Reopened Issue #1345
> Add save empty validation to sl_eob_invoice.

- interface/forms/group_attendance/save.php
A small fix to fix a problem when trying to update group attendance form
> fix update form bug

- library/reminder/src/BirthdayReminder.php
I forgot the year changes (oops)
Fixed to check the birthday passed not adding year not only month and day, as the patient that his birthday on the 31-Dec, we didn't saw the popup
> AddFixed birthday pupup to check also "past" year birthday day

- library/dialog.js
- portal/_header.php
- portal/home.php
- portal/lib/portal_mail.inc
- portal/messaging/messages.php
- portal/patient/fwk/libs/verysimple/HTTP/RequestUtil.php
- portal/report/pat_ledger.php
- portal/report/portal_custom_report.php
- portal/report/portal_patient_report.php
@bradymiller I'm not sure what is going on but I'm seeing issues with portal I know i've fixed before especially the RequestUtil.php rest library. Also, mail has php7.1 errors (this too thought was addressed) so there will be another commit to this but won't hurt to docker this branch so I can be sure the pathing works.
> Fix some missing updates

- interface/modules/zend_modules/module/Application/src/Application/Model/ApplicationTable.php
- interface/modules/zend_modules/module/Application/src/Application/Plugin/CommonPlugin.php
- interface/modules/zend_modules/module/Carecoordination/Module.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CcdController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
- interface/modules/zend_modules/module/Ccr/src/Ccr/Controller/CcrController.php
- interface/modules/zend_modules/module/Ccr/src/Ccr/Model/CcrTable.php
- interface/modules/zend_modules/module/Documents/src/Documents/Controller/DocumentsController.php
- interface/modules/zend_modules/module/Syndromicsurveillance/src/Syndromicsurveillance/Model/SyndromicsurveillanceTable.php
From following issue:
https://github.com/openemr/openemr/issues/1196
> PHP 7 fixes in care coordination by ZH Healthcare

- interface/main/calendar/find_patient_popup.php
- interface/main/messages/messages.php
- interface/patient_file/transaction/transactions.php
fix wandering '>' in patient finder.
> fix transactions delete return.

- interface/super/rules/base/library/BaseController.php
- interface/super/rules/controllers/add/controller.php
- interface/super/rules/controllers/alerts/controller.php
- interface/super/rules/controllers/browse/controller.php
- interface/super/rules/controllers/detail/controller.php
- interface/super/rules/controllers/edit/controller.php
- interface/super/rules/library/ReminderIntervals.php
> fix php warnings for Rules

- custom/zutil.cli.doc_import.php
Optional setting of owner for all imported documents.
> Update documents import utility

- interface/globals.php
HI @bradymiller 
Here we send solution of xss  vulnerability according your suggest  (#1385 ).
Thank you!
Amiel
> Prevent xss attack through css link

- gacl/admin/templates/phpgacl/object_search.tpl
https://github.com/openemr/openemr/issues/498
> security fix

- interface/main/tabs/menu/menu_updates.php
Hi.
Here I add the missing feature in the tabs layout.. hooks in the reports category. (Probably only we use this.. ;-) )
Thanks 
Amiel
> Hooks in the 'Reports' tab

- controllers/C_Document.class.php
- library/dicom_frame.php
- templates/documents/general_list.html
- templates/documents/general_view.html
Not sure about file permissions with this solution. Otherwise may need to change dicom library or bundle different.
Demo for this PR is here: http://www.open-emr.org/wiki/index.php/Development_Demo#Theta_-_Up_For_Grabs_Demo
> change viewer calling paths

- config/config.yaml
- interface/main/tabs/main.php
- interface/main/tabs/templates/menu_template.php
- interface/main/tabs/templates/patient_data_template.php
- interface/themes/rtl_tabs_style_compact.css
- interface/themes/rtl_tabs_style_full.css
- interface/themes/tabs_style_compact.css
Hi all, 
This commit purpose is to add RTL support for the tabs mod
in the commit :
1. Delete inline css
2. create  rtl_tabs_style_full.css file
Below added by bradymiller:
Can demo this PR here: http://www.open-emr.org/wiki/index.php/Development_Demo#Gamma_-_Up_For_Grabs_Demo
> Create RTL css  for tabs, delete inline css

- interface/main/tabs/templates/patient_data_template.php
- interface/themes/rtl_tabs_style_compact.css
- interface/themes/rtl_tabs_style_full.css
- interface/themes/tabs_style_compact.css
- interface/themes/tabs_style_full.css
Hi.
I fixed the bug caused by the css canges in the last [PR](https://github.com/openemr/openemr/pull/1407) 
Thanks
Amiel
> Fix css in the patient details (LTR languages)

- gacl/admin/edit_object_sections.php
- gacl/admin/templates/phpgacl/edit_object_sections.tpl
before getting into acl_admin, I thought, I can address the edit sections (by escaping html)
> escape html in edit_object_search

- interface/patient_file/summary/demographics.php
- phpfhir/classes/src/fetch_live.class.php
- phpfhir/classes/src/oeFHIRHttpClient.php
- phpfhir/classes/src/oeFHIRResource.php
- phpfhir/libs/controller/ClientAppController.php
- phpfhir/libs/controller/oeDispatcher.php
- phpfhir/providerPublishUI.php
@sjpadgett ,
Here's some minor stuff:
1. license/author/copyright Headers
2. Translations and escaping
3. ONly show Publish in demographics screen if fhir is turned on
> minor fhir code updates

- interface/main/calendar/modules/PostCalendar/pnadmin.php
- interface/modules/zend_modules/module/Installer/view/layout/layout.phtml
- interface/usergroup/usergroup_admin.php
This fix include 3 minor translation fixes 
1. Modules ->Multipledb -> tab with 'unknown' name 
2. Administration -> Users page title is : User / Groups tab name is :User / Group (added s char)
3.Administration -> Other-> Calendar  -> tab with 'unknown' name
> fix translation

- interface/main/tabs/js/tabs_view_model.js
- library/dialog.js
I believe popup menu items are best served with dialogs as they are legacy, however; may have been intentional to place in tabs and if so, can add a global to enable such. I do hate adding globals tho ...
> Add back popup dialogs for tabs U.I.

- sql/5_0_0-to-5_0_1_upgrade.sql
- sql/database.sql
Hi.
Here I add unique key to the constant_id column in the openemr_postcalendar_categories table.
Thanks
Amiel
> Make constant_id unique column

- interface/main/left_nav.php
- interface/main/messages/js/reminder_appts.js
- interface/main/messages/messages.php
- interface/patient_tracker/patient_tracker.php
JS tabsYourIt functions in frames
For now, hide KIOSK mode button - fullscreen does not work in deprecated framesets/frames environment…
Add Recall Board to left nav.
optionally shrink left nav icons to normal size not 2x.
Ensure standard headers and theme css are not over-ridden - place them after base css for messages.
Datepicker z-index in front of navbar.
Menu hover text color improvement across themes.
> Tabs->Frames Backward Compatability

- contrib/util/docker/Dockerfile
- contrib/util/ubuntu_package_scripts/development/control-php7
- contrib/util/ubuntu_package_scripts/production/control-php7
- controllers/C_Document.class.php
- interface/logview/logview.php
- interface/modules/zend_modules/module/Documents/src/Documents/Plugin/Documents.php
- interface/super/edit_globals.php
- library/log.inc
- sites/default/documents/logs_and_misc/methods/README.md
- sql/5_0_0-to-5_0_1_upgrade.sql
- sql/database.sql
- templates/documents/general_upload.html
- version.php
From this issue:
https://github.com/openemr/openemr/issues/1451
> add support for openssl (and drop mcrypt)

- controllers/C_Document.class.php
- interface/logview/logview.php
- interface/reports/audit_log_tamper_report.php
- library/crypto.php
- library/log.inc
- portal/lib/appsql.class.php
- portal/portal_payment.php
Finishing up the mcrypt to openssl migration.
> More openssl stuff 1

- interface/main/dated_reminders/dated_reminders_add.php
fix for strlen() function does not count correctly none English chars
> Fix for dated reminders: issue with none english chars

- interface/patient_file/summary/demographics_full.php
Fix display distortions caused by wide insurance company names list
> Demographics insurance section display update

- interface/usergroup/usergroup_admin.php
Code change based on the suggestion solution.
> fixed bug #1468

- interface/forms/newpatient/common.php
- interface/login/login.php
Changed the SQL not to retrieve 'no_show' record from the database.
> fixed bug #1502

- interface/modules/zend_modules/module/Multipledb/view/multipledb/multipledb/index.phtml
fix unknown title 
related to 
https://github.com/openemr/openemr/issues/1431#issuecomment-374013971
> fix title Multiple DataBase title

- interface/billing/get_claim_file.php
- interface/billing/sl_eob_process.php
- interface/billing/sl_eob_search.php
- interface/de_identification_forms/find_code_popup.php
- interface/de_identification_forms/find_immunization_popup.php
- interface/fax/fax_dispatch.php
- interface/forms/CAMOS/view.php
- interface/forms/reviewofs/view.php
- interface/main/finder/finder_navigation.php
- interface/orders/types.php
- interface/patient_file/letter.php
- interface/patient_file/transaction/add_transaction.php
- library/custom_template/personalize.php
- library/sanitize.inc.php
https://github.com/openemr/openemr/issues/1518
> security fixes

- library/js/dwv/dicom_launcher.js
- templates/documents/general_view.html
This will need to backport to v5.0.0 patch 8. Tested windows...
> Fix path for public lib asset''s

- templates/documents/general_view.html
Should work, but need to test it.
> remove pure php in a smarty script

- acl_setup.php
- acl_upgrade.php
- controllers/C_Document.class.php
- interface/patient_file/deleter.php
- library/acl.inc
- version.php
Hi.
Right now only admin can delete documents.
Here I added a new ACL for document deleting, so another users could delete files with this permission. 
The default of this ACL is only admin.
Thanks
Amiel
> New ACL for documents deleting

- interface/forms/eye_mag/a_issue.php
- interface/forms/eye_mag/css/style.css
- interface/forms/eye_mag/js/eye_base.php
- interface/forms/eye_mag/php/eye_mag_functions.php
- interface/forms/eye_mag/save.php
- interface/forms/eye_mag/view.php
- interface/themes/style_manila.css
a_issue.php - tighten display and styling
eye_mag_functions.php - define arrays for php 7.1.  Tighten display for ThemeBuilder
tab_your_it function failed due to new layer of tabs added to encounter form - fixed to open Fee Sheet from within Eye Form
Add justifiers to CPT codes in Billing Engine
> Updates in eye form for 5.0.1 release

- interface/patient_tracker/patient_tracker.php
- library/globals.inc.php
Give option for flow board begin date: Same day or beginning of work week.
Also added option for flow board end date: D7 one week ahead.
Not the most elegant selection structure, but I am young in php so I don't really know all the date math functions yet.
> Flow board begin date

- interface/patient_file/summary/demographics.php
In the patient file's recurrent appointments widget, changed the category to bold to make things clearer.
> recurring appointments categories in bold

- interface/globals.php
- interface/login/login.php
- library/auth.inc
- Show login screen if logout request is received from expired session.
- Minor changes to login screen in prep for bootstrap 4
> Logout from expired session

- interface/main/calendar/modules/PostCalendar/pntemplates/default/admin/submit_category.html
Allow use of color picker provided by modern / html5 compliant browsers.
> Use of built-in color picker for appt categories

- library/pid.inc
> fix log for viewing pid

- library/menu/src/MenuRole.php
critical bug fix for functionality when using non-admin users in patient summary screen , so expediting this fix and a soon to be released patch.
> menu fix for patient menu

- interface/main/tabs/menu/menus/patient_menus/standard.json
- sites/default/documents/custom_menus/patient_menus/Custom.json
just some minor patient menu cleanup. testing well and will bring in after travis pass
> patient menu cleanup

- interface/patient_file/front_payment.php
Oops, I suppose, is all I can say about this...
> prepayment test missing in payment validation.

- interface/main/messages/js/reminder_appts.js
- interface/main/messages/save.php
- library/MedEx/API.php
> Recall Populate using $pid from Session

- library/dialog.js
New option frameContent useful for document display or dynamically creating content in dialogs.
> dlgopen update to allow dynamic variable iframe content in dialog.

- interface/forms/misc_billing_options/new.php
fix reported for bug reported on forum https://community.open-emr.org/t/misc-billing-options-bug-warning-data-loss-potential/10031?u=stephenwaite and is testing well
> fix sql query for new.php misc bill options

- interface/main/finder/multi_patients_finder.php
- interface/main/finder/multi_patients_finder_ajax.php
- interface/main/messages/messages.php
Hi.
Here new feature for messages screen, enables to create list of patients and send message to the list.
Thanks
Amiel   
Up For Grabs demo for this PR is here: https://www.open-emr.org/wiki/index.php/Development_Demo#Lambda_-_Up_For_Grabs_Demo
> New popup for multi selecting in the messages screen

- interface/main/finder/dynamic_finder.php
- interface/main/finder/dynamic_finder_ajax.php
- library/ajax/user_settings.php
- library/globals.inc.php
This is a new feature for the Patient Finder.
It enables the user to control the type of search (exact/like) in the patient finder.
This is done by the new global "Search method in patient list"  under Features
> Add new global to control the search exact/like int the Patient Finder

- interface/fax/fax_dispatch.php
- interface/fax/faxq.php
Change window popups to dialogs and bring dependencies up to date. Fix for forum issue: https://community.open-emr.org/t/copying-pages-to-patient-chart-from-fax-dispatch-not-working-since-v5-0-1-upgrade/10032
> Fax module update

- library/billing/src/Claim.php
- library/gen_x12_837.inc.php
hopefully won't rock the billing boat ;) too bad
> begin to support DME billing from misc_billing_options form

- library/MedEx/API.php
> MedEx updates

- interface/reports/collections_report.php
fix prior commit, https://github.com/openemr/openemr/commit/9700418b0adc6f83a98b1353391f2930d1a57751
> fix php warning

- interface/main/finder/dynamic_finder.php
- interface/main/finder/dynamic_finder_ajax.php
This fix contain 2 small fixes 
1. small HTML fix for the patient finder added label for css and uniformity purposes 
2. make the like search the default search method
related to 
https://github.com/openemr/openemr/pull/1571/
> fix html uniformity

- library/gen_hcfa_1500.inc.php
- library/gen_hcfa_1500_02_12.inc.php
- library/globals.inc.php
thanks to @juggernautsei for pointing out the problem and posting solution; went ahead and removed the old hcfa 1500 since it's no longer in use
> fix onset date, remove 08/05 NUCC 1500 form from globals and logic

- interface/weno/admin.php
- interface/weno/validate.php
- library/globals.inc.php
Please add this to the next patch.
> Pharmacies are no longer required to be imported

- portal/get_patient_info.php
Still issue on Alpine where can't read from document onsite template directory. Permissions okay.
> multisite fix for portal two

- library/gen_x12_837.inc.php
another billing fix, jeez, i'm sorry...
> remove 2010AB REF segment for 5010

- library/globals.inc.php
- library/reminder/src/BirthdayReminder.php
This is a small feature that allows the admin to configure the OpenEMR  (through Global Settings)
to automatically turn off the birthday alert after 28 days from the birthday date arrived .
> Add  another option to the birthday alert -only 28 days after 

- interface/main/calendar/add_edit_event.php
- interface/patient_tracker/patient_tracker.php
- library/appointments.inc.php
1. add edit event fails when save edited single provider recurring events for future and current. sql insert fails form_provider is array.
2. ensure provider is user.
3. ensure while loop doesn't race.
> Appointments and Flow Board issues

- interface/main/calendar/add_edit_event.php
- interface/patient_tracker/patient_tracker.php
- library/appointments.inc.php
Reverts openemr/openemr#1633 Still issue on Linux/Alpine???
> Revert "Appointments and Flow Board issues"

- interface/main/calendar/add_edit_event.php
- interface/patient_tracker/patient_tracker.php
1. add edit event fails when save edited single provider recurring events for future and current. sql insert fails as form_provider is array.
2. ensure provider is user in flowboard.
> Recurring event save issue

- contrib/util/express.php
- docker-compose.yml
- interface/login/login.php
- interface/usergroup/usergroup_admin.php
- interface/usergroup/usergroup_admin_add.php
- library/auth.inc
- library/authentication/login_operations.php
- library/classes/Installer.class.php
- setup.php
https://community.open-emr.org/t/the-mysql-8-challenge-for-developers/10138
(yes, I know, I have proposed a solution to my own challenge... :) )
> mysql 8 fixes

- interface/main/backup.php
> Prevent out of memory on download.

- interface/usergroup/adminacl.php
testing well and will bring this in via merge (to keep correct author attribution) after pass travis
For following issue:
https://github.com/openemr/openemr/issues/1641
> acl admin username fix

- interface/forms/fee_sheet/review/views/justify_display.php
interface/forms/fee_sheet/review/views/justify_display.php
> Minor modification to fee sheet justify display popup to make it bootstrap compatible

- ccdaservice/README.md
- ccdaservice/package.json
- ccdaservice/serveccda.js
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
Add HIE data hook for local ccda service. CCM data discrepancies and bugs.
> Update CCDA  phase 1.

- library/core/src/Header.php
> Simple fix to resolve the notice

- library/classes/Installer.class.php
revision of this PR (expedited for a 5.0.1 patch)(note author is @zbig01 ):
https://github.com/openemr/openemr/pull/1663
> install fix related to mysql

- sql/database.sql
looking for simple solution to #1671
> make icd9 inactive and change justify default to icd10

- interface/usergroup/addrbook_list.php
- library/dialog.js
- templates/documents/general_list.html
added a hook for address book to return selected in a callback to dlgopen.
minor fix for select patient pull down to limit return list in new documents.
added dlgclose to be in same scope with dlgopen.
> Minor fixes and updates

- Documentation/help_files/fee_sheet_help.php
- interface/help_modal.php
help_modal.php added to make the help modal work
> Added missing help_modal.php file and minor styling fee_sheet_help.php

- interface/forms/LBF/new.php
A nation note context name with spaces did not pass correctly.
> encode custom_template calling Url.

- interface/patient_file/encounter/superbill_custom_full.php
This will display the entry under Admin->Lists->Service Category for the code's selection under Admin->Codes.
It's testing fine.
> add category to admin->codes

- Documentation/help_files/common_help.php
- interface/billing/billing_report.php
- interface/forms/newpatient/common.php
- library/globals.inc.php
New encounter form restyled , now uses the styleguide based stylesheets
- Documentation/help_files/common_help.php
- interface/forms/newpatient/common.php
Up for grabs demo for this PR is here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Lambda_-_Up_For_Grabs_Demo
> Restyled New Encounter Form with Help file

- config/config.yaml
- interface/billing/sl_eob_search.php
- interface/help_modal.php
- interface/usergroup/adminacl.php
Added ability to drag and resize help modal
Changed two files to use jquery-ui tooltip instead of bootstrap tooltip
````openemr/interface/billing/sl_eob_search.php````
````openemr/interface/usergroup/adminacl.php````
> Drag and resize help modal using jquery-ui

- interface/patient_file/encounter/find_code_dynamic.php
Invokes bootstrap as part of standard header and attaches table class to the datatable results.
> Use standard components in code finder dialog

- Documentation/help_files/cms_1500_help.php
- interface/forms/misc_billing_options/new.php
- library/globals.inc.php
Documentation/help_files/cms_1500_help.php
interface/forms/misc_billing_options/new.php
Up For Grabs demo for this is here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Beta_-_Up_For_Grabs_Demo
> Restyled  Miscellaneous Billing Options HCFA with help file

- interface/forms/vitals/templates/vitals/general_new.html
- interface/patient_file/encounter/trend_form.php
Up For Grabs demo for this is here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Gamma_-_Up_For_Grabs_Demo
> Restyled Form Vitals

- interface/patient_file/summary/add_edit_issue.php
Invokes bootstrap as part of standard header.
> Use standard components in issue dialog

- library/gen_x12_837.inc.php
could bring this into the next patch along with another bug report
https://community.open-emr.org/t/1500-form-box-12-box-14-box-24-i-j/10361/5?u=stephenwaite
> remove else that was logging

- interface/forms/procedure_order/new.php
- library/globals.inc.php
Up For Grabs demo of this PR is here:
http://www.open-emr.org/wiki/index.php/Development_Demo#Beta_-_Up_For_Grabs_Demo
> Restyled Procedure order to match the other restyled pages

- Documentation/help_files/message_center_help.php
- interface/main/dated_reminders/dated_reminders.php
- interface/main/dated_reminders/dated_reminders_add.php
- interface/main/dated_reminders/dated_reminders_log.php
- interface/main/messages/messages.php
- library/MedEx/API.php
- library/dated_reminder_functions.php
- library/globals.inc.php
Message captions more meaningful, changed links to buttons, restyled dated
reminders to have the ability to display more than 5 reminders by
adding scroll bar now set to show 30 days reminders by default
All aspects of the message center are fully responsive
library/MedEx/API.php
interface/main/messages/messages.php
Documentation/help_files/message_center_help.php
library/dated_reminder_functions.php
interface/main/dated_reminders/dated_reminders.php
interface/main/dated_reminders/dated_reminders_add.php
interface/main/dated_reminders/dated_reminders_log.php
https://www.open-emr.org/wiki/index.php/Development_Demo#Beta_-_Up_For_Grabs_Demo
> Restyled messages, dated reminders and added styling to integrate Recall Board

- interface/forms/LBF/report.php
- library/options.inc.php
Display key value for the layout item when key is not found in associated list(s)
> Layout item display when list entry are missing

- common/database/Connector.php
- contrib/util/docker/README.md
- contrib/util/docker/dockers/dev-nginx/nginx.conf
- contrib/util/docker/dockers/dev-php-fpm-7-1-redis/Dockerfile
- contrib/util/docker/dockers/dev-php-fpm-7-1-redis/php.ini
- contrib/util/docker/dockers/dev-php-fpm-7-2-redis/Dockerfile
- contrib/util/docker/dockers/dev-php-fpm-7-2-redis/php.ini
- docker-compose.yml
This is a work in progress. Need to fix a doctrine error with redis first (hopefully via a doctrine version uprade).
> add redis to docker dev env

- library/dialog.js
Too try and get out of BS4's way.
> rename modal classes to be unique to dlgopen

- interface/billing/billing_report.php
- interface/billing/ub04_form.php
- interface/forms/misc_billing_options/new.php
- interface/forms/misc_billing_options/save.php
- library/dialog.js
style changes to better support institutional billing.
dlgopen getting closer to removing include_opener.php.
Move ub04 form edit to dialog.
Up For Grabs demo for this PR is here: https://www.open-emr.org/wiki/index.php/Development_Demo#Gamma_-_Up_For_Grabs_Demo
> Billing manager new feature add/edit MBO form.

- interface/patient_file/encounter/trend_form.php
Currently when there is only 1 vital form the alert states that there is no data.
I changed it to 'not enough data'.
Additionally if no item name was passed added 'This item' instead of leaving the name blank (otherwise the beginning of the sentence is just blank.
> small fix for graph js alert

- interface/patient_file/encounter/find_code_dynamic_ajax.php
Issue being fixed:
When there are no results returned from AJAX, the pagination shows "filtered from NaN ...".
After the fix when there are no results there is no pagination.
> fixed codes search pagination

- library/gen_x12_837.inc.php
debugging thanks to the forum, https://community.open-emr.org/t/1500-form-box-12-box-14-box-24-i-j/10361/15
> fix SBR group name, number and fix duplicate onset date

- interface/patient_file/encounter/find_code_dynamic.php
Hi, 
Just added an id to the search bar so can customize styling for this popup.
Thanks
> added id for search bar styling

- Documentation/help_files/message_center_help.php
Documentation/help_files/message_center_help.php
> Minor addition to message center  help file

- interface/main/tabs/js/tabs_view_model.js
- interface/main/tabs/main.php
Made the "New" word in tab title translatable.
> tab title translation

- interface/super/edit_list.php
> edit_list script updates

- portal/add_edit_event_user.php
- portal/home.php
- portal/import_template.php
Appointment title not displaying on edit.
Add appointment status title in UI presentation.
Fix appointment duration default.
> Portal Two appointments bug fix

- templates/prescription/general_edit.html
- templates/prescription/general_list.html
- templates/prescription/general_send.html
I added am id to several elements so we can use them in css selectors.
> added id so can select element

- interface/forms/procedure_order/new.php
- interface/orders/find_order_popup.php
- interface/orders/types.php
- interface/orders/types_edit.php
styled code pickers and updated dependencies.
minor style of procedure configuration and dependency update.
consolidated procedure form to better handle questions and slim down form height.
> Procedures support update

- interface/main/tabs/js/frame_proxies.js
- interface/main/tabs/js/tabs_view_model.js
- interface/main/tabs/js/user_data_view_model.js
Hi.
Here I suggest solution for the issue #1749 
Now the tab load and only then change.
Thanks
Amiel
> Fix tab transition flow

- interface/main/calendar/add_edit_event.php
by @epsdky 
From issue reported on forum:
https://community.open-emr.org/t/scheduling-failures/10363
> Fix for issue reported in 'Scheduling Failures' on forum

- interface/forms/procedure_order/new.php
- interface/orders/find_order_popup.php
- interface/orders/list_reports.php
- interface/orders/patient_match_dialog.php
- interface/orders/qoe.inc.php
- interface/orders/types.php
- interface/orders/types_ajax.php
- interface/orders/types_edit.php
- sql/5_0_1-to-5_0_2_upgrade.sql
- sql/database.sql
1. New feature to allow adding custom groups of favorite orders.
a.  Add group feature in configuration
b. imports all orders in favorite group from configuration into form.
c. added favorite search to order picker.
d. can give a default icd code to favorite order.
2. Procedure form bug fixes.
3. New delete procedure order items button in forms order list.
4. Updated QOE dependencies, calendar and formatting.
5. List reports for electronic results now will help resolve orphaned orders. (missing order or patient).
Below added by bradymiller:
Can test on following Up For Grabs demo:
https://www.open-emr.org/wiki/index.php/Development_Demo#Beta_-_Up_For_Grabs_Demo
> Update Procedures Functionality

- interface/fax/fax_view.php
- library/log.inc
These fixes will also go in next 5.0.1 patch
> some fixes

- interface/patient_file/summary/stats.php
Added an ACO for the prescription widget on the edit button
> Added ACO to prescriptions edit widget

- interface/globals.php
Changed this to avoid odd bugs down the road.
> minor cleanup in theme code

- interface/patient_file/summary/demographics.php
- library/formatting.inc.php
- library/patient.inc
first stab at https://community.open-emr.org/t/a-thing-or-two-about-deceased-patients/10568
Up for grabs demo for this PR is here: https://www.open-emr.org/wiki/index.php/Development_Demo#Alpha_-_Up_For_Grabs_Demo
> pt summary deceased display fix

- interface/main/calendar/includes/pnAPI.php
- interface/main/calendar/modules/PostCalendar/pnuser.php
- interface/main/calendar/modules/PostCalendar/pnuserapi.php
> calendar fixes

- interface/forms/newpatient/common.php
Fix new encounter window (when locked) in RTL languages
> fix new encounter RTL

- interface/patient_tracker/patient_tracker.php
Hi.
We have found that flow board loaded very slowly in the large amount of appointments -
Discussion about this problem - https://community.open-emr.org/t/flow-board-is-very-slow/9781 
I made a small change in the logic of the flow board code and I load the data using ajax also in the first loading. With this change It's possible to add loader while the loading time (only for first loading or manual loading not for loading by timer).
while developing I found that the summaries of the appointments in the title of table are not refreshed in the ajax process (by filter or timer) and I fixed it.     
This is necessary fix because without the loader the user sees blank page until all the appointments are loaded and he don't know why it not work..
Thanks
Amiel
> Loader in the flow board

- sql/database.sql
Hi @bradymiller 
Sorry I've found sql error from my last[ pull request ](https://github.com/openemr/openemr/pull/1797).
**The installation doesn't work now.** 
Please merge it ASAP.
Sorry..
Amiel
> Fix sql error in the installation file

- portal/lib/doc_lib.php
- portal/patient/scripts/app/onsitedocuments.js
- portal/patient/templates/OnsiteDocumentListView.tpl.php
Fix not saving to audited patient but current patient instead.
> Portal Dashboard audit chart document save bug fix.

- controllers/C_Document.class.php
- interface/forms/LBF/new.php
- interface/super/edit_globals.php
- interface/super/edit_layout.php
- interface/super/layout_listitems_ajax.php
- interface/super/layout_service_codes.php
- interface/super/load_codes.php
- library/ajax/ccr_import_ajax.php
- library/ajax/code_attributes_ajax.php
- library/ajax/collect_new_report_id.php
- library/ajax/offsite_portal_ajax.php
- templates/documents/general_view.html
> csrf ongoing work

- interface/patient_file/transaction/transactions.php
- library/options.inc.php
Fixed issue #1825
The value of the Type of transaction in Transactions page is not being displayed as intended
> minor bug fix in patient transactions

- contrib/forms/body_composition/new.php
- contrib/forms/body_composition/report.php
- contrib/forms/body_composition/view.php
- contrib/forms/clinical_notes/new.php
- contrib/forms/clinical_notes/report.php
- contrib/forms/clinical_notes/view.php
- contrib/forms/contacts/new.php
- contrib/forms/contacts/report.php
- contrib/forms/contacts/save.php
- contrib/forms/contacts/view.php
- contrib/forms/evaluation/C_FormEvaluation.class.php
- contrib/forms/evaluation/FormEvaluation.class.php
- contrib/forms/evaluation/new.php
- contrib/forms/evaluation/report.php
- contrib/forms/evaluation/save.php
- contrib/forms/evaluation/templates/evaluation/general_new.html
- contrib/forms/evaluation/view.php
> bug fixes by Daniel

- interface/forms/CAMOS/admin.php
- interface/forms/CAMOS/ajax_save.php
- interface/forms/CAMOS/content_parser.php
- interface/forms/CAMOS/help.html
- interface/forms/CAMOS/new.php
- interface/forms/CAMOS/notegen.php
- interface/forms/CAMOS/print.php
- interface/forms/CAMOS/report.php
- interface/forms/CAMOS/rx_print.php
- interface/forms/CAMOS/save.php
- interface/forms/CAMOS/view.php
> CAMOS updates

- portal/import_template_ui.php
- portal/messaging/messages.php
- portal/messaging/secure_chat.php
- portal/patient/templates/OnsiteDocumentListView.tpl.php
- portal/patient/templates/_FormsHeader.tpl.php
- portal/patient/templates/_Header.tpl.php
- portal/patient/templates/_ProviderHeader.tpl.php
- portal/portal_payment.php
per issue:
https://github.com/openemr/openemr/issues/1847
> portal fixes in jquery asset path

- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/header.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
- interface/main/dated_reminders/dated_reminders_add.php
- interface/main/messages/messages.php
- interface/patient_file/summary/pnotes_full.php
- interface/patient_file/summary/pnotes_full_add.php
- interface/themes/ajax_calendar.css
- interface/themes/colors/openemr5/bootstrap.scss
- interface/themes/core/forms.scss
- interface/themes/core/patient/notes.scss
- interface/themes/oe-common/acl-common.scss
- interface/themes/rtl.scss
- interface/therapy_groups/therapy_groups_views/groupDetailsGeneralData.php
- interface/therapy_groups/therapy_groups_views/groupDetailsParticipants.php
Hi.
I send here solutions for  UI's bugs we have found.
I attached screenshots of the bugs I fixed.
Regarding  the checkbox and radio inputs, In the openemr/interface/themes/colors/openemr5/bootstrap.scss file was been the lines - 
```
input[type=checkbox], input[type=radio] {
margin: 4px !important;
}
```
Those lines disrupted all the checkbox and radio buttons in all the RTL screens. I removed it and the UI looks good in the LTR also, I found a little problem in the ACL screen and I fixed it specific for this page. I think I bad idea to overwrite the bootstrap classes it could make problems in the future developments.   
Example of checkbox and radio buttons -
Direction of arrows
Lines broken (LTR also)
Calendar header is LTR
Thank you
Amiel
> Style fixes (Mainly RTL)

- interface/forms_admin/forms_admin.php
- library/registry.inc
> some more fixes

- interface/billing/sl_eob_search.php
- interface/forms/fee_sheet/new.php
> more bug fixes

- interface/patient_file/history/encounters.php
- interface/themes/rtl.scss
- interface/themes/rtl_style_pdf.css
Hi.
2 small fixes for RTL languages.
Thanks
Amiel
> 2 minor RTL fixes

- interface/patient_tracker/patient_tracker.php
- interface/therapy_groups/therapy_groups_views/groupDetailsParticipants.php
Hi.
Here 2 UI fixes.
Thanks
Amiel
> 2 UI fixes

- portal/messaging/messages.php
- portal/messaging/secure_chat.php
- portal/patient/scripts/app/onsitedocuments.js
- portal/portal_payment.php
- portal/sign/assets/signpad.css
- portal/sign/css/signer.css
- Revamped Patient Secure Chat
- Bug fix online payment where send receipt not working.
- Signature in documents & dashboard fixes(support admin signature now in audits)
> Portal Two update and bug fixes

- interface/drugs/add_edit_drug.php
- library/dialog.js
https://community.open-emr.org/t/inventory-related-codes-selection/10744
Fix dialog.js not auto loading jquery if missing.
Fixes Add/Edit popup in Inventory.
Restyle add_edit_drug.php for Inventory
> Fix Forum Issue Inventory - Related codes selection

- composer.json
- composer.lock
- interface/main/left_nav.php
- interface/main/main_screen.php
- interface/main/tabs/menu/menus/standard.json
- interface/usergroup/mfa_registrations.php
- interface/usergroup/mfa_u2f.php
- interface/usergroup/user_admin.php
- interface/usergroup/usergroup_admin.php
- library/js/u2f-api.js
- sites/default/documents/custom_menus/Custom.json
- sql/5_0_1-to-5_0_2_upgrade.sql
- sql/database.sql
- version.php
This is for USB U2F key support for Two Factor Authentication. Example products:
https://www.yubico.com/product/security-key-by-yubico/
https://www.key-id.com/key-id-fido-u2f-security-key-online-security/
https://www.ftsafe.com/Products/FIDO/NFC
U2F devices are relatively inexpensive, very secure and easy to use. Chrome and Firefox have built-in support for them.
Comments welcomed!
> Implementing U2F authentication.

- gulpfile.js
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
- interface/themes/ajax_calendar.css
- package-lock.json
- package.json
Reported in #1785
This PR adds icon that a user can click to make appointments semi-transparent, allowing them to see an interact with Provider times underneath. This also makes it easier to schedule multiple appointments at the same start time via the calendar interface.
Also fixes css streaming in gulpfile when using `npm run dev`
Before:
After (GIF):
See screenshots:
Also note that this helps schedule multiple appointments at once (GIF):
> Calendar Patient and Provider times are overlapping

- interface/reports/edi_270.php
- library/edi.inc
starting work on https://community.open-emr.org/t/eligibility-response-not-parsing-into-table/8956/9?u=stephenwaite
will test soon
> change eligibility batch from ssn to policy number, minor fix to filename with extra dot

- portal/lib/doc_lib.php
- portal/patient/scripts/app/onsitedocuments.js
Fix disable admin signature for new templates in patient portal.
Fix send reviewed template doc to correct category.
> Portal bug fixes

- library/globals.inc.php
- portal/_header.php
- portal/home.php
Allow disable of Secure Chat and Appointments features.
> Add Portal Two Features

- interface/billing/billing_report.php
- interface/billing/era_payments.php
- interface/billing/new_payment.php
- interface/billing/search_payments.php
- interface/billing/sl_eob_search.php
- interface/expand_contract_js.php
- interface/forms/fee_sheet/new.php
- interface/themes/oe-common/help-files-common.scss
- library/ajax/user_settings.php
- library/expand_contract_inc.php
- library/globals.inc.php
- library/user.inc
removed POST/GET method for changing state of pages from Expanded to Centered
mode
Now using functions setUserSetting() and getUserSetting() to achieve user
specific state for the pages
Also added Features tab in Edit User Settings for global user level changes
below added by bradymiller
Up for grabs demo for this PR is here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Mu_-_Up_For_Grabs_Demo
> Expandable_forms_user_specific

- interface/forms/newGroupEncounter/common.php
Hi.
Here I redesign the new group encounter form like patient's form.
Thanks
Amiel
> Redesign of new group encounter form like patient's form

- CONTRIBUTING.md
- contrib/util/docker/README.md
- contrib/util/docker/docker-compose.yml
- docker-compose.yml
hi @MatthewVi and @d3sandoval ,
Here's a couple changes in the docker dev environments to make access to the underlying sql database(s) easier and more flexible.
thoughts?
-brady
> improved sql access to the docker dev environments

- interface/globals.php
hi Brady, thanks for bringing in the previous pull request. Here's a minor edit.
> clean up docblock

- interface/billing/sl_eob_invoice.php
- interface/billing/sl_eob_search.php
Fix zero pay/adjust entry causing unwanted actions
Added persistent Disable Auto Adjustments checkbox on Search Title bar.
- Sticky user option to disable auto calc of adjustments.
Added new button to stay in invoice Save and Stay.
Fix to refresh invoice search form after updates from invoice.
Minor styling changes.
> EOB invoice fixes. issue #1880

- interface/main/messages/messages.php
- interface/themes/style_manila.scss
tabcontainer was smaller than the underlying div.
> Display fix: width

- interface/main/messages/messages.php
- interface/themes/style_manila.scss
Currently the message center is sorted by patient last name.  Work flow analysis suggests it is more efficient to default sort by date received, with the most recent messages at the top.
> Sort Order

- interface/billing/sl_eob_invoice.php
- interface/billing/sl_eob_search.php
If in adjustment disabled mode a zero payment and/or adjustment with a reason will post.
> More zero adjustment fix

- interface/billing/sl_eob_invoice.php
- interface/billing/sl_eob_search.php
- interface/main/tabs/menu/menus/standard.json
- invoice now auto advances/persists insurance to reflect insurance done.
- New Past Encounter Billing View button in invoice.
- Posting tab now persists when patient changes.
> More Postings EOB features

- interface/billing/search_payments.php
- interface/main/finder/dynamic_finder.php
@bradymiller 
restyled patient-finder
> restyled patient-finder

- interface/main/backup.php
> backup script changes

- interface/billing/sl_eob_search.php
- portal/lib/portal_mail.inc
- portal/messaging/messages.php
- log message soft delete to audit logs
- fix eob search for All alerts
- cleanup dependencies.
> Portal Secure Messaging Audits

- library/reminder/src/BirthdayReminder.php
> fix birthday alert 

- interface/main/backuplog.php
- interface/main/blank.php
- interface/main/daemon_frame.php
- interface/main/display_documents.php
- interface/main/ippf_export.php
- interface/main/left_nav.php
- interface/main/main_info.php
- interface/main/main_screen.php
- interface/main/main_title.php
- interface/main/pwd_expires_alert.php
- interface/main/tabs/js/tabs_view_model.js
- interface/main/tabs/main.php
- library/ajax/unset_session_ajax.php
> another one of those bug fix commits

- interface/forms/eye_mag/view.php
from following issue:
https://github.com/openemr/openemr/issues/1940
> bug fix in eye form - bug report by serixscorpio

- contrib/util/language_translations/collectConstants.pl
- interface/main/left_nav.php
- interface/orders/orders_results.php
- interface/patient_file/summary/demographics.php
- interface/patient_file/summary/demographics_full.php
- interface/patient_file/summary/pnotes_full.php
- interface/patient_file/summary/pnotes_full_add.php
- library/ajax/left_nav_encounter_ajax.php
- library/htmlspecialchars.inc.php
hi @isears ,
Turns out that the mechanism in https://github.com/openemr/openemr/pull/1933 will likely not be international. I did some internet sleuthing and turns out json_encode is a potential good way to do js escaping in the project. Here I am just doing the escaping on the line in your PR (and it seems to kill XSS attacks and also treat apostrophes and quotes well in paitent names). Thoughts?
(btw, @isears, whatever we come up with, plan to make you the author on the first commit :) )
(@sunsetsystems , do you have any thoughts on this js escaping mechanism?)
thanks,
-brady
> using json_encode to escape js stuff

- interface/reports/patient_list.php
add translations to city,state,street
> fix translations for this report

- interface/forms/eye_mag/js/eye_base.php
Fix Corneal K readings bug.
Fix Billing module for a code found in multiple locations.
> Eye JS Bug Fix

- portal/_header.php
- portal/home.php
- portal/patient/libs/Controller/ProviderController.php
- portal/sign/css/signer.css
Separated Patient Report Content feature disable from ccda disable.
> Dashboard User signature change fix.

- interface/main/tabs/menu/menus/standard.json
- interface/new/new_comprehensive.php
- sites/default/documents/custom_menus/Custom.json
Menu item Patient/Client > Summary changed to Dashboard
interface/new/new_comprehensive.php
interface/main/tabs/menu/menus/standard.json
sites/default/documents/custom_menus/Custom.json
> Search Add Patient restyled as a centered form

- library/billing/src/Claim.php
- library/billing/src/X12837P.php
gonna test this fix to 2010BA loop and adding service facility in x12 837
> path to pay to provider, fix facility logic

- interface/patient_file/summary/labdata.php
fix to grabbing wrong patient name dob in printable report
> fix trend print labdata

- controllers/C_Document.class.php
- library/options.inc.php
- library/patient.inc
https://community.open-emr.org/t/error-log-warning-array-expected-parameter-2/10992
Numeric data type modifiers "012" where not caught as options.
> in_array() warning Reported on Forum by Sherwin

- interface/super/edit_globals.php
- interface/super/edit_layout.php
- interface/super/edit_layout_props.php
- interface/super/edit_list.php
- interface/super/layout_listitems_ajax.php
- interface/super/layout_service_codes.php
- interface/super/load_codes.php
- interface/super/manage_document_templates.php
- interface/super/manage_site_files.php
> some more bug fixes

- controllers/C_Prescription.class.php
- interface/weno/RxLog.php
- interface/weno/admin.php
- interface/weno/ajax_sample_code.php
- interface/weno/confirm.php
- interface/weno/drug-drug.php
- interface/weno/drugPaidInsert.php
- interface/weno/formularyInsert.php
- interface/weno/formularyUpdate.php
- interface/weno/import_pharmacies.php
- interface/weno/jsonScript.php
- interface/weno/markTx.php
- interface/weno/validate.php
- templates/prescription/general_list.html
hi @juggernautsei ,
I'm just doing some minor security hardening the codebase and this shouldn't change the weno featureset.
One question I have is that the following scripts are not called anywhere:
drug-drug.php
formularyUpdate.php
formularyInsert.php
import_pharmacies.php
RxLog.php
Is that because these scripts are not used?
thanks,
-brady
> minor bug fixes in weno code

- interface/de_identification_forms/de_identification_screen2.php
- interface/forms/eye_mag/SpectacleRx.php
- interface/forms/eye_mag/php/Anything_simple.php
- interface/forms/eye_mag/report.php
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
- interface/usergroup/ssl_certificates_admin.php
- library/create_ssl_certificate.php
@sjpadgett ,
Finished the job :)
-brady
> fixes to nonexistent $["webserver_root"]

- _rest_config.php
- _rest_routes.inc.php
- apis/dispatch.php
- rest_controllers/AuthRestController.php
- create separate fhir and oemr api route arrays
- added context to dispatch i.e running clients in authenticated session
- migrating Fhir Provider Client to REST
- add method for non token acl check
> Rest api capabilities upgrade

- interface/eRx.php
- interface/forms/track_anything/history.php
- interface/patient_file/encounter/delete_form.php
- interface/patient_file/history/encounters.php
- interface/patient_file/summary/labdata.php
- interface/reports/edi_271.php
- package.json
- templates/prescription/general_list.html
part of following issue:
https://github.com/openemr/openemr/issues/842
> Some jquery updates

- interface/billing/billing_report.php
- interface/billing/era_payments.php
- interface/billing/new_payment.php
- interface/billing/search_payments.php
- interface/forms/fee_sheet/new.php
- interface/patient_file/front_payment.php
- interface/patient_file/pos_checkout.php
- library/globals.inc.php
- library/js/oeUI/oeFileUploads.js
- library/oeUI/src/OemrUI.php
Converted all user facing files in Fees to use the OemrUI class
> using  OemrUI class  in Fees > Fee Sheet, Billing, Payment, Checkout, Batch Payments, Posting

- contrib/forms/body_composition/new.php
- contrib/forms/body_composition/view.php
- contrib/forms/clinical_notes/new.php
- contrib/forms/clinical_notes/view.php
- contrib/forms/hist_exam_plan/new.php
- contrib/forms/hist_exam_plan/view.php
- contrib/forms/sports_fitness/new.php
- contrib/forms/sports_fitness/view.php
- interface/billing/sl_eob_process.php
- interface/forms/physical_exam/edit_diagnoses.php
- interface/orders/procedure_provider_edit.php
- interface/super/rules/controllers/edit/view/add_criteria.php
> Remove empty in-line <script> tags

- interface/patient_file/summary/pnotes_full.php
- interface/patient_file/summary/pnotes_full_add.php
- library/pnotes.inc
- sql/5_0_1-to-5_0_2_upgrade.sql
- sql/database.sql
Hi.
Here I made some improvements in the patient messages.
1. Style fixes:
- Hide  tabs 'index'/'sent items' if offsite patient portal is turn off
- Put all the buttons in single row
-  Adding bootstrap classes
Before -
After - 
2. Adding 2 columns to pnote table - update_date and update_by for tracking on the current status of message. 
Thanks
Amiel
> Changes in the patient messages

- interface/forms/newpatient/common.php
- library/classes/POSRef.class.php
-  Add Telemedicine POS ie. 02
- Fix encounter newpatient form logic flow
- Fix POS default logic
- Fix not selecting saved POS on encounter view(chance of selecting multiple POS on list init)
- Back ported to v5.0.1 for patch
Back port 5.0.1 commit is here:https://github.com/openemr/openemr/pull/1895/commits/43cd97c48427169c7bd3506526a49b7a9d1bb11c
> Fix encounter POS

- controllers/C_Prescription.class.php
- library/globals.inc.php
- templates/prescription/general_list.html
- version.php
Continued from the following PR: https://github.com/openemr/openemr/pull/2036
Also added a global, fixed some bugs, and used bootstrap
> drug drug interaction update by Sherwin

- library/globals.inc.php
- portal/_header.php
- portal/home.php
- add disable patient ledger
- fix hide menu in Reports
requested here: https://community.open-emr.org/t/how-to-hide-appointments-menu-from-patient-portal/11223
> Portal Update Forum Request 

- library/globals.inc.php
- portal/add_edit_event_user.php
- portal/get_patient_info.php
- portal/index.php
Forum request https://community.open-emr.org/t/how-to-do-these-modification/11235
Will leave this open to add appointment change notifications to portal feature request from forum
https://community.open-emr.org/t/patient-portal-is-there-a-notification-when-an-appointment-is-made/11244
> Add enforce email for portal logon (default) and Appointment notifications.

- interface/main/display_documents.php
Fixes #2071 
Up For Grabs demo for this PR:
https://www.open-emr.org/wiki/index.php/Development_Demo#Gamma_-_Up_For_Grabs_Demo
> Replaced qtip2 tooltip with plain javascript tooltip

- interface/main/display_documents.php
- library/payment_jav.inc.php
Testing well and will bring in after pass travis
> Minor updates 1

- interface/patient_file/summary/pnotes_full.php
Hi.
Adding translation in the patient notes.
Thanks
Amiel
> Translation fix

- sql/5_0_0-to-5_0_1_upgrade.sql
- sql/5_0_1-to-5_0_2_upgrade.sql
Possible fix for this issue:
https://github.com/openemr/openemr/issues/2049
> possible fix for the sql upgrade

- sql/5_0_1-to-5_0_2_upgrade.sql
- sql/database.sql
- version.php
@sjpadgett ,
This fixes the pnotes that are created from the portal
@matrix-amiel,
This does not appear to break anything in main part of OpenEMR
bringing this in now, since need to expedite this fix (since it is in the database upgrade script)
-brady
> pnotes portal fix

- interface/forms/eye_mag/SpectacleRx.php
- interface/forms/eye_mag/a_issue.php
- interface/forms/eye_mag/help.php
- interface/forms/eye_mag/js/eye_base.php
- interface/forms/eye_mag/php/Anything_simple.php
- interface/forms/eye_mag/view.php
- interface/main/display_documents.php
For #2083 - Commented out all uses of qtip2
Up For Grabs demo for this PR at:
https://www.open-emr.org/wiki/index.php/Development_Demo#Gamma_-_Up_For_Grabs_Demo
> Remove qtip2

- library/spreadsheet.inc.php
PR for issue #2095 for spreadsheet.inc.php
> Bind sql parameters spreadsheet (#2095)

- composer.json
- composer.lock
- interface/main/tabs/js/user_data_view_model.js
- interface/main/tabs/main.php
- interface/main/tabs/templates/patient_data_template.php
- library/billing/src/PaymentGateway.php
- library/dated_reminder_functions.php
- library/globals.inc.php
- portal/_header.php
- portal/assets/css/style.css
- portal/home.php
- portal/lib/appsql.class.php
- portal/lib/paylib.php
- portal/patient/scripts/app/onsiteactivityviews.js
- portal/portal_payment.php
- portal/sign/css/signer.css
-  Implement Authorize.Net and Stripe processing -- designed to easily add more vendors.
-  Modify payment workflows.
-  Add new Portal Alert for pending payments
bradymiller added below:
Up for grabs demo for this PR is at: https://www.open-emr.org/wiki/index.php/Development_Demo#Mu_-_Up_For_Grabs_Demo
> Portal V2 Online Payment Universal Gateway.

- interface/eRxXMLBuilder.php
https://community.open-emr.org/t/newcrop-problems-after-upgrade-from-4-2-1-to-5-0-1/11304?u=stephenwaite
looks like a closing parentheses was out of place
> moving paren to correct place for newcrop

- interface/code_systems/cqm_valueset_howto.php
- interface/practice/ins_search.php
- library/billing/src/X12_5010_837P.php
- library/classes/InsuranceCompany.class.php
- library/gen_x12_837i.inc.php
- templates/insurance_companies/general_edit.html
We had a hard time finding CMS ID. The term for it now is Payer ID and the GUI should reflect that.
> Update the GUI so that it is uses current terminology

- interface/forms/newpatient/common.php
- library/ajax/facility_ajax_code.php
> update selected facility pos code when facility is changed in encounter.

- interface/globals.php
- library/crypto.php
hi @sharonco-matrix ,
This should fix your issue. Let me know how it goes.
-brady
> fixed newer version openssl issue where only lower case cipher is returned

- portal/lib/paylib.php
- portal/portal_payment.php
fix error percolation to interface
Will leave open for a minute to maybe write a readme
> fix published key decrypt

- interface/usergroup/facilities.php
If the facility has a translated name bring the translated name in the facilities list (e.g. our facilities have an english name and a hebrew name).
thanks
> get translation of facilities

- library/calendar.inc
Removing non bind variables in SQL calls
> Fixing issue #2097

- ccr/transmitCCD.php
- interface/batchcom/batch_phone_notification.php
- interface/cmsportal/portal.inc.php
- interface/eRxGlobals.php
- interface/eRx_xml.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncountermanagerTable.php
- interface/modules/zend_modules/module/Documents/src/Documents/Plugin/Documents.php
- interface/weno/jsonScript.php
- library/classes/CouchDB.class.php
- library/direct_message_check.inc
- library/globals.inc.php
- library/reminders.php
- modules/sms_email_reminder/batch_phone_notification.php
- myportal/soap_service/server_med_rec.php
Issue: #2094 
I added an encryption data type to globals that were passwords and tracked down the places where the globals were used to add to decrypt them. I think I got all of the passwords except for SMS_GATEWAY_PASSWORD because I wasn't too sure about how to add decrypt standard to that.
> Added encryption and decryptStandard to globals

- interface/billing/billing_report.php
- interface/forms/fee_sheet/new.php
- add onchange event to update x12 partner selected on payer change
- remove some script tags that made no sense.
- give margin to partner pull down.
> Billing Manager x12 partner fix.

- interface/forms/LBF/new.php
- interface/forms/LBF/printable.php
- interface/super/edit_layout.php
- library/options.inc.php
- library/options.js.php
Added translation of layout subtitles.
Added checking for duplicate field IDs when editing a layout.
Fixes for radio button field types.
> Some layout-related bug fixes.

- interface/reports/collections_report.php
helps breakdown in a spreadsheet what was collected during a set period of time
> add zero balances to csv export of collections

- controllers/C_Prescription.class.php
Hi.
Adding xlt to message in the prescription screen.
Thanks
Amiel
> Translate message

- interface/forms/LBF/new.php
- interface/forms/LBF/printable.php
- interface/super/edit_layout.php
- library/options.inc.php
- library/options.js.php
J is to start this field on a new row, regardless of whether the current row is full.
K is to insert a blank row before this field, and also forces a new row.
M and m work with radio button fields. A field with M is a "master" field which, when changed,
will cause the following m "member" fields to receive the same change. You can have multiple
such groups with each M field starting a new group.
> Added layout edit options J, K, M and m.

- Documentation/help_files/openemr_installation_help.php
- Documentation/help_files/openemr_multisite_admin_help.php
- admin.php
- library/classes/Installer.class.php
- setup.php
> Bootstrapped admin.php for multisite installation

- library/acl.inc
- library/billing/src/Claim.php
- library/billrep.inc
- library/classes/Address.class.php
- library/classes/CategoryTree.class.php
- library/classes/Company.class.php
- library/classes/Document.class.php
- library/classes/InsuranceCompany.class.php
- library/classes/InsuranceNumbers.class.php
- library/classes/Note.class.php
- library/classes/ORDataObject.class.php
- library/classes/Patient.class.php
- library/classes/Pharmacy.class.php
- library/classes/PhoneNumber.class.php
- library/classes/Prescription.class.php
- library/create_ssl_certificate.php
- library/encounter.inc
- library/forms.inc
- library/lab.inc
- library/log.inc
- library/options.inc.php
- library/standard_tables_capture.inc
In order to prevent SQL injection attacks, parameter binding should be implemented throughout the repository.  
- ADOdb's bind variables implementation is being used.
- The scope of this PR is the `library` directory.  (The original issue, #2053, was scoped to `library/classes`, but I forgot and did the whole `library` directory.)
- [ISSUE-2096] Add variable binding to prevent SQL injection attacks
@bradymiller, @danehrlich1
> [ISSUE-2053] Add variable binding to prevent SQL injection attacks

- config/config.yaml
- interface/globals.php
- interface/main/calendar/add_edit_event.php
- interface/main/main_screen.php
- interface/main/tabs/main.php
- interface/patient_file/summary/demographics.php
- interface/patient_tracker/patient_tracker_status.php
- library/dialog.js
- library/encounter_events.inc.php
- library/globals.inc.php
- library/js/userDebug.js
- library/patient_tracker.inc.php
- templates/prescription/general_edit.html
- new global to allow auto encounter per event per day
- new user debug feature
- add alert feature to dialog
- fix dialog stepping on styles(found with smarty template)
- fix dialog not working in frames ui due to window order being changed(unknown when happened)
> Allow multi auto encounters and bug fixes

- interface/de_identification_forms/de_identification_screen1.php
- interface/de_identification_forms/de_identification_screen2.php
- interface/de_identification_forms/find_code_popup.php
- interface/de_identification_forms/find_drug_popup.php
- interface/de_identification_forms/find_immunization_popup.php
- interface/de_identification_forms/re_identification_input_screen.php
- interface/de_identification_forms/re_identification_op_single_patient.php
- interface/patient_file/summary/demographics.php
> bug fixing

- interface/billing/sl_eob_invoice.php
- interface/billing/sl_eob_search.php
- interface/patient_file/history/encounters.php
- interface/reports/collections_report.php
- changed from windows to dialog
> Fix for invoice edits close

- Documentation/help_files/openemr_installation_help.php
- contrib/util/ubuntu_package_scripts/development/git-openemr.conf
- contrib/util/ubuntu_package_scripts/production/openemr.conf
- setup.php
finally able to do this (this has recently been updated in the dockers and demo farms and is testing well in those place)
> updated to apache 2.4 syntax

- interface/eRx.php
- interface/eRxXMLBuilder.php
- interface/main/tabs/js/custom_bindings.js
- interface/main/tabs/js/tabs_view_model.js
1- Func required two parames in eRx Builder 
2- Fixed javascript XSS security error when tabs attempted to reach across domain and read newcrop frame. 
3- Fixed tab so it displays New Crop rather than Unknown
> Three NewCrop eRx fixes

- interface/reports/front_receipts_report.php
Facility and Provider Filter option in Front Office Collection Report, which is available under the financial reports section.
> Front Office Collection Report - Facility and Provider Filters

- common/compatibility/Checker.php
- interface/billing/billing_process.php
- interface/billing/billing_report.php
- interface/billing/customize_log.php
- library/billing/src/Claim.php
- library/crypto.php
- library/globals.inc.php
- sql/5_0_1-to-5_0_2_upgrade.sql
- sql/database.sql
- version.php
Crypto upgrades
1. improved passphrase mode
2. added support to encrypt item on drive (by using keys stored in database)
3. increased hmac hash to sha384
Inspired by lack of internet connection and intermittent electricity outages over last couple days :)
(ie. this was all I could work on)
> Crypto updates

- interface/forms/newpatient/common.php
- interface/main/tabs/js/user_data_view_model.js
- interface/main/tabs/main.php
- interface/main/tabs/templates/patient_data_template.php
- library/ajax/dated_reminders_counter.php
- library/ajax/facility_ajax_code.php
- library/classes/POSRef.class.php
- library/dated_reminder_functions.php
- library/dialog.js
- library/globals.inc.php
- library/options.inc.php
- portal/_header.php
- portal/home.php
- portal/import_template_ui.php
- portal/lib/doc_lib.php
- portal/lib/download_template.php
- portal/lib/portal_mail.inc
- portal/messaging/messages.php
- portal/messaging/secure_chat.php
- portal/patient/libs/Controller/ProviderController.php
- portal/patient/scripts/app/onsitedocuments.js
- portal/patient/templates/OnsiteDocumentListView.tpl.php
- portal/patient/templates/_Footer.tpl.php
- portal/portal_payment.php
- portal/sign/assets/signpad.css
- portal/sign/css/signer.css
- sql/database.sql
- sql/patch.sql
- version.php
> Portal fixes back port

- library/edi.inc
> edi 270 batch eligibilty fixes

- interface/billing/sl_eob_search.php
- library/globals.inc.php
- library/invoice_summary.inc.php
- sites/default/statement.inc.php
- use locations that are set in encounter.
- change statement insurance ref to indicate type ie. primary secondary etc.
> reference PR #1612 statement reflects service and billing locations

- library/crypto.php
testing well and will bring in when pass travis
> Crypto update 1

- library/api.inc
- library/auth.inc
- library/forms.inc
delete orphan functions
first iteration
> escape column names in sql statements #2141

- interface/patient_file/summary/stats.php
- library/lists.inc
- library/pnotes.inc
- library/transactions.inc
> escape table column names #2141

- controllers/C_Document.class.php
- interface/forms/eye_mag/php/taskman_functions.php
- interface/forms/eye_mag/report.php
- interface/patient_file/report/custom_report.php
- library/classes/Document.class.php
- library/crypto.php
- portal/report/portal_custom_report.php
- sql/5_0_1-to-5_0_2_upgrade.sql
- sql/database.sql
- version.php
Part of this issue:
https://github.com/openemr/openemr/issues/2181
> drive storage encryption

- sql/5_0_1-to-5_0_2_upgrade.sql
add semicolon back and minor edits
> fix to prior commit, 52248bc

- library/classes/RXList.class.php
This code is by @efleisc
For this issue:
https://github.com/openemr/openemr/issues/2156
> fix online drug lookup

- interface/weno/validate.php
- library/weno/src/TransmitData.php
Starting some work on the Weno module. Going to introduce a little at a time. 
Is there anything security wise that needs to be added to the NPI API.
@sjpadgett
> Adding validation of NPI number

- controllers/C_Prescription.class.php
- library/classes/RXList.class.php
- library/weno/src/TransmitData.php
I need to test
Part of following issue:
https://github.com/openemr/openemr/issues/1983
> replace file_get_contents with oeHttp

- interface/reports/edi_270.php
- interface/reports/edi_271.php
- library/edi.inc
- library/globals.inc.php
- sql/5_0_1-to-5_0_2_upgrade.sql
- sql/database.sql
Up For Grabs demo for this PR is here: https://www.open-emr.org/wiki/index.php/Development_Demo#Zeta_-_Up_For_Grabs_Demo
> Eligibility rework

- interface/forms/eye_mag/view.php
Add title to dlgopen dialog enables "Close" dialog button for refractions and dispensed list.
> dlgopen Fix

- composer.json
- composer.lock
- interface/globals.php
- interface/main/main_screen.php
- interface/usergroup/mfa_registrations.php
- interface/usergroup/mfa_totp.php
- library/classes/Installer.class.php
- library/classes/Totp.class.php
- library/crypto.php
- library/translation.inc.php
- package-lock.json
- setup.php
- sql/database.sql
This is continued from this PR (see for details on this feature):
https://github.com/openemr/openemr/pull/2250
https://www.open-emr.org/wiki/index.php/Development_Demo#Epsilon_-_Up_For_Grabs_Demo
> Integrated MultiFactor Based Authentication with App Based TOTP, take 2.

- library/edi.inc
-  parse bug fix
- report updates
> eligibility updates

- interface/usergroup/usergroup_admin.php
minor fix. testing well and will bring in if pass travis.
> a php warning fix

- common/http/oeHttp.php
- common/http/oeHttpRequest.php
- interface/patient_file/summary/demographics.php
- interface/reports/edi_270.php
- interface/reports/edi_271.php
- library/edi.inc
- add Update Status button to Insurance Eligibility tab.
- oeHttp class PSR7 fix of no no reserved word use.
> new feature

- interface/main/calendar/modules/PostCalendar/pntemplates/default/user/ajax_search.html
jquery and dialog were stepping on environment.
left commented dependencies for ref.
this closes issue #2290
> fix calendar search edit dialog

- controllers/C_InsuranceCompany.class.php
- interface/reports/edi_270.php
- library/classes/InsuranceCompany.class.php
- library/edi.inc
- sql/database.sql
- sql/patch.sql
- templates/insurance_companies/general_edit.html
will leave open til final testing.
> back port PR #2287

- controllers/C_InsuranceCompany.class.php
- interface/reports/edi_270.php
- library/classes/InsuranceCompany.class.php
- library/edi.inc
- sql/5_0_1-to-5_0_2_upgrade.sql
- sql/database.sql
- templates/insurance_companies/general_edit.html
just makes sense. once this is in will take to 501
Note: our old controllers classes that run smarty need to be brought up to stuff. need to abstract or add an init method or soon will blow up on newer PHP versions. good project for moderate.
> add eligibility to insurance setup

- interface/forms/misc_billing_options/date_qualifier_options.php
- interface/forms/misc_billing_options/new.php
https://community.open-emr.org/t/medicare-billing-diabetic-patients-requirements/11774/3
> misc_billing_options fix sql to grab anybody with an npi for referring provider

- interface/usergroup/adminacl.php
fix when using hyphen in user name
> acl bug fix

- interface/billing/billing_process.php
https://community.open-emr.org/t/eligibility-checks-clearinghouses/9742/131?u=stephenwaite
> add bht claim id per kevmccor

- interface/globals.php
- portal/index.php
- portal/logout.php
- fix php session warnings
- fix logout
- remove log output settings override
> portal fixes

- interface/main/finder/dynamic_finder.php
- interface/themes/color_base.scss
- interface/themes/rtl.scss
- interface/themes/style_light.scss
Added a "create patient" button to the patient search screen.
(I'm not sure if I put the css in the right files.)
Up for grabs demo for this PR is here: https://www.open-emr.org/wiki/index.php/Development_Demo#Beta_-_Up_For_Grabs_Demo
> added patient create button

- API_README.md
- rest_controllers/DocumentRestController.php
- services/DocumentService.php
Fixes in the patients documents api, which now supports the native backend document settings (ie. couchdb, encryption).
Testing well.
> fix document api

- acl_upgrade.php
- admin.php
- common/compatibility/Checker.php
- interface/globals.php
- setup.php
- sql_patch.php
- sql_upgrade.php
@adunsulag , This will work with your current PR (I noted that the Checker class was not using the proper namespace).
> clarification of the Checker class

- .gitignore
- interface/billing/payment_master.inc.php
- interface/modules/zend_modules/config/autoload/global.php
- interface/new/new_search_popup.php
- interface/patient_file/ccr_pending_approval.php
- library/classes/ORDataObject.class.php
- library/classes/X12Partner.class.php
- library/menu/src/PatientMenuRole.php
- library/oeUI/src/OemrUI.php
#2274 I looked a few pages and fixed some notices.
Up For Grabs demo for this PR is here: https://www.open-emr.org/wiki/index.php/Development_Demo#Beta_-_Up_For_Grabs_Demo
> Fix php warnings

- interface/main/dated_reminders/dated_reminders.php
- interface/main/dated_reminders/dated_reminders_add.php
- interface/main/dated_reminders/dated_reminders_log.php
Updated deprecated $(document).ready under interface/main/dated_reminders scripts
> Issue #2314 - Updated deprecated dated_reminders scripts

- setup.php
From following issue:
https://github.com/openemr/openemr/issues/2361
This is testing well
> setup mysql user pass remove requirements

- interface/billing/billing_report.php
- interface/main/tabs/js/patient_data_view_model.js
- interface/main/tabs/js/therapy_group_data_view_model.js
Fix for issue: https://github.com/openemr/openemr/issues/297
1. bug fix in display of newly created encounter link
2. bug fix in display of encounter linked from billing report
This is testing well
> Fix encounter links

- interface/billing/sl_eob_process.php
- library/billing/src/ParseERA.php
- library/globals.inc.php
get mbi from era, update policy number in insurance data if globals m…bi update is set
this will be handy for billers so the medicare policy # will auto update when they post an ERA, will start debug/test tomorrow
> auto-update medicare HICN to MBI

- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
Add button in day view to not display calendar for a provider.
> Close button to hide provider in day view

- library/encounter_events.inc.php
Fixes recurring PHP Notice:  
Only variable references should be returned by reference in /var/www/html/emr-prd/library/encounter_events.inc.php on line 470
> PHP Notice fix

- interface/main/display_documents.php
- interface/main/finder/dynamic_finder.php
- interface/main/finder/patient_select.php
- interface/main/left_nav.php
- interface/main/messages/js/reminder_appts.js
- interface/main/messages/messages.php
- interface/main/tabs/main.php
- interface/new/new.php
- interface/new/new_comprehensive.php
- interface/new/new_search_popup.php
- interface/orders/list_reports.php
- interface/orders/orders_results.php
- interface/orders/patient_match_dialog.php
- interface/orders/pending_followup.php
- interface/orders/pending_orders.php
- interface/orders/procedure_provider_edit.php
- interface/orders/procedure_stats.php
- interface/orders/types.php
- interface/orders/types_edit.php
Updated deprecated jQuery $(document).ready, related to issue #2314.
> Updated deprecated jQuery $(document).ready

- interface/usergroup/usergroup_admin.php
minor improvement to show whether a user is using mfa (multifactor authorization) on the user list gui
> show mfa status in user list

- library/billing/src/X12_5010_837P.php
> fixed typo in billing facility state section

- library/authentication/login_operations.php
- library/globals.inc.php
- sql/5_0_1-to-5_0_2_upgrade.sql
- sql/database.sql
- version.php
https://github.com/openemr/openemr/issues/2100
> add feature to set maximum number of failed login attempts

- common/http/oeHttp.php
- common/http/oeHttpRequest.php
- controllers/C_Prescription.class.php
- interface/reports/edi_270.php
- library/weno/src/TransmitData.php
- phpfhir/libs/controller/ClientAppController.php
This is a continuation from the prior PR:
https://github.com/openemr/openemr/pull/2398
Still testing.
> internal api call clarifications

- interface/usergroup/usergroup_admin.php
https://community.open-emr.org/t/raw-code-on-user-groups-page/12056
> quick bug fix reports on forum by Jeremiah

- interface/main/finder/dynamic_finder.php
- interface/main/finder/dynamic_finder_ajax.php
- interface/main/tabs/js/user_data_view_model.js
- interface/main/tabs/templates/patient_data_template.php
- New search box does same search as frames Find By Any.
- Enter is supported in Find By Any search box.
- Search icon will open finder tab as before unless search box is populated then will open tab with 'any' results.
- All searches in finder will override 'any' results but will default back to 'any' results if all finder search boxes are reverted back to empty.
- Moved Processing... to top and changed to a refresh spinner.
- Rewrite searches sql's to support binding search param's.
- Maybe some cleanup, I forget....
below by bradymiller:
Up for Grabs demos for this PR is at: https://www.open-emr.org/wiki/index.php/Development_Demo#Delta_-_Up_For_Grabs_Demo
> Emulate frames left nav 'Any' search

- interface/clickmap/template/general_new.html
- interface/forms/eye_mag/js/eye_base.php
- interface/forms/misc_billing_options/new.php
- interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/revandapprove.phtml
- interface/modules/zend_modules/module/Patientvalidation/view/patientvalidation/patientvalidation/index.phtml
- interface/modules/zend_modules/public/js/acl/acl.js
- interface/modules/zend_modules/public/js/carecoordination/responsive-tables.js
- interface/patient_file/encounter/encounter_top.php
- interface/patient_file/encounter/find_code_dynamic.php
- interface/patient_file/pos_checkout.php
- interface/patient_file/reminder/clinical_reminders.php
- interface/patient_file/summary/add_edit_amendments.php
- interface/patient_file/summary/add_edit_issue.php
- interface/patient_file/summary/demographics_full.php
- interface/patient_file/transaction/add_transaction.php
- interface/patient_file/transaction/record_request.php
> editing_interface_code

- interface/main/calendar/find_appt_popup.php
Revision of the following PR:
https://github.com/openemr/openemr/pull/2404
@stephenwaite , this is to fix the date locale issues in the appt finder gui (I leveraged what you did in the prior PR and used functions we have to support the date locales). Testing well for me. Let me know if this fixes the issue in the prior PR. 
(also, sorry for all the unrelated security fixes; I couldn't help myself :) )
> appt finder locale date support and some security updates

- contrib/forms/scanned_notes/new.php
- contrib/forms/scanned_notes/report.php
- contrib/forms/scanned_notes/view.php
- controllers/C_Document.class.php
- controllers/C_DocumentCategory.class.php
- controllers/C_PatientFinder.class.php
- library/classes/Controller.class.php
- templates/documents/general_view.html
> some bug fixes

- cloudbuild.yaml
> see what happens (trying google cloud build ci)

- interface/billing/sl_eob_invoice.php
reminiscent of #2416, tests ok
> use locale for check date, deposit date

- interface/orders/list_reports.php
- interface/orders/single_order_results.inc.php
- interface/orders/single_order_results.php
- interface/patient_file/summary/pnotes_full.php
- interface/patient_file/summary/pnotes_full_add.php
- interface/themes/core/patient/notes.scss
- interface/themes/rtl_style_pdf.css
- interface/themes/style_pdf.css
- library/dialog.js
- in electronic report single results and encounter reports
- add order diagnosis to reports
- fix styles
- fix several bugs
- redo that once signed will stay in result review as requested
> Fix Related Patient Notes

- interface/weno/validate.php
> Bug reported by Ginger Singletary APRN

- interface/forms/eye_mag/php/eye_mag_functions.php
- interface/forms/eye_mag/report.php
- interface/forms/eye_mag/save.php
- interface/forms/eye_mag/view.php
- interface/reports/insurance_allocation_report.php
- library/classes/thumbnail/ThumbnailGenerator.php
from issue:
https://github.com/openemr/openemr/issues/2339
Still need to test.
> php 7.3 fixes

- interface/patient_file/printed_fee_sheet.php
- interface/patient_file/report/custom_report.php
- interface/reports/appointments_report.php
finally bringing in Ron's fixes to superbill, https://github.com/rpulcer6488/openemr/tree/ronp-printfeesheet
> add appointments and some better demographics to superbill

- interface/orders/orders_results.php
replaced htmlspecialchars( with text(
Issue #2145 and #2161
replaced xl( with xlt(
> htmlspecialchars fixes

- interface/forms/misc_billing_options/new.php
> make mbo smarter with ref prov from demos

- interface/super/edit_globals.php
- interface/themes/color_base.scss
- interface/themes/colors/openemr5/edit_globals_colors.scss
- interface/themes/colors/openemr5/tabs-full.scss
- interface/themes/colors/style_ash_blue.scss
- interface/themes/colors/style_cadmium_yellow.scss
- interface/themes/colors/style_chocolate.scss
- interface/themes/colors/style_cobalt_blue.scss
- interface/themes/colors/style_emerald.scss
- interface/themes/colors/style_mauve.scss
- interface/themes/colors/style_mustard_green.scss
- interface/themes/colors/style_powder_blue.scss
- interface/themes/colors/style_red.scss
- interface/themes/colors/style_tangerine.scss
- interface/themes/core.scss
- interface/themes/core/edit_globals.scss
- interface/themes/core/oe-mobile.scss
- interface/themes/style_light.scss
- interface/themes/style_manila.scss
- interface/themes/tabs_style_compact.css
- library/globals.inc.php
- library/js/oeUI/universalTooltip.js
Replaced tabs with vertical left menu for globals.php
Now has a workable UI on iPad and Smartphones
Some screenshots
**Default view condensed:**
**Default view full screen:**
**User Settings:**
**On Tablet - landscape:**
**On Smartphone - Portrait:**
**On Smartphone - Landscape:**
https://www.open-emr.org/wiki/index.php/Development_Demo#Zeta_-_Up_For_Grabs_Demo
> Fully responsive globals.php with vertical menu

- interface/reports/edi_270.php
- library/edi.inc
fix a few hardcoded values, filename and formatting for excluded policies in where clause
> few fixes for batch eligibility

- ccr/createCCR.php
- custom/ajax_download.php
- interface/usergroup/ssl_certificates_admin.php
- library/edihistory/edih_archive.php
- library/edihistory/edih_uploads.php
- library/standard_tables_capture.inc
- portal/get_patient_documents.php
at least it did on aws express package running 7.1.17
> zip needs flags on php 7.1?

- gacl/gacl.class.php
- interface/forms/LBF/printable.php
- interface/globals.php
- interface/main/main_screen.php
- interface/modules/zend_modules/module/Application/src/Application/Model/ApplicationTable.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
- interface/modules/zend_modules/module/Installer/src/Installer/Model/InstModuleTable.php
- interface/patient_file/summary/create_portallogin.php
- interface/super/edit_globals.php
- interface/super/manage_site_files.php
- interface/themes/themeBuilder.php
- interface/usergroup/usergroup_admin.php
- library/ESign/Api.php
- library/authentication/login_operations.php
- library/authentication/privDB.php
- library/classes/Installer.class.php
- library/classes/thumbnail/Thumbnail.class.php
- library/classes/thumbnail/ThumbnailGenerator.php
- library/options.inc.php
- library/pid.inc
- library/sanitize.inc.php
- library/sql.inc
- library/sql_upgrade_fx.php
- portal/lib/appsql.class.php
- portal/patient/fwk/libs/verysimple/DB/DataDriver/MySQLi.php
- src/Common/Database/Connector.php
- src/Core/Header.php
This PR will complete the following issue:
https://github.com/openemr/openemr/issues/2356
And is documented here:
https://www.open-emr.org/wiki/index.php/Codebase_Security#Log_Injection
> completed error log escaping

- library/classes/Prescription.class.php
- library/sql_upgrade_fx.php
> weno drug sql import fails window

- interface/billing/ub04_form.php
- interface/forms/misc_billing_options/new.php
- interface/forms/misc_billing_options/save.php
symptom is garbage populates ub04.
> already json encoded in form php init

- interface/billing/billing_process.php
- interface/main/calendar/add_edit_event.php
> simple fixes to 7.3 errors

- interface/reports/receipts_by_method_report.php
https://community.open-emr.org/t/payment-method-showing-as-unknown-in-reports-financial-pmt-method/12314?u=stephenwaite
> fix payment method in receipts report - alerted by forum post

- apis/dispatch.php
- interface/globals.php
- interface/main/main_screen.php
- library/sanitize.inc.php
- tests/api/InternalApiTest.php
1. Extended csrf to support multiple tokens
2. Timing attack prevent
> csrf mechanism improvements

- src/Services/InsuranceService.php
think this change gives the correct return result
https://github.com/openemr/openemr/blob/master/library/sql.inc#L286-L291
> fix return of doesInsuranceTypeHaveEntry method

- contrib/util/docker/dockers/dev-php-fpm-7-2-redis/php.ini
- contrib/util/docker/dockers/dev-php-fpm-7-2/php.ini
- contrib/util/docker/dockers/dev-php-fpm-7-3-redis/php.ini
- contrib/util/docker/dockers/dev-php-fpm-7-3/php.ini
- contrib/util/docker/dockers/dev-php-fpm-7-4-redis/php.ini
- contrib/util/docker/dockers/dev-php-fpm-7-4/php.ini
- setup.php
fix for this issue:
https://github.com/openemr/openemr/issues/2479
> fix to ensure mysqli.allow_local_infile setting is on

- composer.json
- composer.lock
- interface/main/backup.php
hi @bradymiller , not sure if composer.lock is off limits :)
it tests ok after composer update in the flex docker, then cut and pasted the pear portion of that update to the composer.lock file :crossed_fingers: 
addresses #2515
> composer require pear/archive_tar to update backup script

- interface/modules/zend_modules/module/Installer/Module.php
- interface/modules/zend_modules/module/Installer/config/module.config.php
hi @adunsulag , Yanked the session stuff that zend was doing, which was overwriting the cookie for no reason. Testing well and bringing this into codebase. Just check it out and let me know if not sane changes. thanks, -brady
> remove session stuff from zend

- src/Billing/BillingUtilities.php
> fixes #2540 with floatval cast

- interface/main/tabs/js/user_data_view_model.js
- interface/main/tabs/main.php
- library/auth.inc
- library/globals.inc.php
- version.php
> refresh fix for issue #2530

- config/config.yaml
- interface/patient_file/encounter/load_form.php
- interface/patient_file/encounter/view_form.php
- library/globals.inc.php
- Remove global scope
- Add global and user settings enable for feature.(default off)
> Modify text template feature

- interface/main/left_nav.php
- interface/main/tabs/menu/menus/standard.json
- sites/default/documents/custom_menus/Custom.json
This will remove Password, MFA Management and Preferences, all children of Miscellaneous.
> Fix #2564 - Remove duplicate menu entries 

- interface/main/tabs/menu/menus/standard.json
- interface/reports/collections_report.php
aligned report to the left so columns would match up on screen and
fixed issue with due patient and due insurance
> Signed-off-by: Sherwin Gaddis <sherwingaddis@gmail.com>

- interface/main/tabs/menu/menus/standard.json
- sites/default/documents/custom_menus/Custom.json
Duplicate entry:
- Administration/Addr Book
- Miscellaneous/Addr Book
> Delete Addr. Book from Miscellaneous menu

- _rest_config.php
Adjust rest config session util require path
> Fix REST API include path for login

- composer.json
- composer.lock
- interface/super/edit_globals.php
- library/globals.inc.php
- version.php
Going to be used for reporting (when need a installation id in reporting metrics).
> Add a unique id for the installation

- interface/billing/billing_process.php
- interface/billing/billing_report.php
- redo drop down lists button styles to links
- added new dry run validate claims action
- fix clear to not update claim after downloads after setting billed flag and clearing processing dates
- fix cancel to cancel action
- fix payer_type
- update jquery to 3.1.1 version
Up For Grabs for this PR is here: https://www.open-emr.org/wiki/index.php/Development_Demo#Zeta_-_Up_For_Grabs_Demo
> Billing Manager Update

- interface/main/tabs/menu/menus/standard.json
- sites/default/documents/custom_menus/Custom.json
inspired by @dimitristsilis :)
> fix in Miscellaneous menu item permissions

- interface/forms/eye_mag/css/style.css
- interface/forms/eye_mag/save.php
BUG:  ROS was not being saved.  Fixed.
Simple css change to fit PMSFH titles in one line on PMH panel.
> Simple Eye Bug Fix

- interface/main/tabs/menu/menus/standard.json
- sites/default/documents/custom_menus/Custom.json
Up For Grabs demo for this PR here: https://www.open-emr.org/wiki/index.php/Development_Demo#Lambda_-_Up_For_Grabs_Demo
> Organize Admin. menu, Remove items from Miscellaneous-relative to #2301

- src/Common/Session/SessionUtil.php
> remove cookie when remove the session

- interface/billing/billing_process.php
- interface/billing/billing_report.php
- log available from claim form popup
> Billing Manager validate claim review

- interface/billing/billing_process.php
hmm, what the heck is it with my aversion to escaping!
Will leave open for a minute while I retest for insurance missing on validate.
> invalid escaping to html

- interface/billing/billing_process.php
- putting this to bed.
Five years ago I complained about the Clear Cancel Okay dialog. So, finally!!!!!
> ensure current payer is used when validating claim

- build.xml
- composer.json
- composer.lock
- interface/globals.php
- src/Core/Header.php
> Bringing Twig back in

- interface/usergroup/usergroup_admin.php
The provider ID won't update correctly. Throws an error. 
@robertdown
> This popped up when setup up an instance

- library/authentication/login_operations.php
- library/translation.inc.php
Related to https://github.com/openemr/openemr/issues/2499
testing well and bringing in after pass travis
> couple minor php 7.4 fixes

- interface/forms/LBF/printable.php
- library/encounter.inc
- library/patient.inc
Added Patient information to the header and footer of the PDF from the LBF's
> Got a request that it is mandatory for the header and footer by CMS

- contrib/util/docker/dockers/dev-nginx/nginx.conf
- interface/login/login.php
- interface/main/authorizations/authorizations.php
- interface/main/tabs/main.php
- library/calendar.inc
- library/patient.inc
https://github.com/openemr/openemr/issues/2499
> Php 74 fixes 2

- interface/billing/billing_report.php
- interface/billing/clear_log.php
hi @juggernautsei ,
I rebased your code from https://github.com/openemr/openemr/pull/2391 into 1 commit. And the followed it with a couple changes. This is testing well.
> Clear billing log feature

- interface/orders/gen_hl7_order.inc.php
Im sorry about the previous incorrect pull request.  This is what I meant to send.
> Adds OBR-15 aka specimen type to a procedure order HL7 message

- interface/expand_contract_js.php
- interface/login/login.php
- interface/main/about_page.php
- interface/main/calendar/modules/PostCalendar/pntemplates/default/user/ajax_search.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day_print/outlook_ajax_template.html
- interface/main/dated_reminders/dated_reminders_add.php
- interface/modules/zend_modules/public/js/scripts/file_uploader.js
- interface/patient_file/erx_patient_portal_js.php
- interface/patient_file/front_payment.php
- interface/patient_file/history/encounters.php
Updated deprecated jQuery .ready code
> Issue #2314 - Deprecated jQuery. ready() method

- src/Core/Header.php
Hi.
Here I push a minor fix in the process of loading assets from a custom yaml file.
The array of selected assets was missing.
Thanks
Amiel
> Custom asset fix

- interface/forms/LBF/new.php
This has been a bug for a while. Small fix
> This is so the lbf defaults to the provider that is logged in.

- interface/patient_file/report/custom_report.php
- interface/patient_file/report/patient_report.php
- library/dialog.js
- library/globals.inc.php
- library/smarty/plugins/function.dispatchPatientDocumentEvent.php
- src/Core/ModulesApplication.php
- src/Events/PatientDocuments/PatientDocumentEvent.php
- src/Events/PatientReport/PatientReportEvent.php
- templates/documents/general_view.html
- add dispatch events to patient documents for fax send.
- New patient documents event class
> Fax Custom Module Support

- interface/billing/new_payment.php
minor travis fix for prior commit
> appease travis for previous commit

- interface/modules/zend_modules/config/application.config.php
- interface/modules/zend_modules/module/Installer/view/installer/installer/index.phtml
- interface/patient_file/report/custom_report.php
- interface/patient_file/report/patient_report.php
- library/dialog.js
- library/smarty/plugins/function.dispatchPatientDocumentEvent.php
- src/Core/ModulesApplication.php
- src/Events/PatientDocuments/PatientDocumentEvent.php
- src/Events/PatientReport/PatientReportEvent.php
- src/Services/Globals/GlobalSetting.php
- templates/documents/general_view.html
Maybe you guys can check me. I don't think I missed anything but this is me, don't cha know.....
> Port custom modules

- interface/patient_file/history/history.php
Been bugging me so here it is.
@bradymiller if you need I can put this in v502 and/or bring clear logs by Sherwin or other you need done.
> bug fix for null skipArray in History

- interface/modules/zend_modules/module/Carecoordination/config/module.config.php
- EncounterccdadispatchTable service manager factory missing adapter
> CCDA  fetch bug

- src/Billing/X12_5010_837P.php
here's another bug that @opthal found that will need to go in the next patch
> remove invalid ordering provider for DME

- interface/forms/fee_sheet/new.php
- interface/forms/fee_sheet/review/fee_sheet_justify_view_model.js
- interface/forms/fee_sheet/review/initialize_review.js
- interface/forms/fee_sheet/review/js/fee_sheet_core.js
- interface/main/dated_reminders/dated_reminders.php
- ensure current form state is saved before justify
> Fix issue #686

- interface/forms/fee_sheet/new.php
- interface/forms/fee_sheet/review/js/fee_sheet_core.js
- ignore adding justify dialog anchor if procedure is being deleted.
- refactor deprecated `<strike>` with `<del>` style
- added spinner for justify dialog fetch
- some code clean up
> Feesheet code type strike out bug fix.

- interface/forms/fee_sheet/new.php
- interface/forms/fee_sheet/review/js/fee_sheet_core.js
Code type strike out on del bug
> Port PR #2686 to 5.0.2

- interface/forms/fee_sheet/review/initialize_review.php
@sjpadgett , just incorporated cache busting mechanism for the fee sheet stuff. Will bring this into the rel-502 branch and patch (I keep delaying the patch since fixes keep coming in :) ).
> minor fee sheet fix

- interface/forms/fee_sheet/review/initialize_review.php
- version.php
> minor fee sheet fix (#2688)

- src/Services/PatientService.php
will add to growing patch numero uno :)
> missing comma after email affected dob return

- interface/orders/procedure_provider_edit.php
- library/MedEx/MedEx.php
- procedure provider fac name wrong so breaks save
- MedEx log.inc remove and conditional fix
> Bug Fix MedEx and Provider

- portal/_header.php
- portal/add_edit_event_user.php
- portal/home.php
- portal/index.php
- portal/sign/lib/save-signature.php
- portal/sign/lib/show-signature.php
You'd think i'd know better!!!
> Globals overwrite fetch $pid

- portal/_header.php
- portal/add_edit_event_user.php
- portal/home.php
- portal/index.php
- portal/sign/lib/save-signature.php
- portal/sign/lib/show-signature.php
will leave the two(port to 502 and 503) PR's open for a bit in case there is more.
> Global $pid overwrites $pid

- library/options.inc.php
> fix DOB datepicker in new/search client for chrome users

- interface/patient_file/summary/create_portallogin.php
- portal/_header.php
- portal/account/account.lib.php
- portal/account/account.php
- portal/account/index_reset.php
- portal/account/register.php
- portal/add_edit_event_user.php
- portal/get_patient_info.php
- portal/home.php
- portal/index.php
- sql/5_0_2-to-5_0_3_upgrade.sql
- sql/database.sql
- src/Common/Crypto/CryptoGen.php
- src/Common/Utils/RandomGenUtils.php
feature by @sjpadgett 
just doing some minor work on it
Continued from:
https://github.com/openemr/openemr/pull/2715
Up For Grabs demo here: https://www.open-emr.org/wiki/index.php/Development_Demo#Gamma_-_Up_For_Grabs_Demo
> Portal credential enhancements rebased

- interface/patient_file/pos_checkout.php
> add value attribute form_save for pos_checkout

- interface/patient_file/pos_checkout.php
- interface/patient_file/summary/create_portallogin.php
- library/standard_tables_capture.inc
- portal/_header.php
- portal/account/account.lib.php
- portal/account/account.php
- portal/account/index_reset.php
- portal/account/register.php
- portal/add_edit_event_user.php
- portal/get_patient_info.php
- portal/home.php
- portal/index.php
- sql/database.sql
- sql/patch.sql
- src/Common/Crypto/CryptoGen.php
- src/Common/Utils/RandomGenUtils.php
- version.php
> back port portal password

- portal/account/index_reset.php
- portal/index.php
> patch testing bugs

- interface/patient_file/history/history.php
- interface/patient_file/history/history_full.php
- interface/patient_file/letter.php
- interface/patient_file/printed_fee_sheet.php
- interface/patient_file/reminder/patient_reminders.php
- interface/patient_file/report/patient_report.php
- interface/patient_file/rules/patient_data.php
- interface/patient_file/summary/add_edit_issue.php
- interface/patient_file/summary/advancedirectives.php
- interface/patient_file/summary/browse.php
- interface/patient_file/summary/demographics.php
- interface/patient_file/summary/demographics_full.php
- interface/patient_file/summary/disclosure_full.php
- interface/patient_file/summary/immunizations.php
- interface/patient_file/summary/pnotes.php
- interface/patient_file/summary/pnotes_fragment.php
- interface/patient_file/summary/pnotes_full.php
- interface/patient_file/summary/pnotes_full_add.php
- interface/patient_file/summary/record_disclosure.php
- interface/patient_file/summary/stats_full.php
- interface/patient_file/transaction/add_transaction.php
- interface/patient_file/transaction/transactions.php
Update for issue #2314 
Cheers!
> Update deprecated $(document).ready()

- apis/dispatch.php
- library/authentication/common_operations.php
- library/authentication/login_operations.php
- library/authentication/password_hashing.php
- sql/5_0_2-to-5_0_3_upgrade.sql
- sql/database.sql
- src/RestControllers/AuthRestController.php
- version.php
> api updates

- ccdaservice/README.md
always forget this piece, plus haven't found that localhost setting for mirth matters anymore, at least on the demos, https://six.openemr.io/c/openemr/interface/login/login.php?site=default, just installed it :wrench:
> ccda advice

- contrib/util/installScripts/InstallerAuto.php
also will bring this fix over to rel-502
> auto installer fix

- setup.php
testing well and will bring in after pass travis
> minor setup.php code clarfification

- composer.json
- composer.lock
related to following PR:
https://github.com/openemr/openemr/pull/2746
> remove adldap2/adldap2 package since migrated to native php ldap library

- library/authentication/login_operations.php
- library/authentication/password_change.php
@sunsetsystems ,
Just a couple minor changes. I was testing out the LDAP on that cool server you pointed out. Very nice to be able to test it so easily. Changes are testing well. Just let me know if you have any issues with the changes.
> minor ldap changes

- interface/usergroup/facilities.php
- interface/usergroup/facilities_add.php
- interface/usergroup/facility_admin.php
- sql/5_0_2-to-5_0_3_upgrade.sql
- sql/database.sql
- src/Services/FacilityService.php
Hi,
We have a need to facility info in our project for our reports.
thanks
Dror G.
> Adding info field to facilities mechanism

- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
may have to delete a provider's vacation now and then :smirk: 
testing well and may finally get a chance to cherry pick for 5.0.2.2 :smiling_imp:
> make provider vacation event clickable again

- interface/forms/procedure_order/new.php
- interface/orders/single_order_results.inc.php
- interface/patient_file/encounter/find_code_history.php
Kind of neat feature. 
- Accumulates  dx codes from current patient issues/problems and global past procedures for easy reuse on new procedure forms.
- Reduced form details to one table header, cleaner.
- Fixed js error for redeclare of mypcc.
> add dx history finder for procedure order form

- interface/main/calendar/modules/PostCalendar/pntemplates/default/user/ajax_search.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/header.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
- interface/main/main_info.php
- interface/themes/ajax_calendar.css
Day view so far. Week and Month views nexr.
- Replaced framesets and frame with iframe.
- collapse left sidebar.
iPhone7/8 portrait
Sidebar
Landscape
one more
> Calendar Restyle

- interface/forms/procedure_order/new.php
- interface/patient_file/encounter/find_code_history.php
This just gets cooler imho. Made allowances for snomeds or other code types.
> update procedure orders dx finder

- interface/main/messages/messages.php
- interface/patient_tracker/patient_tracker.php
- library/MedEx/API.php
- library/MedEx/MedEx.php
- library/MedEx/MedEx_background.php
Streamline API calls.  Improve page loads, remove fluff, reduce overhead.
> 5.0.2.3_MedEx

- interface/login/login.php
- interface/main/calendar/add_edit_event.php
- interface/main/calendar/find_patient_popup.php
- interface/main/calendar/modules/PostCalendar/pntemplates/default/user/ajax_search.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/header.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
- interface/main/main_info.php
- interface/patient_file/encounter/find_code_history.php
- interface/themes/ajax_calendar.css
- interface/themes/tabs_style_compact.css
- interface/themes/tabs_style_full.css
- library/dialog.js
calendar restyle update port from 5.0.3
will bring in, build patch of all current patch 2 commits for testing then, do portal.
> 5.0.3 calendar restyle port

- interface/code_systems/list_staged.php
- sql/5_0_2-to-5_0_3_upgrade.sql
- sql/database.sql
- version.php
supported external dataloads tests fine
> allow 2019 ecqm value set

- portal/_header.php
- portal/account/account.php
- portal/account/register.php
- portal/assets/css/base.css
- portal/assets/css/register.css
- portal/assets/css/style.css
- portal/index.php
> Restyle for mobile

- portal/account/register.php
- portal/assets/css/base.css
- portal/assets/css/register.css
- portal/assets/css/style.css
- portal/index.php
- portal/patient/templates/PatientListView.tpl.php
This fixes a ton of responsive design flaws in the Patient Portal.
This is change 1 of 2 for #2793. The 2nd change will fix the register.php area as well as fixes any errors done on my part (now available).
Changelog of Overall Changes:
- CSS beautified base.css and register.css
- Fixed a ton of Bootstrap code
- Added dynamic padding to wrapper class that changes based upon device type
- Fixed login logo to be under Bootstrap responsive image classes
- Added dynamic sizing to login logo
- Replaced table in reset password area with Bootstrap CSS
- Removed a ton of col-xs-12 as it is not needed at all in this CSS
- Removed repetitive class text-center declarations
- Removed inline CSS code and placed into external CSS
- Changed login background color and wrapper background color to match …
> Fix for Patient Portal Responsiveness (#2793)

- portal/account/register.php
- portal/assets/css/base.css
- portal/assets/css/register.css
- portal/assets/css/style.css
- portal/index.php
- portal/patient/templates/PatientListView.tpl.php
> portal restyle from #2800

- interface/orders/receive_hl7_results.inc.php
> NTE segment in PID leads to rejected results

- interface/main/messages/messages.php
https://community.open-emr.org/t/bug-in-add-new-message-screen/13200/5?u=stephenwaite
> forgotten anchor bracket

- src/Billing/Claim.php
> fix zips with dashes and not padded with 9 for zip+4

- apis/dispatch.php
just minor reorg to keep the use statements together
> quick consolidation of use statements in dispatch.php script

- interface/patient_file/history/history_save.php
thank you @visolve-openemr 
https://community.open-emr.org/t/demographics-history-redirection-issue/13311?u=stephenwaite
> change include to header for redirect

- portal/find_appt_popup_user.php
> Fix - Onsite Patient Portal cannot handle recurrtype 3 events

- sites/default/statement.inc.php
- tests/unit/NumberToTextTest.php
- missing single quote
- resize image
> issue #2846

- interface/eRxStore.php
- interface/eRxXMLBuilder.php
Added vitals to NewCrop erx message, and a warning if patient is under age 19 years old and vitals are not present. I will also need to backport this to 502 and 501 if possible.
> New requirements for NewCrop

- interface/eRxStore.php
- interface/eRxXMLBuilder.php
* New requirements, Added vitals to NewCrop erx message, and a warning if patient is under age 19 years old and vitals are not present
* Fix for Travis
> New requirements for NewCrop (#2852)

- interface/main/messages/save.php
> Recall Board PID_Fix

- library/clinical_rules.php
> fix for #2834

- gacl/gacl_api.class.php
proposed fix for following issue:
https://github.com/openemr/openemr/issues/2870
> mysql8 bug fix

- interface/patient_file/transaction/transactions.php
reported here:
https://community.open-emr.org/t/date-in-the-transaction-form-not-populating-bug-fix/13493
author of fix is @juggernautsei
> transaction date bug fix

- docker-compose.yml
> easy docker dev env fixes

- interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
> simple fix for move from zend to laminas

- interface/forms/functional_cognitive_status/save.php
https://community.open-emr.org/t/sql-error-when-adding-a-patients-functional-and-cognitive-status/13695?u=stephenwaite
> fix from forum

- config/config.yaml
Fixes an issue where datatables-colreorder CSS was 404'ing. Ready for immediately merging.
> Quick datatables-colreorder fix & Format Fix (#2940)

- library/classes/Installer.class.php
This Pr adds green colour to the ok button in step number 3 of setup.php
fixes #2946
> Adds green colour to OK button (Step 3 in setup.php)

- README.md
Fixed Issue:  #2955
Improve README.md and fix the link.
> Issue Fix #2955: Improve README.md 

- interface/super/edit_globals.php
**Description:**
Adds Highlight to the required item on search in Global setting(also for user mode)
fixes #2948
**Screenshots:**
> Fixes search in Global setting section (Highlight)

- custom/export_xml.php
- custom/import_xml.php
Fixes #2957
The fix is tested, I can provide a video if required.
> Fixes: Close/Cancle button not working in Export/Import Popup

- interface/logview/logview.php
Fixed Issue: #2958
Improve Logs Viewer UI, Added nav pills to choose main log or other logs.
> Issue Fix #2958: Improve Logs Viewer UI

- interface/super/edit_globals.php
fixes #2971 
Applied margin like his counter parts have.
**Screenshot:**-
Please review @bradymiller
> Fixes: Expandle button not completely visible on edit globals/user page

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/security_report.md
**It will appear like this:**
Please verify the template content, and propose changes(if any).
I will add PR template after this since it requires suggestions from mentors. 
**Note:** We can also add a third type of issue template - security report in which we provide only the details to personally contact the mentors and not let them open an issue( since we don't want everyone to know the security threat :P )
**Edit 1:**
There is also a blank issue option present, in case the issue does not fit in the above two criteria.
**Edit 2:**
I will take suggestions for the PR template when we close on issue template :)
> Added: Issue Template (Feature Request and Bug report)

- interface/new/new_comprehensive.php
- interface/new/new_search_popup.php
- interface/patient_file/history/history.php
- library/js/utility.js
- one include has script tags other doesn't. there ya go.
- patient search popup ref to opener button invalid.
- widen search/dup dialog.
> Issue fixes #2950 #2951

- interface/language/lang_constant.php
- interface/language/lang_definition.php
- interface/language/lang_language.php
- interface/language/lang_manage.php
- interface/language/language.php
Fixed Issue: #2959
Improve language editor UI,  Added nav pills to choose the page content.
Also, I replaced the uppercase HTML tag to lowercase, and prettify code format.
> Issue Fix #2959: Improve language editor UI

- interface/patient_file/printed_fee_sheet.php
I did some code refactoring, and the print button had no styles:
> Added Missing style and refactored code in SuperBill popup

- .github/PULL_REQUEST_TEMPLATE.md
> Added: PR template for github

- interface/main/messages/messages.php
Fixed Issue: #2989
Fixed form label field alignment issue, and Improve button style.
> Issue Fix #2989: Form label field alignment issue

- interface/patient_file/printed_fee_sheet.php
- src/Core/Header.php
Fixes #2994 
the now closed #2990 
following at @bradymiller 's advice, sorry @thesmallstar but maybe this needs more work since haven't tested yet
> add return to core/header

- interface/patient_file/summary/stats.php
- interface/patient_file/transaction/record_request.php
- library/amc.php
- library/clinical_rules.php
- library/patient.inc
- library/sanitize.inc.php
> empty date checks encapsualted

- library/patient.inc
Fixes #2996
It corrects the check behavior for special cases.
Move any needed where clauses in a variable which are being joined with the SQL statement.
> tobacco or any given case fixed for input check

- setup.php
> improved credentials line

- src/Core/Header.php
Fixes #3018 
In #2995 function was modified to return value instead of echo but as it's used at other places where the echo was the expected value it was causing the problem so added a flag to the method.
> TypeError: this.element.getAttribute

- interface/help_modal.php
- src/OeUI/OemrUI.php
Fixes #3000 
Part of jquery-ui removal project
> fixes #3000

- interface/new/new_comprehensive.php
- interface/new/new_search_popup.php
fixes #2983 
Scope of the variable  is corrected
**Previous behavior**: Modal does not appear after closing it once
**Current behavior**: If there are any changes after clicking the create patient for the first time modal will appear or else the patient will be saved.
> Modal does not appear after closing it once

- interface/billing/sl_eob_search.php
- interface/orders/types.php
- interface/usergroup/adminacl.php
Fixes #3004 
Change jquery UI tooltip to Bootstrap tooltip.
> Fix #3004 change jquery ui tooltip

- Documentation/help_files/add_edit_transactions_dashboard_help.php
- Documentation/help_files/adminacl_help.php
- Documentation/help_files/cms_1500_help.php
- Documentation/help_files/common_help.php
- Documentation/help_files/configure_orders_help.php
- Documentation/help_files/fee_sheet_help.php
- Documentation/help_files/history_dashboard_help.php
- Documentation/help_files/issues_dashboard_help.php
- Documentation/help_files/ledger_dashboard_help.php
- Documentation/help_files/medical_dashboard_help.php
- Documentation/help_files/message_center_help.php
- Documentation/help_files/mfa_help.php
- Documentation/help_files/openemr_installation_help.php
- Documentation/help_files/openemr_multisite_admin_help.php
- Documentation/help_files/procedure_provider_help.php
- Documentation/help_files/report_dashboard_help.php
- Documentation/help_files/sl_eob_help.php
- Documentation/help_files/transactions_dashboard_help.php
Fixes #3029 
Added </p> tag and used bootstrap text-center style to instead of <center> tag
> Fix #3029 close p tag

- interface/patient_file/reminder/clinical_reminders.php
Fixes #2961 
- Added bootstrap button classes
- Added shading and hover to table
- Removed unwanted borders
SS:
dark table row is the hover effect
> Improved UI: Edit Clinical Reminder - Admin

- src/Tabs/TabsWrapper.php
> Remove jquery-ui dependency from TabsWrapper.php

- interface/forms/fee_sheet/new.php
- interface/forms/group_attendance/new.php
- interface/forms/newpatient/common.php
- interface/main/messages/messages.php
- interface/main/pwd_expires_alert.php
- interface/main/tabs/main.php
- interface/new/new_comprehensive.php
- interface/orders/procedure_provider_edit.php
- interface/orders/single_order_results.php
- interface/orders/types_edit.php
> Remove jquery-ui from batch 3 of scripts

- interface/patient_file/encounter/superbill_custom_full.php
- interface/patient_file/front_payment.php
- interface/patient_file/merge_patients.php
- interface/patient_file/summary/add_edit_issue.php
- interface/patient_file/summary/immunizations.php
- interface/patient_file/summary/pnotes_full.php
- interface/patient_tracker/patient_tracker.php
- interface/therapy_groups/therapy_groups_views/header.php
- interface/usergroup/facilities.php
- interface/usergroup/facility_admin.php
> Remove jquery-ui from batch 4 of scripts

- config/config.yaml
- interface/forms/group_attendance/new.php
- interface/therapy_groups/therapy_groups_views/header.php
n/a
Fixes the theming of these 2 therapy group scripts
(otherwise they have no styling)
> fixes in therapy groups datatables use for bs4

- interface/main/onotes/office_comments_full.php
Fixes #3040
Use the required attribute to prevent empty content.
Add the Bootstrap button style.
Fix table list more tbody problem.
> Fix #3040 empty note content

- .github/ISSUE_TEMPLATE/bug_report.md
> fix: issue template typo

- interface/reports/immunization_report.php
Fixes #3047
Change td width to CSS class w-50
Remove outdated syntax.
> Fix#3047 remove outdated syntax

- interface/patient_file/encounter/forms.php
> Encounter tabs UI improved

- interface/patient_file/encounter/find_code_popup.php
UI improvements in the Procedure search popup
Screenshots:
**before:**
**after:**
thanks
> UI improvements: Report -> Procedure search popup

- interface/orders/procedure_provider_edit.php
Before(un zoomed ver.):
After(un zoomed ver.):
-thanks
> UI Improvements: Add new Procedure provider popup

- interface/super/edit_layout_props.php
Suggested Improvement
Layout ID and name are required for the creation.
> layout should have a name

- interface/usergroup/facilities_add.php
- interface/usergroup/facility_admin.php
Fixes #3061 
Remove add facilities modal button group.
Remove add facilities outdated syntax.
Modify edit facilities modal switch align to left.
Modify edit facilities modal field align to center.
Coding indent change.
> Fix #3061 facilities modal

- interface/super/edit_globals.php
- src/OeUI/OemrUI.php
Fixes #3060 
Change expand and go to the top to a tag.
> Fix#3060 Add expand and go to top button cursor 

- .gitignore
- composer.json
- interface/usergroup/facilities_add.php
Fixes 
> #3065 
This resolves the UI consistency issue for Toggle elements in Facility Add/Edit
- Changed the checkboxes in "Add Facility" to new toggle buttons as per the "Edit Facility" form
> Changed Add Facility checkboxes to new UI following Edit Facility

- interface/usergroup/addrbook_list.php
Admin -> Address Book
**before:**
**after:**
> UI Imrovement: Admin -> Address Book

- interface/usergroup/facilities_add.php
Fixes #3075 
The overall form presentation of "add facility" has been made consistent with "edit facility"
- The arrangement of the form fields has been altered in "add facility" and made consistent with "edit facility"
- "Add facility" modal has been made responsive
> add facility modal made consistent with edit facility

- admin.php
- custom/download_qrda.php
- interface/billing/search_payments.php
- interface/billing/ub04_form.php
> Remove jquery-ui from batch 1 of scripts

- interface/forms/eye_mag/report.php
> Removed existing headers

- src/Tabs/TabsWrapper.php
> fixed Remove tab button

- interface/orders/types.php
> fixed heading to Add Mode

- interface/cmsportal/history_form.php
- interface/cmsportal/patient_form.php
- interface/forms/LBF/new.php
- interface/forms/eye_mag/a_issue.php
- interface/new/new_comprehensive.php
- interface/patient_file/summary/demographics_full.php
- interface/patient_file/transaction/add_transaction.php
- interface/usergroup/facility_user_admin.php
- library/js/xl/jquery-datetimepicker-2-5-4.js.php
- library/options.inc.php
- sql/5_0_2-to-5_0_3_upgrade.sql
- sql/database.sql
Fixes #3016 
Added validation for past_date and future_date
I'm not completely sure about the `seq` field in `database.sql`
https://www.open-emr.org/wiki/index.php/Development_Demo#Eta_-_Up_For_Grabs_Demo
> validation based check on generate_form_field method

- interface/drugs/add_edit_drug.php
Fixes #3114 
Buttons on the form are generated based on the condition
> Misleading Add/Edit Drug Form

- interface/code_systems/cqm_valueset_howto.php
- interface/code_systems/dataloads_ajax.php
- interface/code_systems/icd10_howto.php
- interface/code_systems/icd9_howto.php
- interface/code_systems/rxnorm_howto.php
- interface/code_systems/snomed_howto.php
Fixes #3077 
Remove jquery-UI.
Add Bootstrap tooltip, collapse, modal, button style.
> Fix #3077 remove jqueryui

- interface/main/calendar/modules/PostCalendar/common.api.php
- interface/main/calendar/modules/PostCalendar/pnuserapi.php
- library/sanitize.inc.php
- src/Core/Header.php
https://github.com/openemr/openemr/issues/3118
> php notices removal

- interface/drugs/drug_inventory.php
Fixes #3113 
Table is replaced with datatables UI
**Before:** ![Screenshot from 2020-03-08 13-47-42](https://user-images.githubusercontent.com/29653282/76159159-888f0980-6143-11ea-83f8-7dbec2f316b6.png)
**After Makeup:** ![Screenshot from 2020-03-08 13-47-58](https://user-images.githubusercontent.com/29653282/76159160-8a58cd00-6143-11ea-9309-d946f9209b13.png)
> Drug Inventory UI

- interface/super/load_codes.php
Fixes #3104 
Refine the install code set.
Add Bootstrap table style.
Remove outdated syntax.
> Fix #3104 refine install code set

- CONTRIBUTING.md
Previous: Redirect to 404
Now: Redirect to contributors page
> Quick Fix CONTRIBUTING.md link
