openemr/openemr

interface/main/calendar/add_edit_event.php

If a recurrtype 3 (Days of Week) appointment is edited by unchecking a week day that corresponds to an individual appointment with date equal to pc_eventDate, an individual appointment corresponding to that weekday will persist (with date equal to pc_eventDate).
EDIT - added detail to description.

Fix - persistent appointment for recurrtype 3

---

interface/forms/vitals/C_FormVitals.class.php
interface/forms/vitals/new.php
interface/forms/vitals/view.php

This is a second revision from the original PR here:
https://github.com/openemr/openemr/pull/240
This fixes the following php warning in php7:
PHP Warning:  Declaration of C_FormVitals::default_action($form_id) should be compatible with Controller::default_action() in /var/www/openemr/interface/forms/vitals/C_FormVitals.class.php on line 8

php warning fix by Sherwin in vitals form

---

interface/main/tabs/js/tabs_view_model.js
interface/main/tabs/main.php
version.php

This is to fix several translations in the tab layout.

translations fixes in the tab layout

---

interface/globals.php

Default values for optional variables that are allowed to be set by callers.
This eliminates repeated PHP warnings about use of undefined variables.

Default values for optional variables for globals.php

---

interface/login/login.php

In PHP 7.0.4 installation the error log is showing
[23-Oct-2016 12:06:09 UTC] PHP Stack trace:
[23-Oct-2016 12:06:09 UTC] PHP   1. {main}() C:\emr_wamp\www\openemr\interface\login\login.php:0
[23-Oct-2016 12:06:09 UTC] PHP Notice:  Use of undefined constant lang_description - assumed 'lang_description' in C:\emr_wamp\www\openemr\interface\login\login.php on line 195

Bug fix for login.php

---

interface/forms/soap/report.php

This is to preserve the formatting that goes into the soap note for the report output to be more presentable.

Signed-off-by: Sherwin Gaddis <sherwingaddis@gmail.com>

---

library/classes/thumbnail/Thumbnail.class.php
sites/default/documents/temp/README

Hi.
1. I added error message in the construct of thumbnail generator in case that missing GD extension (PHP extension).
2. adding  empty folder in the sites/documents. without this folder php throws warning error when retrieving file from couchDB and doesn't present the file .
Error screenshot -   
Thanks.
Amiel

2 minor fixes in document system

---

interface/forms/vitals/report.php
interface/forms/vitals/templates/vitals/general_new.html

here I try to resolved error that occur when you use for distance calculation with centimeter  and not with inch.
this form gets the data in cm converts it to inch but it saves the number in the database only with 2 decimal places so when the form shows the data again in centimeter it can show wrong.
example - 
height - 160cm -> convert to inch -> 62.99 -> convert again to cm ->  159.99
The solution is to round but only the second decimal.
thanks
Amiel

Fix in vitals form

---

interface/main/calendar/add_edit_event.php
interface/main/calendar/modules/PostCalendar/pnuserapi.php
library/appointments.inc.php

For rt2 recurring appointments set on the 29th, 30th and 31st where there is a month associated with a date in the corresponding recurring series that has a total number of days less than the day of month the appointment was set on (29 30 or 31) (first month if more than one) the date for this month will be missing when freq = 1. For freq > 1 all subsequent dates will be missing also and a series of wrong dates will be included each one month shifted from the missing correct dates.
Only new (post fix) appointment experience the fix, old appointments remain unchanged.

Fix - missing and incorrect dates for rt2 recurring appointments set on the 29th, 30th and 31st

---

library/dialog.js

Fix to add top.restoreSession() call to the dlgopen() function that is used by the tabs user interface.

Fix tab ui dlgopen top.restoreSession

---

interface/usergroup/facilities_add.php

a month go i made a fix for same bug on the edit facility form, and it merged to the codebase.
this time the bug appears in the add new facility form.
> When you add a new facility/clinic, there is an address field, which is required to complete the form.
> However, the field is not marked as required and there is no visible sign indicating that.
> for the other required fields, there is an asterisks next to them to indicate this. those asterisks are hard-coded in the form.

facility form fix

---

interface/forms/LBF/report.php
interface/patient_file/encounter/forms.php

The width of the LBF content in the Encounter Summary is being restricted (by a recent code change) to 30 characters.

Fix - LBF content width limited to 30 characters in Encounter Summary

---

interface/super/edit_list.php
sql/5_0_0-to-5_0_1_upgrade.sql
sql/database.sql

Brady hello,
Here we want to add a feature that enables you to decide whether a list or option is editable in admin panel. We added a column to the list_options table called 'edit_options'. If the value is 0 it's not editable.
If a list/option is not editable it simply won't show up in the lists view in admin panel. 
If we insert 0 in the list's general row, the whole list won't show. If it's for a specific option, then only that option won't show.
Hope you like it! :)
thanks,
oshri

Add management options to premission 

---

interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
library/formatting.inc.php

Hi,
In the calendar week view, the date shows up in mm/dd format (it's hardcoded). This is not optimal for places where the standard is dd/mm. 
I used the oeShortDate function that takes date format from the globals and shows the date according to this.
This shows the year too in the date, so if we want to show only month and day I'm not sure how to go about it. Do you have any suggestions for this issue? Or maybe it's not such an issue.
Thanks,
shachar

calendar date format fix

---

interface/main/calendar/add_edit_event.php
library/globals.inc.php

Hi,
Here we're adding am option to turn off the option for submitting changes to all appointments in a recurrence, so users can't alter past information (only current or future).
Thanks!

added global for 'all' option

---

interface/main/calendar/modules/PostCalendar/pnuserapi.php

Hello Brady,
No recurring appointments are being displayed in the sixth row of the calendar month view (when present).
And no recurring appointments are being displayed for the last day of the fifth row of the calendar month view when there is a day in the month view prior to the last day of the fifth row that contains more than 24 hours (daylight saving).
(Also some changes for efficiency).

Fix - no recurring appointments are being displayed in the sixth row of calendar month view

---

.travis.yml
README.md
ci/lint.sh
library/ajax/log_print_action_ajax.php
patients/get_patient_documents.php

@bradymiller,
For issue https://github.com/openemr/openemr/issues/489
This is a rather exciting piece of the Modernization Project. Although it's just doing linting at the moment, I'm sure you can see the more advanced usages of CI as the codebase becomes more modern (unit tests, style cop checks, automated tests, etc).
Here's the build on my fork (runs on all PHP versions we support):
When this is brought into the main codebase, stats will appear on each pull requests in real time such as:
Here's the build badge on my fork (with some README cleanups):
All that needs to be done to merge this is sign up for https://travis-ci.org, click on OpenEMR, open up the badge config modal:
(Obviously replace with OpenEMR master and master branch)
...and update the badge URL on the README.
Thanks, …

Starting with CI

---

interface/patient_file/summary/disclosure_full.php

Fix lang issue at disclosure_full file

---

controllers/C_Document.class.php
interface/super/manage_site_files.php
interface/themes/rtl.css
interface/themes/style_babyblu.css
interface/themes/style_blue.css
interface/themes/style_light.css
interface/themes/style_metal.css
interface/themes/style_oemr.css
interface/themes/style_purple.css
interface/themes/style_radiant.css
interface/themes/style_sky_blue.css
interface/themes/style_tan.css
library/globals.inc.php
library/sanitize.inc.php
sql/5_0_0-to-5_0_1_upgrade.sql
sql/database.sql
templates/documents/general_upload.html

Hi.
Here new feature to ensure secure uploading files in the system.
Right now all the files are allowed to upload even script file what that enabled easy incursion to server (and it was tried..)
This feature enables to create white list of MIME content types of  allowed files and blocks all the others.
It should turn on with 'secure_upload' global  and the edit interface is found at administator->files.
hopefully you agree with the importance of this issues..
Thanks
Amiel

White list of files types that allowed to upload to server 

---

interface/forms_admin/forms_admin.php
interface/main/left_nav.php
interface/main/tabs/menu/menu_data.php
interface/main/tabs/menu/menu_updates.php
interface/patient_file/encounter/forms.php
interface/patient_file/encounter/new_form.php
interface/super/edit_layout_props.php
library/acl.inc
library/registry.inc
sql/5_0_0-to-5_0_1_upgrade.sql
sql/database.sql
version.php

This is similar to and builds on my PR #473 on 2017-02-08, but deals with standard encounter forms rather than layout-based. In the forms admin page you can specify an ACO for each form, and appropriate checking is done where menus and buttons are presented.
Reviews/comments appreciated.

Form-specific access control for standard encounter forms.

---

controllers/C_Document.class.php
controllers/C_DocumentCategory.class.php
interface/forms/newpatient/common.php
interface/forms/newpatient/new.php
interface/forms/newpatient/save.php
interface/patient_file/report/patient_report.php
interface/patient_file/summary/add_edit_issue.php
interface/patient_file/summary/stats.php
interface/patient_file/summary/stats_full.php
interface/super/edit_list.php
library/acl.inc
library/classes/CategoryTree.class.php
library/classes/Tree.class.php
library/js/CategoryTreeMenu.js
library/lists.inc
sql/5_0_0-to-5_0_1_upgrade.sql
sql/database.sql
templates/document_categories/general_list.html
templates/practice_settings/general_list.html
version.php

Here are more access control improvements.
This adds features for assigning ACOs to specific issue types and specific document categories, and adds some associated logic for checking those permissions.
For issue type ACOs see Administration -> Lists -> Issue Types.
For document category ACOs see  Administration -> Practice -> Documents -> Edit Categories. Note the new "(Edit)" link, and the new fields when adding a category. The "Value" attribute was already in the database and seems to be used by the eye exam forms, so I included that as an editable field.

Access control for individual issue types and document categories.

---

common/database/connector.php
interface/globals.php
interface/main/calendar/includes/pnAPI.php
interface/modules/zend_modules/config/autoload/global.php
library/globals.inc.php
portal/patient/_machine_config.php

This adds a global setting for a site's time zone, and at script startup sets the default PHP and MySQL time zones to that.
Anyone see a problem with this?

New global parameter for time zone.

---

contrib/util/docker/Dockerfile
contrib/util/docker/container_init.sh
contrib/util/docker/setup_automation.sh

Docker now lets you mount outside files inside /var/ww/html, which means changes made in your favorite editor are now live in the container and changes the container makes go into existing files. I botched moving things around in git when I noticed running the docker container changed some files (e.g. sites/default/sqlconf.php) which hold information specific to one person's machine/setup, I was going to use .gitignore to keep them out of future commits. If anyone has a better idea I'd love to hear it. (like selectively picking files for commits - I have a script which just pushes everything in the working directory (shame on me)).

Optimized docker for development

---

interface/patient_file/summary/demographics.php

Hello Brady,
The Past Appointments widget is obscured when Recurrent Appointments widget is closed. Also the font size for display of past appointments is effected by this bug.

Fix - Past Appointments widget obscured when Recurrent Appointments widget is closed

---

interface/globals.php
interface/patient_file/report/custom_report.php

Restyled printable patient reports heading for consistency and fixed practice logo path error in img scr.
ref issue: #670
With more and more use of sites document directory the building in-place of uri's for properties that require a uri instead of a file path becomes tedious. Made available $GLOBALS['OE_SITE_WEBROOT'] to address.

Restyled printable reports heading and new global addition. 

---

interface/patient_file/summary/demographics.php

Noted this bug when I was testing the delete bug fix in the recent 5.0.0 patch. After deleting a patient in the tabs layout, nothing happened (ie. patient wasn't cleared from the display). This fixes that.

patient delete bug fix for tabs layout

---

interface/forms/group_attendance/functions.php
interface/forms/group_attendance/new.php
interface/patient_file/history/encounters.php
interface/therapy_groups/therapy_groups_models/therapy_groups_participants_model.php
interface/therapy_groups/therapy_groups_views/groupDetailsParticipants.php
library/group.inc

Hi.
Here some improvements and fixes in the therapy group system.
1. option to get only active patients in the form group attendance.
2. sort participants (according Alphabetical and active before inactive).
3. empty fields on click 'cancel' in add participants forms.
4. hide columns that not relevant to group (billing and insurance ) from encounters history of groups.
Thanks
Amiel

Therapy group improvements

---

interface/globals.php

Our PHP min is 5.4, magic quotes was deprecated in PHP 5.3 and removed
in 5.4 so we no longer need to worry about this

Remove undoMagicQuotes function

---

interface/forms/group_attendance/new.php

Brady hi,
The query would bring in the same participants multiple times (as many times as the groups they participate in) because of the extra JOIN.
This fixes it.
(And even though only active participants are supposed to be brought in, because this query is only for retrieving data from an already existing form, it makes no difference at this stage so we dont need to check this).
Also made the query more readable.
Thanks,
shachar

fix for attendance form

---

interface/main/tabs/templates/tabs_template.php
interface/themes/tabs_style_full.css

When hovering over the tab bar in an area without a tab, the entire area would
change to the :hover background-color of a tabNotChosen. This PR supresses that
hover

Minor styling fix to full tab styling

---

library/patient.inc

Bug:
When saving empty deceased date (patient demographics) the date would be inserted as 00-00-0000, not as null.
Fix:
Now if empty or 00-00-0000, will be saved as null in db and appear empty in demographics.
Thank you!

deceased date fix

---

interface/main/left_nav.php
interface/main/tabs/menu/menu_updates.php
interface/modules/zend_modules/module/Installer/src/Installer/Model/InstModuleTable.php

Hi brady.
Here I've added functionality for the hooks of openemr modules.
Without this PR after installation of new module added new link for the module under  'Modules' section, but it's doesn't support sub categories and it's possible to add only one screen for every modules.
I've saved on the last  functionality but I add option for locate hooks in the modules section -
Now if you choose to put the hooks in the modules it will locate in sub categories under the name of the module and it's possible to put few screens under one label.
It's work correctly in the frames menu and also with tabs layout.
Thanks.
Amiel

Sub categories in the 'modules' section

---

interface/main/tabs/menu/menu_updates.php

completion of PR [#789](https://github.com/openemr/openemr/pull/789).
I removed the permissions of super admin because the logic of permissions of modules working only with 'modules acl settings' and modules without acl configs not should be shown in the menu.

Remove auto permission for super admin

---

interface/forms/soap/templates/general_new.html
library/smarty/plugins/function.headerTemplate.php
library/templates/standard_header_template.php

For future proofing (to allow going smarty2 to smarty3 or to change to another templating structure), need to remove the pure php code from the smarty templates. This is the first code towards that where make the SOAP template without any pure php and also bring in a mechanism to bring in the standard header.

start of project to remove pure php code from smarty templates

---

controllers/C_InsuranceCompany.class.php
library/classes/Pharmacy.class.php
templates/document_categories/general_list.html
templates/documents/general_queue.html
templates/hl7/general_parse.html
templates/insurance_companies/general_edit.html
templates/insurance_companies/general_list.html
templates/insurance_numbers/general_edit.html
templates/insurance_numbers/general_list.html
templates/pharmacies/general_edit.html
templates/pharmacies/general_list.html
templates/practice_settings/general_list.html
templates/x12_partners/general_edit.html
templates/x12_partners/general_list.html

https://github.com/openemr/openemr/issues/799

Practices gui - bootstrap light, no pure php in smarty, html escaping in smarty

---

library/sql.inc

Hi Brady,
Issue:
Whenever sqlInsert is called and returns an error, this HelpfulDie method shows the query on the screen.
So I used the `sql_string_no_show_screen` global so we have the option not to show the sql query.
Is it okay that I used this global or do I need to create a new global?
thanks

option not to show sql query in lists edit

---

interface/main/calendar/add_edit_event.php

hi, 
bug fixed:
When multi provider is turned on, there's a js error when saving an event in provider tab.

fixed save js error in provider tab

---

interface/therapy_groups/therapy_groups_views/groupDetailsParticipants.php

Changed to be more informative, so we can know how many participants there are in total (there was no indication until now).

changed info of datatable

---

interface/forms/newpatient/common.php
interface/super/edit_globals.php
library/globals.inc.php

Adds an option under Administration --> Globals --> Features which
allows the user to set a default category which will be automatically
set on the new encounter form

Allow a default Visit Category type to be set

---

interface/main/tabs/js/patient_data_view_model.js
interface/main/tabs/templates/patient_data_template.php
interface/themes/tabs_style_compact.css
interface/themes/tabs_style_full.css

@robertdown noticed the following issues with the new patient image picture feature:
1. `alt` text was showing while the image was being loaded in.
2. `/openemr` is not safe to hard code for public images.
3. His custom picture is not loading :(.
I have fixed the first 2 issues and incorporated his bootstrap css change recommendations in. However, the custom picture not loading needs to be tested out. Perhaps the category was not `Patient Photograph` and was the `Patient ID card` which shouldn't be shown as the patient picture.

Patient image fixups

---

interface/therapy_groups/therapy_groups_views/groupDetailsParticipants.php

Hi.
I fixed the translation of the info statement of datatable in the participants screen as it work well in the openemr/library/js/xl/datatables-net.js.php (patients list).
Thanks.
Amiel

fix translation in the group's participants screen

---

interface/super/edit_layout.php
interface/super/edit_list.php
sql/5_0_0-to-5_0_1_upgrade.sql
sql/database.sql
version.php

Hi.
We've found problem with the white list of files mime-types that could be uploaded.
In the case type bigger than 31 (max length of option_id) only the first 31 chars is saved.
This causes duplicate entries between similar types in some of the files.
There is any problem with change of max length of option_id?
This is the simple and clean solution. 
Thanks
Amiel

Enable larger option_id in the list_options table 

---

library/formatting.inc.php

hope to fix this:
PHP Warning:  number_format() expects parameter 1 to be double, string given in /var/www/html/openemr/library/formatting.inc.php on line 13, referer: https:// /openemr/interface/billing/sl_eob_process.php?eraname=20170725_441355165_&debug=0&paydate=&original=original

fix php warn double value oeformatmoney

---

interface/main/finder/dynamic_finder_ajax.php

Hi.
I added 'trim' function on the search input in the patients list screen. 
Without trim searches that beginning with space are not found. 
Thanks.
Amiel

Trim search patient 

---

interface/patient_file/report/patient_report.php

Fixes the following issue:
If there are multiple encounters created on the same day, in the patient's reports (accessed from patient demographics) the forms are grouped under the wrong encounter.
This happens because the algorithm for grouping the forms relies on the order in which the forms return from the query, and this is ordered by date.
This fix orders them first by encounter id so that forms are always grouped correctly.

reports order fix

---

templates/prescription/general_fragment.html
templates/prescription/general_list.html

Used the smarty php escape function to prevent the rendering of html
tags both in the prescription summary screen in the patient record and
in the prescription edit modal.
ASC

XSS remediation in prescription module  - re: issue #1018

---

interface/patient_file/encounter/forms.php

Hi.
This is addition fix connect to PR [959](https://github.com/openemr/openemr/pull/959) in the forms frames.
I've found that screen of edit from is opened in the parent frame and not in the forms frame so it cause bug when clicking on save/cancel buttons (it's opened in the parent frame - full screen).
I removed traget="_parent" from a tag.
Thanks.
Amiel

Fix link to edit encounter's forms screen

---

cloud/assets/OpenEMR.json
cloud/chapters/01-Getting-Started.md

Amazon gates access to Elastic Beanstalk environments based on the age of the account -- the newest of the new accounts can't access older environments that lack new features or security enhancements. This updates the stack to use the new v2.4.3 environment, instead of the deprecated v2.4.2.

Fix for moving Amazon target

---

interface/forms/newGroupEncounter/save.php
interface/forms/newpatient/save.php

Fixed the following issue:
Because the hierarchy of the frames changed, this caused a js error when trying to redirect the bottom part of window back to encounters list after editing a 'new encounter' form.

fix for new encounters form edit because of new hierarchy of frames

---

interface/main/calendar/add_edit_event.php
sql/5_0_0-to-5_0_1_upgrade.sql
sql/database.sql

There was a js error that prevents the recurrent event for provider to be saved when the javascript validation mechanism is on

Fixed javascript error when saving a recurrent provider event using js validation

---

interface/forms/vitals/FormVitals.class.php

Hi.
The fields of user and groupname in the  table 'form_vitals' are always NULL. I changed it and now the session parameters about user is saved instead. 
Thanks.
Amiel

Save current user and group in the vitals table

---

interface/reports/edi_271.php

references this [community post](https://community.open-emr.org/t/4-1-2-dev-270-271/5359/5?u=stephenwaite) by @juggernautsei 
with this simple fix was able to view elig info from this [sample](https://community.open-emr.org/t/eligibility-response-not-parsing-into-table/8956/3?u=stephenwaite)
also found this old doc 
[mmf-batch_eligibilityverification.pdf](https://github.com/openemr/openemr/files/1275539/mmf-batch_eligibilityverification.pdf)
you view the 271 response info on the tab next to patient insurance from their main page
kudos to mmf whose code still holds up and brady's work bringing it in 7 years ago

simple fix to segment delimiter

---

library/classes/rulesets/Cqm/reports/NFQ_0101.php
library/classes/rulesets/Cqm/reports/NFQ_0384.php

found this after running Reports->Clinic->Quality Measures(CQM)

add php tag to cqm reports

---

contrib/weno/drugspaidinsert.sql
interface/weno/drugPaidInsert.php

@juggernautsei ,
The import formulary was not working in Admistration->Weno. This is because adodb/mysqli will not allow multistatement queries since this is a sql-injection risk. This fixes that by doing a separate query for each statement. Is testing well and will bring it into the codebase.

weno formulary import fix

---

interface/forms/newGroupEncounter/save.php
interface/forms/newpatient/save.php

Currently there are critical js errors when saving and editing forms and encounters.
After some testing I did, I saw that the problem was that in many scenarios the frames hierarchies were different from one another, so checking what the current hierarchy is in the code (by checking for undefined) was the only way I was able to fix this issue.

fix for saving encounters and forms

---

interface/therapy_groups/therapy_groups_controllers/therapy_groups_controller.php

Issue:
When adding new group would take very long time to load. This is because when there is no group id in session all openemr post calendar events are loaded (not just a specific group's).
Fix:
Events are loaded only when there is a group id in session.

groups performance fix

---

interface/patient_file/encounter/encounter_top.php
interface/patient_file/encounter/forms.php
library/api.inc

When an encounter is entered the code has been creating a frameset for it with
a single frame named "Forms". This seems to be a holdover from when the frameset
had a second frame in it.
Currently this frameset seems unnecessary since it is contained in another frame
or iframe, depending on the layout. In addition there is at least one bug where
canceling forms causes the frameset to be nested to arbitrary levels.
This commit removes the "Forms" frameset.

Removing unnecessary frameset and related bugs.

---

interface/billing/billing_report.php

Billing manager select all reset fix found by @stephenwaite .

Prevent default form action on select all button.

---

contrib/weno/drugspaidinsert.sql
interface/weno/admin.php
interface/weno/confirm.php
interface/weno/drugPaidInsert.php
interface/weno/import_pharmacies.php
interface/weno/jsonScript.php
interface/weno/markTx.php
library/classes/Prescription.class.php
templates/prescription/general_list.html

Fixed imports- had to redo drug paid import sql file as old was breaking transaction!
Redid pharmacies import and wrapped in transaction.
Fixed NDC (drug_id) not being saved with prescription or populating json.
Fixed qualifier and provider id syntax for populating transmission json.
Maybe others!

Weno eRx fixes

---

interface/therapy_groups/therapy_groups_controllers/participants_controller.php
interface/therapy_groups/therapy_groups_views/groupDetailsParticipants.php
interface/therapy_groups/therapy_groups_views/header.php

Hi.
1. Remove unnecessary escaping from comment field.
2. Adding date format to JS validation of 'end date' field.
Thanks.
Amiel

Fix 2 bugs in the group's participants screen

---

interface/patient_file/summary/demographics.php
interface/patient_file/summary/pnotes_full.php

This is a small fix in the titles of the notes widget and notes full screen:
What these screens are actually showing are **messages**, not **notes**.
When we add a message in the bottom messages screen (accessed from the left nav), this is what later shows up in the 'notes widget'.
Therefore, in order to prevent confusion, we think it's important that the names match so users understand that this refers to messages.

fix for notes titles

---

interface/forms/vitals/templates/vitals/general_new.html

Hi.
Completion of PR  [#1110](https://github.com/openemr/openemr/pull/1110).
I removed 'parent' from cancel link in vitals form.
Thanks 
Amiel

Remove unnecessary 'parent' from cancel link in vitals form (related to #1110)

---

interface/super/edit_layout.php

I Missed handling 0 in legacy modifier string to json array conversion. Still have the on select data type error to deal with and found that the onchange call to NationNotesContext() from the select tag is fine but the document.getElementById("fld["+lineitem+"][contextName]").style.display=''; in function, returns null. Will add fix here when I find one.
Thought @matrix-amiel  could go ahead and see if this fixes his issue with Read Only option...

Allow for zero in string or singular in legacy modifiers.

---

interface/patient_file/summary/demographics_full.php

Hi.
This is bug in the page validation of Zend framework. 
The edit page was missing preventDefault for pause submit until validation finished.
Thanks.
Amiel

Prevent submit before opening validation popup

---

interface/therapy_groups/therapy_groups_controllers/participants_controller.php
library/encounter_events.inc.php

Hi.
We found bug in the auto create of group's encounter's, the encounter is created in every edit of event. the problem was that '$today' is always null.
+ fix of warning in the groups screen.
Thanks
Amiel

Fix auto create of group's encounters and warning message

---

interface/forms/eye_mag/a_issue.php
interface/forms/eye_mag/help.php
interface/forms/eye_mag/php/eye_mag_functions.php
interface/forms/eye_mag/view.php

The problem with 1-11-3 version is you may no longer invoke .each or .map on a string, null or undefined. Really should fix where these errors occur at some point.
Fixed module up for PHP7.1 capability and tested as much as the basics including code lookup's with new dialog.
The font size is causing content to overflow container and I would recommend making the tabs and panels responsive rather than simply changing font size.
See https://github.com/openemr/openemr/issues/1161

Downed jquery version 1-11-3 to 1-10-2.

---

interface/main/messages/messages.php

Hi Brady,
This addition enables the user to send a message to multiple patients (and acts pretty much like sending to multiple users which is an existing feature).
Everything is supposed to work the same besides for being able to send to multiple patients.
thanks,
shachar
demo is here:
http://www.open-emr.org/wiki/index.php/Development_Demo#Lambda_-_Up_For_Grabs_Demo

Messages to multiple patients

---

library/globals.inc.php
portal/patient/_machine_config.php
portal/patient/fwk/libs/verysimple/HTTP/RequestUtil.php
portal/patient/templates/_modalFormHeader.tpl.php

Trying to live in Docker and AWS world. @bradymiller Think you could get this on demo site or my up for grab? I can use relative pathing to a point for my rest api calls but depending where my call originates, I may need base path, especially if sharing same controller between two app's(Openemr and portal). Proxies, Redirects and load balancer's tend to leave a trail and hoping it is with HTTP_X_FORWARDED_PROTO and if not I put a flag in Globals to force proper protocol....
Demo: http://www.open-emr.org/wiki/index.php/Development_Demo#Epsilon_-_Up_For_Grabs_Demo

Mod to base url structure

---

acl_setup.php
acl_upgrade.php
interface/main/left_nav.php
interface/main/tabs/menu/menus/standard.json
version.php

Hi.
This PR contains creation of new ACO for manage modules.
Without the new ACO every user with one of ACO of admin section (Calendar Settings, Pharmacy Dispensary etc.) in the old menu or every user with ACO Modules->menus in the new tabs menu can edit/remove all the modules of the clinic.
Thanks.
Amiel

New ACO for manage modules

---

library/js/xl/jquery-datetimepicker-2-5-4.js.php

Hi @sjpadgett @bradymiller .
I've found strange behavior of datepicker popup in the add/edit event screen after the last changes.
I'ts happen **only in RTL languages** .
1. The popup is opened at a distance of 50px from the input (It's happen in a few screens) -
2. In the another place a popup is cutted  in the edge of screen.
I tried to research what the problem, I think it's bug in the datetimepicker library (https://xdsoft.net/jqplugins/datetimepicker/).
I suggest here option of patch to resolved this. (I haven't time to fix a library now).
If you knew another solution I will be happy, but we need any solution for this because a screen of edd/edit event is not working for RTL now.
Thank you!
Amiel

Patch in the datepicker popup for RTL languages

---

library/dialog.js

Hi.
The last changes in the popups contains a new JS function - 'isInteger', [IE not supports that function](https://developer.mozilla.org/he/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger#Browser_compatibility) and all the screens are failed.  
So I changed it to another function.
Thanks.
Amiel

New dialog not working in IE browser

---

gacl/gacl.class.php
library/acl.inc
library/sql.inc

-Do not open a new database connection for every acl_check call
-Change back the main and gacl adodb connections to be persistent

database performance improvements

---

interface/forms/newpatient/common.php

This was an add-on issue within #1313. This replaced another fancybox for encounters add issues button. This is a pretty good example of a fancybox replace. The trick really is finding out where the modal html lands for frames u.i because we can't have one set place for building the modal like we have in the tabs interface. Then include the required dependencies.

R&R'ed fancybox for encounter common dialogs.

---

interface/main/left_nav.php

Tested across all browser's including IE11. Appears all left nav menus are now consistent. Bootstrap, for some reason, sets html base font to 10px causing newer themes to calculate font-size incorrectly. This was very apparent in light theme(tiny font-size). My previous attempt to fix broke other themes so here we are.

Left Nav fix for bootstrap override of doc html font-size.

---

controllers/C_Document.class.php
library/classes/Document.class.php
library/dicom_frame.php
library/js/dwv/dwv_i18n.js
templates/documents/general_list.html
templates/documents/general_view.html

viewer needed to be in a container because of viewer style/html stepping on tab/frame html.
Cheap fix for windows dicom mime type.
Pop out of viewer allowed.

move dicom viewer to iframe

---

interface/forms/fee_sheet/review/fee_sheet_review_view_model.js

I have encountered this again. In our database, the justify field does not always contain data. So when the review button is clicked. The console error is shows that the justification justify_codes is null. I believe you can test this out on any system. Leave the justification null and it should hang or from the users view cause the Review button not to work.

Fee sheet review hangs if the justify field in the database is empty

---

gacl/admin/edit_group.php
gacl/admin/templates/phpgacl/edit_group.tpl
gacl/gacl_api.class.php

Continued from https://github.com/openemr/openemr/pull/1402
@priya-anand ,
Here's for edit_group. Let me know if any issues on testing for you. Note that in this case needed edit format_groups() function to ensure that the entries in Parent are html escaped.

 html escape edit_group

---

interface/forms/eye_mag/php/eye_mag_functions.php

Canvas drawing uploads fails if thumbnail checked #283
Turns out that when “Thumbnail” Global is checked, you always get the thumbnail with a traditional request - you have to GET the original specifically (show_original=true)

Bug Fix #283

---

library/js/vendors/validate/validate_extend.js
library/validation/validation_script.js.php

This commit add the option to validate dates in format dd/mm/YYYY format  with the pastDate function 
by editing the  LBF_Validations and changing it to 
{"pastDate":{"message":"must be past date","format":"2"}}

Extend the JS validation to support dd/mm/YYYY format 

---

interface/themes/rtl_tabs_style_compact.css
interface/themes/rtl_tabs_style_full.css

Fixes following issues:
- The 'fa-caret-right' arrow in submenus was outside of menu box.
- The child of submenu would open up on right side instead of left.

fix for rtl in tabs

---

library/js/vendors/validate/validate_extend.js

If an only year validation is activated  and the value passes the check 
the function should terminate and not continue

Fix Only Year validation

---

interface/usergroup/adminacl.php

@stephenwaite ,
This is fix for your issue: https://github.com/openemr/openemr/issues/477
This is testing well for me (when have space in usernames).
Feel free to give it a spin.
-brady

acl admin gui fix to allow spaces in usernames

---

interface/main/main_screen.php
interface/main/tabs/main.php
library/dialog.js

This is meant to allow the correct css to be loaded by dialog.js for rtl if dependency is missing from calling script. A more correct solution is to add the correct dependency where it is needed but I guess it can't hurt to have the global in top.

Add language direction javascript global to top frames. issue #1456

---

interface/super/edit_globals.php

For:
``````
PHP Warning:  socket_connect(): unable to connect [111]: Connection refused in /var/www/openemr/ccdaservice/ssmanager.php on line 105, referer: http://localhost/openemr/interface/super/edit_globals.php
``````
Note there is no way to actually avoid this warning. So the next best thing is to just have php not report it :)

php warning fix in edit_globals.php

---

interface/main/calendar/add_edit_event.php
library/js/vendors/validate/validate_extend.js

I changed the validation logic to support all date formats 
one can use the validation by setting 
options.format
OR
var g_date_format='<?php echo $GLOBALS["date_display_format"];?>';

Add support for different date validation formats

---

library/pnotes.inc

Including `activity` column in functions that do not allow its inclusion in returned columns.  This value is important when `all` messages are returned.

Include `activity` columns in pnotes.inc results

---

interface/main/dated_reminders/dated_reminders.php
interface/main/messages/messages.php

Hi.
The messages screen was changed in the last months and the style was broken, Every message is showing in a few lines and half of screen is empty..
I commit here suggestion for improving this..
After fix -
Thanks
Amiel

Fix style of messages screen

---

interface/super/edit_list.php

Bootstrap uses navbar-form for forms within navbar.  
This minor change makes theform correctly span navbar and remaining body.  Also fixes BS 4 issue.

Adjust form tag placement

---

interface/drugs/drug_inventory.php

This change adds active status as first key in listing drugs or inventory items.
Also nothing seems to require older version of jquery.  So switching to standard.

Always list active drugs/inventory items first

---

library/patient.inc

Enables developer to specify certain encounter when fetching a patient's bills.
Can be many use cases - we specifically are using this to fetch just the bills from the latest month on which at least 1 bill exists.

Fetch bills for specific encoutner

---

interface/super/edit_globals.php

@sjpadgett ,
It looks like the ccda background service is a thing of the past, so figured this code in edit_globals.php needs to go also. Just want to confirm that we should remove this?
thanks,
-brady

ccda background service remove from edit globals

---

controllers/C_Document.class.php
library/dicom_frame.php

No longer requires .dcm extension in zips or single file to determine dicom. Detects mime from file header and will add extensions if appropriate.

DICOM viewer mime detection update

---

interface/main/calendar/add_edit_event.php

Hi.
Here I fixed bug that happen if user has only view permission for events of therapy group - `acl_check("groups", "gcalendar", false, 'view')`.
In this case (if global of group is turn on), all the inputs are disabled also for patient and provider tabs, so I changed it only for group tab.  
Thanks
Amiel

Fix bug in the permission of group in the add/edit event popup

---

interface/fax/faxq.php

Fix wrong passed variable name

---

library/appointments.inc.php

Hi.
Minor fix in the flow board. fetch from 'openemr_postcalendar_categories' only active categories.
Thanks
Amiel

Fetch only active visit categories in the flow board

---

interface/patient_file/history/encounters.php

Issue:
When a user has no access to the encounters screen, the tab title is 'Unknown'.
This happens because the script is exited before the title is set in the html (which is where the javascript gets the title to insert into the tab title).
(I also combined the groups acl check with the rest of the acl checks - didn't see a reason for them to be separate).

fixed tab title when access is forbidden

---

contrib/util/docker/README.md
docker-compose.yml

Note mysql8 does not work with OpenEMR at this time. This will add mysql8 as an option in the docker development environment, so we can work on this.

add mysql8 option to development docker environment

---

interface/main/main_screen.php
interface/main/tabs/main.php

Hi.
Her 2 minor fixes:  
1. If you select patient list for default top pane (in the globals) the screen is opened splited because the target of tab is incorrect in the code.
2. The process of login unsets the sessions of frame1url and frame2url, and if you refresh the screen the clinic is opened with calendar instead the url is saved in the globals. (I haven't found any problem with this removing, hopefully it's ok) .
Thanks
Amiel

Fixes in the loading of default tabs 

---

library/ajax/document_helpers.php

1. Limit number of autocomplete entries as specified in the request (default=20).
2. Display deceased patients' names last.

Apply limit to names shown in document helper

---

library/authentication/privDB.php

Noted this causing an odd bug here:
https://community.open-emr.org/t/adodb-mysql-log-inc-php/10251/23
Can't really test this feature (ie. will obviously make sure it doesn't break normal use openemr) since I only think it is rarely used and i do not know how to set it all up.

blind fix to support mysqli for privDB code

---

contrib/util/docker/README.md
contrib/util/docker/stuff/configs/dev-php-fpm-7-2/php.ini
contrib/util/docker/stuff/configs/nginx/nginx.conf
contrib/util/docker/stuff/dockers/dev-php-fpm-7-2/Dockerfile
docker-compose.yml

This is really cool and only possible from Sandra Gutierrez's hard work, which is detailed here:
https://community.open-emr.org/t/openemr-lemp-on-freebsd/10283
This solution was derived from the wiki page here(written by Sandra):
https://www.open-emr.org/wiki/index.php/OpenEMR_with_nginx_and_php-fpm
Need to also incorporate ssl at some point, but goal was to just get it working (ie. a starting point so devs and testers could start testing and playing around with this).
To briefly summarize what we can now do in the docker dev development environment. We can simultaneously test same openemr code on apache/php7.1 , apache/php7.2  , and nginx/php7.2 .
Just as a visual, below are the screenshots from the Administration->Other->Calendar->Test System in these 3 different things (again, all on …

Initial support for nginx and php-fpm for openemr docker development environment

---

interface/forms/newpatient/save.php

Hi.
In the case there is category name with a double quote (") or singlequote (') , the name appears with html entities in the encounters list (only after create new encounter)
I changed the code to right security function.
Thanks
Amiel

Enable encounter name with quotes

---

library/dialog.js

Only affected portal, especially appointments where patient was not populated due to wrong ajax data location. Yes dlgopen() can popup using html content like in an alert, form e.t.c

minor bug fix for dlgopen ajax  mode

---

interface/main/messages/messages.php

Issue fixed by PR:
When disabling recall global, the recall title & tab are still visible in the messages center.

when recall disabled recall elements still visible

---

interface/forms/newpatient/report.php

Treat Sensetivity='None' as no restriction for display of encounter form data.

Display encounter data when Sensetivity is not set

---

portal/account/account.php
portal/account/register.php
portal/add_edit_event_user.php
portal/find_appt_popup_user.php
portal/import_template.php
portal/import_template_ui.php
portal/patient/_machine_config.php

PP2 Update

---

ccdaservice/ccda_gateway.php
interface/billing/sl_eob_search.php
interface/de_identification_forms/de_identification_screen2.php
interface/de_identification_forms/find_code_popup.php
interface/de_identification_forms/find_drug_popup.php
interface/de_identification_forms/find_immunization_popup.php
interface/fax/fax_dispatch.php
interface/fax/faxq.php
interface/main/daemon_frame.php
interface/patient_file/encounter/search_code.php
interface/super/manage_site_files.php
library/forms.inc
library/registry.inc
patients/add_edit_event_user.php
patients/find_appt_popup_user.php
portal/add_edit_event_user.php
portal/find_appt_popup_user.php

security fixes

---

interface/forms/LBF/printable.php
interface/forms/eye_mag/php/taskman_functions.php
interface/forms/eye_mag/save.php
interface/globals.php
interface/patient_file/report/custom_report.php

The mechanism for mpdf version 7 has changed for declaring the tmp directory:
https://mpdf.github.io/installation-setup/folders-for-temporary-files.html

proposed mpdf version 7 tmp directory fix

---

interface/forms/newGroupEncounter/common.php

Fix for following issue:
When clicking cancel in a new encounter for therapy groups, user is redirected to a patient file demographics screen.

fixed cancel link in groups encounters

---

contrib/util/docker/dockers/dev-nginx/nginx.conf

Orthanc doesn't allow for cross origin resource sharing by default. If we use nginx as a reverse proxy we can add CORS headers to all the requests coming from Orthanc. See http://book.orthanc-server.com/faq/nginx.html and https://groups.google.com/forum/#!topic/orthanc-users/GG-dFIn2LQ0 for more. The default url of `http://localhost:8042` is okay since we are already specifying that in our docker-compose file.

Set up nginx as reverse proxy for Orthanc

---

interface/themes/oe-common/acl-common.scss
interface/usergroup/adminacl.php
package-lock.json

Hi.
In the CSS files there is class -
```
.alert {
font-size: 10px;
color: red;
font-weight: bold;
}
```
This class is found in the  `openemr/interface/themes/oe-common/acl-common.scss` file and belong to ACL administration screen (I haven't found another place..)
This class overwrites the [.alert class of bootstrap ](https://www.w3schools.com/bootstrap/bootstrap_alerts.asp) and we can't use with bootstrap  alerts in our modules. (The 'loading' class from same reason)
So I changed the css that work only in acl file. (Hopefully there isn't another screen that uses that class.. I didn't find)
Thanks
Amiel

CSS change

---

interface/forms/CAMOS/ajax_save.php
interface/forms/CAMOS/content_parser.php

Fixes double escaping of entries in CAMOS. Also can fix the "bad" entries prior to this commit by editing them and saving them.

CAMOS critical bug fix

---

interface/patient_file/summary/pnotes.php

Patient Messages: clicking the row in the table leads to Unknown window 
since there is an "edit" botton for each row the functionality can be removed 
on clicking the row

remove EditNote function

---

library/menu/src/MainMenuRole.php
library/registry.inc

Hi.
Now all the active forms are shown in the patient menu (patient -> visit forms).
I added parameter to 'getRegistered'  function that filters only patient encounter forms. 
Thanks
Amiel

Remove therapy group forms from menu (patient -> visit forms)

---

interface/billing/sl_eob_invoice.php

form_save value unset since changing `<input> to <button>`.  Need to set form_save value to update invoice.  Without it adjustments are not saved.

Invoice Fix

---

interface/main/tabs/main.php

hi @stephenwaite and @sjpadgett ,
Was hoping to get your thoughts on this change. This will basically not allow users to copy/paste the main.php link or even do a browser refresh to the main.php page. Is this overly invasive? If do this should I throw up a warning if a user tries to do a page refresh from browser (via window.onbeforeunload) to prevent user from doing a browser refresh and losing their work?
thanks,
-brady

possible security improvement

---

interface/usergroup/user_info.php
library/auth.inc
library/authentication/login_operations.php
library/sanitize.inc.php

When collecting ip address.
$_SERVER['REMOTE_ADDR'] is not always correct (for example, when behind a reverse-proxy), however it can't really be spoofed.
$_SERVER['HTTP_X_FORWARDED_FOR'] will get correct ip address when behind a correctly set reverse-proxy, however it can be spoofed.
So set it up in log that $_SERVER['REMOTE_ADDR'] is always collected and then will also record if $_SERVER['HTTP_X_FORWARDED_FOR']  if exists.
Encapsulated this in a function, so we can fix it up as needed in the future.

log ip improve

---

interface/billing/sl_eob_search.php
library/globals.inc.php
library/invoice_summary.inc.php
sites/default/statement.inc.php

- Statement reflects the service facility and billing facility specified in encounter. The default logo if a logo is selected is 'practice_logo.gif' but the end user has the ability to change this. The logo has been placed left. Formatting issues if the service facility has a long name should auto size up to 40-50% of header width.
- statement header should now auto size w/w/o logo.
- moved logo to left where most logo appear on letterheads.
- added insurance names to adjustment notes.
- changed logo file logic.

Update of P.R #1612 by Daniel Pflieger to 5.0.2

---

library/user.inc

found this error
[Sun Oct 21 13:41:03.850345 2018] [php7:warn] [pid 604] [client 172.18.0.1:46614] PHP Warning:  Use of undefined constant length - assumed 'length' (this will throw an Error in a future version of PHP) in /var/www/localhost/htdocs/openemr/library/user.inc on line 161, referer: http://localhost:8300/interface/billing/sl_eob_search.php

fix array count

---

interface/main/holidays/Holidays_Storage.php

Hi.
The error I fixed- 
The `$_SESSION['pc_facility']`  is created when you visit in the calendar screen, if you go to import holiday before you go to calendar you have sql error.
Thanks
Amiel

Fix error in the import holiday

---

interface/main/tabs/menu/menus/patient_menus/standard.json
interface/patient_file/summary/demographics.php
interface/themes/rtl.scss
sites/default/documents/custom_menus/patient_menus/Custom.json

Hi.
I send here 2 fixes we have found in the new style of patient file in our language.
1. rtl issue.
2. We have problem the translation of 'Dashboard', the meaning of dashboard is very general and not match  in Hebrew. I suggest to replace the title to 'Medical record' I think is more  understandable.   
Thanks
Amiel.

Minor fixes for internationalization of new style of patient file

---

library/MedEx/API.php

Add button to “Add Recall” to make Recall Board not be “totally useless”.
More style removal.
Autofill with PID in session’s info.
Clean up API logging methodology.
SQL logic to pick up NoShows and
Add SMS capacity to GoGreen Messaging.

Recall Board+API

---

library/billing/src/X12837P.php

clearinghouses like office ally have edited prior erroneous x12s on openemr user's behalf but need this fix if going str8 to payer

put adj group codes on same line for 2ndary claims

---

interface/patient_file/history/history.php
interface/patient_file/report/patient_report.php
interface/patient_file/summary/demographics.php
interface/patient_file/summary/stats_full.php
interface/patient_file/transaction/transactions.php
interface/reports/external_data.php
interface/reports/pat_ledger.php
library/menu/src/PatientMenuRole.php
library/options.inc.php

Hi.
In the our clinics we change the standard patient menu and remove part of the links, I found that in the new style of menu the ID's of links is numeric in ascending order and it is hardcode so there is problem with the mark as active of the current page.
(For example - I remove History tab so issues is number 2 but the id is still 'nav-list3' therefore the  'Documenst' tab marks as active)
I changed it to the Id from the json and now it is dynamic.   
In additional I added option to add class to link (in the json), we need it because we need change the style of the links (we have extra modules and no space in the one line with current style)   
And more translation fix..
Thanks
Amiel (Matrix)

Patient menu fixes

---

interface/main/calendar/add_edit_event.php

add_edit_event only used the request to gather pid.   This changes it to use session if no request pid, and global $pid if no session.  Sets no pid if all three fail.  Thanks @sjpadgett for confirming bug and suggested fix.  I'm still new to this:)

using request, session, global pid to select patient

---

interface/main/calendar/find_patient_popup.php

in find_patient_popup, if no patients are found a link to create a new patient is shown.  It was not protected by an acl check for demographics write or addonly.  I added this to the existing if created by VicarePlus.
I am finding bugs because I am a novice php coder, and I don't know what I am doing.  It makes me read and think and do things that no user or coder with experience with openemr would think to try.

added acl check for create new patient link

---

library/billing/src/X12837P.php

adding more warnings for missing demographics in X12 837 like when claims would fail for missing city state zip, this way can see the trouble in the log and while the claims are still selected in the billing manager can navigate to the pt demos and fix and then regen the x12 837

adding more warnings for missing demographics in X12 837.

---

package-lock.json
package.json

Immediate fix for https://github.com/openemr/openemr-devops/issues/159. Updates to a bunch of node packages should probably be incoming. Note that npm, when running 'install' decided on significant changes to `package-lock.json`. Most changes are of the form `x.y.z` -> `^x.y.z`, but there are quite a few with odd behavior, like dropping down a minor version or switching from beta builds to regular builds. Some manual testing is likely warranted.

Removing `npm-run-all` as dependency

---

library/core/src/Kernel.php

@bradymiller @robertdown 
Global no longer exist.
edit: appears $webserver_root is not set explicit in globals so there is a chance $GLOBALS['webserver_root'] can be not in scope depending how globals.php is called.
To be safe going to leave this changed to $GLOBALS['fileroot'] because I know it will always be in scope.

$GLOBALS['webserver_root']  being used in Kernel class..

---

library/classes/postmaster.php

Hi.
MyMailer class (quick connection to PHPMailer) doesn't working without 'use' statement.
Thanks
Amiel

MyMailer class missing 'use' statement

---

library/crypto.php

Quick fix to correctly deal with the document encryption/decryption where both keys need to be indentical since are created from the passkey (note this is not the standard mechanism for encyryption/decryption and is just there to support this prior feature which is required by MU).
TEsting well and will bring this in after travis pass

minor crypto fix

---

library/menu/src/PatientMenuRole.php

Hi.
Here I added option to make dropdown menu in the patient file (In the new style the amount of the tabs is limited in the case you have a lot of modules.. like us ;) ).
From now if there are children in the patient menu json, they will created in dropdown, like the main menu (but with regular bootstrap style and only for single level) 
Thanks
Amiel

Enable drowpdown tab in the patient menu

---

library/auth.inc
library/authentication/login_operations.php

This one is pretty simple. The call to ``newEvent`` in ``verify_user_gacl_group`` appears to have been refactored out of ``validate_user_password``, but the ``$provider`` variable was not passed to the new function. This fixes that.
On a side note, how I discovered this was by going thru the setup: the created admin account does not get a corresponding ARO created for it in phpGACL. I had to add the ARO manually. I will open a separate issue about this.

authentication: fix undefined ``$provider`` variable in ``verify_user_gacl_group``

---

interface/usergroup/user_admin.php
interface/usergroup/usergroup_admin_add.php

The term 'Federal Drug ID' is used on the User Add and User Edit forms in the Administration section.  The term 'DEA Number' better describes the field.  
- Update User Add and User Edit administration forms to display 'DEA Number', rather than 'Federal Drug ID'.
@bradymiller There are references to `federaldrugid` throughout the app, but I wasn't sure if changing those to `deanumber` was part of the scope of this issue, or if this was literally just a request to change the text of the span elements.  Please take a look when you have a moment.

[ISSUE-470] Update Federal Drug ID span text to DEA Number

---

package.json

Hi.
We found errors in the our development server were happened because the jquery-ui-themes files not found after new installation.
The solution we found was to cancel the napa cache using new parameter in the package.json, we recommend to add it to the json.
Thanks.
Amiel

Disable napa cache

---

interface/eRxXMLBuilder.php
library/classes/QRDAXml.class.php

cherry picks from 502
d85a1449c93a32ac1e3a1798bd78a39ce3928d94 (QRDA reporting fixes for php 7.1 - fixed by Brady Miller)
057382026c520d9cedd99b6c8acfeb0b6a3efabc (rxnorm fix - reported by Craig Sparks, fixed by Stephen Waite)

Rel 501 back ports continued

---

sql/5_0_1-to-5_0_2_upgrade.sql
sql/database.sql
version.php

A bug was caused by the fact that some database tables holding `pid` were of type int while others were of type bigint.   To resolve that issue, all database tables that hold `pid` or whose `foreign_id` references it should have a column type of bigint.  
[ISSUE-1350] Modify all table references to `pid` columns to type bigint
Per the "Database Table Changes" section of the [Development Policies](https://www.open-emr.org/wiki/index.php/Development_Policies#Commit_Messages), I made the following changes 
- Made database changes in `database.sql` 
- Alter statements added in `5_0_1-to-5_0_2_upgrade.sql`
- Increment database version in `version.php`
Installing the app after making these changes was successful.
There does not seem to be consistency about whether these `pid` columns can hold a …

[ISSUE-1350] Modify all table references of `pid` to type bigint

---

sql/5_0_1-to-5_0_2_upgrade.sql
sql/database.sql
version.php

This is a small follow up to PR #2234. All database tables that hold `patient_id` should have a column type of bigint.  
[ISSUE-1350] Modify all table references of `patient_id` to type bigint
Per the "Database Table Changes" section of the [Development Policies](https://www.open-emr.org/wiki/index.php/Development_Policies#Commit_Messages), I made the following changes 
- Made database changes in `database.sql` 
- Alter statements added in `5_0_1-to-5_0_2_upgrade.sql`
- Increment database version in `version.php`
@bradymiller

[ISSUE-1350] Modify all table references of `patient_id` to type bigint

---

setup.php

Did:
* remove unnecessary `version_compare`
* remove a bunch of trailing spaces
* add `ini_set('display_errors', 0);`  
I did the manual install and had warnings Step 3 (entering the wrong MySQL host) and Step 4 (did nothing wrong). As these are displayed before the "check your PHP configs" step (Step 6), and can be confusing, I think showing PHP errors should be disabled at runtime.

Remove unnecessary version_compare + add diplay_errors=0

---

library/globals.inc.php
sql/database.sql

Fixes #2242.
- Set `secure_upload` on as default
- Whitelist `image/*`, `text/*`, `audio/*`, `video/*` as default  
[Full list of MIME types](https://cdn.rawgit.com/jshttp/mime-db/master/db.json)
Is that correct?

Set secure_upload on as default

---

library/authentication/login_operations.php

bing with empty user name and password returns authentication error.

Fixed error when connecting with LDAP using the new library

---

config/config.yaml
custom/assets/README
custom/assets/css/README
custom/assets/custom.yaml.example
custom/assets/js/README
library/core/src/Header.php

Hi.
Here I add option to inject custom js and css into any file in the system.
How to use - 
Add new file config/custom.yaml with same syntax as  config/config.yaml.
In that file you can add links to your custom assets.
I add new attribute called `loadInFile` for config file, This attribute enables to inject js and css only in specific file.
Example of custom.yaml
```
assets:
custom:
basePath: %webroot%/custom/public/
script: js/fix_messages.js
link: css/custom.css
loadInFile: interface/main/messages/messages.php
```
Files js/fix_messages.js and css/custom.css will inject into interface/main/messages/messages.php
Thanks
Amiel

new feature - custom assets

---

interface/billing/billing_report.php
library/billrep.inc

This is a small follow up to pull request #2154, to bind the IN clauses in `billing_report.php`.  
In order to implement this type of IN clause binding, `getBillsListBetween` first needs to return an `array`.
@bradymiller

[ISSUE-2053] Add variable binding to IN clauses to prevent SQL injection

---

interface/usergroup/ssl_certificates_admin.php
library/create_ssl_certificate.php

List of fixes:  
In `create_and_download_certificates`
- initialize the variables, just to avoid a few warnings
- `openssl_pkey_export_to_file`: if the path to the OpenSSL's config file isn't passed as an argument ($config), then it uses the value of the environment variable OPENSSL_CONF. With my Xampp install, that variable was set to the wrong location, and I ended up with the error message "Error, unable to create the admin.p12 certificate."
In `create_crt`  
- the parameter $privkey isn't used, just remove it
- was creating a CA certificate even when it was supposed to be a server certificate signed by a Certificate Authority we just created. If the user wants to trust the CA instead of adding an exception in his browser, Firefox refuses the server certificate …

Fix Creation of SSL Certificates

---

interface/themes/tabs_style_compact.css
interface/themes/tabs_style_full.css

Hi.
The bug - the style of disabled tab works only on hover.
I added !important to fix it.
Thanks
Amiel

Fix style of disabled tab

---

common/compatibility/Checker.php

Should not try to translate this message since that overcomplicates things and goal is to do the least amount of stuff (assuming that database connections to translate to work is not a good assumption).

fix low php version warning message

---

acl_upgrade.php
admin.php
composer.json
interface/globals.php
setup.php
sql_patch.php
sql_upgrade.php

This will now work for any version of PHP (prior mechanism was breaking in php 5.6 on the setup script)

make php version checker more robust

---

interface/super/manage_site_files.php

@sunsetsystems and @sjpadgett ,
Related to this issue: https://github.com/openemr/openemr/issues/2319
I removed ability to edit  files that could allow easy php script injection. Looks like only 2 files can be safely edited. Would it make sense to remove this generic edit file feature completely?
(would still keep the image uploaded and education upload features though)
-brady

secure the admin files edit feature

---

API_README.md
interface/globals.php

The Rest API was fatally failing if you sent an invalid site id.  The code was using the escape function of text() but that file is not loaded until later on in the codebase.  I could have moved the load order of the files so that composer (which in turn loads htmlspecialchars.inc.php) would load earlier, but this appeared to be the safer approach to minimize any system changes by just calling htmlspecialchars(..) directly.
Also documented what the scope parameter is supposed to be in the REST API as it was unclear with the example 'site id' for a newcomer to the system.

Fixes #2324 Rest API Fatal Error.

---

rest_controllers/AuthRestController.php

2 api items:
1. used a cryptographically secure method to randomly create tokens
2. Concatenated api and site_id before running bin2hex on them (to be consistent with the way it is unwrapped with hex2bin).

api token crypto secure and another minor change

---

interface/weno/jsonScript.php
library/weno/src/TransmitData.php

Weno requires more accurate information about the script. These fields were added and are the reason for the new table with the rxcui codes. 
@bradymiller

Adding more information to the prescription

---

composer.json
composer.lock

See the issue for more details but this goes through and specifies where the namespaces that don't match PSR-4 naming convention can be found to make it PSR-4 compliant.  This makes things backwards compatible and works with command line tools that rely on PSR-4 autoloading to work correctly.

Fixes #2352 PSR Class Load

---

interface/billing/sl_eob_search.php

by default, the due pt drop down grabbed anybody with pt due but no sense sending a statement if already in collection, it's testing fine, thank you.
also removed the label "select method" so could move the radio buttons over to the left for easier user selection

pt statements: do not select in collection by default

---

interface/patient_file/encounter/encounter_top.php
library/tabs/src/TabsWrapper.php
portal/patient/templates/OnsiteDocumentListView.tpl.php

umm, this was driving me nuts. Seems giving tab panels content iframe 100% height doesn't account for the tabs headers height so tabbed encounter UI always displays with an overflow.

Decrease encounter tab container height to prevent scroll bar.

---

interface/billing/billing_process.php

payers will reject a file if the icn is the same as a previous submission and since before was rounding to minutes some quickly regenerated files or files generated by another site were set to fail

refine bat icn for uniqueness

---

interface/patient_file/summary/demographics.php

quite often you have to grab the policy number to do a lookup on a billing site
this fixes the dbl click copy and paste so a tab and a new line character don't come along with the data

fix dbl click copy and paste extra character

---

library/billing/src/X12_5010_837P.php
library/htmlspecialchars.inc.php
portal/account/account.lib.php

From this issue:
https://github.com/openemr/openemr/issues/2356
Note this is now a wrapper for simply attr(), but we can change this in the future as needed (guessing some more escaping will be needed, but important to just have the wrappers in place).
I am going to dedicate this new escaping function to @sjpadgett 
:)

seed for the error log escape project

---

interface/eRxXMLBuilder.php

NewCrop is now requiring midlevel prescribers to provide NPI. This also needs to be ported to 501. 
Thanks, 
Ken
ken@mi-squared.com

Added NPI to NewCrop eRx for midlevel prescribers

---

interface/globals.php
interface/main/left_nav.php
interface/main/tabs/menu/menu_json.php
interface/modules/zend_modules/module/Application/Module.php
interface/modules/zend_modules/module/Application/config/module.config.php
interface/modules/zend_modules/module/Application/src/Application/Listener/ModuleMenuSubscriber.php
interface/modules/zend_modules/public/index.php
interface/usergroup/user_admin.php
interface/usergroup/usergroup_admin_add.php
src/Core/ModulesApplication.php
src/Menu/MainMenuRole.php
src/Menu/MenuEvent.php

Event Dispatcher integration with Tab Menu system.  Moved all of the module menu code into the same code area as the rest of the module code.
Made it so we integrate the event dispatcher code in the OpenEMR system with the ZF3 module code.
Moved the module menu code outside of the core OpenEMR codebase into the module system which is where the code should belong as it creates and defines the module database code.
Added the Update and Restrict menu events (defined in Menu/MenuEvent) and tied them into the tabs interface as an example of how to use the EventDispatcher to hook into the main codebase to extend it.
All of this moves the code to be more S.O.L.I.D (https://en.wikipedia.org/wiki/SOLID) by modifying the module menu system.  The menu files in Core are closed for modification but …

Zend Module Event Dispatcher w/ Consolidated Menu

---

interface/weno/jsonScript.php

@sjpadgett ,
This is a quick fix to the weno password. The weno password is odd since it is included on install/upgrade in a decrypted form. And it will then get encrypted when the user does a save in Administration->Globals. So, this bug only shows up prior to that first save in Administration->Globals. I posted the fix for this issue and will bring it in when it passes travis.

weno-pass-fix

---

build.xml
composer.json
composer.lock
interface/globals.php
src/Core/Header.php

This is throwing php deprecation errors in php 7.4(alpha), and realized we are not using twig anywhere in the current codebase. Seems easiest thing to do is to remove it (we can always add it back by reverting this commit in the future if anybody wishes to use twig).
@robertdown , making sure you are ok with this

remove twig

---

interface/modules/zend_modules/module/Application/src/Application/Controller/SendtoController.php
interface/modules/zend_modules/module/Carecoordination/config/module.config.php
interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml
interface/modules/zend_modules/module/Carecoordination/view/carecoordination/ccd/upload.phtml
interface/modules/zend_modules/module/Ccr/config/module.config.php
interface/modules/zend_modules/module/Ccr/view/ccr/ccr/index.phtml
interface/modules/zend_modules/module/Documents/src/Documents/Controller/DocumentsController.php
interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
interface/modules/zend_modules/module/Installer/src/Installer/Model/InstModuleTable.php
interface/modules/zend_modules/module/Syndromicsurveillance/view/syndromicsurveillance/syndromicsurveillance/index.phtml

Fixed a bunch of warnings in the CareCoordination module and broken code.  We broke the dependency resolution when we made modules load from the database so I fixed that.
It looks like the preview of data in the CCDA import process was broken and quite a few areas just didn't load any data.  Improved that significantly so both the review and approve as well as the import process do much more than basic demographics. Detailed breakdown is listed below.
- Fix deprecation, warnings,bugs, in CCDA module.
- Several bug fixes, deprecation, and warning fixes to make the ccda work in modern PHP version.
- Fix count php warning in installer. If you emptied the number of enabled hooks it threw a warning.
- Made it so the rev and approve errors thrown are now fixed in the care coordination and …

Fixes #1524 CCDA Warnings, Dependency resolution in modules

---

ccdaservice/ccda_gateway.php
interface/globals.php
interface/login/login.php
interface/modules/zend_modules/module/Installer/config/module.config.php
library/restoreSession.php

Updated OpenEMR session/cookie strategy
1. If a session does not yet exist, then will start the OpenEMR session, which
will create a cookie with OpenEMR name. If a session already exists, then
this means portal is being used and will bypass setting of the OpenEMR session/cookie.
2. If using php version 7.3.0 or above, then will set the cookie_samesite in order
to prevent csrf vulnerabilities. Setting it to Strict for now; if this is to
strict on testing, then will instead set it to Lax.
3. Need to set cookie_httponly to false, since javascript needs to be able to
access/modify the cookie to support separate logins into OpenEMR. This is important
to support in OpenEMR since the application needs to robustly support access of
separate patients via separate logins by same users. This is done …

Fixed session/cookie bug and other related work

---

interface/main/finder/dynamic_finder.php
interface/main/tabs/js/user_data_view_model.js
interface/main/tabs/main.php
interface/main/tabs/templates/patient_data_template.php
interface/themes/buttons/_manilla.scss
interface/themes/color_base.scss
interface/themes/oe-common/main-common.scss
interface/themes/rtl.scss
interface/themes/style_light.scss
interface/themes/style_manila.scss
interface/themes/tabs_style_compact.css
interface/themes/tabs_style_full.css
library/globals.inc.php
src/OeUI/OemrUI.php

After a lively discussion in the previous PR #2513 here is a solution to address the key issues raised
1 - Whether or not to have the Search Any button have dual behavior
- to open a filtered set of results in Patient Finder based on a non-empty search string in the search any text box
- to directly open Patient Finder and display the entire patient list 
2 - Whether or not to hide the entire input box behind the search button and to only allow filtered results if the 
search any text box contained a non-empty string
There is a case to be made for and against both these arguments and the current solution is to have both these options available
and let the administrator or individual user choose what they want.
The two options are called 'Dual' and 'Comprehensive'.
Dual - lets the user …

UX - Expandable Search Patient By Any Demographics - Take 3

---

interface/reports/receipts_by_method_report.php

The payment method report was showing the payment method as `payment_method` instead of `title` (e.g. "cash" instead of "Cash" or "credit_card" instead of "Credit Card".

Payment method report fix

---

interface/reports/ippf_cyp_report.php

Quick fix for no translation of 'Το:' and use of "xlt" instead of "xl"

Fixes #2562

---

src/Billing/Claim.php

Changed the default qualifier to '' from 'DK'.
The problem with 'DK' is that the 837P generator sees a non-empty value and assumes some sort of reference provider is being supplied (Referring, Ordering, Supervising).
With this as empty, if there is no auxillary provider then the NM1, N3 and N4 fields are not added to the EDI file.
P.S. sorry about the typo in the commit comment. I didn't see it until after the push.

Fix to Billing Options

---

src/Billing/X12_5010_837P.php

This is a follow on to the Claim fix that changed the default type from DK to ''.
The 837 generator is currently only adding a referring/ordering/supervising physician if the qualifier value is DK. The logic should be to check that the qualifier is not empty first and if not then add the user selected qualifier and physician information.

Fix box 17 qualifier check

---

src/Billing/X12_5010_837P.php

Someone had a semi-colon in the 2330B loop that was breaking systems. This restores it to the string concatenation.

Restore X12_5010_837P.php

---

interface/main/tabs/templates/menu_template.php
interface/main/tabs/templates/user_data_template.php
interface/themes/oe-common/help-files-common.scss
interface/themes/rtl_style_pdf.css
interface/themes/tabs_style_compact.css
interface/themes/tabs_style_full.css

To whom it may concern,
The menu buttons in the header now have a transition time of **0.5** seconds for a better user experience. However, I noticed that the transition would not appear if you immediately go onto a button that has a dropdown. 
Note that this is my first PR, so do correct me if I made any mistakes. Thank you.
Up For Grabs demo to demo this PR is here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Mu_-_Up_For_Grabs_Demo

Add hover over background colour transition in .menuLabel

---

interface/modules/zend_modules/config/application.config.php
interface/modules/zend_modules/module/Installer/view/installer/installer/index.phtml
interface/patient_file/report/patient_report.php
src/Core/ModulesApplication.php
src/Events/PatientReport/PatientReportEvent.php

This pull request contains the work for both zend and custom modules to be used and installed via composer.  Its intent is to continue to allow customization and vendor support of the OpenEMR codebase without requiring all the changes to be done directly in the core system files.
Before this code, the only workable modules were zend modules and developers were finding it cumbersome to implement.  This work makes it possible to have a custom module that connects to OpenEMR via a single file the openemr.bootstrap.php file.  Module developers can now use either whatever programming style they want (procedural, oop, functional, etc) as well as whatever framework they want without impacting the core OpenEMR code.
I changed the ModuleApplications class to load the openemr.bootstrap.php file for …

Initial Custom Module support and installer.

---

interface/weno/validate.php

Weno Validate was not pulling the default facility.  It was using the first facility which may not be correct…  Switch to use PrimaryBillingLocation.  If you need/want Rx’s to contain a specific facility, or always from the facility where encounter occurred, then more adjustments needed…

Weno Validate Fix

---

interface/billing/billing_report.php
interface/billing/edit_payment.php
interface/billing/new_payment.php
interface/billing/payment_master.inc.php
interface/billing/payment_pat_sel.inc.php
interface/billing/search_payments.php
library/billrep.inc

Some code changes in the modernization of the UI rendered parts of
the Batch payemnts pages unusable/difficult to use
Changes are made to the following files:
interface/billing/edit_payment.php
interface/billing/new_payment.php
interface/billing/payment_master.inc.php
interface/billing/payment_pat_sel.inc.php
interface/billing/search_payments.php
with these changes the Batch payments section is once again functional
The issues fixed are:
1. html code populating Payment Method, Paying Entity and Payment Category select boxes when Fees > Batch Payments > New Payment 'Save Changes' button is clicked after filling in valid data
**Cause:** In interface/billing/payment_master.inc.php which is a part of interface/billing/new_patient.php i.e. Fees > Batch Payments > New Payment form - `function …

Fixing critical issues with Fees > Batch Payments

---

src/Billing/X12_5010_837P.php

thanks to @ophthal, https://github.com/openemr/openemr/pull/2664, here's something for the next patch

fix typo in an 837 claim function call

---

interface/patient_file/history/history_save.php

reported on forum, https://community.open-emr.org/t/empty-checkboxes-cant-be-stored/12833, by CodderEMR
wondering if this should be fixed instead by https://github.com/openemr/openemr/blob/master/library/options.js.php
also saw this error in the console when loading the history
```
TypeError: skipArray[i] is null
```

save all unchecked cbs in patient history

---

interface/forms/eye_mag/a_issue.php
interface/forms/eye_mag/php/eye_mag_functions.php
interface/forms/eye_mag/view.php

Encode pid values correctly in output

---

ci/ci.sh

This is only for rel502 in order to not require psr2 specific code changes in new PHP_CodeSniffer 3.5 version.

PHP_CodeSniffer fix for rel502

---

library/clinical_rules.php
library/patient.inc

Improved bug fix from https://github.com/openemr/openemr/pull/2692/files

better bug fix

---

interface/forms/eye_mag/SpectacleRx.php

Potentially non-exploitable due to error earlier in the page, but just in-case.

Properly escape encounter.

---

interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html

If you have many providers, the calendar day view only shows the
first however many fit in the bigCal div (depending on your screen
size). If you have a large number of providers, the only way
to see their schedules is to select individuals in the
"pc_username" box.
When blocking out time for vacations, it is useful for us to
be able to get a quick overview of what is going on with all
the providers.
This just adds "overflow-x: auto;" to the "bigCal" div style
on the Day template, allowing us to view the provider schedules
that render past the right-hand limit of the div.

Add horizontal scroll to PostCalendar Day template

---

interface/forms/eye_mag/php/eye_mag_functions.php
interface/forms/eye_mag/view.php

Escape the form_id

---

interface/patient_file/merge_patients.php

fix for this issue:
https://github.com/openemr/openemr/issues/2720
(explanation: keys is a reserved mysql/mariadb word, so needs that backquote thing)

merge patient bug fix

---

interface/usergroup/adminacl.php

Noted that interface/usergroup/adminacl.php does not do well with usernames containing an underscore. Here's a fix.

ACL User Memberships fix for usernames with underscore.

---

interface/themes/login.css

Just an minor enhancement to where when the invalid message in the "Product Registration" modal appears, it should be display more clearly, in this case, I set it to red and bold. 
After:  
Let me know if this works. 
Cheers!

Set Valid Message On Product Registration Modal To Red

---

interface/forms/LBF/report.php

- specifically the checkbox with text where config'ed list items were considered text string and word wrapped.

LBF form report data type 25 fix

---

interface/main/calendar/modules/PostCalendar/pnuserapi.php

fix for the calendar on the flex docker
testing well

flex docker does not like parens in sql query

---

src/RestControllers/AuthRestController.php

Hi
We started to develop with REST API and we have missing important information about the ID of the logged-in user. 
Every application needs to know who is the connected user for fetching only the relevant information.
I added it to the response of the authentication route, the client-side will store this data and can use it in every request it needed.
Thanks
Amiel

Add userId to authentication response

---

interface/forms/newpatient/common.php

Hi,
We wanted for the encounter type and facility in a follow-up encounter to be readonly (because if it's a follow up then it's naturally of the same type and in the same facility as "parent" encounter).
Thanks

readonly fix for follow-up encounter

---

src/Entities/ChartTracker.php
tests/Tests/Unit/Entity/ChartTrackerTest.php

I have changed the __toString() method, the undefined call "$this->getDate()" is moved to "$this->getWhen()".
I'm not sure about the string format of the date object.
Should be fine I guess.

Fix #2904 undefined method in chart traker entity

---

interface/modules/zend_modules/module/PrescriptionTemplates/src/PrescriptionTemplates/Controller/HtmlTemplatesController.php
interface/modules/zend_modules/module/PrescriptionTemplates/src/PrescriptionTemplates/Controller/PdfTemplatesController.php

for #2915 seems like the zend PrescriptionTemplates module is a little different from the others...
in the config there is no service manager so maybe that's why there's no need to call the parent constructor
only @matrix-amiel and @adunsulag can make sense of this really :) please no more links to martin fowler articles :smile: 
it's testing well and the html print is pretty cool

remove constructors in prescriptions template controller

---

interface/main/tabs/js/tabs_view_model.js

Related to #1804 
**Previous behavior**: If the encounter frameset already exists, just tell it to add a tab for this form. 
**Expected behavior**: Add a tab and activate it so the client won't get confused about the action result.
**Result Video**
https://www.loom.com/share/dec847fe2ae54db984049ae6b177cdf7

Activate a tab when it's created

---

src/Common/Http/HttpRestRouteHandler.php

Hi, we are implementing the FHIR standard in our api, and the "operations" parameters in FHIR start with a "$" (e.g. $expand).
This is why we need to enable a "$" in the route parameters.

added $ to regex

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/security_report.md
interface/patient_file/problem_encounter.php

**Screenshot:**
Note:
I have also added some minor changes in issue template: ' - ' is used to add a bullet and it doesn't make sense keeping it by default, I have also added missing footer comment to the security report template.

Added styles to buttons in issue popup and minor issue template fixes

---

interface/patient_file/encounter/forms.php

Fixes #3002
Change encounter tabs to bootstrap style

Fix #3002 change encounter tabs to bootstrap style

---

interface/themes/oe-common/main-common.scss

Fixes #3091 
This resolves the dislocation of the search icon on the search bar. Minor UI issue present in chrome browser.
- The issue is simply solved by changing some values in the stylesheet.

Search icon position issue fixed

---

interface/patient_file/encounter/forms.php

Fixes #3109 
In encounter tab current `collpase/expand button` toggle(if a tab is collapsed then it will it to show and vice versa) tabs instead of what is expected of him.
https://www.loom.com/share/051965df4c064af98e3f0c0868e14a80
Introducing two button inplace of `Expand/Collapse` which can perform Expand all and Collpase all.
https://www.loom.com/share/f386c90fd6c74c87b110ee750e981fea

Quick fix for encounter expand/collpase all

---

interface/drugs/add_edit_drug.php

It's just a suggestion from my side
If we won't check for drugname then a person can create drugname using `blank` `space` `double space`
Person should always enter drug name

Drug name should be required

---

interface/main/tabs/main.php

Fixes #3110 
Note: Now dropdown menu is also spread to width-100 and i think it's better because spreading it to  width-100/6 when mobile screen are already small in size is not efficent IMHO.

Fixed uneven body top

---

interface/main/finder/dynamic_finder.php
interface/main/main_screen.php
interface/main/tabs/js/tabs_view_model.js
interface/main/tabs/main.php
interface/super/edit_list.php
library/globals.inc.php
library/options.inc.php
sql/5_0_2-to-5_0_3_upgrade.sql
sql/database.sql

Fixes #
This pull request addresses 3 issues:
1- When creating a "Facility" field in the patient demographics layout, and adding it to the patient finder columns, the facility name would not be displayed. This was because there was not a facility type implemented in the options function that generated a plain text field. This was added by using the facility service to map the facility ID to the facility name so it can be displayed.
2- There is currently no way to specify default column ordering (sort direction) on patient list columns. This pull request addresses this issue by adding a list option for Sort_Direction, as well as adding a sort direction column to the Patient List Columns list, so the user can specify the default sort direction (for a date-created for example.) This does not …

Ken patient finder and tab settings

---

CONTRIBUTING.md

docs: add command to view php logs within openemr docker
fixes issue  #3144

docs: add command to view php logs within openemr docker

---

interface/drugs/drug_inventory.php

Fixes #
Ignore mapping if received `$row` is `null` or `undefined`

Quick Fix - Drug inventory Table

---

interface/code_systems/dataloads_ajax.php
interface/forms/fee_sheet/review/initialize_review.js
interface/modules/zend_modules/public/js/installer/action.js
tests/api/InternalApiTest.php

This PR Fixes #2314
This PR remove `$( document ).ready(function() {
});` to `$(function () { }); ` as it is no longer recommended in jquery 3+.
@bradymiller Please review this PR

removed deprecated jquery's ready function

---

interface/main/finder/dynamic_finder.php

Fixes #3147 
Remove pt_table_next style.
Upgrade datatables to Bootstrap theme.

fix: upgrade datatables to bootstrap 4 theme

---

interface/main/tabs/js/custom_bindings.js
interface/reports/daily_summary_report.php
interface/super/rules/www/js/bucket.js
interface/super/rules/www/js/custom.js
interface/super/rules/www/js/detail.js
interface/super/rules/www/js/edit.js
interface/super/rules/www/js/list.js
interface/super/rules/www/js/typeahead.js
library/options_listadd.inc
portal/sign/assets/signer_api.js

This PR Fixes #2314
This PR remove remaining $( document ).ready(function() { }); to $(function () { }); as it is no longer recommended in jquery 3+.
@bradymiller As commented in PR https://github.com/openemr/openemr/pull/3158 I have created a new branch removed deprecated method. Please review this one.

removed jquery's deprecated  ready method

---

interface/main/tabs/menu/menus/standard.json

Fixes #2949 
Add diagnostics in navbar Administration->System

Fix #2949: add diagnostics to navbar

---

interface/main/messages/save.php

found in error_log in production, think it's triggered from changing medex preferences after it's enabled

add leading slash to medex require

---

interface/modules/zend_modules/module/Installer/view/installer/installer/configure.phtml

- depends on module having a moduleConfig.php in module root.
This is a baby step. Still much to do with custom modules validation/error checking in zend Module Manager. ie modules states in code can get away from us quick. Thanks @mdsupport for the code snippet.
See oe-module-faxsms https://github.com/openemr/oe-module-faxsms/tree/rel-2.0.0_oe5.0.3
for example

Add custom module config support to Zend Module Manager

---

interface/themes/core/closeDlgIframe.scss

Fix modal dialog close icon broken.

fix: modal dialog close icon broken.

---

interface/themes/core/FontAwesome.scss

Fix search-plus and search-minus icons broken
Before:
After:

fix: search-plus and search-minus icons broken

---

API_README.md
_rest_routes.inc.php
src/RestControllers/EncounterRestController.php
src/Services/EncounterService.php

fixes #3194
Add Update patient encounter AP
Test Endpoint http://localhost:8300/apis/api/patient/1/encounter/1
Test Payload
```
{
"date":"2019-09-14",
"onset_date": "0000-00-00 00:00:00",
"reason": "Pregnancy Test",
"pc_catid": "5",
"facility_id": "3",
"billing_facility": "3",
"sensitivity": "normal",
"referral_source": "",
"pos_code": "0"
}
```
Returns Object on update instead of updated data eg 
```
{
"dataProvider": "empty",
"databaseType": false,
"EOF": true,
"_numOfRows": 0,
"fields": false,
"connection": false
}
```
In case where Encounter  sensitive field is normal, it returns string e.g
`"You are not authorized to see this encounter."`
Code replicated from https://github.com/openemr/openemr/blob/master/interface/forms/newpatient/save.php

Add patient encounter PUT API

---

interface/super/edit_list.php

Fixes #2914
Increased the max length to 127 for the storage of mime types in the file types list
- Just increase the max length to 127(btw 127 is not chosen out of random, reason for increasing to 127 -> https://stackoverflow.com/questions/643690/maximum-mimetype-length-when-storing-type-in-db
-
-

Fix #2914 Increased Maxlength for mime types

---

interface/main/calendar/add_edit_event.php

Fixes #3262 
According to #3160 , buttons should be styled using BS4 Classes. This commit does exactly that for the Calendar modal 
-Keeping the "Save" button as btn-primary
-Changing the "Delete" button to btn-danger
-Changing all other buttons of the modal to btn-secondary

Syling Calendar modal buttons

---

apis/dispatch.php
src/Common/Http/HttpRestRouteHandler.php

- add logic to return a 404 if route doesn't exist
Fixes #
some reason we'd return a 200 http status if route did not exists.
I stopped that nonsense forthwith. :)

fix apis route dispatcher

---

library/dialog.js

Fixes #
As you can see in the following image, a double vertical scrollbar appears in iFrame modals. 
The issue seems to appear in Google Chrome and not in Firefox.
This commit resolves this issue as seen below
- Removing double scrollbar from modals containing iFrames

Fixed "double scroll-bar" bug on modals

---

src/Services/PatientService.php

Missing comma causing the email to behave as dob(alias) and thus missing dob when `get all patient data` API is called.
P.S.: First API fix PR :wink:

Quick-Fix: Get all patient API correction

---

interface/clickmap/template/css/clickmap.css
interface/clickmap/template/general_new.html

Fixes #3309 
Fixed duplicate summary tabs.
Removed `clickmap.css` body background color.

fix #3309: duplicate summary tabs and background color

---

interface/new/new_comprehensive.php
interface/new/new_comprehensive_save.php
interface/patient_file/summary/demographics.php
interface/patient_file/summary/demographics_full.php
interface/patient_file/summary/demographics_save.php
library/globals.inc.php

Not able to hide unused insurances for countries that only use one.
Added the ability to only show one insurance in demographics along with new/search patient. Also moved some of the globals for insurance settings to a new insurance tap since they were scattered around.

Option - show only one insurance 

---

interface/forms/eye_mag/css/report.css

When we have the Eye Exam, The report.css a style will affect the button font colors are incorrect.
https://github.com/openemr/openemr/pull/3323#issuecomment-609164229

Fix: remove report.css a tag style.

---

sql/4_2_2-to-5_0_0_upgrade.sql
sql/5_0_2-to-5_0_3_upgrade.sql
sql/database.sql
version.php

Github Issue:
https://github.com/openemr/openemr/issues/3239
In the table `form_eye_mag_prefs1` the type of `ordering` column is changed from `tinyint` to smallint to store larger values as one of the insert statement is having the value `2048`
Initially without `SQL_MODE` it's stores the max value in the tinyint ie. 127 but with `SQL_MODE` it throws error
- Changed the type of ordering column from `tinyint` to `smallint`
-
-
Note:
- Thinking of using [SQL] in the SQL_MODE related PRs, what are your thoughts on the same?

[SQL]: Converting tinyint to smallint to store large values

---

interface/forms/soap/templates/general_new.html
src/Tabs/TabsWrapper.php

Fixes #3279
Added warning dialog to show when the user closes the tabs.

Fix #3279 warning closing form

---

docker-compose.yml

Fixes #3320
Add Turn_API_ON environment variable to docker
this environment variable will be used to turn the OpenEMR API on from
within a docker install

Add turn API on variable to docker environment

---

interface/themes/ajax_calendar_sass.scss

Fixes #2888 
Added float calendar widget on page scroll 
Testing on Edge, Chrome, and Firefox.
Edge - Default
Edge - Page Scroll Down
Chrome - Default
Chrome - Page Scroll Down
Firefox - Default
Firefox - Page Scroll Down

feat #2888: add float calendar widget

---

sql/database.sql

Fixes #3332
We are using blank for null values while inserting into database(for the table `form_eye_mag_prefs `), but after applying sql modes this appears to show a show error
- Changed blank(`''`) to `NULL`
-
-

[SQL]: Fix #3332 using null instead of blank

---

CONTRIBUTING.md

Add PHP log docker Alias to contibuting guide
Fixes #3358

Add PHP error log Alias  command for docker

---

API_README.md
FHIR_README.md

Remove Licence from API and FHIR docs
Fix broken services and controller links for both docs
Add sections to API docs for easy navigation
Remove FHIR docs from API docs
Add single refrence for FHIR docs in API docs
Fixes issues #3361 #3366

Improve API and FHIR docs

---

sql/patch.sql

@stephenwaite , just some minor stuff. This should avoid issues if the icd10 stuff is empty. Then will use the revision of 1 that is set when adding the covid codes (otherwise not sure what will happen if collect revision from a code that doesn't exist).

some minor cleanup in covid patch stuff

---

src/Validators/BaseValidator.php
src/Validators/PatientValidator.php
src/Validators/ProcessingResult.php
tests/Tests/Fixtures/FixtureManager.php
tests/Tests/Fixtures/FixtureManagerTest.php
tests/Tests/Services/PatientServiceTest.php
tests/Tests/Validators/ProcessingResultTest.php

Fixes #3353 (sort of :) 
This PR simply updates the email address I'm listing in OpenEMR's copyright notices.
Hi @bradymiller - I'm still on-board to enhance/update OpenEMR's API and FHIR publishing features. I just need to update the email address I'm using. Thanks!

Updating Email Address Listed In Copyright Notice

---

sql/5_0_2-to-5_0_3_upgrade.sql
sql/database.sql
version.php

Fixes #3378
We removed the wrong default timestamp and instead of that made the `created_time` column of the table `amendments_history ` nullable.
-

[SQL]: Fix #3378 fix default timestamp issue `amendments_history`

---

interface/billing/edih_view.php
library/css/edi_history_v2.css

Fixes #3005
Remove EDI History jquery ui

Fix#3005 : Remove EDI History jquery ui

---

sql/5_0_2-to-5_0_3_upgrade.sql
sql/database.sql
version.php

Fixes #3378
We removed the wrong default timestamp and instead of that made the `msg_date_sent` column of the table `batchcom ` nullable.
-

[SQL]: Fix #3378 fix default datetime issue `batchcom`

---

interface/modules/zend_modules/module/Installer/Module.php
interface/modules/zend_modules/module/Installer/config/module.config.php
interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php

Add functionality  (register,unregister,disable,enable,install) to cli 
in order to enable the following commands : 
php openemr/interface/modules/zend_modules/public/index.php 
and 
1. register --mtype=zend --modname=Imaging
2. zfc-module --site=default --modaction=disable --modname=Documents
3. zfc-module --site=default --modaction=enable --modname=Documents
4. zfc-module --site=default --modaction=install --modname=Documents
5. zfc-module --site=default --modaction=unregister --modname=Documents
The commands, along with the existing commands, allows to write script to manually install 
zend (Laminas) modules from bash script
related pull request 
https://github.com/openemr/openemr/pull/2922

Add cli commands for installing Laminas modules

---

package-lock.json
package.json

Fixes #3425
Updates jQuery to 3.5.1

Update jQuery to 3.5.1 (#3425)

---

sql/5_0_2-to-5_0_3_upgrade.sql
sql/database.sql
version.php

Fixes #3378
We removed the wrong default date and instead of that made the `last_notify` column of the table `drug_inventory ` nullable.
- Added the Update SQL command to update past records (for previous ones also)

[SQL]: Fix #3378 fix default date issue `drug_inventory`

---

package-lock.json
package.json

Fixes #3508 
This updates Bootstrap to 4.5.0.
Note that this does not update RTL to 4.5.0 as they haven't updated that part yet. There should be no real difference between the two as this is a very minor update.

Update Bootstrap to 4.5.0

---

sql/5_0_2-to-5_0_3_upgrade.sql
sql/database.sql
version.php

Fixes #3378
We removed the wrong default date and instead of that made the `last_notify` column of the table `drug` nullable.

[SQL]: Fix #3378 fix default date issue `drug`

---

sql/5_0_2-to-5_0_3_upgrade.sql
sql/database.sql
version.php

Fixes #3378
We removed the wrong default date and instead of that made the `date` column of the table `insurance_data ` nullable.

[SQL]: Fix #3378 fix default date issue `insurance_data`

---

library/js/ajax_functions_writer.js

@bradymiller I just noticed that in my previous PR about `removal of jquery in nation notes`. I forgot to take the case when elements get updated or added.
This PR is a fix to this

quick fix nation notes

---

.github/stale.yml

Fixes #3544
This adds the GitHub Stale Add-on config file to allow the add-on to work.
**Note: In order for this add-on to work after this PR is merged, please go to [this link](https://github.com/apps/stale) and configure the stale add-on to point to the OpenEMR repository.**

Add GitHub Stale Add-on (#3544)

---

API_README.md
FHIR_README.md
_rest_routes.inc.php
src/RestControllers/PatientRestController.php
src/Services/BaseService.php
src/Services/FHIR/FhirPatientService.php
src/Services/PatientService.php
src/Validators/PatientValidator.php
tests/Tests/Api/PatientApiTest.php
tests/Tests/RestControllers/PatientRestControllerTest.php
tests/Tests/Services/PatientServiceTest.php
tests/Tests/Validators/PatientValidatorTest.php

@dixonwhitmire , @yashrajbothra , @sjpadgett ,
Just toying around with what we should be using for the patient ids for the api endpoints. At this point, we will be using uuid in fhir and pid on the api. Per this PR (overall strategy), it wouldn't be too tough to support both, although doing this really seems murky to me. Am thinking may make sense to use uuid (and not pid) on the api also to keep things consistent.
thoughts?

using uuid in patient api endpoints

---

portal/index.php

Fixes #3613
Make UI clearer concerning username on reset password. Will now show current username in dialog and still allow patient to change.

Portal reset password changes

---

interface/login/login.php
src/Common/Session/SessionUtil.php

Dealing with following warning that is showing up in browsers:
Cookie “OpenEMR” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
Note really need php 7.3 to be able to set this setting. And the issue in 7.3 is that is wasn't being set when removing cookies (ie. expiring cookies). This fix addresses that.

fixes to remove warnings as browsers start to crack down on missing SameSite attributes

---

interface/main/tabs/js/tabs_view_model.js

- dup function clickEncounterList
- add iframe load
Fixes #3659 
Existing tabs were not loading iframe but switching back and forth if an exiting iframe already exist.
-

issue #3659 fix

---

interface/main/tabs/js/user_data_view_model.js

@tywrenn , the parenthesis at end of this were breaking the search icon at top right. So, I added them back. Let me know if better way.
(these parenthesis were add in this PR: https://github.com/openemr/openemr/pull/3636)

fix broken search icon; TypeError: event.stopImmediatePropagation is not a function

---

interface/patient_file/encounter/superbill_custom_full.php
sql/5_0_2-to-6_0_0_upgrade.sql

Fixes #
update in upgrade would set `code_text` on non-cvx entries
back pagination was not working in admin->codes
fixins :)
-
-
-

set codetype on update, fix pagination in admin->codes

---

tests/Tests/Fixtures/FHIR/facility.json
tests/Tests/Fixtures/FHIR/practitioners.json
tests/Tests/Fixtures/PractitionerFixtureManager.php
tests/Tests/Fixtures/practitioners.json
tests/Tests/RestControllers/FHIR/FhirOrganizationRestControllerTest.php
tests/Tests/RestControllers/FacilityRestControllerTest.php
tests/Tests/RestControllers/PractitionerRestControllerTest.php
tests/Tests/Services/FHIR/FhirOrganizationServiceCrudTest.php
tests/Tests/Services/FHIR/FhirPatientServiceQueryTest.php

@yashrajbothra , Noted lots of lingering users/facilities in database after running automated testing. These changes wipe them out. Note can't used negative id's for fhir fixtures, so just used the first name :)
The negative id's are good, though, for the main fixtures, since it avoids clashing with any current users.

fixtures cleanup

---

interface/themes/login_page.scss

Fixes #
In the Firefox browser, The login form didn't vertical-align center.
Before:
After:

fix: firefox vertical align center

---

CONTRIBUTING.md

Fixes #  The git and compose installation link in Easy Development Docker Environment.
Before:  It didn't mention the git and compose link in the doc
After: added the git and compose link in the doc
```
If you haven't already, [install git](https://git-scm.com/downloads) for your system
If you haven't already, install [Docker](https://docs.docker.com/install/) and compose(https://docs.docker.com/compose/install/) for your system
```
-  Especially compose, you can not run step 3 `docker-compose up`, there is no `docker-compose` command

miss the git and compose installation link in md

---

controllers/C_Document.class.php

- viewer requires a LC extension
- image must have a DICM signature in header.

Fixup folder management

---

interface/usergroup/user_admin.php

Fixes #1541 
* Lists a collection of facilities in the user "default facility" field as long as it is flagged as a "service location"
- uses `getAllServiceLocations` instead of `getPrimaryBillingLocation` to load available facilities

using getAllServiceLocations in user_admin.php to retrieve facility list

---

interface/code_systems/standard_tables_manage.php
library/standard_tables_capture.inc

no issue, see https://community.open-emr.org/t/does-rxnorm-work/14854/2
revert unarchive to restore `RxNorm` load and add kludge for `icd10`, maybe this needs more work to determine the nested folder like when it switches to 2021 in a few months :)

external dataload fix for RxNorm and necessary change for ICD10

---

src/Services/FacilityService.php

Fixes #
Corrected issue where insert function in facility service was using sqlStatement not sqlInsert and resulted in insert ID not being returned. The previous behavior was that the id of the inserted record was returned.
insert method in FacilityService returns ID of inserted record.
-
-
-

Bug/typo in FacilityService class

---

interface/super/rules/www/css/rules.css

Fixes #3728 
Fixes the rule config row so it won't break the line width.
- removes negative margin of `.rule_detail p` in `rules.css`
- sets the `width` of `.intervals span select` to `inherit`
**Google Chrome:**
**Mozilla Firefox:**

fixed .interval span select width

---

interface/billing/edit_payment.php
interface/billing/payment_master.inc.php
interface/billing/search_payments.php
interface/billing/sl_eob_invoice.php
interface/billing/sl_eob_search.php
library/dialog.js
library/invoice_summary.inc.php
library/payment.inc.php

- honor follow up flag for denied claims
- add a link in EOB Invoice to only change/save selected Done with(last level closed)
- some styling
Please read this forum thread:
https://community.open-emr.org/t/major-billing-issues-with-5-0-2-please-help/14641/35

Final 502 batch payments. Yeah right!

---

package-lock.json
package.json

Fixes #3818
Updates Bootstrap to 4.5.2 as well as RTL and also regenerates the package lockfile

Update BS4 to 4.5.2 and Regen Package Lock

---

templates/documents/general_list.html
templates/documents/general_upload.html

Add the bootstrap input style in dashboard documents.
- Remove outdated code and inline-style.
- Add the bootstrap input style.

Feat: add the bootstrap input style in dashboard documents.

---

sql/5_0_2-to-6_0_0_upgrade.sql
sql/database.sql
src/Common/Uuid/UuidMapping.php
src/Common/Uuid/UuidRegistry.php
version.php

@yashrajbothra  , here's the uuid mapping mechanism. Can ensure all needed stuff is populated with:
```
use OpenEMR\Common\Uuid\UuidMapping;
UuidMapping::createMissingResourceUuids('Location', 'patient_data');
UuidMapping::createMissingResourceUuids('Location', 'users');
UuidMapping::createMissingResourceUuids('Location', 'facility');
```
The uuid in the mapping table is the resource uuid. the target_uuid is for mapping to the item in the table. Note still need to populate the anchor tables with the `->createMissingUuids` which need to be done prior to the above calls.
This is working well for me, so plan to bring in soon; which you can then integrate into your Location resource PR

added uuid mapping mechanism

---

library/MedEx/API.php

Fix the recall board disappears when clicking the arrow button.
Fixes #3842
- Adjust the PHP curly braces to fix the recall board disappears.
- Adjust the table thead style.

Fix #3842: fix the recall board disappear when click the arrow button.

---

interface/billing/billing_report.php
interface/easipro/pro.php
interface/login/login.php
interface/patient_file/report/custom_report.js
interface/patient_file/report/custom_report.php
interface/super/edit_layout.php
library/js/utility.js
portal/home.php
portal/report/portal_custom_report.php

This is an issue that does not come up very often in the codebase, but we don't really have a tool to deal with the situation (now, we simply just overescape stuff in in the javascript context to deal with this). This kind of function would allow use to correctly escape in the javascript context (and then also do html escaping in the not very frequent cases where are injecting html from javascript).

js html escaping

---

interface/main/left_nav.php

- fix for frames left nav messages reminder showing object instead of text
Fixes #
Forum issue https://community.open-emr.org/t/new-artifact-shows-after-upgrade-5-0-0-patch-7-to-5-0-2-patch-4/15004

frames left nav messages

---

.gitignore
interface/patient_file/encounter/select_codes.php
interface/patient_file/summary/add_edit_issue.php

Fixes #3619
Fixes some usability issues inn the **Add/Edit Issue** dialog wrt code selection and display.
- Created a new **Select Codes** dialog that works like a standard selection dialog with **OK** and **Cancel** buttons. It's patterned after _find_code_dynamic.php_ but simplified to only provide functionality for the `what == codes` case (I'm unclear as to the other cases and only saw them referenced from one other php). Other minor changes were made including toggling row selection.
- The **Add/Edit Issue** dialog was changed to utilize the new **Select Codes** dialog. The prior **Coding** text field that launched the old dialog is now a hidden field. The visible field is now a selection list with **Add** and **Remove** buttons. The **Add** button launches the new **Select Codes** …

Improve code selection usability in Add/Edit Issue dialog

---

interface/patient_file/summary/stats_full.php

In the issues (ie Medical Problem, Allergies etc) tables, clicking the **Title** column launches the edit dialog. However this is not intuitive - it took a bit of time for me to realize it.
The text in the **Title** column now displays as a hyperlink (ie underlined) to make it clear it is clickable.

Make Title column a hyperlink

---

library/globals.inc.php
src/Common/Auth/AuthHash.php
src/Common/Auth/AuthUtils.php
version.php

Added support for ONC 2015 item d12:
Encrypt authentication credentials certification criterion
The gist of this is that the hashing needs to be listed by NIST document ("Yes – the Health IT Module encrypts stored authentication credentials in accordance with standards adopted in § 170.210(a)(2)", which is the document linked below):
http://csrc.nist.gov/publications/fips/fips140-2/fips1402annexa.pdf
The current hash schemes (blowfish and argon2/blake2b) are not listed.
So added support for hashing by SHA-512.
(as an aside, blowfish is better and argon2/blake2b is way better than SHA-512 for hashing passwords, but that is the US government for you :) )

support item d12 for onc 2015

---

interface/patient_file/deleter.php
interface/patient_file/summary/add_edit_issue.php
interface/patient_file/summary/stats_full.php

Previously, to delete an issue from the table, one opened the Add/Edit Issue dialog which contained a Delete button at the bottom. This workflow is non-standard and a bit non-intuitive.
Now the issues table contains a Delete button with a checkbox column to select the issue row(s) to delete. The column header's checkbox toggles selection/de-selection of all the rows. The Delete button in the Add/Edit Issue dialog has been removed.

Move deletion of issues to the table

---

src/Services/FHIR/FhirObservationService.php

strtoupper is not required as 'final' is the valid observation Code whereas 'FINAL' is not a valid Code in FHIR
Fixes #
For FHIR Observation resource 'status' has the following valid codes :
registered | preliminary | final | amended
Currently the FHIR Observation resource is sending status with capitalised codes  due to strtoupper usage
-Removed the conversion of status from smallcase to capitalcase
-
-

removed strtoupper conversion for result status

---

src/Services/FHIR/FhirProcedureService.php

Fixes #
For Procedure FHIR Resource, the performedDateTime is not being populated with valid FHIRDatetime format
Example : The current value being populated is 2020-09-10 12:03:00 
It should be in the format  as given here (https://www.hl7.org/fhir/datatypes.html#dateTime)
-  converted the datetime to a valid FHIR DateTime format using gmdate
-
-

converted to FHIR Datetime format

---

_rest_routes.inc.php
src/RestControllers/InsuranceCompanyRestController.php
src/Services/FHIR/FhirProcedureService.php

Fixes #
The functionality for getting the insurance company details by id has been written but the API end point was not created.
function getOne($id) in the InsuranceCompanyService.php
Created a new GET api endpoint for the same by
adding the endpoint in the route map (_rest_routes.inc.php)
adding the function for this in the appropriate restcontroller (InsuranceCompanyRestController.php)
-
-
-

Adding new get api endpoint for Insurance Company by Id

---

src/Services/FHIR/FhirObservationService.php
src/Services/ObservationLabService.php

Fixes #
- Fields _code , effectiveDateTime_ and _valueQuantity_ will now be available in Observation FHIR resource.
- And fixed single Observation Retrieval by id.
- Added '_code_' field into Observation FHIR Resource which was showing up as empty before and is a mandatory field as per FHIR standards.
- Added '_effectiveDate_' field in Observation FHIR Resource by considering Procedure order reporting date.
- Added '_valueQuantity_' field in Observation FHIR Resource by taking result and units values from Procedure Result . 
- The Observation FHIR resource's _id_ should be compared with _uuid_ in  Procedure Result table in _getOne_ function but its being compared with the _uuid_ in Procedure Report table. Fixed this .

Adding code , effectiveDate and valueQuantity in Observation FHIR Resource

---

interface/code_systems/dataloads_ajax.php

external dataload wasn't setting updated values in `standardized_tables_track` which resulted in misleading info after install
change `.prop()` to `.attr()`

fix for install/upgrade external data load deets

---

custom/code_types.inc.php
interface/super/edit_list.php

Fixes #3967 
restores code type edit
declare global
change var name (minor)

declare ct_external_options global for edit list

---

src/Common/Session/SessionUtil.php

- session id is different functioning than name
A session id is required to recall session across requests. As we are using cookie only and secure cookie, I don't see an opportunity for fixation attacks via session id.

Session Id

---

.gitignore

excludes visual studio workspace files
add to '.gitignore'

for vscoders

---

src/RestControllers/AuthorizationController.php

- ensure that local openssl.cnf setting are overrided just in case the local settings are not secure

Couple settings for oauth2 key

---

API_README.md
apis/dispatch.php
oauth2/authorize.php
oauth2/provider/.well-known/discovery.php
sql/5_0_2-to-6_0_0_upgrade.sql
sql/database.sql
src/RestControllers/AuthorizationController.php

Provides a logout endpoint that will destroy the trusted users logged in session.

add logout endpoint to server

---

library/MedEx/API.php

- finish converting previous div table to BS table.
Fixes #4046 
Recall items were not displaying in table. 
This is a result from container table being converted from a div table to a BS table however, populating rows were never converted to table format.
I'm not sure if the same issue applies to the icon and SMS displays and needs watching. Refer to this PR if so.
Restyle divs to td

recall board fix

---

.github/workflows/test.yml
tests/Tests/E2e/CreateStaffTest.php
tests/Tests/E2e/Pages/MainPage.php
tests/Tests/E2e/Pages/UsersTab.php

trying to isolate and fix the automated testing e2e bug that happens about 1 in every 8 tests or so:
```
Create Staff (OpenEMR\Tests\E2e\CreateStaff)
✘ Check add user
│
│ Facebook\WebDriver\Exception\TimeoutException:
│
│ /var/www/localhost/htdocs/openemr/vendor/php-webdriver/webdriver/lib/WebDriverWait.php:71
│ /var/www/localhost/htdocs/openemr/vendor/symfony/panther/src/Client.php:331
│ /var/www/localhost/htdocs/openemr/tests/Tests/E2e/Pages/UsersTab.php:53
│ /var/www/localhost/htdocs/openemr/tests/Tests/E2e/CreateStaffTest.php:42
│
```

At e2e fix

---

interface/main/tabs/menu/menus/front_office.json
interface/main/tabs/menu/menus/standard.json

Fixes #4078
Various menu wording improvements for OpenEMR Patch 5:
Miscellaneous > "Ofc Notes" would be clearer as "Office Notes"
Miscellaneous > "BatchCom" would be clearer as "Batch Communication Tool"
Administration > "Addr Book" would be clearer as "Address Book"
Popups > "Appts" would be clearer as "Appointments"
Edited the menu labels to proper wordings

Menu wordings improvements

---

src/OeUI/OemrUI.php

Fixes #
For some reason, the default behavior is to hide the individual column filters, which was annoying for customers that use this feature regularly. This fix adds code that remembers what you selected, show or hide when you reload the tab or even close the browser.

Enable browser's localStorage to remember showing of patient filters

---

contrib/forms/xmlformgen/xslt/common_objects.xslt
contrib/forms/xmlformgen/xslt/report.php.xslt

Signed-off-by: Arnab Naha <superarnab@gmail.com>
Fixes #4103 
It resolves the non functioning of xml formgen created forms due to split function being removed from php 7
Changed the split function to explode to make the forms work again.

XMLFormgen Changes for PHP 7 and above

---

interface/smart/register-app.php

@adunsulag , Gonna only access to this script if fhir api is turned on. I assumed only used when fhir api is on, but let me know if also need this if just the standard (non-fhir) api is turned on. Or if also need it on even if the apis are turned off.

only allow access to smart client register if fhir api is turned on

---

interface/main/backup.php

- refactored command escaping to work on window and linux
Fixes #4158 
Backups LBF export dump command was breaking due to escaping on windows.

fix layout export for windows

---

src/Menu/PatientMenuEvent.php
src/Menu/PatientMenuRole.php
tests/eventdispatcher/oe-modify-patient-menu-example/README.md
tests/eventdispatcher/oe-modify-patient-menu-example/composer.json
tests/eventdispatcher/oe-modify-patient-menu-example/custom_patient_menu.json
tests/eventdispatcher/oe-modify-patient-menu-example/openemr.bootstrap.php

Added event and hook to allow 3rd party modules to modify the tab navigation in the patient dashboard, similar to the main menu
Fixes #

Patient menu hook

---

interface/new/new_comprehensive_save.php
interface/patient_file/summary/demographics_save.php
library/patient.inc
src/Events/Patient/PatientCreatedEvent.php
src/Events/Patient/PatientUpdatedEvent.php
src/Services/BaseService.php
src/Services/PatientService.php
src/Validators/ProcessingResult.php
tests/eventdispatcher/oe-patient-create-update-hooks-example/README.md
tests/eventdispatcher/oe-patient-create-update-hooks-example/composer.json
tests/eventdispatcher/oe-patient-create-update-hooks-example/openemr.bootstrap.php

Questions:
- I didn't add this behavior to the "old style" new patient form. Should that be removed?
- (1) below may break API even though I think it's a bug. When returning the ProcessResult, the service would not append the pid, and uuid to the existing data attribute array of the Result. Instead, the [pid, uuid] array was placed in a NEW array as an element of the existing data attribute. 
In the PR:
1. Fixed issue in PatientService when passing array to addData()
2. Added escape_table to BaseService when getting uuid
3. Consolidated patient update and create to the PatientService
4. Added events so modules can subscribe to patient update and create events
5. Added example module for usage of patient update/create hooks
Fixes #

EventDispatcher hooks for patient create, and patient update

---

library/sql_upgrade_fx.php

I found a couple of issues with sql_upgrade_fx.php when converting a customized vintage 4.x.x release to 6.0.0.
1. The database() MySQL function was returning "information_schema" instead of the current OpenEMR database name when querying information_schema.
2. sqlNumRows() did not seem to be working properly for such queries.
3. information_schema table and column names are in upper case, however the code was written as if they are lower case. This fix should handle either way.

Fixing multiple problems with database conversion from old releases.

---

portal/patient/_global_config.php
portal/patient/fwk/libs/verysimple/Phreeze/PortalController.php
portal/patient/libs/Controller/AppBasePortalController.php
portal/patient/libs/Controller/DefaultController.php
portal/patient/libs/Controller/OnsiteActivityViewController.php
portal/patient/libs/Controller/OnsiteDocumentController.php
portal/patient/libs/Controller/OnsitePortalActivityController.php
portal/patient/libs/Controller/PatientController.php
portal/patient/libs/Controller/PortalPatientController.php
portal/patient/libs/Controller/ProviderController.php

- rename controller
There is, and has been, a class naming conflict between cores smarty 'Controller' and the patient portal application api 'Controller'.
Because they both live in the PHPs default namespace ie. no namespace, the possibility for contention exists, especially since the portal controller is an abstract class so, whose final!
It's unknown if this resolve any outstanding issues but my guess is that it may explain some unexplainable issues in the past.

Refactor portal base controller scope

---

interface/themes/core/tabs.scss

This is a forum issue on some screen sizes. 
We'll let browser decide but trying to scale between full tab and half tab using absolute sizing isn't the answer.
this supersedes previous attempt.

fix demographics responsiveness

---

src/Billing/BillingProcessor/Tasks/GeneratorHCFA_PDF.php
src/Billing/BillingProcessor/Tasks/GeneratorUB04X12.php
src/Billing/BillingProcessor/Tasks/GeneratorX12.php
src/Billing/BillingProcessor/Tasks/GeneratorX12Direct.php

fixed file download for HCFA and X-12 generators 
don't set last claim in batch if there are none on direct-to-insurance mode
Fixes #

Small fixes for BillingProcessor refactor

---

library/sql_upgrade_fx.php
library/uuid.php
sql/6_0_0-to-6_1_0_upgrade.sql
sql/database.sql
src/Common/Uuid/UuidRegistry.php
version.php

Goal of this is to avoid getting in a position where a huge amount of uuids need to be created at one time for when making an api/fhir request or when upgrade. This is set to populate all uuids via a service every 4 hours.
interesting openemr factoid: if this gets into the codebase, this will be the first openemr background service that is active by default :)

automated uuid updating service

---

src/Common/Uuid/UuidRegistry.php

Just seeing if:
1. Can speed things up a bit
2. Avoid breakage on huge updates
example of testing script:
```
<?php
// halved on each subsequent run (there are 4 runs)
$records_run_start = 1000000;
set_time_limit(0);
$ignoreAuth = true; // no login required
require_once('interface/globals.php');
use OpenEMR\Common\Uuid\UuidRegistry;
foreach (['one', 'two', 'three', 'four'] as $run) {
if ($run == 'one') {
$records_this_run = $records_run_start;
} elseif ($run == 'two') {
$records_this_run = $records_run_start / 2;
} elseif ($run == 'three') {
$records_this_run = $records_run_start / 4;
} else { // $run == 'four'
$records_this_run = $records_run_start / 8;
}
echo "number of records on this run: " . $records_this_run . "<br>";
error_log("number of records on this run: " . $records_this_run); …
```

optimize uuid building

---

interface/practice/ins_list.php

if there was no phone # entered it messed up the name matching since some ins had no entries in the `phone_numbers` table

fix ins search when no phone # entered

---

interface/usergroup/usergroup_admin.php

fix related to google sign in
This fixes error when trying to add a new user with a blank google sign in email address. If you already have a user with a blank google sign in email address then it will break. This fixes it by converting blank to null, which does not need to be unique in the database field.

fix related to google sign in

---

src/Common/Logging/EventAuditLogger.php

Fixes SQL error "Incorrect DATETIME value: ''" when viewing the event log using MySQL 8 (and perhaps other versions).

Fix sql error with MySQL 8 when viewing event log.

---

interface/main/messages/messages.php

…center
currently if a sent message is more than 1 line you have to go into the pt's dashboard to view the whole message
gives 5 rows like the textarea reply below
also makes the received msg readonly

change received message into textarea for easier viewing in messages

---

interface/main/finder/dynamic_finder_ajax.php

Fix to custom filter (via module/event) that allowed searches to bypass filter
Fixes #

Fix to custom filter (via module/event)

---

src/Billing/EDI270.php

Fixes # The error message received during the eligibility process
It said that the provider was missing and when a provider is entered is says the provider is missing when in fact. It is the NPI that is missing not the provider in choices.

The error message was miss leading.

---

interface/main/backup.php

Configuration Import was trying to use mysqldump instead of mysql, causing it to fail. This fixes that.
Should be applied to 6.0.0 as well.

Fixing import bug in backup.php.

---

src/Events/Patient/BeforePatientCreatedEvent.php
src/Events/Patient/BeforePatientUpdatedEvent.php
src/Services/PatientService.php

Adds two events: before a patient is created and before a patient is updated. This is helpful to do any extra processing to DB fields before they are inserted into the database. 
We are using this to dynamically generate a PUBPID that is based on a combination of sources. We can listen to the event, and in our module, calculate the PUBPID before it is inserted into the database.

Add events on before-patient-create and before-patient-update

---

interface/main/tabs/js/tabs_view_model.js

loads correct encounter after opening a pt in a new window from from patient finder
couple restoreSession()s

couple places top_restore was needed

---

interface/patient_file/encounter/forms.php
library/registry.inc

The visit summary page has dropdowns to select new forms. Currently there is a dropdown for each of the traditional form categories, and a separate one for all LBF forms. However users don't care which technology is behind each form.
This PR consolidates LBF entries into the form categories, and sorts the categories and forms. Note that categories and sorting sequence can be assigned in the LBF properties dialog.

Integrate traditional and layout-based forms into their chosen categories in the visit summary dropdowns.

---

interface/language/csv/commit_csv.php
interface/language/csv/load_csv_file.php
interface/language/csv/translation_utilities.php
interface/language/csv/validate_csv.php
interface/language/lang_constant.php
interface/language/lang_definition.php
interface/language/lang_language.php
interface/language/lang_manage.php
interface/language/language.php

This is based on old work from Kevin Yeh for IPPF. I adapted it as an enhancement to the existing Multi Language Tool.
The idea is that you can easily upload and process a CSV spreadsheet that has language constants in one column, and the desired translations in some other column.

Implemented CSV loader for language translations.

---

README.md

Fixes #
IT SHOULD BE -  "This project exists thanks to all the people who have contributed."

Updated Readme File - grammatical error in sentence

---

FHIR_README.md

Fixes #4316
As per Issue #4316; when creating a Patient entity via the FHIR API endpoint it's expected that one of the provided names has the `use` attribute set to `official`. The FHIR specification actually states that this property should be mandatory.
- [`HumanName`](http://hl7.org/fhir/stu3/datatypes.html#HumanName) FHIR resource documentation
- [`Patient`](http://hl7.org/fhir/stu3/patient.html) FHIR resource documentation
- One line change to documentation showing the presence of the above attribute.

Issue #4316: Minor amendment to FHIR API docs

---

interface/login/login.php
library/restoreSession.php

restoreSession() was setting a session cookie with different attributes (most notably path) from the one set originally by PHP. This resulted in duplicated cookies and dismal failure of session swapping. This PR fixes that.

Fixes for restoreSession logic.

---

src/Billing/BillingProcessor/BillingLogger.php
src/Billing/BillingProcessor/Tasks/GeneratorX12.php
src/Billing/BillingProcessor/Tasks/GeneratorX12Direct.php

The billing log was only being written to disk if the generator task set an onLogCompleteCallback. In the case of the X12Direct generator, it doesn't set a callback, so the log is never written. This change writes the process_bills.log to disk every time.

write to billing log, even if there is not an onLogComplete callback set

---

interface/main/tabs/js/tabs_view_model.js

added a tabRefreshByName() api call in the tabs view model so tabs can be refreshed by api.
I use this in a module where a form is opened in a new tab by clicking on an element in a list. There is a delete button at the bottom of the form. When the entity is deleted by clicking the button on the form, we navigate the user back to the list, but we have to refresh the "list tab" first so the deleted entity is removed from the list.
Ken

added a tabRefreshByName() api call in the tabs view model

---

controllers/C_Prescription.class.php
interface/patient_file/summary/add_edit_issue.php
library/ajax/prescription_drugname_lookup.php
library/classes/RXList.class.php
src/Rx/RxList.php
templates/insurance_companies/general_edit.html
templates/prescription/general_edit.html
templates/prescription/general_lookup.html

ultimately trying to fix #4373 
the way we grab the `rxnorm` code isn't working; think it's since the array flip doesn't store the code in a hidden post variable or in the array for smarty
some minor edits with a couple php warnings but nothing significant yet

store Rxnorm in prescription table from nlm lookup api

---

interface/forms/eye_mag/a_issue.php
interface/forms/eye_mag/css/style.css
interface/forms/eye_mag/save.php

Some tweaks needed for the Eye Form.
The addition in save.php is critical: default value for “billed” was null and it needs to be =“0” explicitly. The Billing Manager requires this.
Other changes are cosmetic.
Fixes #

Eye Form Patch 2

---

custom/code_types.inc.php
interface/forms/eye_mag/view.php
interface/forms/fee_sheet/new.php

Fixes #
https://community.open-emr.org/t/default-to-icd10-on-fee-sheet/16657/
variable wasn't in scope so added to session
as an aside, couldn't figure out why `code_types.inc.php` was being called by the `execute_background_services.php` script so `require_once("$srcdir/options.inc.php");` in the `fee_sheet/new.php` is causing the `custom/code_types.inc.php` to be loaded twice

add default search type to session for fee sheet search for add'l codes

---

contrib/util/ccda_import/import_ccda.php
interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
interface/modules/zend_modules/module/Installer/Module.php
interface/modules/zend_modules/module/Installer/config/module.config.php

- optimize dev bulk ccda import (by bypassing use of the audit_* tables)
```
Completed patients import (1000 patients) (2545 total seconds) (2.545 average seconds per patient)
Started uuid creation
Completed uuid creation (2805 total seconds; 0.77916666666667 total hours)
```
- gender fix for synthea ccda import

optimize dev bulk ccda import

---

interface/forms/care_plan/new.php
interface/forms/care_plan/save.php
interface/forms/care_plan/table.sql
interface/forms/clinical_notes/new.php
interface/forms/clinical_notes/save.php
interface/forms/clinical_notes/table.sql
library/custom_template/custom_template.php
sql/6_0_0-to-6_1_0_upgrade.sql
sql/database.sql
version.php

- from Text Templating feature
- Ensure Administration->Globals->Features `Enable Text Templates in Encounter Forms` is enabled.
- Double click in note narrative.
- Add from templating dialog.
Now `form_clinical_notes` has the ref mapping to lists table id in `note_related_to` column as json array.
See issue #4462

Add issue relations to clinical notes

---

ccr/stylesheet/ccr.xsl
interface/patient_file/encounter/diagnosis.php

missing `patient.inc` require for charges panel
[bug report via forum](https://community.open-emr.org/t/openemr-ccr-stylesheet-ccr-xsl-error/16770?u=stephenwaite)

missing require, missing close tag

---

src/Common/Uuid/UuidRegistry.php

If an exception is thrown in generating the UUIDs the tables were being
locked through an open transaction.  PHP did not have the Exception
class imported so SqlQueryException was not being caught, fatal error
occurred and the transaction was left open.
Fixing the import now lets the transaction be caught and then roll backed.  It looks like there is also a timing element involved as I had difficulty reproducing the bug. Regardless we need to catch the exception and roll back the uuid transactions if a sql query exception is thrown.

Fixed a MySQL Innodb table lock bug

---

src/Common/Acl/AccessDeniedException.php
src/Common/Http/HttpRestRequest.php
src/Common/Http/HttpRestRouteHandler.php

Map the get requests onto a post operation for FHIR get.  Saved us
from having to duplicate all the routes just to deal with a simple
_search parameter.
Also fixed an issue where ACL exceptions were not being logged properly.

Fixes #4497 - FHIR search via POST

---

interface/forms/procedure_order/common.php

Fixed the PHP8 error where count was being used on an un-initialized
variable in procedure_order.  Editing an existing procedure order would trigger the error. Fixes #4499
Added the CPT4 and LOINC codes to the procedure_order file so we can
select them for diagnoses.

Fixes #4499, php8 error, add SNOMED,LOINC codes.

---

contrib/util/dupscore.cli.php
interface/main/tabs/menu/menus/standard.json
interface/patient_file/manage_dup_patients.php
interface/patient_file/merge_patients.php
library/dupscore.inc.php
library/patient.inc
sql/6_0_0-to-6_1_0_upgrade.sql
sql/database.sql
version.php

Identification and correction of duplicate patients involves the following:
1. Column "dupscore" in the patient_data table was created to contain a value representing
the likelihood that the patient duplicates any of the patients created earlier (that is,
with a lesser "pid" value). It may have any of the following values:
o -9, initially assigned, indicating that it needs to be computed.
o -1, indicating that the patient has been manually flagged as not duplicating a previous patient.
o A score in the range 0-40 computed by the SQL expression found in library/dupscore.inc.php.
A value of 12 or higher is considered to be very likely a duplicate.
2. The script library/dupscore.inc.php which provides the SQL expression needed for scoring.
3. The command-line tool …

Implemented duplicate patients management.

---

src/Common/Crypto/CryptoGen.php

more accurate error messages when critical key errors
(this will make it more clear when key collection is failing when the key on the drive can not be decrypted by the key in the database)

more accurate error messages when critical key errors

---

contrib/util/ccda_import/import_ccda.php
interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php

@stephenwaite , Was still getting the memory error every several thousand patients or so with the prior fix. Think is because the main ccda import script is actually running the care coordination script from commandline for each patient import (i.e. running separate php commandline processes, so not using the php settings set in the main ccda import script). This fix is within the separate php process and so far no errors yet so far on about 30K patient imports :)
As an aside, would a script that creates thousands of active users and a large number of facilities be helpful (been starting to look into how to do this).

ccda import memory fix

---

ccdaservice/ccda_gateway.php
interface/globals.php
interface/modules/zend_modules/public/index.php
interface/patient_file/report/patient_report.php
library/globals.inc.php
portal/patient/_machine_config.php
src/Services/CDADocumentService.php

- fixes for prior PR
Having user set site host address for Api's in globals is problematic IMO. Also we need to be able to resolve domain and ports that may be behind proxies, load balancers etc to the originating requests address.
Since we can't know the many different environments we run under, this is my best attempt.
As a note: Since PHP7 and deprecated in PHP5.4 it is required to provide parentheses when using new for classes.(code sniffer: Parentheses must be used when instantiating a new class).
Patterns like `throw new \RuntimeException()` will error in code sniffer. Generally using namespace paths for new() instantiations.
Even though PHP doesn't seem to mind!
Btw: I added new $GLOBALS['qualified_site_addr'] for $GLOBALS['site_addr_oath'] + webroot eg. …

Dynamically resolve host domain Uri for API's and CCDA

---

interface/orders/orders_results.php

Modify query to select unit title instead of id.
Fixes #
Forum issue:
https://community.open-emr.org/t/results-unit-id-shows-instead-of-text-value/16930

Patient Results correct units type fix

---

_rest_routes.inc.php
interface/forms/newpatient/common.php
interface/forms/newpatient/new.php
interface/forms/newpatient/save.php
sql/6_0_0-to-6_1_0_upgrade.sql
sql/database.sql
src/RestControllers/FHIR/FhirLocationRestController.php
src/Services/EncounterService.php
src/Services/FHIR/FhirCodeSystemConstants.php
src/Services/FHIR/FhirEncounterService.php
src/Services/FHIR/FhirLocationService.php
src/Services/LocationService.php
version.php

Implemented FHIR encounters endpoint.  I had to change a couple of minor things in the encounter service, but the biggest change involved adding a discharge_disposition to form_encounters and showing the dropdown on the encounters form.  FHIR requires we at least support the property and have some resources flagged with it, fortunately its optional and doesn't have to be filled in for historical data.  
Here is all the happy green checkmarks from Inferno.
Here is what the discharge dropdown looks like:
Available list options are here.  Note I specifically called it Discharge Disposition for the list as the Appointment FHIR resource (not ONC required) also has a dischargeDisposition property which would likely use this same list.

Openemr fhir encounters

---

interface/patient_file/deleter.php
interface/super/edit_layout.php
sql/6_0_0-to-6_1_0_upgrade.sql
sql/database.sql
src/Common/Uuid/UuidRegistry.php
src/Services/CareTeamService.php
src/Services/FHIR/FhirCareTeamService.php
src/Services/PatientService.php
version.php

Added a history table for the a patient's Care Team.  Any changes to the
care team providers or facilities that are part of the care team are
saved off to the patient_careteam_history table.  Note the status column
in patient_data is specifically for the current Care Team.  Past care
teams in the history table always have a status of 'inactive'.
I changed up the queries and report these changes back via FHIR.
I also made sure the records are cleaned up if a patient is deleted via the deleter.php script.
Long term we probably want to break up the care team properties in patient_data but that is a bigger engineering effort that hopefully can be taken on in the future.

Fixes #4560 Support multiple care team records.

---

_rest_routes.inc.php
src/Common/Http/HttpRestParsedRoute.php
src/RestControllers/FHIR/FhirProvenanceRestController.php
src/RestControllers/RestControllerHelper.php
src/Services/FHIR/FhirPatientService.php
src/Services/FHIR/FhirProvenanceService.php
tests/Tests/Unit/Common/Http/HttpRestParsedRouteTest.php

I took a creative approach to implementing the provenance. Instead of trying to figure out how to tie the provenance to each individual resource I use the resource and the resource uuid to uniquely identify the provenance resource.  Using that ID I can load the corresponding FHIR resource service and re-run all of the queries and grab the correct Provenance exactly as it was generated.  If we ever do need to grab a list of all Provenance records... that is going to be pretty hard to do as we don't track anything globally except for perhaps the uuid_registry which wouldn't be a perfect map for resources but could be implemented to do this...
I still am not sure that only putting the OpenEMR organization as the provenance source is the right approach as I would imagine most people would …

Openemr fhir provenance

---

_rest_config.php
apis/dispatch.php
sql/6_0_0-to-6_1_0_upgrade.sql
sql/database.sql
src/Common/Auth/OAuth2KeyConfig.php
src/Common/Auth/OAuth2KeyException.php
src/Common/Auth/OpenIDConnect/Entities/ClientEntity.php
src/Common/Auth/OpenIDConnect/JWT/JsonWebKeyParser.php
src/Common/Auth/OpenIDConnect/Repositories/AccessTokenRepository.php
src/Common/Auth/OpenIDConnect/Repositories/ClientRepository.php
src/Common/Auth/OpenIDConnect/Repositories/RefreshTokenRepository.php
src/Common/Database/QueryUtils.php
src/FHIR/SMART/ClientAdminController.php
src/RestControllers/AuthorizationController.php
src/Services/TrustedUserService.php
version.php

Fixes #4573 FHIR Inferno requires you to provide an access token and a refresh token
that will be revoked in order to pass the test cases.  The developer has
to visually demonstrate revoking the token and then run the automated
test case.  This doesn't work with the trusted user mechanism we
originally had for token revokation as there isn't a way to tie the
token back to the trusted user given just the JWT.
I implemented the access token and refresh token revocation by adding a
revoked column and implementing the methods in the repositories to
handle token revocation.  I had to implement a separate isTokenRevoked
method for the access token due to the way League and OpenEMR interact
on the token revocation.  Because we store the site id inside the token
we have to allow League to …

Fix #4573 Openemr fhir token revocation

---

src/Common/Auth/OpenIDConnect/IdTokenSMARTResponse.php

@adunsulag , I just noticed this when searching the pathing to ensure the MU3 demos will work (the ones with `a`, `b`, and `c` in the paths). Noted this one was missing the webroot in it.

possible pathing fix

---

src/Services/CodeTypesService.php
src/Services/FHIR/FhirCareTeamService.php

As discussed in this issue #4590 instead of changing the facility column size we needed to fix the FHIR code to always use NUCC for the facility taxonomy when reporting in FHIR.

Fix facility code to be NUCC for FHIR.

---

src/Common/Http/HttpRestRouteHandler.php
src/Services/FHIR/FhirAllergyIntoleranceService.php

This fixes #4593  which removes escaping for the forward slash as well as adding a data absent reason to the Allergy Intolerance resource.  This was many, many hours of debugging ruby code to figure out what was happening.  I'm glad I finally figured this out.
Hooray for more check marks!
Here is my original commit message:
Our api endpoints were escaping the forward slashes in the JSON
responses.  This is optional in the JSON spec and is really only
necessary as far as I can tell when embedding JSON inside of an html
<script> tag.
However, some servers don't handle this forward slash escaping well.  In
the ONC Inferno test suite it does a strict string match for a URL.  The
match fails because of the escaped forward-slashes in the URL.  This is
why the data absent reason codes/extensions …

Openemr fhir data absent reasons

---

_rest_config.php
apis/dispatch.php
src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
src/Common/Database/QueryUtils.php
src/Common/Http/HttpRestRequest.php
src/Events/RestApiExtend/RestApiScopeEvent.php
src/Events/Services/ServiceSaveEvent.php

Added an event to handle adding additional scopes via event listeners.
If a module adds to the REST api the api is pretty useless if there is
not an accompanying scope added with the api.
Also added some helper methods to the http request object and some
more api logging.  I needed this for a module I am building and it
will be useful for the community to have it in core.

Openemr events scope vitals

---

interface/patient_file/front_payment.php

Minor fix for php8 issue where the 0 + $payment type conversion was throwing errors.  @sjpadgett and I discovered this issue.

Fix php8 issue with front payment.

---

interface/forms/newpatient/common.php
interface/forms/newpatient/save.php
src/Common/Twig/TwigContainer.php
src/FHIR/SMART/SmartLaunchController.php
src/Services/EncounterService.php

Add empty option for encounter discharge.  Right now there is no way to opt out of setting an encounter's hospital discharge status.  Looking at the ONC FHIR encounter spec it looks like this is a MUST Support requirement and not a Required attribute.  Adding the optional value allows people to not fill this encounter in.
Made it so you can add additional search directories for twig.   This makes it so modules can use twig templates inside their own folders.
Added a helper method to the EncounterService to be able to get the most recent encounter for a patient based on the encounter date.
Modified the search method in EncounterService so you can have order by and limit conditions.
Removed spam log from patient demographics.

Openemr encounters twig kernel

---

interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
interface/super/edit_layout.php
library/forms.inc
src/Services/Cda/CdaTemplateImportDispose.php
src/Services/Cda/CdaTemplateParse.php

@sjpadgett , just had several php8 related warnings to fix. The time per patient has increased from average of 0.4 seconds per patient to 1.5 seconds per patient, which is likely because the labs are now correctly being imported (by the way, all the importing looks great and much improved from before, so the OpenEMR fans are happy!). I'll see if can find any way to speed things up, although it's currently at a really good speed (would work out to 57600 patient imports per day, so getting to 1 million would take awhile :) ). Another really good thing is that the speed isn't slowly down as more patients are added (this was an issue in past that was a pain to fix), so overall the random patient generator is in great shape! thanks!
Pasted a sample run of 1000 patients below:
```
Starting …
```

random patient generator related updates

---

src/Common/Twig/TwigContainer.php
src/Common/Twig/TwigExtension.php
src/Events/Core/TwigEnvironmentEvent.php
templates/error/400.html.twig
templates/error/general_http_error.html.twig

Added a twig extension to fire a generic event.  For now that is helpful
in being able to migrate over some of our php/html files that dispatch
render events.
I also added a twig environment event that module authors can hook into
in order to extend the file loader and load their own template files.  I
put an example in the twig environment event header of how to go about
doing this. Here it is:
```
function addTemplateOverrideLoader(TwigEnvironmentEvent $event)
{
$twig = $event->getTwigEnvironment();
// we make sure we can override our file system directory here.
$loader = $twig->getLoader();
if ($loader instanceof FilesystemLoader) {
$loader->prependPath(\dirname(__DIR__) . DIRECTORY_SEPARATOR . "templates" . DIRECTORY_SEPARATOR);
}
} …
```

Twig module author extensions

---

src/Services/Search/FhirSearchWhereClauseBuilder.php

Made it so the fhir search classes will convert strings and numbers into
an exact string match.  This makes it so that search methods can pass in
simple array values without having to create the search field objects each time.  This
was a request from @sjpadgett to make the classes a little easier to
use.

Make fhir search service classes easier to use

---

src/Services/PatientService.php

Really quick and simple fix as apparently we weren't sending the inserted id into the patient event data.  Didn't realize I needed this until everything else was done... should be my last thing tonight lol.

Add the inserted id to the patient event data

---

interface/usergroup/usergroup_admin.php
src/Events/User/UserCreatedEvent.php
src/Events/User/UserUpdatedEvent.php

Fixes #4725 
Made it so the create user event only fires if the user successfully
saves.  Also made it so creating a user generates a uuid for it so we
have it at the time of the save user event.  Added some helper methods
to the user created and user updated event to make them more useful.

Fix #4725 user events, uuid generation

---

src/Common/Twig/TwigExtension.php
src/Services/AppointmentService.php

The fireEvent was missing the twig kernel.  No idea how that somehow got
left out of the code as it was working when I tested the fireEvent
stuff.
Also the manageTracker needed a bug fix on the appt status update.  It
was sending in the entire encounter instead of the encounter id.

Fix twig and appointment bugs.

---

interface/patient_file/encounter/forms.php
library/ESign/views/form/esign_button.php
src/Common/Twig/TwigExtension.php
templates/encounter/forms/navbar.html.twig

This PR moves the button-based, centered form-navigation on the Encounter screen to an bootstrap navbar. Additionally, it moves btn-primary buttons to more appropriate btn-secondary classes. Some small changes to the form title as well as prepping some inline code for a twig overhaul. The new navbar leverages twig. Fun fact, you don't have to migrate the ENTIRE page to twig in one go, it's flexible enough to take a phased approach.

Encounter Screen UI Improvements

---

composer.json
interface/patient_file/encounter/forms.php
src/Events/Encounter/EncounterMenuEvent.php
templates/encounter/forms/navbar.html.twig

Support for `EncounterMenuEvent`. Currently only support for `MENU_RENDER` which is used to populate the Twig variable for output.
Forms.php builds traditional forms menu and zend hooks. Both of those were wrapped in event listeners to streamline a future project to move those out of forms.php and into a better location. (Just means technically this page both adds 2 listeners and then fires the dispatch()).
Is testing well

Encounter Menu Hook

---

portal/messaging/secure_chat.php

Fixes #4761
Recent portal changes introduced a bug with the SessionUtil class.  This post adds the namespace escape for the OpenEMR namespace.  Essentially 2 character changes so going to bring this in.

Fix portal fatal errors due to not found class.

---

interface/billing/billing_tracker.php

Fixes #
The billing tracker shows the claims sent in ascending order which means you have to click all the way to the end to see the latest claims.
Change to descending order so that on load the lastest claims are sent

Changing the order from ascending to descending

---

src/Common/Crypto/CryptoGen.php
src/Common/Logging/EventAuditLogger.php

Related to an interesting deprecated error in future PHP 8.2 (noted it while was updating the insane dev environment) that is discussed by php folks here:
https://wiki.php.net/rfc/deprecate_dynamic_properties
Notably, the deprecation errors do not actually go away with this, but assuming this is simply because of a bug in php 8.2 since very early in development.
Makes sense to do this for CryptoGen class since it is using dynamic properties to cache keys (much more efficient doing this).
Will reengineer the EventAuditLogger class a tiny bit since really don't need a dynamic property for this. Prob just initiate it to null and then create the new CryptoGen call if the variable is not instance of CryptoGen class (or something like that). (btw caching that CryptoGen isntance also makes …

first php 8.2 fix

---

interface/patient_file/report/patient_report.php
templates/documents/general_view.html

Fixes #
These events were wrapped in if statements checking if oefax is installed
I am building a fax module. I need to use the current event dispatcher that is in the system. 
Remove the if statements so that the event fire always and not only when the faxsms module is installed.

Allowing the system to fire patient report/document event always

---

templates/encounter/forms/navbar.html.twig

Allow encounter menu items to change behavior of link action by injecting an "onclick" attribute. This allows non-forms to be opened in the encounter tabs

Allow encounter menu items to override onclick option

---

interface/super/edit_layout.php

Rolls back #4767 
The dialog does not actually indicate _what_ the standard fields are, it just says do not delete them. This leads to confusion for the user as they are being told to not do something but are not being given enough information to safely act on the info given. A better approach would be to identify the standard fields identify them on a row-level in the UI. Additionally, some javascript could be used to check if any standard field is checked, if so, disable the delete button. Additionally, the alert clashes with UI changes made in #4744

Rolling back #4767

---

package-lock.json
package.json

The Node.JS colors developer introduced an infinite loop into the colors
project which breaks this project on dev environments.  We have to lock the
dependency until we figure out a replacement package.
More details can be found here: https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/

Fixes the color dependency infinite loop problem.

---

FHIR_README.md
src/Events/RestApiExtend/RestApiResourceServiceEvent.php
src/RestControllers/AuthorizationController.php
src/RestControllers/RestControllerHelper.php

In order to make sure that a module REST resource shows up in the FHIR
metadata api and to allow us to override service classes in the metadata
we needed a new event.
Made a change to the fhir readme to explain how to register with
swagger.

Add Rest API metadata event. Added swagger doc

---

src/Services/ImmunizationService.php

Not sure how we didn't catch this until now, but ImmunizationService was
failing with the Provenance export due to typo.  Discovered this by
testing the bulk fhir export service.

Fix typo on immunization fhir service.

---

custom/code_types.inc.php

`
Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3
`
I thought we had this licked awhile back. Is this just a newly missed dispatched or is this still an issue elsewhere?
I'm not seeing except in portal dashboard so far...

fix deprecation exception in code types

---

API_README.md

Fixes #4885 by adding the documentation for what the swagger redirect_uri should be in the swagger api.

Fix #4885 add swagger redirect_uri documentation

---

tests/Tests/ECQM/AllPatientsTest.php
tests/Tests/ECQM/MeasureResultsTest.php

```
Generating optimized autoload files
Class OpenEMR\Tests\Qdm\AllPatientsTest located in ./tests/Tests/ECQM/AllPatientsTest.php does not comply with psr-4 autoloading standard. Skipping.
Class OpenEMR\Tests\Qdm\MeasureResultsTest located in ./tests/Tests/ECQM/MeasureResultsTest.php does not comply with psr-4 autoloading standard. Skipping.
Generated optimized autoload files containing 23403 classes
```

fix psr4 ECQM tests

---

interface/main/finder/multi_patients_finder.php
interface/main/messages/messages.php
library/pnotes.inc

Fixes #4912 Made it so you can update the patient for a direct message.
There's been a lot of hands in the messages.php file and it really needs to be refactored into multiple files due to how many branches and its cyclomatic complexity.  I'd greatly appreciate people taking a review of it to make sure I'm not breaking something else here.
Also added helper error messages to the multi select so you know that you need to add at list one patient to the selection before hitting the ok button.

Fixes #4912 direct message patient update fails

---

interface/patient_file/summary/stats.php
templates/patient/partials/erx.html.twig

Fixes #4921 
Fix the broken endif statement in twig that was throwing a fatal error on the patient demographics screen.
When the dashboard pieces were refactored into twig files one of the
global options was not tested.

Remove broken endif for twig for erx newcrop

---

ci/ciLibrary.source

make e2e run a bit more efficient; rather than always run 3 times, only do that if needed
of course, ideally would figure out why e2e runs are so flaky in the github action environments

make e2e run a bit more efficient; rather than always run 3 times, only do that if needed

---

ccr/createCCR.php
ccr/transmitCCD.php
interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncountermanagerController.php
interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncountermanagerTable.php
library/direct_message_check.inc
src/Common/DirectMessaging/ErrorConstants.php

Fixes #4941 
The direct send was not working with the CareCoordination module as it
had a duplicate code of the ccr/transmitCCD.  Working with EMRDirect
found that the Direct community expects one message per patient instead
of bundling multiple patients into a single message per recipient.  I
changed up the code flow to make this happen as well as removed the
duplicate code.  I was able to extend the ccr/transmitCCD.php file to
handle pdf and html files.
Also pulled out some of the constants in the transmitCCD function into
a class with better explanations.  This made the code more legible.
Also documented some of the AMC stuff with the care coordination.
Per request from EMRDirect we add in the version information so they can
have better debugging facilities on their end when OpenEMR …

Openemr fix #4941 direct send ccda

---

library/direct_message_check.inc

Fixes #4888 
I discovered that the document white listing fails if the local
operating system's mime type detection on the document is
different than the mime type received via direct. This was
discovered with a CCDA xml file. EMRDirect was sending a mime type
of application/xml mime type and the local OS detected it as
text/xml. This breaks our current solution as we temporarily allow
the EMRDirect mime type if it matches the document mime type and
then we remove the temporary bypass.
Since we don't want to build a file quarantine process I went
with our original design approach and bypass the mime type check
altogether during the document storage process.
The files are protected on the drive as is so this should be fine.

Fixes #4888 Direct Message Whitelist

---

src/Common/Twig/TwigExtension.php

Creates a new Twig function called `csrfToken()` which optionally accepts 1 parameter for the subject.
Returns a hidden field named `_token` with the value from `CsrfUtils::collectCsrfToken()`

New Twig function, csrfToken() to auto generate the input field

---

interface/main/tabs/templates/patient_data_template.php
interface/main/tabs/templates/user_data_template.php

- Add callback to ativate correct tab.
- add btn-sm to Portal notification to match messages button.
Fixes #
The About page link in User dropdown required two clicks to view the about page.
Also mismatched button sizes for message and portal notifications.

Fixes for User About tab open

---

library/direct_message_check.inc

See issue.
Basically we would reject Direct mime types text/plain and text/html received message with empty body.
Fixes #4970 #4964

Direct message empty content text/plain and text/html rejected

---

src/Common/Session/SessionUtil.php

fixes #4855
@adunsulag , this seemed like the simplest solution since this class is called before the class autoloader in scripts that need to support both portal and core OpenEMR. Since not critical functionality and just debugging stuff figured easier to remove it than complicate code by needing to bring in class autoloader in these instances.

make SessionUtil class self-sufficient

---

interface/billing/billing_report.php
interface/billing/sl_eob_invoice.php
interface/forms/newpatient/report.php
interface/main/tabs/templates/patient_data_template.php
library/FeeSheet.class.php
src/Billing/BillingUtilities.php
src/Billing/Claim.php
src/Billing/SLEOB.php
src/Services/EncounterService.php

Fixes #4979 by checking for null payer id 
Insurance information was missing with validate only option in billing manager
restores ability to see all encounters in billing manager, even those with no fee sheet in the encounter but warns if no criteria selected
fix setup secondary when save level in invoice
adds payer id to billing from fee sheet

fix validate only in billing manager

---

composer.json

hi @kchapple and @sjpadgett ,
The ^M line endings ended up in composer.json and all the mustache files. I only addressed composer.json in this PR (this is something we needed to address a long time ago since was causing issues and will figure out how to do the mustache files later). Ensure repos are correctly set for line endings here: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings (if this is set correctly, then the ^M character won't be included in the commits)

removal of ^M line endings

---

interface/forms/eye_mag/php/eye_mag_functions.php

Fixes #5026
fix fatal error
```
[23-Mar-2022 20:17:39 Europe/Athens] PHP Fatal error:  Uncaught Error: Undefined constant "id" in /var/www/localhost/htdocs/openemr/interface/forms/eye_mag/php/eye_mag_functions.php:157
```
put single quotes around array keys

fix fatal error in eye form

---

library/globals.inc.php

New global for the machine name of the application. Used to identify the EMR when working with HL7 and other systems that may want this information.

Introduce machine_name as a global option

---

library/classes/Installer.class.php
setup.php

Fixes #5082 , thanks @gutiersa
Short description of what this resolves:
removes source keys from new site unless site was a clone
the keys for the new site are created on first login
Changes proposed in this pull request:

Multi site install rm keys for new site that wasn't cloned

---

interface/patient_file/encounter/find_code_popup.php

Set the allowed_code_types to be populated if no default code type is passed in as a query parameter.  This fixes #5130

Fixes #5130 code type selector when no default code type is passed in.
