- interface/code_systems/dataloads_ajax.php
- interface/code_systems/icd10_howto.php
- interface/code_systems/icd9_howto.php
- interface/code_systems/list_staged.php
- interface/code_systems/rxnorm_howto.php
Some BS4 and UI suggestions for  Issue #3077 and in continuations of  PR #3116
> BS4 & UI suggestions

- interface/drugs/drug_inventory.php
Fixes #3125 
Group Lot number wih the drugs.
Little bit of testing and verification:
https://www.loom.com/share/7c548dcfa491453eafd5c98d145462b9
> Drug Inventory Group Lot Numbers

- interface/usergroup/facilities_add.php
- interface/usergroup/facility_admin.php
> Improved: Edit and Add Facility Button position and size

- interface/main/tabs/main.php
> Fixed NavBar Style

- interface/orders/load_compendium.php
Fixes #3130 
Add load compendium title
> Fix #3130: load compendium title

- interface/patient_file/encounter/encounter_top.php
- interface/patient_file/encounter/forms.php
- src/Tabs/TabsWrapper.php
- remove obsolete divtoggle() and replace with bs
- fixed JS error form title click
- add some margin to forms
- fix scroll showing in tabs. ie summary or tab content
Mainly resolves error on form title click caused by divtoggle(). Removed the function and replaced with BS. minor margining and fix tabs content showing scroll.
- encounter form
> encounter form fixes

- interface/forms_admin/forms_admin.php
Fixes #3099
Add bootstrap table style.
Remove outdated syntax.
> Fix #3099: add bootstrap table style and remove outdated syntax

- API_README.md
Add markdown code block highlight.
> docs: add API_README.md command highlight

- CONTRIBUTING.md
Change http link to https link.
Add the command block highlight.
> docs: change http link to https link

- interface/drugs/add_edit_lot.php
> Add edit lot BS4 updates

- interface/reports/destroyed_drugs_report.php
Fixes #3155 
https://www.loom.com/share/b01ea711bfb84fad9d3bd3f134ef3e9f
> fixes Outdated drug destroyed interface

- interface/billing/sl_receipts_report.php
Fixes #3129 
Remove unnecessary string.
Move the title header and form to the Bootstrap container class.
> Fix #3129 cash rec form aligment

- interface/main/main_screen.php
- interface/main/tabs/js/tabs_view_model.js
- interface/main/tabs/main.php
- interface/main/tabs/templates/tabs_template.php
Fixes #3068 
It will add loader while the tab gets loaded
https://www.open-emr.org/wiki/index.php/Development_Demo#Alpha_-_Up_For_Grabs_Demo
> [WIP] Added Loading in tabs

- ci/phpcs.xml
Fixes #
https://community.open-emr.org/t/project-idea-refactoring-codebase-and-adding-some-coding-standard/13942/7?u=stephenwaite
in title
-
-
-
> remove bower components from phpcs

- interface/super/manage_document_templates.php
**Before:**
**After:**
Fixes #3106
> UI Improvement: Document Template Management

- src/OeUI/OemrUI.php
Fixes #3164 
Added expand button cursor property.
> Fix #3164: eob posting - search expand button lost cursor

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
> Explanatory Error Message

- config/config.yaml
- interface/themes/core/FontAwesome.scss
- package.json
Fixes #3179 
Update the npm package version.
Modify fontAwesome config.yaml.
> Fix #3179 Update font awesome

- API_README.md
- _rest_routes.inc.php
- src/RestControllers/EncounterRestController.php
- src/Services/EncounterService.php
Fixes  #3131
Create Patient encounter API
endpoint POST:  http://localhost:8300/apis/api/patient/1/encounter
```
{
"onset_date": "0000-00-00 00:00:00",
"reason": "Corona test",
"facility": "Maris Hospital",
"pc_catid": "5",
"facility_id": "3",
"billing_facility": "3",
"sensitivity": "normal",
"referral_source": "",
"pid": "1",
"encounter": "1",
"pos_code": "0",
"external_id": "5",
"provider_id": "1"
}
```
> Create patient encounter API

- interface/main/tabs/main.php
- interface/main/tabs/templates/menu_template.php
- interface/main/tabs/templates/tabs_template.php
- interface/main/tabs/templates/user_data_template.php
- interface/themes/core/navmenu.scss
- interface/themes/tabs_style_compact.css
- interface/themes/tabs_style_full.css
- library/globals.inc.php
- src/Menu/PatientMenuRole.php
- fix patient bar expand/collapse for responsive (left chevrons)
- removed the vertical_responsive_menu functionality
Fixes #3181
Many responsive issues.
> Replace top menu with BS4 navbar

- interface/main/tabs/templates/patient_data_template.php
- library/options.inc.php
- changes superscript tag to span for missing elements exclamation point.
- helps alignment
Restyle any search and patient bar, a coming attraction.
> Main cleanup continued

- gulpfile.js
- interface/themes/core.scss
- package-lock.json
- package.json
If remove the package-lock.json and run npm install then it breaks because of the wrong path for @ttskch/select2-bootstrap4-theme
This fixes that along with downstream issues resulting from the fix. Testing well.
@tywrenn , even though testing well, I am getting following warnings on the build (anything worrisome here?):
```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN bootstrap@4.4.1 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer …
```
> fixed when remove package-lock issue

- src/RestControllers/FhirPatientRestController.php
- src/Services/FhirResourcesService.php
Fixes #3195 
Added Error Response with OperationOutcome Resource
http://hl7.org/fhir/operationoutcome.html
- added OperationOutcomeResouce for 404
> FHIR API Error Response

- _rest_routes.inc.php
- src/RestControllers/FhirPatientRestController.php
- src/Services/FhirResourcesService.php
> Implemented Post and Put feature in FHIRPatientRestController and added their routes.

- interface/login/login.php
- interface/main/about_page.php
- interface/product_registration/product_registration_controller.js
Fixes #3001
Remove dependency of registration-modal from jquery-ui
> Fixed #3001 Remove jquery-ui

- interface/billing/billing_report.php
- interface/forms/fee_sheet/review/js/fee_sheet_core.js
- interface/login/login.php
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
- interface/main/finder/dynamic_finder.php
- interface/main/tabs/templates/patient_data_template.php
- interface/patient_file/encounter/find_code_history.php
- interface/patient_tracker/patient_tracker.php
- interface/weno/ajax_sample_code.php
- interface/weno/confirm.php
- portal/messaging/messages.php
Fix: #3213
Change refresh to sync icon
> fix: update font awesome refresh to sync icon 

- interface/main/calendar/modules/PostCalendar/pnadmin.php
> feat #3205 : improve diagnostics gui

- src/RestControllers/FhirPatientRestController.php
- src/Services/FhirResourcesService.php
- patient service getOne always returns a 404.
@yashrajbothra you might want to note this commit.
> Fhir Client fixes

- interface/login/login.php
- interface/main/about_page.php
Added form-control in register email input.
> Fix: register email input lost form-control style

- docker-compose.yml
Fixes #3193
Add setting to allow for developer tools in docker
> add developer tools setting to docker

- CONTRIBUTING.md
Fixes #3159
Add Database login credentials to Contributing.md
- Just added the username and password for the db login in the `Contributing.md` file
-
-
> Fix #3159 Added the DB creds in the contributing.md

- interface/language/lang_constant.php
- interface/language/lang_definition.php
- interface/language/lang_language.php
- interface/language/lang_manage.php
- interface/language/language.php
Fixes #3107 
Added Bootstrap button style.
Changed table layout to Bootstrap form-group.
Removed outdated syntax.
> Fix #3107 mult language tool style

- CONTRIBUTING.md
- ci/phpcs.xml
some fixes for docker developer tools
> some fixes for docker developer tools

- interface/themes/core/navmenu.scss
Quick fixed css style background url
> Fix: css style background url

- src/RestControllers/FhirPatientRestController.php
- src/Services/FhirResourcesService.php
- src/Services/FhirValidationService.php
Fixes #3216 
Added Validate Function with Validation Service
> Added ValidationService

- .travis.yml
- contrib/util/docker/docker-compose.yml
> some misc dev stuff

- interface/modules/zend_modules/module/Application/src/Application/Listener/Listener.php
- interface/modules/zend_modules/module/Application/src/Application/Model/ApplicationTable.php
- interface/modules/zend_modules/module/Application/src/Application/Plugin/CommonPlugin.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
- interface/modules/zend_modules/module/Documents/src/Documents/Plugin/Documents.php
> Fixed : Deprecated Warinings

- .travis.yml
- CONTRIBUTING.md
- README.md
- composer.json
- composer.lock
- contrib/util/docker/docker-compose.yml
this will make dev's lives easier
> support standard use of --no-dev in composer

- interface/main/calendar/add_edit_event.php
> fix: add miss btn-group style

- phpfhir/providerPublishUI.php
- src/RestControllers/FhirPatientRestController.php
- src/RestControllers/FhirQuestionnaireResponseController.php
- src/RestControllers/PatientRestController.php
- src/Services/FhirQuestionnaireResponseService.php
- src/Services/FhirResourcesService.php
- src/Services/PatientService.php
- refactor dob to DOB
- make Publish test jig BS4
- start questionnaire response for PRO use
Fixes #3232
> some fhir work

- Documentation/help_files/configure_orders_help.php
- interface/billing/sl_eob_patient_note.php
- interface/forms/eye_mag/a_issue.php
- interface/forms/eye_mag/php/eye_mag_functions.php
- interface/forms/eye_mag/view.php
- interface/orders/procedure_provider_list.php
- interface/orders/types.php
- interface/orders/types_ajax.php
> fixes for fontawesome pencil icon

- interface/login/login.php
> Suggestion: using btn-group on action button can be confusing

- interface/billing/sl_eob_invoice.php
Fixes #3166
Adjusted the form table Bootstrap style.
Fixed close the dialog ```doClose()``` function error.
Updated javascript syntax to ES6 and added miss semicolon.
> Fix #3166 eob invoice bs4 updates

- interface/patient_tracker/patient_tracker.php
Fixes #
As seen below, not all form elements were styled in BS4 and for the 3rd column (datepicker) a table element was used:
Also, at some screen size, the form alignment would break:
With this commit, the whole form is integrated to BS4, maintaining the styling and responsive behaviour of the existing form:
While the form won't break at any screensize
-Integrating form to BS4, removing some inline styling and unnecessary or obsolete classes
-Replacing the "table" structure of the third column with BS4
-Fixing the responsive behaviour of the form
-Providing cohesion for all form elements
> Integrating the "Flow Board" form to Bootstrap 4

- interface/main/calendar/add_edit_event.php
Reverts openemr/openemr#3271
Fixes #3300 
`btn-group` shouldn't be here.
> Revert "fix: add miss btn-group style"

- src/Tabs/TabsWrapper.php
Current Behaviour: 
https://www.loom.com/share/fa5def06a3b34fc2bf4ff5740e3c9569
Expected Behaviour:
https://www.loom.com/share/08b019847ebb435aa05250dd3e1ccdaf
> Quick-fix: Only activate the latest tab

- interface/main/calendar/modules/PostCalendar/pntemplates/default/user/ajax_search.html
Changed to button tag.
Added FontAwesome icon.
> fix: change to button tag and add FontAwesome icon

- interface/orders/procedure_stats.php
Fixes #3233
Fixed the allignment of the form fields.
> Fixed-alignment

- CONTRIBUTING.md
Fixes #3308
Add new devtool alias for docker environment to contributing.md
> Add new dev tools alias to contibuting.md

- interface/main/messages/messages.php
Fixes #3314 
Updated the cancel button class to btn-secondary
-
-
-
> Updating message section

- interface/clickmap/template/general_new.html
- library/js/clickmap.js
Fixes #3003 
Removed jQuery-UI dialog.
Updated `clickmap.js` file syntax and indent.
Refine Graphic Pain Map page style
> Fix #3003 clickmap remove jquery ui

- interface/clickmap/template/general_new.html
Pain form currently shows buttons in the reporting output. This fixes that.
> pain form fixes

- sites/default/statement.inc.php
there was a blank page printing after the last statement printed
> suppress formfeed printing statements

- _rest_routes.inc.php
- src/RestControllers/FHIR/FhirPatientRestController.php
- src/Services/BaseService.php
- src/Services/FHIR/FhirPatientService.php
- src/Services/FacilityService.php
- src/Services/PatientService.php
- insert and update sql helpers ideas
- adding validation ideas
Not fully tested. Hope this may give some ideas. We can bring this in or you guys can take from it to work/add to your projects
There are alternatives to validation placement but this gets us closer.
> New services base class

- interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
- interface/modules/zend_modules/module/Installer/src/Installer/Model/InstModuleTable.php
- interface/modules/zend_modules/module/Installer/view/installer/installer/configure.phtml
- interface/modules/zend_modules/module/Installer/view/installer/installer/index.phtml
- interface/modules/zend_modules/public/js/installer/action.js
- allow config
- allow unregister
Backport
> From master 5.0.3 PR#3343

- interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
- interface/modules/zend_modules/module/Installer/src/Installer/Model/InstModuleTable.php
- interface/modules/zend_modules/module/Installer/view/installer/installer/configure.phtml
- interface/modules/zend_modules/module/Installer/view/installer/installer/index.phtml
- interface/modules/zend_modules/public/js/installer/action.js
- When a custom module is disabled a trash icon is presented.
- Clicking will unregister module ie remove ref from database.
This aids in cleanup
> Module Manager Updates

- src/RestControllers/PatientRestController.php
- src/RestControllers/RestControllerHelper.php
- src/Services/BaseService.php
- src/Services/FHIR/FhirPatientService.php
- src/Services/PatientService.php
> Fixed Validation in API

- library/dialog.js
- library/js/utility.js
- phpfhir/libs/controller/ClientAppController.php
- portal/add_edit_event_user.php
- portal/home.php
- portal/report/portal_custom_report.php
- portal/report/portal_patient_report.php
- add selectable promise resolves
- moved includeScript() function to utility.js
- removed deprecated synchronous file gets. replaced with async await script loads
- fixed some dependencies scope issues in portal
- fix recent overflow-y:auto removal causing content not contained in dialog body
at least for dialogs I know about. See method in source for clues.
fixes issue #3073
> dialog enhancements

- library/js/utility.js
> yet another attempt to get drag the way I want

- FHIR_README.md
Fixes #3357
This is only the beginning for FHIR, hopefully this sets the pace for further documentation.
> Create FHIR API guide

- interface/main/calendar/find_appt_popup.php
- interface/patient_file/history/encounters.php
Fixes #3341 
Added the Bootstrap button and font awesome icon.
Added the Bootstrap table and form style.
Replaced inline style to the Bootstrap class.
> Fix #3341: Add the Bootstrap style in available appointments

- src/Tabs/TabsWrapper.php
Fixes #3135 
This will allow fee-sheet tab to be open ones and does not affect the other tabs.
> multiple fee-sheet issue

- FHIR_README.md
- _rest_routes.inc.php
- src/RestControllers/FHIR/FhirConditionRestController.php
- src/Services/FHIR/FhirConditionService.php
Fixes #3346 
FHIR Condition Resource with GET methods
> FHIR Condition Resource

- sql/patch.sql
> add U07.1 to icd10_dx_order_code

- interface/patient_file/history/encounters.php
Fixes #2892
Fixed the form inner scrollbar.
Hi @bradymiller 
I am not careful to override #3352 PR, So I created a new PR. 
Please review it again, Thanks.
> fix #2892: form inner scrollbar

- sql/database.sql
> index typo

- FHIR_README.md
- _rest_routes.inc.php
- src/RestControllers/FHIR/FhirProcedureRestController.php
- src/Services/FHIR/FhirProcedureService.php
Fixes #3347
Fhir Procedure Resource with GET methods
> FHIR Procedure Resource

- interface/patient_file/encounter/forms.php
Fixes #3383 
Fixed Firefox button focus state style.
> Fix #3383 encounter summary dropdown

- interface/main/tabs/js/tabs_view_model.js
Fixes #3142 
If a tab is already Open then it tries to use it rather than reload it 😃 
https://www.open-emr.org/wiki/index.php/Development_Demo#Alpha_-_Up_For_Grabs_Demo
> Feature : Open Existing Tab

- controllers/C_Document.class.php
- custom/code_types.inc.php
- custom/qrda_functions.php
- interface/billing/ub04_dispose.php
- interface/eRx_xml.php
- interface/forms/CAMOS/content_parser.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- library/clinical_rules.php
- portal/lib/appsql.class.php
- portal/lib/portal_mail.inc
- portal/lib/portal_pnotes.inc
- src/Billing/BillingUtilities.php
- src/Billing/EDI_270.php
Fixes #3101
php8 Travis warnings
> [WIP] php 8 fun fix

- package-lock.json
- package.json
https://github.com/openemr/openemr/issues/3425
> revert jquery to version 3.4.1

- interface/language/lang_definition.php
- interface/login/login.php
- interface/super/edit_list.php
- library/options.inc.php
- library/translation.inc.php
- portal/account/register.php
- portal/index.php
discovered from [post on forum](https://community.open-emr.org/t/fatal-error-in-opening-patient-document-template-forms-in-newly-upgraded-5-0-2-1/14309/11?u=stephenwaite)
> time to remove skip_english_translation, not in globals anymore

- interface/usergroup/facility_user.php
- interface/usergroup/facility_user_admin.php
- interface/usergroup/usergroup_admin.php
- interface/weno/ajax_sample_code.php
- interface/weno/confirm.php
- library/custom_template/custom_template.php
- library/custom_template/personalize.php
- library/js/ajax_functions_writer.js
- library/js/utility.js
Fixes #3010 
A short video
https://www.loom.com/share/ee5520b8614a4f039a653d841d85dc97
> Remove jquery-ui part-5

- interface/forms/observation/new.php
> Query error

- src/RestControllers/FHIR/FhirAllergyIntoleranceRestController.php
- src/RestControllers/FHIR/FhirConditionRestController.php
- src/RestControllers/FHIR/FhirImmunizationRestController.php
- src/RestControllers/FHIR/FhirOrganizationRestController.php
- src/RestControllers/FHIR/FhirProcedureRestController.php
- src/Services/FHIR/FhirAllergyIntoleranceService.php
- src/Services/FHIR/FhirProcedureService.php
Validation Resource object was not initialized in a few Resources.
Fixed validation for 'searching with parameters'.
> FHIR Resources Validation fix

- interface/usergroup/facilities.php
- src/Services/FacilityService.php
Fixes #3437 
https://github.com/openemr/openemr/issues/3437#issuecomment-620604599
> Quick Fix : FacilityService Update Query

- sql/patch.sql
still need to do thorough testing
> Fix for patch 2 sql changes in older mysql/mariadb versions

- FHIR_README.md
- _rest_routes.inc.php
- src/RestControllers/FHIR/FhirMedicationRestController.php
- src/Services/FHIR/FhirMedicationService.php
FHIR Medication Resource - GET methods
> FHIR Medication Resource

- FHIR_README.md
- _rest_routes.inc.php
- src/RestControllers/FHIR/FhirMedicationStatementRestController.php
- src/Services/FHIR/FhirMedicationStatementService.php
FHIR MedicationStatement Resource - GET methods
> FHIR MedicationStatement Resource

- FHIR_README.md
I think I forgot to do this in my Observation Resource PR.
> Quick Update : FHIR README

- interface/new/new_comprehensive.php
Fix #3458
Change button color and layout.
> Fix #3458: change button layout

- API_README.md
- _rest_config.php
- src/RestControllers/AuthRestController.php
- src/Services/EncounterService.php
fixes https://github.com/openemr/openemr/issues/3474
testing well
includes following fixes:
1. allows downstream acl checks in api calls
2. minor doc fix
3. fixes encounters to map to correct place for eid
> api fix for downstream acl checks

- interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
Hi @bradymiller 
Here 2 minor fixes to completion the feature of install and upgrade of zend modules.
Thanks
Amiel
> updarde sql modules - last fixes

- setup.php
Fix #3414
Added highlight config.
Added bottom-margin in the login info page.
> Feat #3414: add highlight config

- .github/ISSUE_TEMPLATE/bug_report.md
I think adding the OpenEMR version to the issue template will help users to solve their problems.
> docs: update github issue template

- portal/get_patient_info.php
just reverted a small part of code from the recent RTL PR
> minor portal fix to keep portal auth/session stuff away from core openemr

- ccr/uuid.php
ccr/uuid.php cleanup, testing fine, you can view page source to see the uuids, or download the ccr
> another place to use ramsey

- tests/Tests/Fixtures/FixtureManagerTest.php
- tests/Tests/Validators/ProcessingResultTest.php
> fix typos for composer deprecation notices

- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
Fixes #3502
fixes refresh of session patient
this gets subsequent same day appts but not first, so need a little more work
> refresh add event to get dashboard pt

- interface/forms/newpatient/common.php
- interface/forms/newpatient/save.php
- interface/patient_file/encounter/forms.php
- library/ajax/facility_ajax_code.php
- library/encounter_events.inc.php
- set POS for appointment auto encounter
Working #3449
Up for Grabs demo for this PR is here: https://www.open-emr.org/wiki/index.php/Development_Demo#Alpha_-_Up_For_Grabs_Demo
> Encounter updates

- library/classes/Installer.class.php
> proposed mariadb 10.4+ fix

- .travis.yml
- API_README.md
- FHIR_README.md
- _rest_config.php
- _rest_routes.inc.php
- apis/dispatch.php
- docker-compose.yml
- interface/usergroup/mfa_totp.php
- library/ESign/Encounter/Controller.php
- library/ESign/Form/Controller.php
- library/auth.inc
- library/globals.inc.php
- sql/5_0_2-to-5_0_3_upgrade.sql
- sql/database.sql
- src/Common/Auth/AuthUtils.php
- src/Events/RestApiExtend/RestApiCreateEvent.php
- src/RestControllers/AuthRestController.php
- version.php
Appears to be working, but still some more testing to do
> Add patient portal rest api

- Documentation/help_files/openemr_installation_help.php
- Documentation/help_files/openemr_multisite_admin_help.php
- admin.php
- portal/patient/templates/_ProviderHeader.tpl.php
- portal/patient/templates/_modalFormHeader.tpl.php
- setup.php
I noted the spinner pulse fontawesome icon was not working in setup.php since need to update the new fontawesome 5 path. Also updated this on the other places where it is needed.
> fontawesome fixes

- sql/5_0_2-to-5_0_3_upgrade.sql
- sql/database.sql
Going to take a shot at this.
@dixonwhitmire @rhausam @yashrajbothra @bradymiller 
Swiped these tables from my local Hapi server. 
I hope nobody gets to concerned with using foreign keys. At some point we should be using the power that is relational. I don't understand why its taken this long unless our sql apis get disgruntled. 
I think this is enough to get us where we need to be. Let me know if i'm missing something important.
Fixes #2767 
FHIR resource support
Add tables and indexes and foriegn keys
> Add FHIR resource tables

- interface/globals.php
- interface/modules/zend_modules/config/autoload/global.php
- library/patient.inc
- library/sql_upgrade_fx.php
- sql/5_0_2-to-5_0_3_upgrade.sql
- sql/database.sql
- src/Common/Uuid/UuidRegistry.php
- src/Services/BaseService.php
- src/Services/PatientService.php
- tests/Tests/Fixtures/FixtureManager.php
- version.php
Adds main mechanism for supporting/tracking uuid. Used the mechanism to add uuid support to patient_data table. Still need to test the upgrade mechanism.
Built from prior PRs:
https://github.com/openemr/openemr/pull/2360
https://github.com/openemr/openemr/pull/2574
Fixes issue:
https://github.com/openemr/openemr/issues/2277
Also fixed double escaping in BaseService class
Also fixes some php notices that were showing up on automated testing
> uuid registry support and added uuid to patient_data

- src/Pharmacy/Services/ImportPharmacies.php
from rel-502 to master, jerry would appreciate :)
https://github.com/openemr/openemr/commit/4a6b8b651b46af495bdb46408d5ee2e276e5ad36
> oehttp typo

- .stylelintrc.json
- config/config.yaml
- gulpfile.js
- interface/themes/color_base.scss
- interface/themes/core/FontAwesome.scss
- interface/themes/oe-styles/style_dark.scss
- interface/themes/oe-styles/style_light.scss
- interface/themes/oe-styles/style_manila.scss
- interface/themes/oe-styles/style_superhero.scss
- interface/themes/patientportal-style.scss
Fixes #3539
Imports Font Awesome into the SCSS/SASS that we have.
> Import FontAwesome into SCSS/SASS (#3539)

- interface/billing/billing_report.php
- interface/orders/gen_hl7_order.inc.php
- interface/reports/collections_report.php
- interface/reports/insurance_allocation_report.php
- library/daysheet.inc.php
- library/patient.inc
- library/report.inc
- src/Billing/BillingReport.php
- src/Billing/BillingUtilities.php
- src/Billing/Claim.php
- src/Billing/SLEOB.php
Related to following project: https://github.com/openemr/openemr/issues/3378
> ensure null date used in codebase for insert/update date in insurance_data table

- sql/5_0_2-to-5_0_3_upgrade.sql
- sql/database.sql
This will improve performance. Part of this issue:
https://github.com/openemr/openemr/issues/3546
> use char(36) for uuid columns

- sql/5_0_2-to-5_0_3_upgrade.sql
- sql/database.sql
- src/Common/Uuid/UuidRegistry.php
> storing uuid in byte format rather than string format

- interface/themes/color_base.scss
- interface/themes/oe-styles/style_dark.scss
- interface/themes/oe-styles/style_light.scss
- interface/themes/oe-styles/style_manila.scss
- interface/themes/oe-styles/style_superhero.scss
- interface/themes/patientportal-style.scss
Fixes #3554
Resolves Font Awesome paths issue
> Fix Font Awesome Paths (#3554)

- interface/patient_file/summary/demographics.php
- library/patient.inc
- sql/5_0_2-to-5_0_3_upgrade.sql
- version.php
> change to null date for subscriber_dob

- library/sql_upgrade_fx.php
- sql/5_0_2-to-5_0_3_upgrade.sql
- src/Common/Uuid/UuidRegistry.php
- version.php
Still testing
@stephenwaite , added another "clearing" of the insurance_data date field because of the time gap in the database changes and codebase changes.
> upgrade fixes and minor changes in uuid documentation

- src/RestControllers/FHIR/FhirPatientRestController.php
- src/Services/FHIR/FhirResourcesService.php
fixing my boo boo
Sure would've been nice someone reminded me RestConfig was a singleton! Don't know who did that!!
Wanted to get this in quick for others...
> correct include path

- src/Services/FHIR/FhirPatientService.php
- country_code not set as data key for update query builder.
- some nitpicking
> FhirPatientService minor bug

- .travis.yml
- _rest_routes.inc.php
- sql/5_0_2-to-5_0_3_upgrade.sql
- sql/database.sql
- src/RestControllers/AuthRestController.php
- version.php
1. Add travis testing for common
2. Get portalfhir call working
3. Optimize database to ensure good performance of api
4. Remove tokens that have been expired more than 1 day
> add common test to travis and get the portalfhir call working

- library/clinical_rules.php
- library/reminders.php
- src/RestControllers/AuthRestController.php
- fix a misspelling in param
- some tuning
- delete an invalid foreach in reminders
Fixes #3550
> Clinic Rules and Reminders

- interface/forms/newpatient/common.php
- interface/forms/newpatient/save.php
- only show active authorized user in pull down
- fix POS setting disabled control
- allow non providers to save by reasoning they already have permissions.
> v5.0.3 encounter bug fix issue #3449

- interface/forms/newpatient/common.php
- interface/forms/newpatient/save.php
- only show active authorized user in pull down
- fix POS setting disabled control
- allow non providers to save by reasoning they already have permissions.
Fixes #3449
> encounter bug fix issue #3449

- interface/forms/eye_mag/help.php
- interface/usergroup/facilities_add.php
Fixes #3527
Removed the jQuery-UI.
Changed to the Bootstrap UI components.
Removed outdated code, unnecessary code, and inline-style.
> Refactor #3527: remove jquery-ui and change to bootstrap components ui

- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pnuserapi.php
- interface/themes/ajax_calendar_sass.scss
- content wrongly escaped breaking recurring icon
- fix new events not showing on facilities that don't have a provider assigned
- minor styling top margins
Fixes #3551
> Calendar Fix

- interface/forms/newpatient/common.php
- interface/patient_file/history/encounters.php
- interface/super/edit_list.php
- Replace nbsp with unknown
- fixup encounter where non-auth creator is reflected in provider list.
- add BS alert to Lists for dup lists
- fix broken delete in List
> pay it forward from 5.0.2 PR #3576

- interface/forms/newpatient/common.php
- interface/patient_file/history/encounters.php
- interface/super/edit_list.php
Fixes #3565
- Replace nbsp with unknown
- fixup encounter where non-auth creator is reflected in provider list.
- add BS alert to Lists for dup lists
> Encounter history issue #3565

- interface/themes/patientportal-style.scss
- portal/home.php
- limit sidebar width
Fixes #3538
sidebar was using entire viewport causing overlapping
> portal issue #3538

- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pnuserapi.php
- library/translation.inc.php
- portal/patient/libs/Controller/PatientController.php
- portal/patient/libs/Controller/PortalPatientController.php
- portal/patient/scripts/app.js
- fix translations array error(from 503)
- another array issue with Boolean
- pass full exception trace to user on fails.
Fixes forum issue
https://community.open-emr.org/t/how-to-connect-wordpress-with-openemr/8937/43?u=sjpadgett
> onsite portal PHP 7.4 update

- portal/patient/libs/Controller/PatientController.php
- portal/patient/libs/Controller/PortalPatientController.php
> 503-portal-php74

- interface/main/tabs/js/include_opener.js
- interface/patient_file/report/patient_report.php
- library/dialog.js
- sometime in 502 dev window positions changed. rippled to frames
Fixes # https://community.open-emr.org/t/loss-of-convenient-features/14557/15?u=sjpadgett
Calendar in frames add/edit events dialog was breaking due to windows hierarchy changed in 502.
Calendar is now a top as far as frames dialog is concerned. Nothing to do with PHP 7.4
Fix Patient Report select checks.
> 502 frames calendar event edit/create fix

- library/globals.inc.php
- version.php
This seems reasonable to turn on by default. Thoughts?
> expand encounter forms by default

- CONTRIBUTING.md
- docker-compose.yml
Added support for xdebug and profiling for the openemr easy development docker
> Easy dev xdebug profiler

- ccdaservice/README.md
- docker-compose.yml
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Form/ModuleconfigForm.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/Configuration.php
- library/globals.inc.php
@sjpadgett , dropped the mirth option for ccda creation. Testing well. See any obvious issues with this?
> CCDA creation mechanism update

- interface/patient_file/encounter/find_code_dynamic.php
- Change to the Bootstrap datatables and button style.
- Remove outdated code.
Before:
After:
> feat: add the bootstrap style and remove outdated code

- interface/patient_file/summary/demographics.php
fix for PHP Warning:  session_start(): Cannot start session when headers already sent. Session vars need to be set before any html output when using the special setSession function to avoid this.
This is a quick fix and solves the issue.
> fix for PHP Warning:  session_start():

- portal/index.php
> Portal reset password changes

- interface/forms/newpatient/common.php
- interface/forms/newpatient/save.php
> Add Support to Encounter Class UI

- interface/globals.php
- interface/main/tabs/main.php
- interface/patient_file/history/encounters.php
- interface/patient_file/summary/clinical_reminders_fragment.php
- interface/patient_file/summary/demographics.php
- interface/patient_file/summary/disc_fragment.php
- interface/patient_file/summary/labdata_fragment.php
- interface/patient_file/summary/lbf_fragment.php
- interface/patient_file/summary/patient_reminders_fragment.php
- interface/patient_file/summary/pnotes_fragment.php
- interface/patient_file/summary/pnotes_full.php
- interface/patient_file/summary/stats.php
- interface/patient_file/summary/vitals_fragment.php
- library/clinical_rules.php
- library/pid.inc
- src/Common/Session/SessionUtil.php
- mostly backport of lessons learn in 5.0.3 profiling
- inverse strategy
The main focus is to improve patient chart/demographic loading times.
According to profiling this is a marked improvement.
> v5.0.2 Profile Tuning

- templates/documents/general_upload.html
Fixes #3609
- Fixes bug where mime type blocked message isn't displayed correctly.
PR Ready to merge now
> Rel 5.0.2: Fix Mime Type Blocked Error Placement (#3609)

- ippf_upgrade.php
Fixes #3603 
Add the Bootstrap style.
Remove outdated code.
> Refactor #3603: refine ippf_upgrade page

- library/options_listadd.inc
Fixes #3632
Modernizes options_listadd.inc to BS4 standards.
Ready to merge.
> Modernize options_listadd.inc (#3632)

- interface/forms/fee_sheet/new.php
- interface/usergroup/user_admin.php
- interface/usergroup/usergroup_admin.php
- interface/usergroup/usergroup_admin_add.php
- sql/5_0_2-to-6_0_0_upgrade.sql
- sql/database.sql
- version.php
Fixes #
- need to select what users may appear for portal
- add a supervisor for user.
- feesheet add supervisor default to rendering providers supervisor
> Add portal flag and supervisor to users

- interface/forms/fee_sheet/new.php
- interface/main/tabs/main.php
- interface/usergroup/user_admin.php
- interface/usergroup/usergroup_admin.php
- interface/usergroup/usergroup_admin_add.php
- sql/database.sql
- sql/patch.sql
- version.php
- feesheet select default supervisor from rendering provider supervisor.
>  Portal flag and supervisor add to users

- interface/themes/colors/openemr5/login.scss
- interface/themes/login_page.scss
Fixes #
Resolves the plain look of the front landing page. We are busy modernizing the back end. The front end can use a little TLC. This little bit of CSS can go along way towards the initial impression of the software, in my humble opinion. 
-
-
-
> First impression, update the look of the landing page

- interface/main/calendar/modules/PostCalendar/common.api.php
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
> fixes in calendar setsession call, fixes #3660

- interface/billing/edit_payment.php
- interface/billing/era_payments.php
- interface/billing/new_payment.php
- interface/billing/payment_master.inc.php
- interface/billing/payment_pat_sel.inc.php
- interface/billing/search_payments.php
- library/dialog.js
- library/payment_jav.inc.php
- mainly wrong action buttons presented in edit payments
- leading to fixing styles to be useable
- removed modal and replaced back dialog. There's a reason we have dialog!
Fixes #3621
Still trying to figure that out!
-
-
> Batch Payments bug fixes

- _rest_routes.inc.php
Basically leveraging @yashrajbothra 's very nice api/fhir work for the patient portal api endpoints :)
(still gotta do some testing)
> added encounter endpoints to patient portal api

- DOCKER_README.md
- README.md
- docker/README.md
- docker/docker-compose.yml
> added docker documentation

- library/sql_upgrade_fx.php
- sql/5_0_2-to-6_0_0_upgrade.sql
- sql/database.sql
- src/Common/Uuid/UuidRegistry.php
- version.php
@yashrajbothra , Here's the mechanism for supporting resource ids in vertical tables, which applied to the facility_user_ids table. Testing well so far.
> Added support for uuid to vertical tables

- tests/Tests/Fixtures/FacilityFixtureManager.php
- tests/Tests/Fixtures/facility.json
- tests/Tests/Services/FacilityServiceTest.php
quick fix
will bring in if pass travis
> facility testing fix

- interface/main/backup.php
> add hex-blob setting to mysqldump in backup.php

- sql/5_0_2-to-6_0_0_upgrade.sql
> missed code 144 on upgrade

- tests/Tests/Fixtures/PractitionerFixtureManager.php
- tests/Tests/Fixtures/practitioners.json
Fixes #
Just Changed prefix from `test-prefix` to `-` as string can't be added to id but `-` could be :)
> Fixed removeFixture for Practioner

- interface/main/dated_reminders/dated_reminders.php
- interface/main/dated_reminders/dated_reminders_add.php
- interface/main/dated_reminders/dated_reminders_log.php
- interface/main/finder/multi_patients_finder.php
- interface/main/messages/messages.php
- Remove the nested grid system.
- Remove outdated and unnecessary code.
- Adjust the form-group style.
- Fix the form and table responsive overflow issue.
- Fix the button style and broken icon.
> Refactor: refine the message section pages

- interface/billing/edit_payment.php
- interface/billing/new_payment.php
- interface/billing/payment_master.inc.php
- interface/billing/payment_pat_sel.inc.php
- interface/billing/search_payments.php
- library/dialog.js
- library/payment_jav.inc.php
- add dialog full width
- add back full screen dialog for search payments id, date, insurance radios.click
- still use modal for rest
- fix remainder bug
- fix missing brace causing big portion of edit script to not run
- add Global account amount charge off to Payment history
Fixes numerous Forum issues!
Major bugs causing much user shagrin!
> Batch Payments bug fixes v5.0.2

- interface/forms/misc_billing_options/new.php
- interface/forms/misc_billing_options/save.php
- interface/language/lang_constant.php
- interface/language/lang_definition.php
- interface/language/lang_language.php
- interface/language/lang_manage.php
- interface/language/language.php
- interface/main/messages/save.php
- interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
- interface/modules/zend_modules/module/Multipledb/src/Multipledb/Controller/MultipledbController.php
- interface/reports/appointments_report.php
- interface/usergroup/ssl_certificates_admin.php
- library/group.inc
- tests/eventdispatcher/PatientFilterEventHookTest/acl/acl_setup.php
- tests/eventdispatcher/PatientFilterEventHookTest/acl/acl_upgrade.php
> some session work mostly involving unset and some code simplification

- FHIR_README.md
- _rest_routes.inc.php
- src/RestControllers/FHIR/FhirPractitionerRoleRestController.php
- src/Services/FHIR/FhirPractitionerRoleService.php
- src/Services/PractitionerRoleService.php
- src/Validators/PractitionerRoleValidator.php
- Added FHIR GET Endpoint 
- Updated Documentation
> Added FHIR Endpoints for PractitionerRole

- contrib/forms/assessment_intake/view.php
- contrib/forms/contacts/new.php
- contrib/forms/contacts/view.php
- contrib/forms/evaluation/templates/evaluation/general_new.html
- contrib/forms/hearingtest/new.php
- contrib/forms/hearingtest/view.php
- contrib/forms/obstetrical/new.php
- contrib/forms/obstetrical/view.php
- contrib/forms/pain/new.php
- contrib/forms/pain/view.php
- contrib/forms/vision/new.php
- contrib/forms/vision/view.php
- interface/forms/ankleinjury/new.php
- interface/forms/ankleinjury/view.php
- interface/forms/bronchitis/new.php
- interface/forms/bronchitis/view.php
- interface/forms/note/view.php
- interface/patient_file/summary/demographics_full.php
- interface/patient_file/summary/record_disclosure.php
- interface/usergroup/facilities_add.php
- interface/usergroup/facility_admin.php
- interface/usergroup/user_admin.php
- interface/usergroup/usergroup_admin_add.php
According to this comment replace the input type entry with text.
https://github.com/openemr/openemr/pull/3701#discussion_r448060140
> Fix: remove invalid code syntax.

- interface/patient_file/reminder/patient_reminders.php
- interface/patient_file/summary/demographics_full.php
- src/Menu/PatientMenuRole.php
Fixes #
Adjust buttons icon to follow the styling guide.
> Feat: adjust buttons icon

- API_README.md
- FHIR_README.md
- _rest_routes.inc.php
- interface/patient_file/summary/immunizations.php
- sql/5_0_2-to-6_0_0_upgrade.sql
- sql/database.sql
- src/Common/Uuid/UuidRegistry.php
- src/RestControllers/FHIR/FhirImmunizationRestController.php
- src/RestControllers/ImmunizationRestController.php
- src/Services/FHIR/FhirImmunizationService.php
- src/Services/ImmunizationService.php
- src/Validators/ImmunizationValidator.php
Upgrading FHIR Immunization Resource with New Standard Endpoints 
- Upgraded SEARCH Capabilities
> Immuniazation Resource

- library/classes/Installer.class.php
Fixes issue #3741 where sqlconf.php is modified but the old one remains in the opcache.
> Fix #3741 Setup fails on setting up access controls

- interface/patient_file/encounter/find_code_dynamic.php
Fixes #3734 
Add override CSS to fix multiple arrow issue
> Fix #3734: add override css to fix multiple arrow issue

- CONTRIBUTING.md
Fixes # add openemr-cmd tool link
-
-
-
> add openemr-cmd tool link

- controllers/C_Document.class.php
- interface/main/tabs/menu/menus/standard.json
- portal/patient/fwk/libs/verysimple/Phreeze/Criteria.php
- more controller zip stuff
- add viewer to menu
> Dicom viewer update

- controllers/C_Document.class.php
- library/js/dwv/dicom_launcher.js
- more folder and zip validation
- use up to date decoders
> dicom viewer take 3

- templates/prescription/general_edit.html
- templates/prescription/general_list.html
Refine the prescription list and prescription add pages
Remove outdated code and style.
Add the Bootstrap grid system, form, and table style.
Adjust the color and icon of the buttons to follow the styling guide.
> Refactor: refine the prescription list and prescription add pages

- interface/reports/receipts_by_method_report.php
- src/Services/InsuranceCompanyService.php
adds payer name to report
also adds new method to insco service
> set insco name in Reports-Financial-Payment Method, add getOne method to insco service

- interface/patient_file/summary/add_edit_amendments.php
- interface/patient_file/summary/demographics.php
- interface/patient_file/summary/list_amendments.php
Refine the amendments add and edit page.
Add the bootstrap grid system.
Add the bootstrap table and form style.
Remove outdated code and style.
> Refactor: refine the amendments add and edit page.

- library/classes/Installer.class.php
- setup.php
Refine the setup page.
Fixes #
Remove outdated code and inline-style.
Adjust the Bootstrap grid and button style.
> feat: refine the setup page.

- sql/5_0_2-to-6_0_0_upgrade.sql
- sql/database.sql
- src/Common/Uuid/UuidRegistry.php
- version.php
@yashrajbothra , This will support flexible 'id' columns (for procedure stuff). Testing well so far. Gonna bring this in after some more testing (probably bring in this evening).
> support flexible sql id column names in uuid registry

- interface/super/edit_layout.php
Fixes #3778
Change the add field max length to 63
> Fix #3778: change the add field max length to 63

- library/deletedrug.php
Fixes #
Update to the feature to remove the medication from the medication list also. 
- remove medication from the medication list at the same time as from the prescription list.
-
-
> Need to remove drug from the patient medication list also.

- interface/patient_file/summary/immunizations.php
Refine the dashboard immunizations page.
Fixes #3737
Remove outdated code and inline-style.
Convert table layout to Bootstrap form-group style.
> Refactor #3737: refine dashboard immunizations page

- interface/reports/pat_ledger.php
> typo in credits query

- .travis.yml
> nginx chromium bump php7.2

- interface/main/tabs/templates/patient_data_template.php
- interface/super/edit_layout.php
- library/ajax/dated_reminders_counter.php
- library/dated_reminder_functions.php
- library/dialog.js
- portal/account/account.lib.php
- portal/account/account.php
- portal/account/register.php
- portal/home.php
- portal/patient/libs/Controller/PatientController.php
- portal/patient/scripts/app/patientdata.js
- portal/patient/templates/PatientListView.tpl.php
- from layouts UOR = unused and/or new Exclude in Portal edit option
Allows users to select if demographic items from DEM layout are excluded in Portal Profile
and yes I relented. only took four years!
Add new Exclude in Portal edit option to super layouts
Honor UOR unused option
> Allow items exclude in Portal Profile

- portal/messaging/messages.php
- portal/patient/libs/Model/DAO/UserCriteriaDAO.php
- portal/patient/libs/Model/DAO/UserDAO.php
- portal/patient/libs/Model/DAO/UserMap.php
- portal/patient/libs/Reporter/UserReporter.php
- portal/patient/scripts/app/onsiteactivityviews.js
- portal/patient/scripts/app/patientdata.js
- portal/patient/scripts/model.js
- portal/patient/templates/ProviderHome.tpl.php
- new in Users a flag to allow users w/o the authorization flag to still receive portal patients.
- UI adjustments
Allow non auth providers to be selected in portal by setting portal user flag in Users.
Many times a provider will have someone else screening portal transactions, This will get us a step closer to this.
> Support new Users portal authorization flag

- interface/main/tabs/templates/patient_data_template.php
Fixes #3804
Change the visit history icon.
> feat #3804: change visit history icon.

- library/ajax/prescription_drugname_lookup.php
- library/deletedrug.php
- templates/prescription/general_edit.html
- templates/prescription/general_list.html
- templates/prescription/general_lookup.html
Some critical drug name fixes in this PR:
1. When re-editing a drug, the drug name was not populating
2. When select a drug name from drugs table, it was getting a value of 0 (rather than the drug name), thus essentially set to nothing
3. When use the search for a drug, it was not populating the drug name, when select it
> couple drug name fixes

- templates/prescription/general_edit.html
fix to populate drug name when select from in house selector
> another rx fix

- API_README.md
- FHIR_README.md
- _rest_routes.inc.php
- sql/5_0_2-to-6_0_0_upgrade.sql
- sql/database.sql
- src/RestControllers/DrugRestController.php
- src/RestControllers/FHIR/FhirMedicationRestController.php
- src/Services/AllergyIntoleranceService.php
- src/Services/BaseService.php
- src/Services/ConditionService.php
- src/Services/DrugService.php
- src/Services/FHIR/FhirMedicationService.php
Added New Drug Endpoint and Upgraded Existing FHIRMedication Resource
-
-
-
> Upgraded Medication Resource

- interface/super/edit_layout.php
- interface/themes/theme-defaults.scss
Partial fix for:
https://github.com/openemr/openemr/issues/3810
> edit layout fixes (sticky menu and showing filter stuff)

- interface/patient_file/transaction/record_request.php
Refine the patient records request.
- Remove outdated code.
- Adjust the Bootstrap style.
> refactor: refine the patient records request.

- interface/super/edit_globals.php
> obfuscate sensitive fields in edit globals ui

- interface/modules/zend_modules/module/Installer/src/Installer/Model/InstModuleTable.php
Fixes # can't run triggers , and SQL with ; 
extend the ability to run SQL that contain ; in module install.sql
> Add support for special sql in module install script

- ccr/display.php
- composer.json
- composer.lock
- controllers/C_Document.class.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncountermanagerTable.php
- interface/modules/zend_modules/module/Documents/src/Documents/Plugin/Documents.php
- interface/patient_file/deleter.php
- interface/super/edit_globals.php
- library/ajax/ccr_import_ajax.php
- library/classes/CouchDB.class.php
- library/classes/Document.class.php
- library/classes/thumbnail/ThumbnailGenerator.php
- sql/5_0_2-to-6_0_0_upgrade.sql
- sql/database.sql
- src/Common/Uuid/UuidRegistry.php
- version.php
next on the agenda after this is to:
1. fix up the thumbnails module to work with encryption (pretty sure it is broken by just reading the code)
2. finish up https://github.com/openemr/openemr/issues/2181
TODO:
update composer lock
> couchdb updates

- interface/patient_file/deleter.php
- interface/patient_file/encounter/delete_form.php
- interface/patient_file/encounter/forms.php
Refine the encounter delete form page and modal.
- Remove outdated code and inline-style.
- Adjust the bootstrap form and button style.
> Refactor: refine the encounter delete form page and modal.

- interface/patient_tracker/patient_tracker_status.php
Adjust the flow board appt status button style.
Fixes #
- Adjust the button style.
- Remove outdated code.
> fix: adjust the flow board appt status button style.

- API_README.md
- FHIR_README.md
- _rest_routes.inc.php
- src/RestControllers/FHIR/FhirLocationRestController.php
- src/Services/FHIR/FhirLocationService.php
- src/Services/LocationService.php
- src/Validators/BaseValidator.php
Added new endpoints for location resource
-
-
-
> All New FHIR Location Resource 

- portal/messaging/handle_note.php
> fix output before header

- interface/orders/order_manifest.php
- interface/orders/single_order_results.inc.php
Refine the procedure order on the summary page.
Fixes #
- Remove outdated code and inline-style.
- Add the bootstrap table style, and responsive.
> refactor: refine the procedure order on summary page.

- CONTRIBUTING.md
Fixes #  add monitor and portainer link in doc
-
-
-
> add monitor and portainer link in doc

- library/MedEx/API.php
Refine the MedEx setup and register page.
Fixes #3695
Refine the MedEx setup and register page.
Remove outdated code.
Before:
---
After:
> Fix #3695: refine the MedEx setup and register page

- interface/patient_file/ccr_import.php
- interface/patient_file/ccr_pending_approval.php
Refine the import section page.
- Remove outdated code and style.
- Adjust the bootstrap grid system.
- Fix the CCR approval form onsubmit the wrong quote.
> Refactor: refine the import section page.

- interface/globals.php
- interface/login/login.php
- interface/themes/login_page.scss
- library/globals.inc.php
Fixes #3742 
Allows customization of the login page to be whatever direction you want it to be.
https://www.open-emr.org/wiki/index.php/Development_Demo#Delta_-_Up_For_Grabs_Demo
> Fix Login Page (#3742)

- contrib/util/docker/README.md
add monitor portainer link to insane doc
Fixes #
-
-
-
> add monitor portainer link to insane doc

- interface/forms/care_plan/report.php
- interface/forms/eye_mag/report.php
- interface/forms/functional_cognitive_status/report.php
- interface/forms/group_attendance/report.php
- interface/forms/observation/report.php
- interface/forms/vitals/report.php
- interface/patient_file/report/patient_report.php
- library/dialog.js
- portal/home.php
- portal/report/pat_ledger.php
- portal/report/portal_custom_report.php
- portal/report/portal_patient_report.php
- implement portal-user user for acl.
- more encounter reports globals path issues
- portal custom report to iframe
- fix patient reports issue/encounter selects
- patch out eye mag from custom report. forms report broken!
- remove dialog for custom report in portal
- alert in ledger
- dialog tuning
> 502 portal custom report

- interface/forms/fee_sheet/new.php
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day_print/outlook_ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month_print/outlook_ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week_print/outlook_ajax_template.html
- interface/orders/list_reports.php
According to this comment https://github.com/openemr/openemr/pull/3876#discussion_r475091948, So in this PR, I converted the `<strike>` tag to the `<s>` tag.
Fixes #
Convert the `<strike>` tag to the `<s>` tag.
> feat: convert the strike tag to s tag.

- interface/usergroup/usergroup_admin.php
- src/Events/Facility/FacilityCreatedEvent.php
- src/Events/Facility/FacilityUpdatedEvent.php
- src/Events/User/UserCreatedEvent.php
- src/Events/User/UserUpdatedEvent.php
- src/Services/FacilityService.php
Fixes #
Adds events and hooks to add module code when a user is created or update, and when a facility is created or updated.
-
-
-
> Added Events and hooks for create and update facilities and users

- interface/themes/colors/utilities/batch-payments.scss
- interface/themes/colors/utilities/bootstrap-nav-menu.scss
- interface/themes/colors/utilities/bootstrap.scss
- interface/themes/colors/utilities/default_variables.scss
- interface/themes/colors/utilities/tabs-full.scss
Fixes #3898
This fixes the text color not being set right in colored themes. This also starts the process of consolidating the colored theme code.
@bradymiller This fix can be immediately merged
> Fix Color Themes Bug (#3898)

- .travis.yml
- _rest_config.php
- _rest_routes.inc.php
- apis/dispatch.php
- library/globals.inc.php
- sql/5_0_2-to-6_0_0_upgrade.sql
- sql/database.sql
- src/RestControllers/AuthRestController.php
- version.php
work in progress
@sjpadgett , What are your thoughts on this mechanism? Just trying to get something in place that essentially logs all api stuff.
> api logging proposal

- interface/globals.php
- interface/main/calendar/includes/pnAPI.php
- interface/modules/zend_modules/config/autoload/global.php
- library/globals.inc.php
- library/sql.inc
- portal/patient/fwk/libs/verysimple/DB/DataDriver/MySQLi.php
- sql_upgrade.php
- src/Common/Database/Connector.php
- src/Gacl/Gacl.php
Related to Issue: https://github.com/openemr/openemr/issues/3904
Still testing and more of a demonstration of what needs to be done to turn this on and off globally.
outcome:
Testing well and have decided to offer the option.
> added option to turn on/off database connection pooling

- contrib/util/docker/docker-compose.yml
- docker-compose.yml
fixes issue with easy dev environment
> dev fix for couchdb

- contrib/util/docker/docker-compose.yml
- docker-compose.yml
ldap docker fixes for dev environments
> dev ldap fixes

- CONTRIBUTING.md
- contrib/util/docker/README.md
> add env-installer tool link

- library/sql_upgrade_fx.php
- sql/5_0_2-to-6_0_0_upgrade.sql
- sql_upgrade.php
> support readable output when run sql upgrade as commandline and a quick sql upgrade fix

- interface/patient_file/encounter/select_codes.php
> mimic onclick handler for mouseover of codes

- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
- interface/reports/clinical_reports.php
- library/classes/Controller.class.php
- library/options.inc.php
> more php8 fixes

- interface/forms/LBF/new.php
- interface/forms/LBF/printable.php
- interface/forms/LBF/report.php
- interface/patient_file/encounter/view_form.php
- interface/patient_file/history/history_save.php
- library/options.js.php
- portal/get_patient_info.php
- portal/get_profile.php
- portal/import_template_ui.php
- portal/lib/doc_lib.php
- portal/lib/download_template.php
- portal/lib/template_menu.php
- portal/patient/scripts/app/onsiteactivityviews.js
- portal/patient/scripts/app/onsitedocuments.js
- portal/patient/scripts/app/onsiteportalactivities.js
- portal/patient/scripts/view.js
- portal/patient/templates/OnsiteDocumentListView.tpl.php
- portal/sign/assets/signer_api.js
- portal/sign/assets/signer_modal.php
- sites/default/documents/onsite_portal_documents/templates/Medical_History.tpl
See forum where i've made many comments: https://community.open-emr.org/t/implementation-of-lbf-visit-forms-in-onsite-portal/15225
Mostly add LBF forms to portal. Did some work in dashboard template manager via style and moved editor to full dialog.
Next is move to v6
> Portal support for LBF template engine

- interface/super/edit_globals.php
Refine Administration global page.
Fixes #
- Adjust the save button's color to `btn-primary`.
- Add missing input backslash.
- Add the `sticky-top` to fixed the left side menu.
> Refine Administration global page

- interface/new/new_comprehensive.php
- interface/patient_file/history/history.php
- interface/patient_file/history/history_full.php
- interface/patient_file/report/patient_report.php
- interface/patient_file/summary/add_edit_amendments.php
- interface/patient_file/summary/demographics_full.php
- interface/patient_file/summary/disclosure_full.php
- interface/patient_tracker/patient_tracker.php
- interface/super/edit_globals.php
- library/clinical_rules.php
- library/globals.inc.php
- library/options.inc.php
- library/patient.inc
php8 fixes and a couple other misc fixes
> php8 fixes and a couple other misc fixes

- library/standard_tables_capture.inc
rxnorm import restored
add a condition for icd10
> restore non-ICD10 unzip like for rxnorm

- .github/PULL_REQUEST_TEMPLATE.md
Fixes #
deleting these chars for the last time :)
> these chars seem to make everything bold and too big

- _rest_config.php
Related of #3928 issue, I removed the automatic token refresh.
@sjpadgett - please review it. 
Thanks
Amiel
> remove auto refresh token

- CONTRIBUTING.md
- contrib/util/docker/README.md
> add env-migrator link

- interface/forms/LBF/new.php
- interface/main/tabs/js/include_opener.js
- library/custom_template/custom_template.php
- library/dialog.js
- History allowing diagnosis popups
- LBF and Text template dialog fix
- Fix top dependencies
> Fix some LBF issues

- interface/forms/eye_mag/php/eye_mag_functions.php
- interface/forms/eye_mag/php/taskman_functions.php
- interface/logview/logview.php
- interface/main/backup.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- interface/patient_file/deleter.php
- interface/patient_file/report/patient_report.php
- interface/patient_file/summary/advancedirectives.php
- interface/patient_file/summary/demographics.php
- interface/reports/audit_log_tamper_report.php
- library/ajax/adminacl_ajax.php
- library/classes/CategoryTree.class.php
- library/globals.inc.php
- library/sql.inc
- portal/get_patient_documents.php
- portal/report/portal_patient_report.php
- sql/5_0_2-to-6_0_0_upgrade.sql
- sql/database.sql
- src/Common/Logging/EventAuditLogger.php
- src/Services/DocumentService.php
- version.php
in progress
Plan:
* Record changes in user privileges (to fully support this, added logging for when change a user's access control group) (COMPLETED)
* Will need to not delete patient documents (instead need to flag them as deleted). (COMPLETED)
* Need to turn on full logging by default (Administration->Globals->Logging->Audit Logging SELECT Query->On and Administration->Globals->Logging->Printing Log Option->Log entire document). Will plan to add instructions for non MU users to consider turning off the Audit Logging SELECT Query setting. (COMPLETED)
* Deleting a log entry needs to detected. (COMPLETED)
* Clarified use of 'Create Eventlog Backup' in the Backup gui via more detailed instructions. (COMPLETED)
> working on d2 and d3 for onc 2015

- interface/main/calendar/modules/PostCalendar/pnadmin.php
- interface/usergroup/addrbook_edit.php
- interface/usergroup/addrbook_list.php
- library/validation/LBF_Validation.php
- library/validation/validation_script.js.php
> php8 fixes

- library/classes/Prescription.class.php
thanks @vishnuyar for pointing out this issue in some of the session variable names!
> variable fixes

- API_README.md
- FHIR_README.md
> fhir documentation updates

- CONTRIBUTING.md
> Minor update

- interface/main/calendar/modules/PostCalendar/pnadmin.php
- interface/main/calendar/modules/PostCalendar/pnlang/eng/global.php
Fixes #3776
change button name
> button name change

- gacl/admin/about.php
- gacl/admin/acl_admin.php
- gacl/admin/acl_debug.php
- gacl/admin/acl_list.php
- gacl/admin/acl_test2.php
- gacl/admin/acl_test3.php
- gacl/admin/assign_group.php
- gacl/admin/edit_group.php
- gacl/admin/edit_object_sections.php
- gacl/admin/edit_objects.php
- gacl/admin/group_admin.php
- gacl/admin/templates/phpgacl/acl_admin.tpl
- gacl/admin/templates/phpgacl/acl_debug.tpl
- gacl/admin/templates/phpgacl/edit_group.tpl
- gacl/admin/templates/phpgacl/edit_object_sections.tpl
- gacl/admin/templates/phpgacl/edit_objects.tpl
- gacl/admin/templates/phpgacl/navigation.tpl
- gacl/admin/templates/phpgacl/pager.tpl
- library/ajax/adminacl_ajax.php
- src/Gacl/GaclApi.php
> php8 fixes in gacl module

- gacl/admin/about.php
- gacl/admin/acl_admin.php
- gacl/admin/acl_list.php
- gacl/admin/acl_test2.php
- gacl/admin/acl_test3.php
- gacl/admin/assign_group.php
- gacl/admin/edit_group.php
- gacl/admin/edit_object_sections.php
- gacl/admin/edit_objects.php
- gacl/admin/group_admin.php
- gacl/admin/templates/phpgacl/about.tpl
- gacl/admin/templates/phpgacl/acl_admin.tpl
- gacl/admin/templates/phpgacl/acl_debug.tpl
- gacl/admin/templates/phpgacl/acl_list.tpl
- gacl/admin/templates/phpgacl/acl_test2.tpl
- gacl/admin/templates/phpgacl/acl_test3.tpl
- gacl/admin/templates/phpgacl/assign_group.tpl
- gacl/admin/templates/phpgacl/edit_group.tpl
- gacl/admin/templates/phpgacl/edit_object_sections.tpl
- gacl/admin/templates/phpgacl/edit_objects.tpl
- gacl/admin/templates/phpgacl/footer.tpl
- gacl/admin/templates/phpgacl/group_admin.tpl
- gacl/admin/templates/phpgacl/header.tpl
- gacl/admin/templates/phpgacl/navigation.tpl
- gacl/admin/templates/phpgacl/object_search.tpl
- gacl/admin/templates/phpgacl/pager.tpl
- src/Gacl/GaclAdminApi.php
- src/Gacl/GaclApi.php
> gacl fixes

- interface/globals.php
- interface/main/calendar/includes/pnAPI.php
- interface/modules/zend_modules/config/autoload/global.php
- library/ajax/sql_server_status.php
- library/sql.inc
- portal/patient/fwk/libs/verysimple/DB/DataDriver/MySQLi.php
- src/Gacl/Gacl.php
fix for the database pooling global
(issue here is that the database pooling global setting was not working correctly since the database connection is created before actually collecting the globals... oops :) )
> fix for the database pooling global

- library/ajax/sql_server_status.php
- sql_upgrade.php
> sql upgrade stuff

- .travis.yml
remove php8 travis build crutch
> remove php8 travis build crutch

- .travis.yml
- ci/nginx/nginx.conf
- contrib/util/docker/dockers/dev-nginx/nginx.conf
> nginx api fix

- .travis.yml
- README.md
- composer.json
- composer.lock
- phpunit.xml
> automated testing updates

- docker/development-easy-arm/docker-compose.yml
- docker/development-easy-light/README.md
- docker/development-easy-light/docker-compose.yml
- docker/development-easy/docker-compose.yml
fixes: #3864 
@tywrenn ,
Created easy dev light for you :)
> easy dev light

- sites/default/statement.inc.php
> make sure pt payments show on statement as pt paid

- interface/code_systems/dataloads_ajax.php
- sql/5_0_2-to-6_0_0_upgrade.sql
Fixes #4017 
also brings back sorely missed gif loader :)
> fix ajax-loader gif, add U07.2 to ICD10

- _rest_config.php
- apis/dispatch.php
- docker/development-easy-arm32/docker-compose.yml
- docker/development-easy-arm64/docker-compose.yml
- docker/development-easy-light/docker-compose.yml
- docker/development-easy/docker-compose.yml
- docker/development-insane/docker-compose.yml
- interface/globals.php
- library/globals.inc.php
- oauth2/authorize.php
- oauth2/provider/.well-known/discovery.php
- oauth2/provider/jwk.php
- oauth2/provider/login.php
- src/Common/Session/SessionUtil.php
- src/RestControllers/AuthorizationController.php
- src/RestControllers/FHIR/FhirAllergyIntoleranceRestController.php
- src/RestControllers/FHIR/FhirCareTeamRestController.php
- src/RestControllers/FHIR/FhirConditionRestController.php
- src/RestControllers/FHIR/FhirEncounterRestController.php
- src/RestControllers/FHIR/FhirImmunizationRestController.php
- src/RestControllers/FHIR/FhirLocationRestController.php
- src/RestControllers/FHIR/FhirMedicationRequestRestController.php
- src/RestControllers/FHIR/FhirMedicationRestController.php
- src/RestControllers/FHIR/FhirObservationRestController.php
- src/RestControllers/FHIR/FhirOrganizationRestController.php
- src/RestControllers/FHIR/FhirPatientRestController.php
- src/RestControllers/FHIR/FhirPractitionerRestController.php
- src/RestControllers/FHIR/FhirPractitionerRoleRestController.php
- src/RestControllers/FHIR/FhirProcedureRestController.php
- src/Services/FHIR/FhirResourcesService.php
**Work in progress**
Ran into several pathing and session issues, which dealt with in this PR. Also simplified some of the code. Still planning following:
1. Fix broken controller in api **(DONE)**
- J: what controller
- B: This is why travis is failing (likely just some small thing i need to address in the automated testing controller stuff)
2. encrypt all the sensitive stuff that is stored in database (such as client secret) and do not store the bearer/refresh tokens if possible which I think should not need to store the tokens
- J: there is no need for a any token storage if want to rid ourselves of that table.
- B: am thinking best to keep this the table to be able to map the user_id from the oauth_access_token_id and also map whether (but drop the recording of the bearer token for …
> some oauth updates

- interface/globals.php
> check for modules dir for upgr < 4.2.2

- _rest_config.php
- apis/dispatch.php
- library/globals.inc.php
- oauth2/authorize.php
- oauth2/provider/.well-known/discovery.php
- sql/5_0_2-to-6_0_0_upgrade.sql
- sql/database.sql
- src/Common/Auth/OpenIDConnect/Entities/UserEntity.php
- src/Common/Auth/OpenIDConnect/Grant/CustomPasswordGrant.php
- src/Common/Auth/OpenIDConnect/Repositories/AccessTokenRepository.php
- src/Common/Auth/OpenIDConnect/Repositories/ClientRepository.php
- src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
- src/Common/Auth/OpenIDConnect/Repositories/UserRepository.php
- src/Common/Auth/UuidUserAccount.php
- src/RestControllers/AuthorizationController.php
- version.php
- added support so that the client secret is validated
- supported encryption of the client secret
- updated password grant
- removed need for user_roles
> oauth updates

- .travis.yml
- ci/nginx/nginx.conf
- ci/nginx_73/docker-compose.yml
- ci/nginx_74/docker-compose.yml
- ci/nginx_80/docker-compose.yml
- docker/development-easy-arm32/docker-compose.yml
- docker/development-easy-arm64/docker-compose.yml
- docker/development-easy-light/docker-compose.yml
- docker/development-easy/docker-compose.yml
- docker/development-insane/docker-compose.yml
- docker/development-insane/dockers/dev-nginx/nginx.conf
- library/globals.inc.php
- src/Common/Auth/AuthHash.php
- src/Common/Auth/OpenIDConnect/Grant/CustomPasswordGrant.php
- tests/Tests/Api/ApiTestClient.php
- tests/Tests/Api/ApiTestClientTest.php
- tests/Tests/Api/FacilityApiTest.php
- tests/Tests/Api/PatientApiTest.php
- tests/Tests/Api/PractitionerApiTest.php
- tests/Tests/E2e/TestOpenemrPage/ExampleE2eTest.php
- remove api hash stuff since no longer used
- incorporate oauth2 automated testing
- incorporate into development environments
> minor oauth2 related stuff

- interface/globals.php
- issue where pid is lost on encounters opened from billing.
> fix a couple session writes

- tests/Tests/E2e/CreateStaffTest.php
- tests/Tests/E2e/Pages/LoginPage.php
- tests/Tests/E2e/Pages/MainPage.php
- tests/Tests/E2e/Pages/UsersTab.php
Works towards fixing #4023
Adding new e2e test
Test case covering adding new system user. Adding initial [Page Objects]( https://www.automatetheplanet.com/page-object-pattern/)to help with writing more e2e tests.
> E2E test case adding a new system user

- _rest_config.php
- apis/dispatch.php
- tests/Tests/Api/ApiTestClientTest.php
- tests/Tests/Api/CapabilityFhirTest.php
> capability fhir fix

- _rest_config.php
> missed file for pr 4058

- sql/5_0_2-to-6_0_0_upgrade.sql
- sql/database.sql
- src/Common/Auth/OpenIDConnect/Grant/CustomPasswordGrant.php
- src/RestControllers/AuthorizationController.php
add a trusted user for password. allows for admin revokes and security checks
> add password trusted user

- README.md
change travis badge to github actions badges in README.md
> change travis badge to github actions badges in README.md

- docker/development-insane/docker-compose.yml
> quick insane docker env fix

- interface/main/finder/dynamic_finder.php
Fixes #4066 
Small UI improvement for patient finder table. Makes it clearer that the patient rows listed in the table are interactive and can be clicked.
When user hovers over table row, changes the cursor to a pointer instead of text selection/default. Also wraps the user name in table in a link.
> Patient finder improvements

- oauth2/authorize.php
- oauth2/provider/.well-known/discovery.php
- src/RestControllers/AuthorizationController.php
- needed to rename private $encryptionKey ie conflict w/import trait class
- add property for crypto.
Add introspection endpoint required for ONC/OIDC .
> Introspection endpoint

- interface/billing/sl_eob_search.php
> check for no invoices selected

- src/RestControllers/AuthorizationController.php
couldn't stand the red x any minute longer :)
> minor styling, typo

- interface/forms/LBF/new.php
- interface/super/edit_layout.php
- sql/5_0_1-to-5_0_2_upgrade.sql
- sql/database.sql
- change to 255
- implement word wrap for title on render in form
- to note BS won't honor table-responsive unless the first class!!
> LBF title length

- API_README.md
- FHIR_README.md
- _rest_routes.inc.php
- tests/Tests/Api/FacilityApiTest.php
- tests/Tests/Api/PractitionerApiTest.php
@sjpadgett and @adunsulag ,
This should deal with the patch issue (ie. changed them all to put), so patch no longer needed.
> change patch endpoints to put

- ci/ciLibrary.source
- tests/Tests/E2e/CreateStaffTest.php
- tests/Tests/E2e/Pages/UsersTab.php
> new strategy on the e2e testing (ie. run it 3 times and just need one to pass)

- oauth2/provider/login.php
- src/Common/Http/HttpRestRouteHandler.php
- src/RestControllers/FHIR/FhirAllergyIntoleranceRestController.php
- src/RestControllers/FHIR/FhirCareTeamRestController.php
- src/RestControllers/FHIR/FhirConditionRestController.php
- src/RestControllers/FHIR/FhirEncounterRestController.php
- src/RestControllers/FHIR/FhirImmunizationRestController.php
- src/RestControllers/FHIR/FhirLocationRestController.php
- src/RestControllers/FHIR/FhirMedicationRequestRestController.php
- src/RestControllers/FHIR/FhirMedicationRestController.php
- src/RestControllers/FHIR/FhirObservationRestController.php
- src/RestControllers/FHIR/FhirOrganizationRestController.php
- src/RestControllers/FHIR/FhirPatientRestController.php
- src/RestControllers/FHIR/FhirPractitionerRestController.php
- src/RestControllers/FHIR/FhirPractitionerRoleRestController.php
- src/RestControllers/FHIR/FhirProcedureRestController.php
- src/RestControllers/RestControllerHelper.php
- add scopes to sign in dialog
- some tuning in route parsing
> Fix Fhir api response

- tests/Tests/RestControllers/FHIR/FhirOrganizationRestControllerTest.php
- tests/Tests/RestControllers/FHIR/FhirPatientRestControllerTest.php
- tests/Tests/RestControllers/FHIR/FhirPractitionerRestControllerTest.php
> automated testing fixes

- src/Common/Auth/AuthHash.php
- tests/Tests/Unit/PasswordVerifyTest.php
passwordVerify updates and applicable unit testing
> passwordVerify updates and applicable unit testing

- _rest_routes.inc.php
- src/RestControllers/FHIR/FhirMetaDataRestController.php
- remove unused QuestionnaireResponse from routes
- fix implementation metadata url path
> fhir updates

- composer.json
- composer.lock
removed deprecated errors from jwt
> removed deprecated errors from jwt

- interface/main/main_screen.php
- oauth2/provider/login.php
- src/Common/Auth/MfaUtils.php
- src/Common/Auth/OpenIDConnect/Entities/UserEntity.php
- src/RestControllers/AuthorizationController.php
Overall is testing well.
(reminder for self to check to ensure patient login still works)
> mfa u2f oauth fixes and php8 fixes

- _rest_config.php
- apis/dispatch.php
- composer.json
- composer.lock
- oauth2/authorize.php
- oauth2/provider/.well-known/discovery.php
- src/Common/Auth/OpenIDConnect/Entities/ClientEntity.php
- src/Common/Auth/OpenIDConnect/IdTokenSMARTResponse.php
- src/Common/Auth/OpenIDConnect/Repositories/ClientRepository.php
- src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
- src/RestControllers/AuthorizationController.php
- src/RestControllers/FHIR/FhirMetaDataRestController.php
- src/RestControllers/RestControllerHelper.php
- src/RestControllers/SMART/SMARTConfigurationController.php
- consolidated all scope handling to ScopeRepository
- fixed up fhir metadata and moved scope qualify for smart well known to scope repository
Fixes #4121 
Closing in on final scope and claim handling
> Server Scopes

- src/Common/Logging/SystemLogger.php
- tests/Tests/Api/ApiTestClientTest.php
revert logging to warning and couple scope related tests
> revert logging to warning and couple scope related tests

- ccdaservice/README.md
- ccdaservice/serveccda.js
Quick fix to get into release.
- xpath code system oid changes
- change doc header
> fix for ccda v1.1

- .github/workflows/test.yml
- composer.json
- composer.lock
e2e panther update that should now work with php8
> e2e panther update that should now work with php8

- API_README.md
- FHIR_README.md
- _rest_routes.inc.php
- apis/dispatch.php
- library/globals.inc.php
- oauth2/provider/.well-known/discovery.php
- oauth2/provider/jwk.php
- oauth2/provider/login.php
- src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
- src/RestControllers/AuthorizationController.php
make oauth2/api patient role experimental and some php warning fixes
> make oauth2/api patient role experimental and some php warning fixes

- API_README.md
- tests/Tests/Api/ApiTestClientTest.php
documentation and testing updates regarding refresh
> documentation and testing updates regarding refresh

- API_README.md
- interface/smart/admin-client.php
- sites/default/documents/custom_menus/Custom.json
- src/Common/Auth/OpenIDConnect/Repositories/ClientRepository.php
- src/FHIR/SMART/ClientAdminController.php
- src/FHIR/SMART/SmartLaunchController.php
quick smart updates
also not showing the smart app widget in the patient summary when:
1. fhir api turned off
2. no enabled smart apps
> quick smart updates

- interface/smart/admin-client.php
- interface/smart/register-app.php
- src/FHIR/SMART/ClientAdminController.php
- src/RestControllers/AuthorizationController.php
> couple fixes

- setup.php
> multi site disable file/perm checks

- API_README.md
- _rest_config.php
- apis/dispatch.php
- interface/globals.php
- interface/patient_file/summary/labdata.php
- oauth2/authorize.php
- src/Common/Session/SessionUtil.php
> fixes up sessions to work with smart app

- API_README.md
- FHIR_README.md
- library/globals.inc.php
- src/Common/Logging/SystemLogger.php
- version.php
doc updates and logging global
> doc updates and logging global

- contrib/util/language_translations/buildLanguageDatabase.pl
- contrib/util/language_translations/currentConstants.txt
- contrib/util/language_translations/log_buildLanguageDatabase.txt
- contrib/util/language_translations/manuallyRemovedConstants.txt
> translation update

- interface/main/tabs/js/tabs_view_model.js
- changed anonymous generated event in navigateTabs to a oneshot event.
Fixes #4153
> Change in tabs management.

- DOCKER_README.md
updated docker docs to prep for 6.0.0 release
> updated docker docs to prep for 6.0.0 release

- interface/main/backup.php
- interface/themes/ajax_calendar_sass.scss
- calendar facility table not responsive if more than six facilities
- modify dump command option escaping
> calendar facilities list bug

- tests/old_unit_dir/BaseHarness.class.php
> php 8.1 syntax fix

- ccdaservice/serveccda.js
missing oid in xpath for procedures
add oid
> quick OID add for CPT4 coding system

- src/Billing/BillingReport.php
> fix for Billing Manager, Billing Status = Unbilled

- library/patient.inc
- src/Services/PatientService.php
> pesky styling

- interface/forms/fee_sheet/new.php
- library/FeeSheet.class.php
before user would have to type ndc everytime hcpcs was added
use `drugs` :)
> autopopulate ndc from drugs table

- interface/patient_file/summary/demographics_full.php
- interface/themes/core/patient/demographics.scss
- interface/themes/core/tabs.scss
- interface/themes/rtl_style_pdf.css
- interface/themes/style.scss
- fix fields cut off choice edit
- moved inline style demo full to scss
- fix odd labels to right back to left.
- fix rtl_style_pdf.css syntax error
> demographics style change

- acknowledge_license_cert.html
Fixes #
Change company information
> Changing contact information

- interface/patient_file/front_payment.php
- interface/patient_file/front_payment_cc.php
- library/globals.inc.php
- add authorizedotnet and stripe payments
Port feature from v5.0.2
> Front Payment credit cards

- tests/Tests/Unit/Common/Acl/AclMainTest.php
> minor testing fix

- config/config.yaml
- package-lock.json
- package.json
> npm jscolor fix

- .github/workflows/test.yml
- ci/apache_74_102/docker-compose.yml
- ci/apache_74_103/docker-compose.yml
- ci/apache_74_104/docker-compose.yml
- ci/apache_74_105/docker-compose.yml
- ci/apache_74_57/docker-compose.yml
- ci/apache_74_8/docker-compose.yml
- ci/apache_80_105/docker-compose.yml
updated automated testing environments
> updated automated testing environments

- docker/development-insane/README.md
- docker/development-insane/docker-compose.yml
updated insane dev environment with new alpine 3.13 dockers
> updated insane dev environment with new alpine 3.13 dockers

- .github/workflows/test.yml
- ci/nginx_81/docker-compose.yml
- ci/nginx_81/php.ini
- docker/development-insane/README.md
- docker/development-insane/docker-compose.yml
- docker/development-insane/dockers/dev-nginx/nginx.conf
- docker/development-insane/dockers/dev-php-fpm-7-3-redis/Dockerfile
- docker/development-insane/dockers/dev-php-fpm-7-3/Dockerfile
- docker/development-insane/dockers/dev-php-fpm-7-4-redis/Dockerfile
- docker/development-insane/dockers/dev-php-fpm-8-0-redis/Dockerfile
- docker/development-insane/dockers/dev-php-fpm-8-0/Dockerfile
- docker/development-insane/dockers/dev-php-fpm-8-1-redis/Dockerfile
- docker/development-insane/dockers/dev-php-fpm-8-1-redis/php.ini
- docker/development-insane/dockers/dev-php-fpm-8-1/Dockerfile
- docker/development-insane/dockers/dev-php-fpm-8-1/php.ini
php 8.1 added to automated testing and insane dev environment
> php 8.1 added to automated testing and insane dev environment

- library/options.inc.php
weno pharm list fix
see: https://github.com/openemr/openemr/commit/d56a08640c6fef1b71cfccb9f97277e7eb03795d#r46609148
> weno pharm list fix

- interface/forms/procedure_order/common.php
- invalid directory and filename
initial log file create was invalid and to soon.
conditional to check for valid data before creating initial log file.
> procedure order fix

- controllers/C_Document.class.php
- document date over escaped
Fixes  A forum issue
Looking at other document issues so will leave open for a bit.
Removed extra quote.
> Document Issues

- sql/5_0_2-to-6_0_0_upgrade.sql
- sql/6_0_0-to-6_1_0_upgrade.sql
Fixes #4198 
speeds upgrade
@bradymiller noticed the create index should come before the update of the tables, thank you
> Reorder create UUID index

- src/Common/Session/SessionUtil.php
@adunsulag , this logging stuff is awesome btw!
(@sjpadgett , don't worry, portal session still gets special treatment :) )
> minor session consolidation and logging

- src/Billing/BillingProcessor/Tasks/GeneratorX12Direct.php
- src/Billing/X125010837P.php
Dan found an issue while testing related to scope of some variable, so this is removing global keyword from some function-scoped variables and passing the variables into the function instead.
* fixed bug affecting HLcount and edi count (SE Trailer)
> Billing processor fixes

- sql/database.sql
Fixes #
https://community.open-emr.org/t/x12-claim-checks-being-sent-to-patients-instead-of-provider/16045/2?u=stephenwaite
> turn accept assign on by default

- interface/forms/CAMOS/notegen.php
Fixes #
https://community.open-emr.org/t/error-print-pdf-camos/16053?u=stephenwaite
> fix sql query binds

- docker/development-insane/docker-compose.yml
> update insane dev environment

- interface/forms/CAMOS/help.html
- interface/forms/CAMOS/new.php
- interface/forms/CAMOS/notegen.php
- library/ajax/sql_server_status.php
- library/ajax/template_context_search.php
- library/custom_template/ajax_code.php
- library/custom_template/custom_template.php
- library/custom_template/personalize.php
- library/js/CustomTemplateApi.js
- library/js/CustomTemplateLoader.js
- library/js/ajax_functions_writer.js
- add $GLOBALS['ongoing_sql_upgrade'] = true; to status ajax
Fixes a forum issue
Prior version to 5.0.1 failed because new status polling called globals w/o $GLOBALS['ongoing_sql_upgrade'] = true;
> database upgrade fix

- custom/code_types.inc.php
- interface/patient_file/encounter/superbill_custom_full.php
Fixes #
add active codes search
> admininstration of codes search additions

- interface/main/tabs/menu/menus/standard.json
restore api clients from prev commit
> quick follow up

- CONTRIBUTING.md
Fixes #
https://github.com/openemr/openemr-devops/issues/285
> add vscode to contributing guide

- CONTRIBUTING.md
easy dev documentation updates
still in progress
> easy dev documentation updates

- interface/main/backup.php
- export layout and list escaping for windows
At least it's here
> windows backup fix from 6.0.0 ref  PR #4159

- CONTRIBUTING.md
- docker/development-easy-arm32/docker-compose.yml
- docker/development-easy-arm64/docker-compose.yml
- docker/development-easy-light/docker-compose.yml
- docker/development-easy/docker-compose.yml
- docker/development-insane/docker-compose.yml
xdebug updates
companion to this PR: https://github.com/openemr/openemr-devops/pull/286
> xdebug updates

- library/weno_log_sync.php
- src/Rx/Weno/TransmitProperties.php
> Removed function. It was not needed.

- CONTRIBUTING.md
instructions to use different php versions in easy docker development environments
> instructions to use different php versions in easy docker development environments

- interface/forms/fee_sheet/new.php
- interface/new/new_comprehensive.php
- interface/patient_file/summary/demographics_full.php
- library/js/common.js
> add keyup to modifer entry in fee sheet, consolidate in common.js

- docker/development-easy-arm32/docker-compose.yml
- docker/development-easy-arm64/docker-compose.yml
- docker/development-easy-light/docker-compose.yml
- docker/development-easy/docker-compose.yml
- docker/development-insane/docker-compose.yml
xdebug docker development environment setting update
> xdebug docker development environment setting update

- ci/ciLibrary.source
- docker/development-easy-arm32/docker-compose.yml
- docker/development-easy-arm64/docker-compose.yml
- docker/development-easy-light/docker-compose.yml
- docker/development-easy/docker-compose.yml
- docker/development-insane/docker-compose.yml
turn on rest_system_scopes_api in dev docker environments
> turn on rest_system_scopes_api in dev docker environments

- interface/usergroup/addrbook_list.php
- src/Events/Messaging/SendSmsEvent.php
- templates/documents/general_list.html
- templates/documents/general_view.html
- flag lost on a search submit
> Fix popup return selection Address Book

- interface/forms/procedure_order/common.php
> use encounter provider in procedure order

- library/MedEx/API.php
This should be enough to get the patch 6.0.0(1) up-to-date.
> MedEx for 6.0.0

- interface/billing/edit_payment.php
- interface/billing/new_payment.php
- interface/billing/payment_pat_sel.inc.php
- interface/billing/search_payments.php
- interface/forms/LBF/new.php
- library/ajax/payment_ajax.php
- library/payment_jav.inc.php
- restyle insurance and patient select popups
- fix new payment table to fit screens better
Fixes #4260 #4265
> Return to confirm screen in batch payments

- interface/forms/fee_sheet/code_choice/templates/code_choices.php
- can select anyway now except by telepathy perhaps!
Fixes #4267
> Feesheet code select issue.

- sql/6_0_0-to-6_1_0_upgrade.sql
- sql/database.sql
@ophthal , noted this discrepancy in tags and wanted to make sure this is what you meant on this
> medex icon sql fix

- composer.json
- composer.lock
- interface/login/login.php
- interface/usergroup/user_admin.php
- interface/usergroup/usergroup_admin.php
- interface/usergroup/usergroup_admin_add.php
- library/auth.inc
- library/globals.inc.php
- sql/6_0_0-to-6_1_0_upgrade.sql
- sql/database.sql
- src/Common/Auth/AuthUtils.php
- src/Services/UserService.php
This PR adds Google Sign-In, which allows user to login to OpenEMR using a Google email address. This allows organizations who use Google Workspace to sign in with Google Open ID. When an organization wants to use this feature, they would sign the BAA with Google and restrict the app to their organization only. An administrator would add the  Google email for a user in their workspace to the Admin > Users screen. For testing, you can use any Google email, and make your Google app an "external" app.
To test:
Enter your google email address sign in Administration > Users Google sign-in field. 
OpenEMR administrator must enable Google Sign in in Golbals > Connectors and enter your Google Client ID.
I've attached the doc that Dan @growlingflea wrote about how to get a client ID and enter it …
> Google Sign-In

- src/Common/Auth/AuthUtils.php
very minor stuff (doesn't touch the google sign in code, so no testing needed)
> minimal auth updates

- interface/forms/eye_mag/php/eye_mag_functions.php
- interface/forms/eye_mag/view.php
- interface/main/messages/css/reminder_style.css
- interface/main/messages/messages.php
- interface/main/messages/save.php
- interface/main/tabs/templates/tabs_template.php
- interface/patient_file/encounter/forms.php
- interface/patient_tracker/patient_tracker.php
- interface/themes/colors/utilities/tabs-full.scss
- interface/themes/oe-styles/style_manila.scss
- interface/themes/tabs_style_compact.scss
- interface/themes/tabs_style_full.scss
- library/MedEx/API.php
- tests/Tests/E2e/Pages/MainPage.php
Sign-up Bug Fix
Force full login to complete sign-up.
below added by bradymiller
Placed up for grabs demo for this PR here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Gamma_-_Up_For_Grabs_Demo
> MedEx 6.0.0

- sql/6_0_0-to-6_1_0_upgrade.sql
- sql/cvx_codes.sql
- version.php
Fixes #
https://community.open-emr.org/t/icd10-code-for-covid-19/14239/3?u=stephenwaite
> latest covid vacc

- interface/new/new_comprehensive_save.php
- interface/patient_file/history/edit_billnote.php
- library/globals.inc.php
- library/patient.inc
Fixes # add payer id to expose insurers with same name, addr but invalid payer id
also a better bootstrap billing note
and a fix that @juggernautsei found
> Add cms id dropdown

- interface/billing/sl_eob_process.php
- library/classes/Address.class.php
- library/classes/InsuranceCompany.class.php
- library/globals.inc.php
- templates/insurance_companies/general_list.html
previously couldn't view important details like address lines and payer id
show them
> more details for billers on practice settings -> insurance companies

- library/globals.inc.php
- src/Common/Auth/AuthUtils.php
- version.php
add password max length setting
> add password max length setting

- docker/development-easy-arm32/docker-compose.yml
- docker/development-easy-arm64/docker-compose.yml
- docker/development-easy-light/docker-compose.yml
- docker/development-easy/docker-compose.yml
- docker/development-insane/docker-compose.yml
> docker dev fix

- interface/main/backup.php
- library/layout.inc.php
No issue submitted.
Fix for logged error with MySQL 8.
Added feature to backup and/or delete log data.
Added feature to export lists and layouts as CSV.
Added option to export lab configuration.
Added SQL to insert missing patient_data and history_data columns when importing layouts.
Fixed some logged warnings.
> Multiple improvements for backup and configuration export/import.

- interface/usergroup/facilities.php
- src/Billing/X125010837P.php
> billing fix for corrected claims alphanumeric claim no.

- interface/patient_file/summary/demographics_save.php
> Fix bug in demographics layout that causes checkboxes to ALWAYS be Yes

- interface/billing/billing_process.php
- library/classes/InsuranceCompany.class.php
- library/classes/PhoneNumber.class.php
- src/Billing/BillingProcessor/BillingClaim.php
- src/Billing/BillingProcessor/BillingLogger.php
- src/Billing/BillingProcessor/BillingProcessor.php
- src/Billing/BillingProcessor/Tasks/AbstractGenerator.php
- src/Billing/BillingProcessor/Tasks/GeneratorX12Direct.php
- src/Billing/BillingUtilities.php
- src/Billing/Claim.php
- src/Billing/X125010837P.php
- templates/insurance_companies/general_edit.html
- templates/insurance_companies/general_list.html
Fixes #
wasn't writing log output to process_bills.log in billing manager
now writing
> fix paper claims and log in billing manager, add fax for insurance companies in practice settings

- interface/easipro/pro.php
- interface/patient_file/report/custom_report.php
- interface/patient_file/summary/add_edit_issue.php
- library/ajax/udi.php
- library/dialog.js
- portal/home.php
- sql/6_0_0-to-6_1_0_upgrade.sql
- sql/database.sql
- src/MedicalDevice/MedicalDevice.php
- version.php
a14-onc2015 - Implantable device list
related forum thread: https://community.open-emr.org/t/implantable-device-list-2015-onc-mu3-a14/13418
work in progress (working but very ugly)
here's an example UDI if want to try it out: =/08717648200274=,000025=A99971312345600=>014032=}013032&,1000000000000XYZ123
> a14-onc2015 - Implantable device list

- interface/drugs/add_edit_lot.php
- interface/drugs/drug_inventory.php
- interface/forms/clinical_notes/new.php
- sql/6_0_0-to-6_1_0_upgrade.sql
- sql/database.sql
- version.php
> several things

- interface/billing/payment_pat_sel.inc.php
- library/js/common.js
- library/payment.inc.php
…ee sheet
starts fixing #4320 
also  add space and colon to `policykeyup()` for mods in fee sheet
> use int cast for compares with php8 fatal errors in payment scripts

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
- library/htmlspecialchars.inc.php
> centralized xml escaping. also couple sql escaping fixes

- interface/billing/sl_eob_invoice.php
- library/js/utility.js
- src/OeUI/OemrUI.php
- escape fix for ledger title with apostrophe etc.
- utility fix for const delimit
umm whatever!
anyone have any bugs I can add if I get a chance?...
> various bugs

- docker/development-insane/dockers/dev-php-fpm-7-3-redis/Dockerfile
- docker/development-insane/dockers/dev-php-fpm-7-3/Dockerfile
- docker/development-insane/dockers/dev-php-fpm-7-4-redis/Dockerfile
- docker/development-insane/dockers/dev-php-fpm-7-4/Dockerfile
- docker/development-insane/dockers/dev-php-fpm-8-0-redis/Dockerfile
- docker/development-insane/dockers/dev-php-fpm-8-0/Dockerfile
- docker/development-insane/dockers/dev-php-fpm-8-1-redis/Dockerfile
- docker/development-insane/dockers/dev-php-fpm-8-1/Dockerfile
added support for php-intl in the development dockers
> added support for php-intl in the development dockers

- package-lock.json
- package.json
removed popper.js since already bundled with bootstrap
> removed popper.js since already bundled with bootstrap

- interface/reports/collections_report.php
> Scroll collt report

- interface/billing/billing_report.php
> attach bill note to correct encounter

- src/Billing/BillingProcessor/BillingProcessor.php
- src/Billing/BillingProcessor/Tasks/AbstractProcessingTask.php
- src/Billing/BillingProcessor/Tasks/TaskMarkAsClear.php
> fix mark as cleared in billing manager

- interface/billing/billing_report.php
@juggernautsei ,
Here's another proposed solution for https://github.com/openemr/openemr/pull/4348
Test this out and let me know how this works for you. This should deal with contrast issues on the billing listing while also working in all the other themes (ie. dark, colors, etc).
(there's still likely lots of css issues looming in this script, but this should at least deal with contrast issue and the weird blocky hovering stuff that was happening)
> billing contrast css

- interface/forms/LBF/new.php
- library/FeeSheetHtml.class.php
Using container-fluid and form-inline classes to take advantage of much-needed screen width.
Optional removal of bootstrapping of the provider list so it does not force a new line.
Fixed failure to use group-specific layout column counts.
> Fixes for LBF rendering.

- ccdaservice/package-lock.json
- ccdaservice/package.json
- interface/main/backup.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
- library/dialog.js
- portal/sign/assets/signer_api.js
- add some window escaping in dispatch
- sanity check if server is running. ms count!
- add lodash dependency to server
> CCDA server fixups

- interface/main/backup.php
Layout export needed some escaping for windows.
> Backup escaping issue for windows only

- .github/workflows/test.yml
- ci/apache_74_106/docker-compose.yml
- docker/development-insane/README.md
- docker/development-insane/docker-compose.yml
introducing alpha mariadb 10.6
> introducing alpha mariadb 10.6

- library/options.js.php
Fixes improper interpretation of operators in skip conditions that check the state of radio buttons.
> Fixed bug with handling radio buttons in LBF skip conditions.

- interface/main/messages/js/reminder_appts.js
- interface/patient_tracker/patient_tracker.php
(this will go in next 6.0.0 patch):
restoresession cleanup in patient tracker
@juggernautsei , Wasn't able to pinpoint why that top.sessionrestore was needed in the patient tracker yet. But I did look through that script(s) and found several place where it was missing that could potentially cause issues.
~~Commit 2:~~
~~trial of removal of redundant restoreSession.php include from popup scripts~~
> restoresession cleanup in patient tracker

- interface/main/finder/dynamic_finder.php
- interface/main/finder/dynamic_finder_ajax.php
possible fix to dynamic finder when opening a new patient
> Session fix

- interface/weno/facilities.php
- interface/weno/rxlogmanager.php
- interface/weno/wenoconnected.php
- src/Rx/Weno/Container.php
- src/Rx/Weno/TransmitProperties.php
Fixes #
Fixes some changes that Weno made to the operations and fixes some bugs in the core.
> These are some minor adjustments to the feature bug fixes

- interface/reports/pat_ledger.php
> add modifier to code display

- interface/login/login.php
> add back login form submit for chrome

- README.md
update readme for recommended nodejs versions
> update readme for recommended nodejs versions

- interface/main/about_page.php
> update donate link

- interface/main/tabs/menu/menus/standard.json
- interface/reports/message_list.php
- interface/reports/patient_list.php
simple report to show message activity during a time span
> Reports->Clients->Message List

- interface/forms/care_plan/new.php
- interface/forms/care_plan/report.php
- interface/forms/care_plan/save.php
- interface/forms/clinical_notes/new.php
- track user that creates plan item
- clinical notes user fix
Fixes #4317
Track user who created item in plan
More detail to encounter report
We'll track goals in plan as well.
Where to get assessments!
> Add provenance to care plan items

- controllers/C_Prescription.class.php
- interface/patient_file/summary/demographics.php
- library/ajax/prescription_drugname_lookup.php
- src/Rx/RxList.php
- templates/prescription/general_edit.html
- templates/prescription/general_lookup.html
- if installed option to use rxnorms
- fudge dialog size and replace Done button with Quit.
Fixes #4398
> New use RxNORM table for drug lookups.

- templates/prescription/general_edit.html
- prevent hidden rxcode overwrite on already selected drug.
> Quick fix to add lookups.

- library/options.inc.php
Choice edit width was to small(0).
Another problem is user can't empty list. Need a clear on select2 as it's funny that way. Will leave for another....!
> Care Team and Facility width fix.

- composer.json
- interface/patient_file/front_payment.php
- interface/patient_file/front_payment_cc.php
- interface/patient_file/front_payment_terminal.php
- library/globals.inc.php
- turn on in globals
- register terminal in stripe account(openemr must be on local net)
- use in front payments
> New Stripe In Person CC terminal payments

- interface/super/edit_layout.php
Fixes #4406
Layout editor was too permissive as to which columns can be deleted or renamed. Also fixes a bug where checking for columns with existing data was not working.
Would like to get some more eyes on this, as I am guessing in some cases which column names are hard-coded elsewhere. Do you see any that are missing?
> Layout editor fixes to preserve sensitive column names.

- interface/super/edit_list.php
-fix order of operations on save conditional null coalescing
> Can't save new list in list_edit

- _rest_routes.inc.php
- custom/code_types.inc.php
- src/Common/Http/HttpRestRouteHandler.php
- src/RestControllers/FHIR/FhirCarePlanRestController.php
- src/RestControllers/FHIR/FhirOrganizationRestController.php
- src/Services/CareTeamService.php
- src/Services/ConditionService.php
- src/Services/FHIR/FhirCarePlanService.php
- src/Services/FHIR/FhirCareTeamService.php
- src/Services/FHIR/FhirCodeSystemUris.php
- src/Services/FHIR/FhirConditionService.php
- src/Services/FHIR/FhirImmunizationService.php
- src/Services/FHIR/FhirOrganizationService.php
- src/Services/FHIR/FhirProvenanceService.php
- src/Services/FHIR/FhirServiceBase.php
- src/Services/FHIR/UtilsService.php
- src/Services/FacilityService.php
- src/Services/ImmunizationService.php
- src/Services/InsuranceCompanyService.php
- src/Services/OrganizationService.php
- src/Services/PractitionerRoleService.php
- src/Services/PractitionerService.php
- src/Services/Search/SearchFieldStatementResolver.php
- src/Services/Search/StringSearchField.php
Implemented the care team ONC requirements.  Got the queries working on
the practitioner role.
Also fixed a bug with lookup_code_information that got introduced due to a bad rebase in the prior ONC commitment.
We need to implement a status column in the care team on OpenEMR gui before we can fully check this off.
See #4405
> Implement ONC CareTeam, Fixed PractitionerRole, Fix critical bug in lookup_code_information

- docker/development-easy-arm32/docker-compose.yml
- docker/development-easy-arm64/docker-compose.yml
- docker/development-easy-light/docker-compose.yml
- docker/development-easy/docker-compose.yml
details here:
https://github.com/openemr/openemr/issues/2899
> easy dev support for ccdaservice directory

- ccdaservice/oe-blue-button-generate/lib/entryLevel/sharedEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/headerLevel.js
- ccdaservice/serveccda.js
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
- sql/6_0_0-to-6_1_0_upgrade.sql
- sql/database.sql
- fix spelling boo boo in care team status list
- add care team members to documentationOf section
- fix author date to document subject date(mostly encounter).
- more clean up
> CCDA care team

- interface/main/finder/dynamic_finder_ajax.php
The "dynamic" patient finder was not very intuitive when searching by DOB. It expected input in yyyy-mm-dd format. This PR makes it more flexible so that dates or partial dates can be entered in the site's preferred date format. Examples:
12       => Any date with "12" in it
1977     => Any date with "1977" in it (therefore year 1977)
197/12/1 => Dec. 1 of any year in the 1970's
12/1/197 => Same
12/1     => Dec. 1 of any year
/1       => The first day of any month of any year
Appropriate logic adjustments are made if DMY format is specified in global settings.
Also any non-digit character may be used instead of "/".
> Improved searching for patients by DOB in dynamic finder.

- interface/globals.php
- src/Common/Twig/TwigContainer.php
- src/Common/Twig/TwigExtension.php
migrate twig to separate class
> migrate twig to separate class

- src/Rx/Weno/Container.php
- src/Rx/Weno/TransmitProperties.php
> Adding updates to Weno eRx service

- contrib/util/ccda_import/import_ccda.php
- interface/forms/newpatient/new.php
- interface/main/calendar/modules/PostCalendar/pnuserapi.php
- interface/modules/zend_modules/module/Application/src/Application/Model/ApplicationTable.php
- interface/modules/zend_modules/module/Application/src/Application/Plugin/CommonPlugin.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- interface/modules/zend_modules/module/Documents/src/Documents/Plugin/Documents.php
- interface/patient_file/encounter/forms.php
fix missapllied `new UserService()`
> various fixes

- interface/main/tabs/js/user_data_view_model.js
- interface/main/tabs/main.php
- library/ajax/dated_reminders_counter.php
- library/auth.inc
- src/Common/Session/SessionTracker.php
fixes #4438
updated timeout mechanism
> updated timeout mechanism

- version.php
> db version bump

- interface/usergroup/user_admin.php
- interface/usergroup/usergroup_admin.php
- src/Common/Acl/AclExtended.php
- src/Services/UserService.php
a few warnings and typos fixed
> calendar.inc work follow up

- interface/main/tabs/menu/menus/standard.json
- interface/patient_file/summary/demographics_print.php
- interface/themes/tabs_style_compact.scss
- interface/themes/tabs_style_full.scss
- sites/default/documents/custom_menus/Custom.json
- src/Menu/MainMenuRole.php
This reorganizes the Visit Forms menu items within their form categories, and creates a new menu Reports -> Blank Forms for printing blank versions of demographics, fee sheet and LBF visit forms.
> Create menu items for Blank Forms, and organize that and Visit Forms by category.

- docker/development-easy-arm32/docker-compose.yml
- docker/development-easy-arm64/docker-compose.yml
- docker/development-easy/docker-compose.yml
- docker/development-insane/docker-compose.yml
prepping docker setting for care coordination module autoconfiguration
> prepping docker setting for care coordination module autoconfiguration

- interface/patient_tracker/patient_tracker.php
> Flow Board “CALL” response box

- interface/forms/vitals/C_FormVitals.class.php
- interface/forms/vitals/FormVitals.class.php
- interface/forms/vitals/report.php
- interface/forms/vitals/templates/vitals/general_new.html
- library/classes/Controller.class.php
- sql/6_0_0-to-6_1_0_upgrade.sql
- sql/database.sql
- version.php
> add oxygen flow rate to vitals

- CONTRIBUTING.md
- docker/development-easy-light/docker-compose.yml
> flex docker updates

- interface/globals.php
I'll just reference issue #4458
> Temporary fix for deprecated warnings turning into exceptions.

- sql/6_0_0-to-6_1_0_upgrade.sql
> fix typo in upgrade script

- controllers/C_Document.class.php
- interface/forms/procedure_order/common.php
- interface/orders/find_order_popup.php
- interface/orders/types.php
- interface/orders/types_edit.php
- interface/patient_file/encounter/find_code_history.php
- library/classes/Document.class.php
- templates/documents/general_view.html
- restyle view template properties
- cleanup classes
- add test type to picker and configuration
see issue #4462
> Tag documents to procedures

- interface/forms/care_plan/new.php
- library/globals.inc.php
- sql/6_0_0-to-6_1_0_upgrade.sql
> Turn on templating by default

- contrib/util/ccda_import/import_ccda.php
proper escaping of single quote in synthea filenames
> proper escaping of single quote in synthea filenames

- library/dialog.js
See forum issue https://community.open-emr.org/t/ipad-screen-visibility-problem/16726/2
It appears to only show on browsers running on IOS devices (iPad/iPhone)
> fix dialog content height on IOS mobile devices.

- portal/home.php
- portal/import_template.php
- portal/import_template_ui.php
- portal/lib/doc_lib.php
- portal/lib/template_menu.php
- portal/patient/fwk/libs/verysimple/IO/Includer.php
- portal/patient/fwk/libs/verysimple/Phreeze/Dispatcher.php
- portal/patient/fwk/libs/verysimple/Util/ExceptionThrower.php
- portal/patient/templates/OnsiteDocumentListView.tpl.php
- portal/patient/templates/PatientListView.tpl.php
- portal/patient/templates/ProviderHome.tpl.php
- portal/portal_payment.php
More to come
Fixes #4475
Fails on PHP 8
Stripe credit card dialog
> Portal fix for PHP 8 and CC style

- interface/patient_file/summary/demographics.php
- interface/patient_file/summary/pnotes_fragment.php
- interface/patient_file/summary/pnotes_full.php
- moved event handler to demographic context
- cleaned up pnote_fragment
- added back stats.php load on pnote loading.
Fixes #4481
> Demographics pnote completed button doesn't work

- src/Common/Uuid/UuidRegistry.php
minor updates to UuidRegistry class
> minor updates to UuidRegistry class

- interface/main/tabs/main.php
- interface/patient_file/summary/pnotes_fragment.php
- interface/super/edit_globals.php
- interface/super/edit_list.php
- edit_list string to int
Fixes #
> Mostly PHP8 that can be picked to v6

- .github/workflows/test.yml
- CONTRIBUTING.md
- ci/apache_80_102/docker-compose.yml
- ci/apache_80_103/docker-compose.yml
- ci/apache_80_104/docker-compose.yml
- ci/apache_80_106/docker-compose.yml
- ci/apache_80_57/docker-compose.yml
- ci/apache_80_8/docker-compose.yml
- docker/development-insane/docker-compose.yml
migrate dev environments and primary testing environments to php8
> migrate dev environments and primary testing environments to php8

- interface/main/tabs/js/tabs_view_model.js
- interface/main/tabs/main.php
- library/ajax/dated_reminders_counter.php
- bug fix for JS variable init
- add a date time stamp keep alive to session
Fixes #4483
> Site Id intermittent error.

- interface/main/tabs/js/tabs_view_model.js
- interface/main/tabs/main.php
- library/ajax/dated_reminders_counter.php
Fixes #
Couldn't cherry pick this one.
> Port #4492 v6-dev

- src/Services/ClinicalNotesService.php
Clinical notes was breaking on php8.  Added a method @sjpadgett needs for CCDA.
> Fixed php8 issue, added method for ccda.

- CONTRIBUTING.md
- contrib/util/ccda_import/import_ccda.php
- controllers/C_Document.class.php
- interface/modules/zend_modules/module/Application/src/Application/Model/ApplicationTable.php
- interface/modules/zend_modules/module/Application/src/Application/Model/SendtoTable.php
- interface/modules/zend_modules/module/Application/src/Application/Plugin/CommonPlugin.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CcdController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncountermanagerTable.php
- interface/modules/zend_modules/module/Carecoordination/view/carecoordination/encountermanager/index.phtml
- interface/modules/zend_modules/module/Ccr/src/Ccr/Controller/CcrController.php
- interface/modules/zend_modules/module/Ccr/src/Ccr/Model/CcrTable.php
- interface/modules/zend_modules/module/Syndromicsurveillance/src/Syndromicsurveillance/Model/SyndromicsurveillanceTable.php
- interface/modules/zend_modules/module/Syndromicsurveillance/view/syndromicsurveillance/syndromicsurveillance/index.phtml
- interface/modules/zend_modules/public/index.php
- library/classes/Controller.class.php
- library/classes/Document.class.php
- tests/Tests/Services/FHIR/FhirVitalsServiceTest.php
random patient generator updates and ccda import php8 and other misc stuff
> random patient generator updates and ccda import php8 and other misc stuff

- ccdaservice/oe-blue-button-generate/lib/entryLevel/planOfCareEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/fieldLevel.js
- ccdaservice/oe-blue-button-generate/lib/htmlHeaders.js
- ccdaservice/serveccda.js
- interface/forms/care_plan/new.php
- interface/forms/care_plan/save.php
- interface/forms/clinical_notes/new.php
- interface/forms/procedure_order/common.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
- interface/patient_file/summary/stats.php
- interface/super/edit_globals.php
- sql/6_0_0-to-6_1_0_upgrade.sql
- sql/database.sql
- version.php
- procedure order php8
- care plan add LOINC code type
Fixes #4483
> PHP8 and CCDA

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- sql/6_0_0-to-6_1_0_upgrade.sql
- sql/database.sql
- version.php
ccda import speed up and fixes
> ccda import speed up and fixes

- ccdaservice/oe-blue-button-generate/lib/entryLevel/index.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/planOfCareEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/sectionLevel2.js
- ccdaservice/serveccda.js
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
- added several Shall templates
- link concern to problems
Fixes #4504
> CCDA Health Concerns template

- interface/reports/collections_report.php
if there is more than patient have the same first and last name and encounter date it will counted as one patient, to fix it i add pid to sort and this solved the issue
Fixes #
add pid to sort
> the sort function mixed the patient total

- sql/6_0_0-to-6_1_0_upgrade.sql
- src/Menu/MainMenuRole.php
> typo in upgrade script

- library/daysheet.inc.php
- src/Billing/BillingReport.php
@ophthal found the bug and fixed it in #4511 but thinking we can consolidate with this PR
> refactor the query in the daysheet report from the billing manager

- src/Billing/BillingReport.php
ok @ophthal , think i've got it this time :)
> fix for prior commit, use correct indices on elements

- contrib/forms/clinic_note/info.txt
- contrib/forms/clinic_note/new.php
- contrib/forms/clinic_note/report.php
- contrib/forms/clinic_note/table.sql
- contrib/forms/clinic_note/view.php
- contrib/forms/clinical_notes/info.txt
- interface/forms/clinic_note/info.txt
- interface/forms/clinic_note/new.php
- interface/forms/clinic_note/report.php
- interface/forms/clinic_note/table.sql
- interface/forms/clinic_note/view.php
- sql/6_0_0-to-6_1_0_upgrade.sql
- version.php
migrate old clinical notes form to clinic note
> migrate old clinical notes form to clinic note

- interface/forms/newpatient/common.php
- library/globals.inc.php
This makes Onset/Hospitalization date optional.
> Implemented global setting for onset/hospitalization date in main encounter form.

- custom/export_xml.php
- interface/forms/fee_sheet/new.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
- interface/orders/receive_hl7_results.inc.php
- interface/usergroup/facility_user.php
- interface/usergroup/facility_user_admin.php
- library/classes/rulesets/Cqm/library/AbstractCqmReport.php
- library/formdata.inc.php
- library/htmlspecialchars.inc.php
- library/options.inc.php
- library/patient.inc
- sql/6_0_0-to-6_1_0_upgrade.sql
- src/Billing/InvoiceSummary.php
some misc updates/fixes:
php8.0
php8.1
uuid
upgrade
> Misc updates

- custom/code_types.inc.php
- interface/billing/billing_report.php
- interface/forms/fee_sheet/new.php
- library/FeeSheet.class.php
- library/sql_upgrade_fx.php
- src/Billing/BillingReport.php
fix to prior commit, 077a35c5b290317fba8cd939fa3d919dded74a18, so it can continue to create a query on the billing table even though the first query returned no results
> Billing manager fix to query plus php8 fixes

- ccdaservice/ccda_gateway.php
- interface/globals.php
- interface/modules/zend_modules/public/index.php
- src/Services/CDADocumentService.php
minor stuff
(mostly php8 warnings)
> minor stuff

- controllers/C_Document.class.php
- src/Services/ProcedureService.php
Minor pull request to fix the uuid's for procedure_result when a document is uploaded and tied to a procedure.
> Fix uuid for procedure_result for DiagnosticReport

- interface/orders/orders_results.php
Couldn't cherry pick from master but wanted the PHP8 fixes also.
> bug fix from PR#4543

- interface/forms/vitals/report.php
- interface/forms/vitals/templates/vitals/general_new.html
- sql/6_0_0-to-6_1_0_upgrade.sql
- sql/database.sql
- src/Common/Forms/FormVitals.php
- src/Services/FHIR/Observation/FhirObservationVitalsService.php
- src/Services/VitalsService.php
Cleaned up a bit of vitals and added the inhaled_oxygen_concentration
field.  @sjpadgett Does this work for you?
> Add Inhaled Oxygen Concentration for ccda.

- ccdaservice/oe-blue-button-generate/lib/condition.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/allergyEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/index.js
- ccdaservice/oe-blue-button-generate/lib/htmlHeaders.js
- ccdaservice/oe-blue-button-generate/lib/sectionLevel2.js
- ccdaservice/serveccda.js
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
add no known allergies hook and template
fix suffix
Fixes #4290 
Fixes #4523 
Fixes #4462 
Fixes #4317 
Passes all b1 test scenarios. Yea!
> ccda final all test green

- Documentation/README-Log-Backup.txt
Fixes # Nothing
rewording so that it is a little clearer how to created the crontab job
> rewording so that it is a little clearer

- sql/6_0_0-to-6_1_0_upgrade.sql
- sql/database.sql
- version.php
> quick minor database fixes

- _rest_routes.inc.php
- src/RestControllers/FHIR/FhirCareTeamRestController.php
Very minor fix with the careplan not working on a list all in a clinician context rather than the patient context.  Also added a comment to CareTeam to typedoc the service.
> Fix bug in the careplan list endpoint

- docker/development-easy-arm32/docker-compose.yml
- docker/development-easy-arm64/docker-compose.yml
- docker/development-easy-light/docker-compose.yml
- docker/development-easy/docker-compose.yml
- docker/development-insane/docker-compose.yml
- library/classes/Installer.class.php
- setup.php
- sql/6_0_0-to-6_1_0_upgrade.sql
- sql/database.sql
- version.php
turn on care coordination modules by default
> turn on care coordination modules by default

- interface/billing/billing_report.php
- interface/billing/sl_eob_process.php
- interface/billing/sl_eob_search.php
- interface/forms/fee_sheet/new.php
- interface/forms/fee_sheet/review/fee_sheet_queries.php
- interface/main/calendar/modules/PostCalendar/pnadminapi.php
- interface/main/calendar/modules/PostCalendar/pnuser.php
- interface/main/calendar/modules/PostCalendar/pnuserapi.php
- interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
- interface/modules/zend_modules/module/Installer/view/installer/installer/index.phtml
- interface/patient_file/deleter.php
- interface/patient_file/history/encounters.php
- library/MedEx/API.php
- library/globals.inc.php
- library/options.inc.php
- library/patient.inc
- sites/default/statement.inc.php
- src/Billing/Claim.php
- src/Billing/InvoiceSummary.php
- src/Billing/ParseERA.php
- src/Menu/MainMenuRole.php
prior commit a6b530f12b0e99e29acfcf468f1e77a376865f09 left era unpostable :crying_cat_face: 
fix display and service date
php 8 fixes
> era posting work and misc php8 fixes

- library/sql_upgrade_fx.php
- sql/6_0_0-to-6_1_0_upgrade.sql
- src/Services/CareTeamService.php
- src/Services/CodeTypesService.php
- src/Services/FHIR/FhirMedicationRequestService.php
- src/Services/FHIR/FhirPatientService.php
- src/Services/FHIR/Procedure/FhirProcedureOEProcedureService.php
- src/Services/PatientService.php
- src/Services/PrescriptionService.php
- src/Services/ProcedureService.php
- version.php
Hooray - Single Patient API complete!
This pull request implements some fixes on MedicationRequest as well as Procedures.  This also implements the patient previous, careteam, suffix and ethnicity.
We'll need to get the MU3 demos on the latest code, but if the data is setup on the instance the API now comes back 100% for single patient.  Hooray!
> Openemr single patient

- src/Services/CarePlanService.php
- src/Services/ConditionService.php
- src/Services/DeviceService.php
- src/Services/FHIR/DiagnosticReport/FhirDiagnosticReportClinicalNotesService.php
- src/Services/FHIR/DocumentReference/FhirClinicalNotesService.php
- src/Services/FHIR/DocumentReference/FhirPatientDocumentReferenceService.php
- src/Services/FHIR/FhirCarePlanService.php
- src/Services/FHIR/FhirGoalService.php
- src/Services/FHIR/FhirImmunizationService.php
- src/Services/FHIR/FhirMedicationRequestService.php
- src/Services/FHIR/Observation/FhirObservationLaboratoryService.php
- src/Services/FHIR/Observation/FhirObservationVitalsService.php
- src/Services/FHIR/Procedure/FhirProcedureSurgeryService.php
- src/Services/ImmunizationService.php
- src/Services/SurgeryService.php
- src/Services/VitalsService.php
This doesn't really change the inferno test cases but adds more detailed author information if we have access to it for provenance.
> Add provenance author to code commits

- gacl/Cache_Lite/Lite.php
- interface/billing/edih_view.php
- interface/billing/sl_eob_search.php
- interface/main/authorizations/authorizations.php
- interface/main/calendar/modules/PostCalendar/pnincludes/Date/Calc.php
- library/edihistory/edih_271_html.php
- library/edihistory/edih_277_html.php
- library/edihistory/edih_835_html.php
- library/edihistory/edih_csv_inc.php
- library/edihistory/edih_io.php
- library/edihistory/edih_segments.php
- library/report.inc
also copy era posted file to edi history so no more dbl uploads
> fixes for edihistory, remove jquery ui residuals, replace php each function removed in php8

- interface/eRxXMLBuilder.php
- interface/forms/fee_sheet/code_choice/css/code_choices.css
- interface/patient_file/report/patient_report.php
bring back z-index for code-choices
https://community.open-emr.org/t/fee-sheet-editing-problem/17113/9?u=stephenwaite
fix require for patient.inc in newcrop, thanks for the report @jitchawla
select encounter automatically in patient report when click on issue that's linked
https://community.open-emr.org/t/encounter-not-automatically-selected-when-click-on-medical-issues/17126?u=stephenwaite
> fixes from forum

- _rest_routes.inc.php
- swagger/openemr-api.yaml
- also fixed swagger documentation for standard api documents endpoints, so can now upload and download documents in swagger.
> more api documentation

- interface/patient_file/summary/demographics.php
- interface/patient_file/summary/stats.php
- library/clinical_rules.php
- library/options.inc.php
- templates/core/unauthorized.html.twig
- templates/patient/card/appointments.html.twig
- templates/patient/card/appointments_past.html.twig
- templates/patient/card/card_base.html.twig
- templates/patient/card/insurance.html.twig
- templates/patient/card/loader.html.twig
minor fixes for:
insurance wasn't showing
unable to add/edit immunizations
CDR widget admins section wasn't working
Current Medications is only supposed to show when erx is enabled
eligibility function was changed
couple escaping adjustments
testing is looking really good. @robertdown , thanks for this amazing stuff!
> minor fixes for recent twig patient summary improvements

- interface/patient_file/summary/dashboard_header.php
- sql_upgrade.php
- src/Core/Kernel.php
> fix upgrade version selected in dropdown and misc php8 fixes

- _rest_routes.inc.php
- swagger/openemr-api.yaml
another update to api documentation
> another update to api documentation

- ci/phpcs.xml
ignore qdm directory for psr12 styling check
> ignore qdm directory for psr12 styling check

- interface/themes/oe-styles/style_manila.scss
- interface/themes/tabs_style_compact.scss
- library/ESign/views/default/esign_signature_log.php
- light compact theme dropdowns
- manila widgets outside container
- ESign log view background to follow theme color
Fixes #4640
> Some style fixes

- .github/SECURITY.md
- README.md
> security policy readme

- interface/main/calendar/add_edit_event.php
- src/Events/Appointments/AppointmentRenderEvent.php
- src/Events/Appointments/AppointmentSetEvent.php
Adding appointment event dispatchers
Originated from prior PR:
https://github.com/openemr/openemr/pull/4569
> Adding appointment event dispatchers

- interface/main/onotes/office_comments.php
- interface/main/onotes/office_comments_full.php
- interface/modules/zend_modules/module/Installer/view/installer/installer/index.phtml
- interface/reports/audit_log_tamper_report.php
> bug fixes for access

- custom/ajax_download.php
- custom/download_qrda.php
- custom/qrda_category1.inc
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- sql/6_0_0-to-6_1_0_upgrade.sql
- sql/database.sql
- src/Services/Cda/CdaTemplateParse.php
- src/Services/CodeTypesService.php
- src/Services/EncounterService.php
- version.php
- add external loads for the 2021 and 2022 CQM reporting periods
Fixes #4662 
More CQM structural work. QRDA export, import, data loads & report bugs.
> QRDA Export and Value sets

- interface/patient_file/report/custom_report.php
- library/ESign/ESign.php
- library/globals.inc.php
- add some styles custom report
- reduce title sizes
> Port E-Sign global to exclude un-signed forms patch 4

- library/MedEx/API.php
- src/Billing/ParseERA.php
hi @ophthal , does this `php8` fix look ok?
`(int)` cast wasn't balancing claim
> quick billing fix and php8

- composer.json
- interface/main/calendar/modules/PostCalendar/common.api.php
- interface/orders/receive_hl7_results.inc.php
- interface/orders/single_order_results.inc.php
> remove tilde from hl7 results only transcribed reports

- interface/main/tabs/main.php
- Get rid of annoying scroll-x on all views
Fixes #
Add style to main body.
> Main frame scroll bar fix

- interface/eRxStore.php
- interface/eRxXMLBuilder.php
- interface/patient_file/summary/add_edit_issue.php
Adds diagnosis to the NewCrop SOAP message so diagnosis appears in the drug signature list (now required by medicare) and some bug fixes
Fixes #
> Adds diagnosis to the NewCrop SOAP message

- library/patient.inc
- src/Services/PatientService.php
Needed to leverage a number of patient date formatting methods which
were hard to get to w/ them being in the library.  Moved them into the
patient service method so we could access them from the service.
> Move patient date methods into service

- interface/main/calendar/add_edit_event.php
- interface/main/calendar/modules/PostCalendar/pnadmin.php
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day_print/outlook_ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/header.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month_print/outlook_ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week_print/outlook_ajax_template.html
- interface/main/calendar/modules/PostCalendar/pnuserapi.php
- src/Core/ModulesApplication.php
- src/Events/Appointments/CalendarUserGetEventsFilter.php
- src/Events/Core/ScriptFilterEvent.php
- src/Events/Core/StyleFilterEvent.php
- src/Events/Core/TemplatePageEvent.php
Made it so module writers can add javascript and stylesheet files to the
calendar from their module using the script filter and syle filter
event.
Added extension points to the calendar for modifying the event data
structure that comes back for the day/week/month format.  Users can
override the style on each calendar appointment.  Also added the
appointment id and pid information to each calendar event so frontend
javascript work can be done on the calendar appointments.
Added some security method to the modules application class to make sure
module authors don't include files outside the modules directory.
> Created calendar extension points for modules.

- library/forms.inc
- src/Services/FormService.php
Broke master by not checking in the FormService class for the EncounterSessionUtil function.  This fixes that :)
> Refactor getFormByEncounter into service class

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- library/dialog.js
- sql/6_0_0-to-6_1_0_upgrade.sql
- sql/database.sql
- src/Services/Cda/CdaTemplateImportDispose.php
- src/Services/Cda/CdaTemplateParse.php
- src/Services/CodeTypesService.php
- version.php
CCDA 2.16.840.1.113883.10.20.22.4.13 - Procedure Activity Observation.
QRDA 2.16.840.1.113883.10.20.24.3.18 - Diagnostic Study, Performed,
QRDA 2.16.840.1.113883.10.20.24.3.59 - Physical Exam, Performed
> QRDA Import adds and fixes

- library/options.inc.php
1. Fixed bug in selection lists where duplicate translations cause duplicate list entries.
2. Fixed bug in CSS width and height for LBF Canvas field type.
> A couple of small bug fixes for layouts

- interface/super/edit_layout.php
* Swap inputs with type=button to actual buttons
* Sticky group headers
* Better button UI
> LBF Editor UI Improvements

- controllers/C_Document.class.php
- interface/billing/sl_eob_process.php
- interface/main/tabs/menu/menus/standard.json
- interface/patient_file/summary/demographics.php
- src/Billing/BillingUtilities.php
- src/Billing/ParseERA.php
- templates/patient/card/insurance.html.twig
The insurances weren't displaying properly when there was more than 1.
If there is an `Old` insurance it isn't displaying properly which leads to the same insurance being listed twice, still broken though.
> Insurance section cleanup for medical dashboard overhaul plus misc php8 fixes

- CONTRIBUTING.md
quick docker documentation fix
> quick docker documentation fix

- src/Services/AppointmentService.php
Added the duration field to the getAppointment method.  Added two helper methods for grabbing appointment status lists and checking if an appointment status is valid.  Minor documentation improvement as well.
> Add appointment service status methods.

- composer.json
- composer.lock
Made this to match the lock file.  Fixed the mispelling and the version.
Fixes #4763.
> Changing event-dispatcher-contracts dependency

- src/Services/Cda/CdaTemplateParse.php
> QRDA fixes

- src/Billing/BillingProcessor/X12RemoteTracker.php
- src/Billing/InvoiceSummary.php
https://github.com/openemr/openemr/pull/4772#issuecomment-983089582
> fix declaration fatal errors with empty array assignment

- docker/development-insane/README.md
- docker/development-insane/docker-compose.yml
- docker/library/dockers/dev-nginx/nginx.conf
> make the insane dev environment less insane

- controllers/C_Document.class.php
- interface/forms/clinical_notes/new.php
- interface/logview/logview.php
- interface/main/calendar/modules/PostCalendar/common.api.php
- interface/reports/collections_report.php
- library/formatting.inc.php
- library/htmlspecialchars.inc.php
- library/options.inc.php
- library/translation.inc.php
- src/Gacl/Gacl.php
- src/Services/ProductRegistrationService.php
> php 8.1 fixes

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
Fix importer PHP issue where string evaluated to 0 and caused medical problems to not be imported
@sjpadgett 
Fixes #
> Care Coordination Import Fix

- src/Common/Crypto/CryptoGen.php
> php 8.2 fix

- controllers/C_Document.class.php
- controllers/C_DocumentCategory.class.php
- controllers/C_InsuranceCompany.class.php
- controllers/C_Pharmacy.class.php
- controllers/C_Prescription.class.php
- interface/reports/daily_summary_report.php
- library/ESign/Viewer.php
- library/classes/Controller.class.php
- library/classes/InsuranceCompany.class.php
- library/classes/Patient.class.php
- library/classes/PhoneNumber.class.php
- library/classes/Prescription.class.php
- library/classes/Tree.class.php
- library/classes/TreeMenu.php
- library/classes/html2text.class.php
- library/classes/rulesets/Amc/library/AmcPatient.php
- library/classes/rulesets/Amc/library/AmcPopulation.php
- library/classes/rulesets/Amc/library/AmcResult.php
- library/classes/rulesets/Cqm/library/CqmPopulation.php
- library/classes/rulesets/Cqm/library/CqmResult.php
- library/classes/rulesets/library/RsPopulation.php
- portal/patient/fwk/libs/savant/Savant3.php
- portal/patient/fwk/libs/verysimple/Phreeze/SavantRenderEngine.php
- src/Common/Logging/EventAuditLogger.php
- src/Gacl/Gacl.php
- src/Menu/MenuRole.php
- src/Services/Search/BasicSearchField.php
couple more 8.2 fixes
(ok, now need to start working on mu3 stuff...)
> couple more 8.2 fixes

- interface/super/edit_layout.php
Warn users to avoid deletion of standard columns.
> Standard table alert for layout editor

- interface/super/edit_layout.php
> quick fix for last commit

- interface/billing/sl_eob_invoice.php
- interface/billing/sl_eob_search.php
- interface/patient_file/encounter/superbill_custom_full.php
- interface/reports/collections_report.php
- interface/super/edit_list.php
- library/sql.inc
- sites/default/statement.inc.php
- src/Billing/InvoiceSummary.php
- src/Services/EncounterService.php
Aging was previously based on date of service. This takes into account any insurance billing and whether it's the first statement sent to the person.
> improve aging, add billing notes to invoice, misc fixes

- contrib/forms/xmlformgen/xslt/save.php.xslt
> array key syntax for xmlformgen

- src/Core/Kernel.php
just seeing what happens if remove this line of code on ci testing
@robertdown @adunsulag odd to have this include in a class, but guessing there is a reason for it
> testing removal of a line of code in kernel class

- interface/super/edit_globals.php
> Wrap Globals save in a transaction.

- interface/eRxGlobals.php
- interface/eRx_xml.php
- interface/globals.php
- interface/main/about_page.php
- portal/patient/templates/_Footer.tpl.php
- sql_patch.php
- src/Services/ProductRegistrationService.php
- src/Services/VersionService.php
bye bye $GLOBALS['openemr_version'] :)
> complete migration to VersionService class

- library/classes/Installer.class.php
- setup.php
> check for initial user last name in setup

- src/Reminder/BirthdayReminder.php
Fixes #4815
fix a bug
alter function for displaying birthday alert
> fix birthday bug

- interface/main/tabs/menu/menus/standard.json
- interface/patient_file/front_payment.php
- interface/reports/payment_processing_report.php
- interface/super/edit_globals.php
- library/globals.inc.php
- portal/lib/paylib.php
- portal/portal_payment.php
- sites/default/documents/custom_menus/Custom.json
- sphere/initial_response.php
- sphere/process_response.php
- sphere/process_revert_response.php
- sphere/token.php
- sql/6_0_0-to-6_1_0_upgrade.sql
- sql/database.sql
- src/Common/Auth/AuthGlobal.php
- src/PaymentProcessing/PaymentProcessing.php
- src/PaymentProcessing/Sphere/Sphere.php
- src/PaymentProcessing/Sphere/SpherePayment.php
- src/PaymentProcessing/Sphere/SphereRevert.php
- src/Services/Globals/GlobalSetting.php
- version.php
This supports (Sphere tool that was integrated is in parenthesis):
1. Payment capture from front office (Trustee Premier for MOTO)
2. Payment capture from patient portal (Trustee Premier for Ecomm)
3. void/credit of payments (Trustee API)
Main advantage of this approach is that all the sensitive info (cc number) is captured on Sphere's web server and not done on OpenEMR's server. Note there are 3 different Sphere tools that are utilizing, which are listed above, and is why there are several global credentials required for this. Note the front office uses a card reader (or the machine can enter in the cc number); btw, the machines for front office basically leverage native keyboard drivers so super easy to work (basically just focus the field on web page and then read card or enter data …
> Adding support for Sphere payment processing

- .github/workflows/styling.yml
- interface/main/tabs/menu/menus/standard.json
- interface/patient_file/front_payment.php
- interface/reports/payment_processing_report.php
- interface/super/edit_globals.php
- library/globals.inc.php
- portal/lib/paylib.php
- portal/portal_payment.php
- sites/default/documents/custom_menus/Custom.json
- sphere/initial_response.php
- sphere/process_response.php
- sphere/process_revert_response.php
- sphere/token.php
- sql/database.sql
- sql/patch.sql
- src/Common/Auth/AuthGlobal.php
- src/PaymentProcessing/PaymentProcessing.php
- src/PaymentProcessing/Sphere/Sphere.php
- src/PaymentProcessing/Sphere/SpherePayment.php
- src/PaymentProcessing/Sphere/SphereRevert.php
ported from master commit https://github.com/openemr/openemr/commit/802e587138eda86e0d54d6be69243cefbeb57695
> Added support for Sphere payment processing (rel-600 port)

- interface/usergroup/user_admin.php
Fixes #4380 
add a checkbox to show and hide for the reset password
> add a checkbox to show and hide password

- portal/index.php
Replacing package used to display messages by Bootstrap's alerts.
> Use BS Alerts instead of gritter

- config/config.yaml
- package-lock.json
- package.json
> bye bye gritter dependency

- interface/patient_file/front_payment.php
- library/globals.inc.php
- portal/portal_payment.php
- sphere/process_response.php
- src/PaymentProcessing/PaymentProcessing.php
- src/PaymentProcessing/Sphere/Sphere.php
- src/PaymentProcessing/Sphere/SpherePayment.php
- src/PaymentProcessing/Sphere/SphereRevert.php
Needed to differentiate between office payments that were taken
over the phone (MOTO) versus office payments that were taken
in person (RETAIL).
> Sphere payment processing update

- interface/forms/LBF/new.php
- library/options.inc.php
Fixes #4735
Fixed Layout Based Form Validation Failure
> Fixed Layout Based Form Validation Failure #4735

- interface/forms/LBF/new.php
- portal/account/account.lib.php
- portal/account/account.php
- portal/account/register.php
- portal/add_edit_event_user.php
- portal/find_appt_popup_user.php
- portal/home.php
- portal/import_template.php
- portal/index.php
- portal/lib/download_template.php
- portal/lib/patient_groups.php
- portal/messaging/secure_chat.php
- portal/patient/libs/Controller/OnsiteDocumentController.php
- portal/patient/scripts/app/onsitedocuments.js
- portal/patient/templates/OnsiteDocumentListView.tpl.php
- portal/portal_payment.php
- src/Services/DocumentTemplates/DocumentTemplateService.php
- templates/portal/appointment-item.html.twig
- templates/portal/base.html.twig
- templates/portal/header.html.twig
- templates/portal/home.html.twig
Move all new template menu to action bar dropdown New Documents
Restyle appointments to cards
Fixes to chat
Synchronize SPA panel collapses
Override theme for ckeditor height!
> Portal cleanups and fixes

- src/Services/Utils/SQLUpgradeService.php
@sjpadgett , thanks for this new upgrade feature! On my review I forgot to point out escaping (this miss in addition to my screenshot mistake merits demotion or a 1 minute ban from github :) ). Adding escaping here. Also changed it to only show verbage if it is not "skipped". testing well.
> minor upgrade adjustments for escaping and skipping

- interface/usergroup/usergroup_admin.php
Use `table-sm` on the table for users. Drop the `.alert` div in favor of styling the `<td>` of the password expiration column. Only draw attention to the row if they are in grace or expired.
> Improved User Group UI

- interface/main/calendar/add_edit_event.php
- interface/main/calendar/find_appt_popup.php
- interface/super/edit_globals.php
[Fixes forum report](https://community.open-emr.org/t/next-available-shift-not-working-with-24-hour-format-bug-report/17716/9)
> Calendar: Time Display Format 24 hr global fix for Find Available Appointment

- interface/patient_file/summary/demographics.php
> Fix styling issues

- interface/patient_file/pos_checkout_normal.php
> Fix percentage discount

- package-lock.json
- package.json
fixes #4868 
quick build fixes to remove ssh requirements
this will ensure dev dockers and demos keep working
> quick build fixes to remove ssh requirements

- interface/orders/list_reports.php
- interface/orders/receive_hl7_results.inc.php
- interface/patient_file/summary/demographics.php
- src/Services/FacilityService.php
Fixes #4869 #4874
removed exception.
added fix for patient delete
> service throws eception instead should be graceful

- interface/main/messages/messages.php
> fix fortawesome sort classes in messages

- interface/super/rules/base/template/basic.php
- interface/super/rules/controllers/browse/view/list.php
- interface/super/rules/controllers/browse/view/plans_config.php
- interface/super/rules/controllers/detail/view/view.php
- interface/super/rules/controllers/edit/helper/common.php
- interface/super/rules/controllers/edit/template/criteria.php
- interface/super/rules/controllers/edit/view/action.php
- interface/super/rules/controllers/edit/view/add_criteria.php
- interface/super/rules/controllers/edit/view/age.php
- interface/super/rules/controllers/edit/view/bucket.php
- interface/super/rules/controllers/edit/view/custom.php
- interface/super/rules/controllers/edit/view/diagnosis.php
- interface/super/rules/controllers/edit/view/intervals.php
- interface/super/rules/controllers/edit/view/lifestyle.php
- interface/super/rules/controllers/edit/view/sex.php
- interface/super/rules/controllers/edit/view/simple_text_criteria.php
- interface/super/rules/controllers/edit/view/summary.php
- interface/super/rules/include/ui.php
- interface/super/rules/www/css/cdr-multiselect/common.css
- interface/super/rules/www/css/cdr-multiselect/plans_config.css
- interface/super/rules/www/js/bucket.js
- interface/themes/misc/rules.scss
Fixes #4890
Clean up rules engine UI
> Rules UI Restyle

- library/sqlconf.php
Trying to fix the failing tests from #4892
> Condition away potential fatal errors during auto install

- interface/reports/encounters_report.php
> add toEncounter button to encounters report

- README.md
Elaborated the instructions of the readme file as per suggestions, where I found it difficult to understand.
Fixing issue #4909
> Readme docs updated more meaningful, opened the issue and linked it

- portal/import_template.php
- portal/import_template_ui.php
- portal/lib/patient_groups.php
- portal/messaging/handle_note.php
- portal/messaging/messages.php
- sql/6_0_0-to-6_1_0_upgrade.sql
- src/Services/DocumentTemplates/DocumentTemplateService.php
- templates/portal/home.html.twig
fix chat scroll
remove return home in portal messages
> Portal Updates

- portal/add_edit_event_user.php
- portal/home.php
- portal/lib/paylib.php
- portal/lib/persist.php
From issue found in v6 backport.
> fix portal session

- interface/patient_file/summary/demographics.php
div.main > row:first  needs closure.
> Add closing tag

- .github/workflows/test.yml
- ci/apache_74_106/docker-compose.yml
- ci/apache_80_102/docker-compose.yml
- ci/apache_80_103/docker-compose.yml
- ci/apache_80_105/docker-compose.yml
- ci/apache_80_106/docker-compose.yml
- ci/apache_80_107/docker-compose.yml
- ci/apache_80_57/docker-compose.yml
- ci/apache_80_8/docker-compose.yml
- ci/ciLibrary.source
ci: add mariadb 10.7 and updated to currently used alpine 3.15 dockers
> ci: add mariadb 10.7 and updated to currently used alpine 3.15 dockers

- sql/6_1_0-to-7_0_0_upgrade.sql
- version.php
incrementing to 7.0.0-dev in master to prepare for 6.1.0 release
> incrementing to 7.0.0-dev in master to prepare for 6.1.0 release

- .github/workflows/styling.yml
- .github/workflows/syntax.yml
- .github/workflows/test.yml
- README.md
set up github actions for rel-610 branch
> set up github actions for rel-610 branch

- ccdaservice/ccda_gateway.php
- ccdaservice/serveccda.js
- interface/main/tabs/main.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
- library/globals.inc.php
- library/weno_log_sync.php
- portal/get_patient_info.php
- portal/home.php
- portal/patient/templates/OnsiteDocumentListView.tpl.php
- src/Services/CDADocumentService.php
- templates/portal/base.html.twig
- templates/portal/header.html.twig
- templates/portal/home.html.twig
add CCD download to portal menu
update some icons
fix CDADocumentService
fix some CCM module CDA weirdness
fix new CCD view in patient report
change Your Documents to Select Documents in portal toolbar
Fixes #4925
Portal inactivity #4933 
Fix for weno log issue #4930 Removed global required.
Add javascript translation capability to portal #4939
> Updates concerning CCDA and portal

- interface/main/finder/dynamic_finder.php
Fixes #
save a million clicks :smile_cat:
> focus on name in pt finder

- interface/login/login.php
- portal/index.php
removed as is not needed for login
> Portal login checkUserName() undefined error quick fix

- config/config.yaml
- interface/main/tabs/js/shortcuts.js
- interface/main/tabs/main.php
- package-lock.json
- package.json
- version.php
Not the most extendable solution, but this is a start of supporting keyboard shortcuts. For now it support `alt+1` (Go to calendar), `alt+2` (Go to Patient Finder), and `alt+shift+w` (Clear the patient). Would like to also support `alt+r` as a refresh of the current tab, but was having some issues getting that working.
I think this is a good starting point. Some basic navigation. Eventually I'd love to have more robust support but for now, let's run with this.
> Keyboard shortcut support

- interface/main/tabs/menu/menus/standard.json
- interface/main/tabs/templates/user_data_template.php
- interface/themes/oe-styles/style_light.scss
- sites/default/documents/custom_menus/Custom.json
- tests/Tests/E2e/Pages/MainPage.php
Move the Patient Finder menu item from underneath Patient/Client to the top level as the second menu item.
> Promote Patient Finder to top-level menu

- interface/main/tabs/templates/user_data_template.php
- interface/modules/zend_modules/module/Documents/src/Documents/Plugin/Documents.php
- made about page path relative
- CCM Import Documents fetchXmlDocuments() static function fix
Fixes #4968
> Various bug fixes

- interface/patient_file/education.php
- interface/patient_file/summary/demographics.php
- interface/super/rules/controllers/detail/view/view.php
- interface/super/rules/controllers/edit/controller.php
- interface/super/rules/controllers/edit/view/summary.php
- interface/super/rules/library/Rule.php
- interface/super/rules/library/RuleManager.php
- library/clinical_rules.php
- sql/6_1_0-to-7_0_0_upgrade.sql
- sql/database.sql
- version.php
> complete a9

- interface/main/messages/messages.php
- interface/patient_file/summary/pnotes_fragment.php
- interface/patient_file/summary/pnotes_full.php
- interface/patient_file/summary/pnotes_full_add.php
- library/pnotes.inc
complete e3
yep, all of this to simply support a "clickable link" in pnotes to pass e3 :)
https://www.open-emr.org/wiki/index.php/Patient_health_information_capture_(MU3))
> complete e3

- docker/library/dockers/dev-php-fpm-7-4-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-7-4/Dockerfile
- docker/library/dockers/dev-php-fpm-8-0-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-8-0/Dockerfile
- docker/library/dockers/dev-php-fpm-8-1-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-8-1/Dockerfile
> fix ci nginx fails

- library/patient.inc
Fixes #4992
set colnames for update to passed in keys of data array
> update employer data with colnames of passed in data keys

- contrib/util/language_translations/collectConstants.pl
- contrib/util/language_translations/filterDirectories.txt
- contrib/util/language_translations/manuallyRemovedConstants.txt
- interface/forms/eye_mag/php/taskman_functions.php
- interface/forms/gad7/new.php
- interface/language/csv/commit_csv.php
- library/globals.inc.php
- src/Billing/BillingProcessor/Tasks/GeneratorHCFA_PDF.php
- src/RestControllers/SMART/SMARTAuthorizationController.php
- src/Services/PatientService.php
> constants optimize

- src/Services/Qdm/MeasureService.php
- src/Services/Qdm/Services/PatientService.php
These were supposed to be in already!
> missed files previous PR

- interface/usergroup/user_admin.php
- interface/usergroup/usergroup_admin.php
- interface/usergroup/usergroup_admin_add.php
We track it in the database but there wasn't a mechanism for setting a
provider's default billing facility. Since we need that for AMC and CCDA
I've gone ahead and added that in.
> Fixes #5006 User Default Billing Facility

- interface/billing/edit_payment.php
- interface/billing/payment_master.inc.php
- interface/billing/sl_eob_process.php
- src/Billing/ParseERA.php
- src/Services/FacilityService.php
gotta be a few of these in #4793
suppress php 8 warnings
using null coalesce a bunch
> fix warnings

- package-lock.json
- package.json
updated our npm for oe-cqm-parser version to 5.6.0
> update package.json for new oe-cqm-parser version

- interface/forms/observation/new.php
- interface/forms/observation/save.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- library/globals.inc.php
- src/Services/Cda/CdaTemplateImportDispose.php
- src/Services/Cda/CdaTemplateParse.php
- src/Services/Qrda/Helpers/Date.php
- src/Services/Qrda/QrdaReportService.php
update ObservationPerformed template for PQ and CD data types
fix encounter observation form to display ob value and units.
> QRDA import parsing fixes

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml
fix ethnicity not parsing correctly
More to come like mass import add patient
> Some Import fixes

- _rest_routes.inc.php
- swagger/openemr-api.yaml
update dev api version to 7.0.0
> update dev api version to 7.0.0

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
@adunsulag 
Hope this is what is needed. Result flag is map_id true/false. Didn't know if you need to map to document or even the transaction map_id but, you can change as you need.
Bring in if I'm not around.
> Add ccda meets amc numerator for med,allergies and problems

- interface/patient_file/summary/add_edit_issue.php
- src/Services/PatientIssuesService.php
> fix for issue comments not saved

- controllers/C_Document.class.php
- interface/forms/eye_mag/a_issue.php
- interface/forms/eye_mag/php/eye_mag_functions.php
- interface/forms/eye_mag/php/taskman_functions.php
- interface/forms/eye_mag/report.php
- interface/forms/eye_mag/save.php
- interface/forms/eye_mag/view.php
- interface/patient_file/summary/advancedirectives.php
> sql error and php8 Eye form warnings resolved

- interface/forms/eye_mag/php/eye_mag_functions.php
- interface/patient_tracker/patient_tracker.php
- src/Billing/BillingProcessor/BillingClaim.php
- src/Billing/BillingProcessor/BillingClaimBatch.php
- src/Billing/BillingProcessor/BillingProcessor.php
- src/Billing/BillingProcessor/Tasks/AbstractGenerator.php
- src/Billing/BillingProcessor/Tasks/GeneratorHCFA.php
- src/Billing/BillingProcessor/Tasks/GeneratorHCFA_PDF_IMG.php
- src/Common/Crypto/CryptoGen.php
> restore missing hcfa text file

- interface/forms/eye_mag/php/eye_mag_functions.php
- interface/forms/eye_mag/php/taskman_functions.php
- interface/forms/eye_mag/view.php
> fix some handling of empties in recent eye form warning clean up

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- src/Cqm/QrdaControllers/QrdaReportController.php
Fixes #
fix race code not populate patient data
Note @kchapple
> fix race import

- src/Services/InsuranceCompanyService.php
- src/Validators/InsuranceCompanyValidator.php
> clean up insurance company service and validator

- composer.json
- composer.lock
> revert composer from PR #5046

- interface/modules/zend_modules/public/js/application/sendTo.js
Fixes #5078 Make the ccda generation process first and then do the transmitCCDA function in CCM.
> Fixes #5078 CCM Direct Timing

- portal/account/verify.php
registration email verify fix when language menu is off
> registration email verify fix when language menu is off

- library/classes/Installer.class.php
Fixes #5073 
adds theme for multi site clone
> theme fixes for multi site clones

- interface/modules/zend_modules/module/Application/src/Application/Model/ApplicationTable.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
Fixes #5076 Make the care coordination module use the trusted email field instead of the regular email field in the address book.
> Fixes #5076 use email_direct not email

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncountermanagerController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- src/Services/Cda/CdaTemplateImportDispose.php
- src/Services/Cda/CdaTemplateParse.php
- src/Services/Qrda/Helpers/Cat1View.php
- src/Services/Qrda/Helpers/Date.php
- src/Services/Qrda/qrda-export/catI-r5/_codes.mustache
- src/Services/Qrda/qrda-export/catI-r5/qrda_templates/template_partials/_author.mustache
- src/Services/Qrda/qrda-export/catI-r5/qrda_templates/template_partials/_data_element_codes_as_values.mustache
- src/Services/Qrda/qrda-export/catI-r5/qrda_templates/template_partials/_entity.mustache
- src/Services/Qrda/qrda-export/catI-r5/qrda_templates/template_partials/_results.mustache
- src/Services/Qrda/qrda-export/catIII/_supplemental_data.mustache
countable exception EncountermanagerController on refresh
> Some CCM QRDA Fixes

- interface/forms/eye_mag/php/eye_mag_functions.php
- interface/forms/eye_mag/view.php
- interface/patient_file/encounter/find_code_popup.php
- interface/patient_file/summary/add_edit_issue.php
Fixes couple other things in #5040
> return empty array plus fix path to chart.js in eye form

- src/Billing/BillingProcessor/Tasks/AbstractGenerator.php
- src/Billing/BillingProcessor/Tasks/GeneratorHCFA.php
- src/Billing/BillingProcessor/Tasks/GeneratorHCFA_PDF.php
- src/Billing/BillingProcessor/Tasks/GeneratorX12.php
https://github.com/openemr/openemr/pull/5037/files/6b69e0302d3c08101d5cd90c71e7aacba2d6f3f3#r841331470
> quick Hcfa fix

- src/Services/Cda/CdaTemplateParse.php
procedure activity-performed
Unexpected oid order. QRDA is so weird about sometimes using the CDA template to wrap QRDA template and other times just sending the QRDA template.
> Fix Cat1 missing 2.16.840.1.113883.10.20.22.4.14 oid

- interface/forms/care_plan/new.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- sql/6_1_0-to-7_0_0_upgrade.sql
- sql/database.sql
- src/Services/Cda/CdaTemplateImportDispose.php
- src/Services/Cda/CdaTemplateParse.php
- version.php
fix missing low/high dates for substance medication activity
@kchapple If want grab the src/Services/Cda directory from my repo
> QRDA Parsing

- src/Services/Cda/CdaTemplateParse.php
substitute null flavor code with value set oid
note @kchapple
> Fix negated qrda resource code

- src/Services/Qdm/QdmBuilder.php
- src/Services/Qdm/Services/AbstractCarePlanService.php
- src/Services/Qdm/Services/AbstractQdmService.php
- src/Services/Qdm/Services/DiagnosisService.php
- src/Services/Qdm/Services/DiagnosticStudyOrderedService.php
- src/Services/Qdm/Services/EncounterService.php
- src/Services/Qdm/Services/InterventionOrderedService.php
- src/Services/Qdm/Services/LaboratoryTestOrderedService.php
- src/Services/Qdm/Services/MedicationOrderService.php
- src/Services/Qdm/Services/PatientService.php
- src/Services/Qdm/Services/PhysicalExamService.php
- src/Services/Qdm/Services/ProcedureRecommendedService.php
- src/Services/Qdm/Services/SubstanceRecommendedService.php
- src/Services/Qrda/Cat1.php
- src/Services/Qrda/Helpers/Date.php
@sjpadgett here are some additions for care plans.
> add care plans to QDM models for template rendering

- src/Services/Qdm/PopulationSet.php
Fixes #5104 Left out a missing class which is my fault.
> Committing missing populationset file

- composer.json
- composer.lock
- interface/patient_file/summary/demographics.php
- interface/patient_file/summary/demographics_full.php
- interface/practice/address_verify.php
- library/globals.inc.php
- src/Billing/EDI270.php
- src/USPS/USPSAddress.php
- src/USPS/USPSAddressVerify.php
- src/USPS/USPSBase.php
Fixes #5099 
verifies demographics contact address with usps web api
added some code to implement
> Usps address verification

- src/Services/Qdm/Services/AbstractCarePlanService.php
> very minor fix

- src/Cqm/Qdm/Traits/PatientExtension.php
- src/Services/Qdm/CqmCalculator.php
- src/Services/Qdm/IndividualResult.php
- src/Services/Qdm/QdmBuilder.php
- src/Services/Qdm/ResultsCalculator.php
- src/Services/Qdm/Services/PatientService.php
- src/Services/Qrda/AggregateCount.php
- src/Services/Qrda/Cat3.php
- src/Services/Qrda/ExportCat3Service.php
- src/Services/Qrda/qrda-export/catIII/_header.mustache
This builds on commits by @adunsulag to add the aggregate counts to the QRDA Cat III xml document.
> Openemr cqm supplemental data

- interface/main/backup.php
- library/classes/Installer.class.php
fixed #5096
(still need to test)
> skip view when backup

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
- interface/modules/zend_modules/module/Carecoordination/view/carecoordination/encountermanager/index.phtml
- src/Cqm/QrdaControllers/QrdaReportController.php
- src/Services/CodeTypesService.php
- src/Services/Qrda/Cat1.php
- src/Services/Qrda/Helpers/Date.php
- src/Services/Qrda/Helpers/View.php
- src/Services/Qrda/QrdaReportService.php
add last chance lookup for system OID from code type
Missed OID for HCPCS causing validation errors for these codes
@kchapple note.
> Various QRDA Changes

- interface/forms/CAMOS/content_parser.php
Fixes #5120 
a require path wasn't working
fixed require path
> fix path and php8 int cast too

- src/Services/Qdm/Services/AbstractCarePlanService.php
- src/Services/Qdm/Services/AbstractObservationService.php
- src/Services/Qdm/Services/AbstractQdmService.php
- src/Services/Qdm/Services/AssessmentService.php
- src/Services/Qdm/Services/DiagnosticStudyOrderedService.php
- src/Services/Qdm/Services/DiagnosticStudyService.php
- src/Services/Qdm/Services/EncounterService.php
- src/Services/Qdm/Services/InterventionOrderedService.php
- src/Services/Qdm/Services/LaboratoryTestOrderedService.php
- src/Services/Qdm/Services/MedicationOrderService.php
- src/Services/Qdm/Services/PatientService.php
- src/Services/Qdm/Services/PhysicalExamService.php
- src/Services/Qdm/Services/ProcedureRecommendedService.php
- src/Services/Qdm/Services/SubstanceRecommendedService.php
@sjpadgett Here's the addition of payer, works with Cat i, haven't tested yet with Cat iii.
> Add Payer patient characteristic to QDM model

- interface/forms/eye_mag/php/eye_mag_functions.php
- interface/forms/eye_mag/view.php
- interface/patient_file/encounter/find_code_popup.php
- interface/patient_file/summary/add_edit_issue.php
- src/Billing/BillingProcessor/Tasks/AbstractGenerator.php
- src/Billing/BillingProcessor/Tasks/GeneratorHCFA.php
- src/Billing/BillingProcessor/Tasks/GeneratorHCFA_PDF.php
- src/Billing/BillingProcessor/Tasks/GeneratorX12.php
merge 3 upstream fixes into rel-610
b0a00ae2937b03407790b1aac197349b5e692024
81b2f41066daf34350b5fd5467e1198d0400f096
68789f3ee804b51eead49bde9f0bf85868eb33a8
> eye form fixes with merged fix to code type selector and minor billing fixes from upstream

- interface/patient_file/summary/demographics_save.php
- library/options.inc.php
Fixes #5135 
no display of data due to bad conditional
> fix stats and misc dashboard for omit employer section

- interface/patient_file/summary/stats.php
- interface/patient_tracker/patient_tracker.php
- src/Rx/Weno/LogProperties.php
- src/Rx/Weno/TransmitProperties.php
- templates/patient/card/card_base.html.twig
- templates/patient/card/rx.html.twig
Fixes #5140
adds weno back to the prescription dashboard plus some minor php8 fixes
> weno fixes

- src/Cqm/Qdm/DeviceApplied.php
- src/Cqm/Qdm/NegativeDeviceApplied.php
- src/Services/Qdm/QdmBuilder.php
- src/Services/Qdm/ResultsCalculator.php
- src/Services/Qdm/Services/DeviceAppliedService.php
- src/Services/Qdm/Services/DeviceOrderService.php
- src/Services/Qdm/Services/ProcedureService.php
- src/Services/Qrda/AggregateCount.php
- src/Services/Qrda/Cat3.php
- src/Services/Qrda/QrdaReportService.php
- src/Services/Qrda/qrda-export/catI-r5/qrda_templates/device_applied.mustache
Work-in-progress branch for Cat iii fixes.
@sjpadgett I fixed some low-hanging fruit here. Still a lot of cloudy stuff to figure out.
> Cat iii fixes

- interface/forms/fee_sheet/new.php
- interface/patient_file/rules/patient_data.php
- interface/reports/pat_ledger.php
- library/FeeSheet.class.php
- library/custom_template/custom_template.php
- library/globals.inc.php
- src/Billing/BillingUtilities.php
Fixes #4334 
[forum post](https://community.open-emr.org/t/big-issue-with-fee-sheet-record-payment-windows/18291?u=stephenwaite)
> void checkout or reopen global and logic to support

- src/Services/Cda/CdaTemplateImportDispose.php
- src/Services/Cda/CdaTemplateParse.php
- src/Services/Qdm/Services/EncounterService.php
> Qrda encouter issue

- _rest_routes.inc.php
- interface/forms/vitals/templates/vitals/vitals_textbox.tpl
- interface/forms/vitals/templates/vitals/vitals_textbox_conversion.tpl
- src/Common/Forms/FormVitals.php
- src/Common/Uuid/UuidMapping.php
- src/Common/Uuid/UuidRegistry.php
- src/Services/CarePlanService.php
- src/Services/FHIR/DocumentReference/FhirClinicalNotesService.php
- src/Services/FHIR/DocumentReference/FhirPatientDocumentReferenceService.php
- src/Services/FHIR/FhirCarePlanService.php
- src/Services/FHIR/FhirImmunizationService.php
- src/Services/FHIR/FhirMedicationRequestService.php
- src/Services/FHIR/FhirOrganizationService.php
- src/Services/FHIR/FhirProvenanceService.php
- src/Services/FHIR/Procedure/FhirProcedureOEProcedureService.php
- src/Services/ImmunizationService.php
- src/Services/SurgeryService.php
- tests/Tests/Services/CarePlanServiceTest.php
This brings in the following PRs
- #5139 
- #5138 
- #5129 
- #5097 
Which fix the following issues:
- #5127
- #5137 
- #5122 
- #5123 
- #5125 
- #5095
> Merge FHIR Bug Fixes To Release 6.1.0

- interface/smart/register-app.php
Fixes #5161 
Added radio buttons to choose the application context (single patient, multiple patient, client, multi-purpose).
> Fixes #5161 Add application context to SMART app registration

- interface/smart/register-app.php
Fixex #5162 
Make register-app match login colors and show the logo.
> Fixes #5162 Show the logo.

- src/FHIR/SMART/ClientAdminController.php
Add a button to the client list page to register a smart app.
> Fixes #5163 Add App Register Button

- sql/6_1_0-to-7_0_0_upgrade.sql
Fixes #5183 Malay language code needs to be set as well.
> Openemr fix language codes - Missing Malay Language

- oauth2/provider/scope-authorize.php
- src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
- src/RestControllers/AuthorizationController.php
Made the fhir authorization screen show human readable permission descriptions.  Also added the application being authorized.
> Fixes #5192 Improved FHIR Auth page.

- src/Services/FHIR/FhirAllergyIntoleranceService.php
Missing system value for allergy intolerance
Fixes #5187
> Fixes #5187 Allergy Intolerance System

- interface/patient_file/encounter/find_code_popup.php
Fixes #5197 Set the default codetype on a search if its populated in the post.
> Fixes #5197 Set default codetype

- src/FHIR/SMART/ClientAdminController.php
Use webroot for the smart app launch button.
Fixes #5203
> Fixes #5203 smart app btn use webroot

- library/globals.inc.php
> added Uzbek language

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
- src/Services/Qdm/Services/PatientService.php
- src/Services/Qrda/Cat1.php
- src/Services/Qrda/Helpers/View.php
@sjpadgett code was double-converting to hex, so all IDs were the same. This is the fix.
> fix hex conversion of PID

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncountermanagerController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- interface/modules/zend_modules/public/xsd/Schema/CDA2/infrastructure/cda/CDA_SDTC.xsd
- interface/modules/zend_modules/public/xsd/Schema/CDA2/infrastructure/cda/POCD_MT000040_SDTC.xsd
- interface/modules/zend_modules/public/xsd/Schema/CDA2/infrastructure/cda/SDTC.xsd
- interface/modules/zend_modules/public/xsd/Schema/CDA2/processable/coreschemas/NarrativeBlock.xsd
- interface/modules/zend_modules/public/xsd/Schema/CDA2/processable/coreschemas/datatypes-base_SDTC.xsd
- interface/modules/zend_modules/public/xsd/Schema/CDA2/processable/coreschemas/datatypes.xsd
- interface/modules/zend_modules/public/xsd/Schema/CDA2/processable/coreschemas/infrastructureRoot.xsd
- interface/modules/zend_modules/public/xsd/Schema/CDA2/processable/coreschemas/voc.xsd
- src/Services/Cda/CdaTemplateParse.php
- src/Services/Qrda/QrdaReportService.php
- implement node start service for cat3 report
- cleanup unused admin functions. They need to be in an admin class.
@kchapple note
> QRDA Report Service work

- src/Services/PatientService.php
Fixes #5221 
[new forum report](https://community.open-emr.org/t/fatal-error-in-office-ally-eligibility-work-flow-openemr-6-1/18360?u=stephenwaite)
> string + string operand fix

- ccr/transmitCCD.php
- interface/main/finder/document_select.php
- interface/main/messages/js/trusted-messages.js
- interface/main/messages/messages.php
- interface/main/messages/trusted-messages-ajax.php
- interface/main/messages/trusted-messages.php
- src/Services/DocumentService.php
* Fixes #5220 Send Trusted Direct Message
Implemented the ability to send messages w/o attachments via the EMR
Direct service over the Direct protocol.
Built the ability to select a document that has been uploaded to the
system and send it via EMRDirect.
Built a document finder dialog window so that you can select a patient
or non-patient document using the finder.  It checks against the current
user's ACLs and the document category's acos to determine if the user
can see the document.  It only shows 25 results at a time and requires
the user to be more specific in their search if they want to see more.
By default it displays the most recent documents uploaded.
* Direct pdf attachment send.
Made it so we can send a pdf attachment via direct.
Validated the mime types and reject any …
> Openemr fix #5220 direct send attachment (#5226)

- oauth2/provider/scope-authorize.php
- src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
Merging in the PR #5233 into the mu3 branch for testing.
> Fixes #5232 android oauth2 authorization issues. (#5233)

- interface/patient_file/encounter/find_code_popup.php
Fixes #5236 
one more commit for patch 1 to 610
once this is in can tag this as v6_1_0_1
> code type selector fix

- src/Billing/Claim.php
- src/Billing/X125010837P.php
> x12clean submitter name, and some styling fixes

- library/ajax/adminacl_ajax.php
> acl admin fix to allow removing membership from a user

- templates/patient/card/photo.html.twig
> remove bad pt photo link in demographic widget

- library/ajax/adminacl_ajax.php
> rel-610: acl admin fix to allow removing membership from a user 

- interface/forms/newpatient/common.php
- interface/forms/newpatient/save.php
- src/Services/FHIR/FhirEncounterService.php
Fixes #5254 Made the dates in the encounter for Date of Service and Onset/Hosp date to be date time pickers as we need those for CQM.  @stephenwaite this should get the encounters QDM working.
> Fixes #5254 Encounter DateTime picker

- interface/forms/eye_mag/php/eye_mag_functions.php
- interface/forms/eye_mag/report.php
> fix new Chart call and php8 warnings

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncountermanagerController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncountermanagerTable.php
- interface/modules/zend_modules/module/Carecoordination/view/carecoordination/encountermanager/index.phtml
- interface/modules/zend_modules/public/js/carecoordination/encounterManager.js
- src/Cqm/QrdaControllers/QrdaReportController.php
- src/Services/Qdm/Services/ImmunizationAdministeredService.php
- src/Services/Qrda/ExportCat3Service.php
- src/Services/Qrda/QrdaReportService.php
add conditional to cvx_code in service
> Prcedures and Other

- interface/patient_file/summary/demographics.php
Fixes #https://github.com/openemr/openemr/pull/5142#issuecomment-1115529045
> quick fix for editing of demos and ins

- library/ESign/DbRow/Signable.php
Fixes #
https://github.com/openemr/openemr/issues/5279
Doesn't fix anything. It is just minor housekeeping. I am sure someone else saw it and decided to ignore it. The code still works.
> PHPStorm suggested changing this the properties to protected

- src/RestControllers/AuthorizationController.php
- src/Services/EncounterService.php
- src/Services/FHIR/FhirEncounterService.php
- tests/api/InternalFhirTest.php
> add referring provider to FhirEncounterService

- interface/patient_file/summary/add_edit_issue.php
- interface/patient_file/summary/stats_full.php
Fixes #5278 
Added the datetime selector to the begin and end date fields for all the issues.  This brings things in line for CQM reporting.
> Fixes #5278 issues Datetime selector begin/end

- interface/modules/zend_modules/module/CodeTypes/src/CodeTypes/Listener/CodeTypeEventsSubscriber.php
Fixes #5260  - Oops had this commit left out of the prior release which was breaking the upgrade process.
CPT4 lookup comes from the codes table not the code_cpt4 table.
Changing the code to use that table and check if the codes are active on
whether to do our mapping.
> Remove reliance on cpt4 table.

- ccdaservice/serveccda.js
- interface/modules/zend_modules/module/Application/view/application/sendto/send.phtml
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
- src/Services/Cda/CdaTemplateImportDispose.php
- src/Services/DocumentTemplates/DocumentTemplateService.php
adding document type for  rendering referral note, CCD,Careplan and Toc
Fixes #5266 
Need to setup CDA document type headers for various documents e.g. CCD,Referral/ToC etc.
> CCDA Udpates

- .github/PULL_REQUEST_TEMPLATE.md
> ask for issue when PR'ing

- API_README.md
Fixes #5292 add documentation for public private app token request with authorization_code grant.
> FHIR example public/private app authorization_code

- interface/forms/eye_mag/php/eye_mag_functions.php
- interface/forms/eye_mag/report.php
for patch 2 via https://github.com/openemr/openemr/issues/5251
> fix new Chart call and php8 warnings (#5252)

- interface/modules/zend_modules/module/Carecoordination/view/carecoordination/encountermanager/index.phtml
- src/Cqm/QrdaControllers/QrdaReportController.php
> rework zip archive for QRDA CATI Testing Record Sample

- interface/forms/care_plan/careplan.js
- interface/forms/care_plan/templates/careplan_reason_row.php
- interface/patient_file/encounter/find_code_popup.php
> allow for researching for codes in find code popup

- portal/portal_payment.php
> quick fix prior commit

- interface/forms/care_plan/new.php
- interface/forms/observation/new.php
- interface/forms/procedure_order/common.php
- interface/forms/procedure_order/templates/procedure_reason_row.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml
- src/Services/Cda/CdaTemplateParse.php
- src/Services/CodeTypesService.php
- src/Services/Qrda/Helpers/Cat1View.php
> add tooltip for care plan form code field and php8 fixes

- interface/patient_file/encounter/find_code_popup.php
> hardcode OID codetype in find code popup

- interface/forms/care_plan/careplan.js
- interface/forms/care_plan/templates/careplan_actions.php
- interface/forms/observation/observation.js
- interface/forms/observation/templates/observation_actions.php
- interface/forms/procedure_order/common.php
> care plan now able to delete first entry if more than 1

- src/Services/BaseService.php
- src/Services/Qdm/Services/PatientService.php
> save date field as null if empty, add type primary to qdm pt svc

- interface/patient_file/summary/add_edit_issue.php
> fix add edit issue to save begin date, end date and return date as null

- interface/super/edit_layout_props.php
https://github.com/openemr/openemr/issues/5331
Fixes #5331 
LBT not displaying the title in the patient chart
Add a message to change category
> Adding reminder for transaction form generation

- ccdaservice/package-lock.json
> minor changes to ccdaservice/package-lock.json

- library/classes/InsuranceCompany.class.php
- sql/6_1_0-to-7_0_0_upgrade.sql
- sql/database.sql
- src/Services/InsuranceCompanyService.php
- src/Services/Qdm/Services/PatientService.php
- templates/insurance_companies/general_edit.html
- version.php
> cqm source of payment for insurance companies

- interface/forms/procedure_order/common.php
- interface/patient_file/summary/demographics_full.php
- interface/patient_file/summary/immunizations.php
- sql/6_1_0-to-7_0_0_upgrade.sql
- sql/database.sql
> increase field length for procedure code in procedure_type, remove unwanted contrib file

- interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml
- src/Cqm/QrdaControllers/QrdaReportController.php
- src/Services/Qrda/QrdaReportService.php
Fixes #5353 
Make it so we include partial pids of patients.
Fix escaping for duplicate merge patients on qrda.
Fix the directory mkdir to work on linux for the cat3_export.
> CQM cat3 report fixes #5353

- interface/forms/procedure_order/delete.php
- interface/patient_file/encounter/delete_form.php
- src/Services/Qdm/Services/ProcedureService.php
> custom delete form for procedure and change to associated Qdm service

- src/Services/Qdm/QdmRequestSome.php
@sjpadgett I haven't tested this update, but this should get you close. I don't think this was used previously in the system anywhere, so never got a full workout.
> Attempt to fix QdmRequestSome implementation of QDMRequestInterface

- src/Services/Cda/CdaTemplateImportDispose.php
Fixes #
immunization import change to populate option id for refusal code
> Immunization import

- library/report.inc
Fixes #5373 
Deleted codes show on patient billing report.
> filter deleted codes from billing report

- ccdaservice/oe-blue-button-generate/lib/documentLevel.js
- ccdaservice/oe-blue-button-generate/lib/headerLevel.js
- ccdaservice/serveccda.js
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
add desc to document_fetch
Fixes #5370
> QRDA and CCDA fixes

- library/globals.inc.php
> Globals connectors updates

- sql/6_1_0-to-7_0_0_upgrade.sql
- src/Services/Cda/CdaTemplateImportDispose.php
- src/Services/Qdm/CqmCalculator.php
- src/Services/Qdm/IndividualResult.php
- src/Services/Qrda/ExportCat3Service.php
Fixes #5377 updates the reason code lookup for immunization to pass Measure 147 for Clinical Quality Measures.
Also added some debugging functions.  
Fixed a negation rationale error that was being thrown.
> Openemr fix 5377

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncountermanagerController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml
- interface/patient_file/merge_patients.php
- scroll status panel view during long imports
- change encounter deduplication merge button to allow qualifying merge regardless if should be a merge or not. Hopefully prevents mistakenly selecting wrong merge type.
- add Ascending or descending checkbox to import view to change sort order.
- reorder import detail for better clarity
> Import tunings

- sql/database.sql
- version.php
> quick database fix

- src/Services/Qdm/Services/InterventionService.php
> intervention service ignore deleted procedures 

- interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml
- interface/patient_file/merge_patients.php
- display header using modulus 12
- enc dedupe changes
> deduplication changes

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncountermanagerController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncountermanagerTable.php
- interface/modules/zend_modules/module/Carecoordination/view/carecoordination/encountermanager/index.phtml
- src/Validators/ProcessingResult.php
Fixes #5386 
Made it so you can search for patients in the care coordination module by provider, billing facility, or patient creation date through the advanced settings in the search tab.
> Fixes #5386  carecoordination search improvements

- src/Services/Cda/CdaTemplateImportDispose.php
If encounter diagnosis date is an empty string, set it to be a null value on the issues list insert.
> Fixes #5394 QRDA Encounter diagnosis date

- interface/orders/orders_results.php
- interface/patient_file/summary/demographics_full.php
- sql/6_1_0-to-7_0_0_upgrade.sql
- sql/database.sql
- src/Services/Qdm/Services/LaboratoryTestService.php
- version.php
>  cms122 laboratory test performed issues

- src/Services/Cda/CdaValidateDocuments.php
Made it so we don't fatal error if the schematron doesn't run or return
anything.
> Fixes #5398 schematron fatal error

- .github/workflows/test.yml
- CONTRIBUTING.md
- ci/apache_80_108/docker-compose.yml
- ci/apache_81_106/docker-compose.yml
- docker/development-insane/README.md
- docker/development-insane/docker-compose.yml
ci and docker updates to begin to support alpine 3.16 and mariadb 10.8
> ci and docker updates to begin to support alpine 3.16 and mariadb 10.8

- ccdaservice/package-lock.json
- ccdaservice/package.json
- src/Services/Qdm/Services/LaboratoryTestService.php
- reorg oe-schematron-service package and lock file
> ccdaservices oe-schematron-service package updates

- ccdaservice/serveccda.js
- interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/revandapprove.phtml
> comment debug output, php8 error

- src/Services/Cda/CdaTemplateImportDispose.php
- src/Services/CodeTypesService.php
- procedure import was adding additional code type to code on code validation.
> Fix multi code type with code.

- ccdaservice/package-lock.json
> minor changes to package-lock

- interface/new/new_comprehensive.php
> Fixes #5421

- interface/patient_file/summary/dashboard_header.php
- templates/patient/partials/delete.html.twig
> make patient delete url relative

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncountermanagerController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml
- interface/modules/zend_modules/module/Documents/src/Documents/Controller/DocumentsController.php
We make it so we can import a zip file of CCDA files in the format that we export them via OpenEMR.
> Fixes #5416 CCDA Zip Import

- setup.php
> mention characters not allowed in db password setup

- interface/main/messages/messages.php
Made it so the date and time of the message received is shown.
> Fixes #5436 Messages datetime

- interface/main/messages/messages.php
Added a check new messages button for direct messaging that triggers the background service to run immediately.
> Fixes #5434 - Check New Messages button

- FUNDING.yml
- README.md
> updates readme

- interface/main/messages/messages.php
> minor fix to prior commit

- .github/FUNDING.yml
- FUNDING.yml
> fixes FUNDING.yml

- interface/main/tabs/js/frame_proxies.js
- interface/main/tabs/js/tabs_view_model.js
- interface/main/tabs/main.php
- library/globals.inc.php
Fixes #5423
Creates the option to automatically add the patient name to the window title.
When option is enabled:
The window title will be:   [Window Title Specified in Globals] - [Patient name]
> Add Option To Add Patient Name to Window Title

- interface/forms/newpatient/common.php
- sql/6_1_0-to-7_0_0_upgrade.sql
- version.php
> fix unneeded globals insert in upgrade, minor issues

- interface/patient_file/summary/dashboard_header.php
> restore portal login href

- interface/reports/patient_flow_board_report.php
fixes #5468 
@psoas , this will fix the errors you noted on the flow board report during today's call
> flow board report php8 fixes

- interface/forms/care_plan/new.php
- interface/forms/observation/new.php
- interface/forms/procedure_order/common.php
- interface/forms/vitals/C_FormVitals.class.php
- src/Common/Forms/ReasonStatusCodes.php
Fixes #5479 change the reason code from EMPTY to NONE to fix the php keyword problem.
> Fixes #5479 Change reason code empty constant name

- _rest_routes.inc.php
- swagger/openemr-api.yaml
Fixes the swagger file and rest api to support the launch/patient scope.
> Fixes #5488 add launch/patient scope to swagger

- templates/patient/card/card_base.html.twig
> restore appt add from dashboard

- composer.json
- composer.lock
> add symfony http client for portal ccd view and download

- ccdaservice/oe-blue-button-generate/lib/fieldLevel.js
- ccdaservice/oe-blue-button-generate/lib/translate.js
- ccdaservice/serveccda.js
- interface/modules/zend_modules/module/Application/view/application/sendto/send.phtml
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceDocumentRequestor.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceRequestModelGenerator.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
- interface/modules/zend_modules/public/js/application/sendTo.js
- version.php
- mod ccda socket write for better control
- bump db version from prior PR
Fixes #5497
> Filter CCDA export for date range

- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- library/options.inc.php
- library/templates/address_list_display.php
- src/Services/ContactService.php
> minor fix for cal comment hover, fix getContactsForPatient display

- ccdaservice/serveccda.js
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Listener/CCDAEventsSubscriber.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaGenerator.php
- src/Events/PatientDocuments/PatientDocumentCreateCCDAEvent.php
- src/Services/FHIR/DocumentReference/FhirPatientDocumentReferenceService.php
- src/Services/FHIR/FhirDocRefService.php
Fixed the ccda section generation for g9 to be the same as what the UX
does for the most current ccd requested via g9.
Also fixed some other minor bugs that were breaking the g9 api.
> Fixes #5506

- ccdaservice/oe-blue-button-generate/lib/documentLevel.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/careTeamEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/index.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/vitalSignEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/fieldLevel.js
- ccdaservice/oe-blue-button-generate/lib/htmlHeaders.js
- ccdaservice/oe-blue-button-generate/lib/sectionLevel2.js
- ccdaservice/oe-blue-button-generate/lib/translate.js
- ccdaservice/oe-blue-button-meta/lib/CCDA/code-systems.js
- ccdaservice/oe-blue-button-meta/lib/CCDA/sections.js
- ccdaservice/serveccda.js
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
- various JS template modification
- new careTeamEntryLevel
Fixes #5513
> Implement C-CDA Care Team Section

- interface/patient_file/encounter/select_codes.php
- interface/patient_file/summary/add_edit_issue.php
Fixes #5522 
check for code types already added to url and string cast snomed code in select codes
> Fixes #5522 snomed codes not selected in Add/Edit Issue

- src/MedicalDevice/MedicalDevice.php
We want to make sure we display the assigning authority for medical devices for our b1 certification.
> Fixes #5528 show assigning authority.

- ccdaservice/serveccda.js
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
> Fixes #5536,#5537 stylesheet and care team

- sql/6_1_0-to-7_0_0_upgrade.sql
- sql/database.sql
Fixes #5534 
Make it so the prescription drug interval saves for weekly and monthly data types
> Fixes #5534 Prescription Drug Interval save weekly and monthly data types

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
- fix provider flag/id for backup hie provider to prevent duplicate care team member
- last chance get primary provider from first care team member
Small oversight with primary provider duplicate check.
> CCDA Fixes

- version.php
bump db for fde6634cd161408b2da3d80ca16a023cd53b93ab
> bump v db for prior commit 

- interface/main/messages/templates/linked_documents.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaGlobalsConfiguration.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaUserPreferencesTransformer.php
- interface/modules/zend_modules/public/xsl/cda.xsl
Fixes #5543 
Fixes #5546 
Fixes #5545 
Made patient display name be the Legal name if available
Added display of additional patient names in header
Added display of sdtcRace and sdtcEthnicity values
Added multiple address display, multiple telecom display
Added support for Mobile Contact telecom.
> Fixes #5543 patient demographic display in xsl

- ccdaservice/oe-blue-button-generate/lib/documentLevel.js
- ccdaservice/oe-blue-button-generate/lib/fieldLevel.js
- ccdaservice/oe-blue-button-generate/lib/headerLevel.js
- ccdaservice/oe-blue-button-generate/lib/translate.js
- ccdaservice/serveccda.js
- interface/modules/zend_modules/module/Application/view/application/sendto/send.phtml
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Form/ModuleconfigForm.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Listener/CCDAEventsSubscriber.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceRequestModelGenerator.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
- interface/modules/zend_modules/public/xsl/cda.xsl
- src/Events/PatientDocuments/PatientDocumentCreateCCDAEvent.php
- 3 chances for author
- datetime validation changes
> ccda author and dates

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
- interface/patient_file/summary/stats_full.php
Fixes #5569 
Fixes #5568 
Fixes #5567 
Change status from inactive to be Completed for medical problems
Fixed the referral provider being populated as the primary care
physician for ccd documents / referral documents when there is no
referral transaction created.
Fixed the telecom phone numbers having an extra space
> Openemr fix 5569 5568 5567 b1 issues

- ccdaservice/oe-blue-button-generate/lib/entryLevel/allergyEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/goalEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/planOfCareEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/problemEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/sharedEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/fieldLevel.js
- ccdaservice/oe-blue-button-generate/lib/headerLevel.js
- ccdaservice/oe-blue-button-generate/lib/sectionLevel2.js
- ccdaservice/serveccda.js
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
> refactor author ccda templates

- ccdaservice/oe-blue-button-generate/lib/entryLevel/careTeamEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/functionalStatusEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/immunizationEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/medicalDeviceEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/planOfCareEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/procedureEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/entryLevel/socialHistoryEntryLevel.js
- ccdaservice/oe-blue-button-generate/lib/sectionLevel2.js
- ccdaservice/serveccda.js
Health concerns and referral were breaking when empty due to the author provenance changes.
> Fixes #5576 CCDA fix null sections

- templates/patient/card/insurance.html.twig
> fix #5579 eval accept_assignment in twig

- sql/7_0_0-to-7_0_1_upgrade.sql
- version.php
> branching rel-700

- portal/sign/assets/signature_pad.umd.js
> Update signaturePad umb library to v4.04 build 4.0.5

- interface/forms/sdoh/new.php
> sdoh portal form dashboard fix

- src/Services/PatientService.php
> fix #5591 save previous name

- interface/new/new_comprehensive.php
- library/options.inc.php
- library/templates/address_list_form.php
> bring back fix #5558 to rel-700

- interface/forms/CAMOS/new.php
- interface/forms/CAMOS/save.php
- from PR #5600
Fixes #
For next patch
> Fix CAMOS deprecated errors
