openemr/openemr

- templates/x12_partners/general_edit.html
Fixes #5133
inability to specify full sftp host name in x12 partner edit field
> increase max length of sftp host name

- src/Common/Uuid/UuidMapping.php
- src/Common/Uuid/UuidRegistry.php
Fixes #5127  Made it so the uuids for mapped resources such as vitals are being populated in the uuid registry.  Users will need to run the sql_upgrade.php for any existing installation in order for any new vitals to be retrievable via FHIR for the single resource GET operation.
> Fixes #5127 mapped uuids not saving in registry

- interface/forms/vitals/templates/vitals/vitals_textbox.tpl
- interface/forms/vitals/templates/vitals/vitals_textbox_conversion.tpl
- src/Common/Forms/FormVitals.php
Make it so we can save a 0 value for columns in vitals to signify the data is missing.  We need this for FHIR.  We originally had it for blood pressure systolic and diastolic values.  New Inferno validation requires it for many more fields so I just made it so every field in vitals can have a 0 value to represent missing data.
Fixes #5137
> Fixes #5137 Vitals save data absent value

- src/Services/CarePlanService.php
- src/Services/FHIR/DocumentReference/FhirClinicalNotesService.php
- src/Services/FHIR/DocumentReference/FhirPatientDocumentReferenceService.php
- src/Services/FHIR/FhirCarePlanService.php
- src/Services/FHIR/FhirImmunizationService.php
- src/Services/FHIR/FhirMedicationRequestService.php
- src/Services/FHIR/FhirOrganizationService.php
- src/Services/FHIR/FhirProvenanceService.php
- src/Services/FHIR/Procedure/FhirProcedureOEProcedureService.php
- src/Services/SurgeryService.php
- tests/Tests/Services/CarePlanServiceTest.php
This PR holds the fixes to many of the sub issues in #5122.  
I will keep it as a draft for now, but it does the following:
- Fixes #5123 
- Fixes #5124 
- Fixes #5125 
I add the username to the SurgerService.
I fix all the provenance queries for DiagnosticReports,DocumentReference,Immunization,Procedure,CarePlan,Goals.
I switch Careplan and Goal to use -SK- for the uuid separator instead of an underscore(_).
I switch Provenance to use -PSK- for the id separator (since a CarePlan/Goal can be inside a Provenance logical id).  
I put in code to handle old resources for the ids to handle consumers of the API prior to this fix.
> Openemr fhir single patient api #5122

- interface/main/messages/messages.php
Fixes #5126
`pubpid` can be saved as an empty value which causes the document display function `gotoReport()` to fail
use the pid in such cases
> handle empty pubpid for documents linked via messages

- interface/forms/CAMOS/content_parser.php
- interface/forms/track_anything/report.php
- library/api.inc
Remove unneeded globals.php requires from libraries
(in process of testing)
Did search of entire codebase for both the content_parser.php and api.inc and global.php is always required before these libraries are used (this is the standard pattern in openemr where globals.php is required and then the libraries after that in scripts).
I did note one place where globals.php was not brought in prior to api.inc in track_anything/report.php , which I added. However, this points out a good issue and that is that all the report.php files in all the forms should not need to require globals.php , but that is code cleanup for another day :)
> Remove unneeded globals.php from libraries

- _rest_config.php
- apis/dispatch.php
- sql/6_1_0-to-7_0_0_upgrade.sql
- sql/database.sql
- src/Common/Auth/OpenIDConnect/Grant/CustomClientCredentialsGrant.php
- src/Common/Auth/OpenIDConnect/Grant/CustomRefreshTokenGrant.php
- src/Common/Auth/OpenIDConnect/IdTokenSMARTResponse.php
- src/Common/Auth/OpenIDConnect/Repositories/AccessTokenRepository.php
- src/Common/Auth/OpenIDConnect/SMARTSessionTokenContextBuilder.php
- src/Common/Http/HttpRestRequest.php
- src/Common/Http/HttpRestRouteHandler.php
- src/RestControllers/AuthorizationController.php
- src/RestControllers/SMART/SMARTAuthorizationController.php
Fixes #5157 
We need to handle in the standalone application context the ability to use patient scopes while logged in as a practitioner.  We originally restricted patient scopes to JUST patients and user scopes to JUST users.  However, latest inferno and v2 of smart on FHIR is expecting a practitioner to be able to select a user and have their scopes
restricted to JUST that user.
Currently I have this working when used for a single patient.  I did this by overriding the http request's isPatientRequest and getPatientStringUUID properties to populate these values IF we are in a user/system context and the launch/patient scope is present (meaning the user has requested to have a patient context bound) and the resource endpoint being requested has a patient scope (but no overriding privilege …
> Fix patient scopes when used by users

- src/Services/FHIR/FhirGoalService.php
Fixes #5169 Goal was changed for its date to become a datetime at the database level which was messing up the public FHIR inferno server.  CCDA and QRDA requires Goal to be a datetime.  FHIR however reports it as a date so we modify the FHIR service to transform the dates into the right format.
> Fixes #5169 Goal Date in FHIR

- interface/patient_file/summary/demographics.php
Fixes #5173
simple fix for past appt display in add edit event popup
> add jsevent for past appt display

- src/Services/FHIR/FhirCodeSystemConstants.php
- src/Services/FHIR/FhirPatientService.php
The system property was not set correctly for the patient language.
Went and found inferno's sample patients and changed the system property
to be what it has listed.
Fixes #5182
> Fixes #5182 set correct patient language system

- src/Common/Auth/OpenIDConnect/SMARTSessionTokenContextBuilder.php
- src/RestControllers/FHIR/FhirExportRestController.php
- src/Services/FHIR/FhirCareTeamService.php
- src/Services/FHIR/FhirCodeSystemConstants.php
- src/Services/FHIR/UtilsService.php
- src/Services/PractitionerRoleService.php
Changed up the care team value sets since we can't use NUCC anymore and
instead need to use a SNOMED-CT valuset for the care team provider.
Oddly there is no 'valid' value for facilities as the role is all
provider centric.  However, SNOMED-CT still has values for health care
organization so we use that for our code.
Added some fixes to get rid of warnings with the smart session context
builder.
Also Changed up the group export to use getOne which is what we really
want instead of hitting getAll.
> Fixes #5181 CareTeams,Minor FHIR bug fixes

- src/Common/Auth/OpenIDConnect/Grant/CustomRefreshTokenGrant.php
- src/Common/Auth/OpenIDConnect/IdTokenSMARTResponse.php
- src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
Fixes #5191 
Made it so the refresh_grant will provide patient context and other
SMART context variables if scopes are omitted or if a subset of scopes
are sent.
Had a few resources that didn't have scope permission messages setup which this commit
fixes.
> Openemr fix #5191 refresh token

- src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
- src/Services/PatientService.php
#5202 Use the LBF suffix field first if we can then fallback to last name parsing if we don't have a suffix value.
> Fixes #5202 Patient Suffix support

- src/Services/FHIR/FhirDeviceService.php
- src/Services/FHIR/FhirDiagnosticReportService.php
- src/Services/FHIR/FhirEncounterService.php
- src/Services/FHIR/FhirLocationService.php
- src/Services/FHIR/FhirMedicationService.php
- src/Services/FHIR/FhirObservationService.php
- src/Services/FHIR/FhirOrganizationService.php
- src/Services/FHIR/FhirPractitionerRoleService.php
- src/Services/FHIR/FhirPractitionerService.php
Inferno validator changed up some of the us core profiles we had to
report.  We also were missing a bunch of them in other resources.  This
gets rid of the inferno warning on our capability statement.  It also
advertises to FHIR clients that we support the full US Core profile
spectrum.
This is the very last inferno warning!  Fingers crossed that when all the PRs are merged in that there's no cross contamination.  There shouldn't be as I've tested it locally.
> Fixes #5201 Report US Core Profiles for capability

- src/Services/ConditionService.php
Fixes #
The medical problem API fails with the following error:
_{{ _.base_url }}/apis/default/api/patient/961b34f1-2244-4826-bbac-8ee62af69499/medical_problem_
`
Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /var/www/localhost/htdocs/openemr/src/Services/ConditionService.php:80 Stack trace: #0 /var/www/localhost/htdocs/openemr/src/Services/ConditionService.php(137): OpenEMR\Services\ConditionService->search() #1 /var/www/localhost/htdocs/openemr/src/RestControllers/ConditionRestController.php(57): OpenEMR\Services\ConditionService->getAll() #2 /var/www/localhost/htdocs/openemr/_rest_routes.inc.php(3642): OpenEMR\RestControllers\ConditionRestController->getAll() #3 /var/www/localhost/htdocs/openemr/src/Common/Http/HttpRestRouteHandler.php(84): …
> Fixing medical problem GET api - StringSearchField

- FHIR_README.md
- src/FHIR/Export/ExportStreamWriter.php
- src/Services/FHIR/FhirEncounterService.php
- src/Services/FHIR/FhirProvenanceService.php
Fixes #5215
Fixes #5126 
Made the provenance use its own logic instead of relying on the bulk
export trait.  We first only grab resources that have been included in
the JOB (which are filtered by scopes and patient queries).  Then we
correctly set the patient filters on the individual sub resources.
Lastly instead of wrapping everything up in a processing result which is
memory and cpu intensive, we write things out to the stream as we go
through the system.
> Openemr fixes #5215 bulk export provenance, fixes #5216 api docs

- ccr/transmitCCD.php
- interface/main/finder/document_select.php
- interface/main/messages/js/trusted-messages.js
- interface/main/messages/messages.php
- interface/main/messages/trusted-messages-ajax.php
- interface/main/messages/trusted-messages.php
- src/Services/DocumentService.php
Fixes #5220 
Fixes #5229
Implemented the ability to send messages w/o attachments via the EMR
Direct service over the Direct protocol.
Built the ability to select a document that has been uploaded to the
system and send it via EMRDirect.
Built a document finder dialog window so that you can select a patient
or non-patient document using the finder.  It checks against the current
user's ACLs and the document category's acos to determine if the user
can see the document.  It only shows 25 results at a time and requires
the user to be more specific in their search if they want to see more.
By default it displays the most recent documents uploaded.
Made it so we can send a pdf attachment via direct.
Validated the mime types and reject any document that can't be sent via
Direct.  Interestingly …
> Openemr fix #5220 direct send attachment

- oauth2/provider/scope-authorize.php
- src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
#5232
Fixes the scope nonce validation so native apps can authorize using the
nonce from the identity token.
Fixes the css view on mobile native devices so we can see the scope
authorization screen without half of it cut off.
> Fixes #5232 android oauth2 authorization issues.

- config/config.yaml
- interface/forms/observation/new.php
- interface/forms/observation/observation.js
- interface/forms/observation/save.php
- interface/forms/observation/templates/observation_actions.php
- interface/forms/observation/templates/observation_reason_row.php
- interface/forms/vitals/C_FormVitals.class.php
- interface/forms/vitals/templates/vitals/general_new.html
- interface/forms/vitals/templates/vitals/vitals_actions.tpl
- interface/forms/vitals/templates/vitals/vitals_notes.tpl
- interface/forms/vitals/templates/vitals/vitals_reason_row.tpl
- interface/forms/vitals/templates/vitals/vitals_temp_method.tpl
- interface/forms/vitals/templates/vitals/vitals_textbox.tpl
- interface/forms/vitals/templates/vitals/vitals_textbox_conversion.tpl
- interface/forms/vitals/vitals.css
- interface/forms/vitals/vitals.js
- library/dialog.js
- library/js/reasonCodeWidget.js
- library/smarty/plugins/function.assetVersionNumber.php
- sql/6_1_0-to-7_0_0_upgrade.sql
- sql/database.sql
- src/Common/Forms/FormVitalDetails.php
- src/Common/Forms/FormVitals.php
- src/Common/Forms/ReasonStatusCodes.php
- src/Core/Header.php
- src/Services/VitalsService.php
Fixes #5255
Added support for reason code, reason_status, and reason_description for
the observation form as well as for the vitals_form.
Fixed the observation form to use a datetime selector instead of just a
regular date field.
Implemented a reason code widget script that allows us to implement the
code selector and hide/display of the reason container based upon the
launch button.
Refactored a lot of the javascript i the observation and vitals form
into separate javascript files to simplify debugging and to make it
easier to work with.
Added reason_code, reason_status, and reason_description to the
vital_form_details table.
Added a callback function parameter to the dialog so that you can pass a
callback that doesn't have to exist in the global document window.
Made it so if we attempt …
> Openemr fix #5255 forms reason code

- interface/main/backup.php
1. Generated SQL for exported services contains syntax errors.
2. Error when exporting a large number of lists due to command line too long.
> Some export fixes for the backup script.

- interface/forms/care_plan/careplan.js
- interface/forms/care_plan/new.php
- interface/forms/care_plan/save.php
- interface/forms/care_plan/templates/careplan_actions.php
- interface/forms/care_plan/templates/careplan_reason_row.php
- interface/forms/observation/new.php
- interface/forms/observation/observation.js
- library/js/reasonCodeWidget.js
- sql/6_1_0-to-7_0_0_upgrade.sql
- sql/database.sql
- src/Services/FHIR/FhirCarePlanService.php
Fixes #5267 
Added the reason code and start and end date selectors for the care plan
entries.  Also added the ability to have more code type selectors in the
reason code popup.  Added comments to explain the low and high on the
reason code in care plan.
Also added a comment in FHIR to explain how we'd leverage reason code if
we start reporting on the overall activity for CarePlan.
> Add Reason support to careplan Fixes #5267

- interface/forms/newpatient/common.php
- interface/forms/newpatient/save.php
- interface/modules/zend_modules/config/application.config.php
- interface/modules/zend_modules/module/CodeTypes/Module.php
- interface/modules/zend_modules/module/CodeTypes/config/module.config.php
- interface/modules/zend_modules/module/CodeTypes/src/CodeTypes/Listener/CodeTypeEventsSubscriber.php
- interface/modules/zend_modules/module/CodeTypes/src/Module.php
- library/standard_tables_capture.inc
- sql/6_1_0-to-7_0_0_upgrade.sql
- sql/database.sql
- src/Events/Codes/CodeTypeInstalledEvent.php
- src/Events/Core/SQLUpgradeEvent.php
- src/Services/Utils/SQLUpgradeService.php
This eventually will fix #5260.  I'm putting this out as a draft PR so people can see what I'm doing here.
Since we can't bundle certain codes like CPT4 or even SNOMED in
non-member countries we want to only install the codes property for
the Encounter Type list options if we have the right code systems
installed.  So we have added a CodeTypes event subscriber that listens
to newly installed coded types as well as the SQL Upgrade script process
to update the Encounter Type codes property.
This is WIP and is not finalized.  I've still got to add the codes the database.sql file and do some testing on the events to make sure this is all working properly.
> Encounter type field in encounter form.  Fixes #5260

- interface/modules/zend_modules/module/CodeTypes/src/CodeTypes/Listener/CodeTypeEventsSubscriber.php
- interface/patient_file/summary/immunizations.php
- sql/6_1_0-to-7_0_0_upgrade.sql
- sql/database.sql
- src/Services/FHIR/FhirImmunizationService.php
- src/Services/ImmunizationService.php
- src/Services/Qdm/Services/ImmunizationAdministeredService.php
Fixes #5277 
Added additional value options for the Immunization Refusal Reason so we can report it in Clinical Quality Measures.  I made sure to map the values to the USA CDC's NIP0002 valueset so reporting to immunization registries will still function.
Fixed up the QDM services to use the refusal reason codes.  Since the Immunization QDM model supports both a reason and a negationRationale I added the reason_code and support both fields.  
Implemented code type mappings for when SNOMED is installed to map SNOMED codes to the immunization refusal reason code.  
Implemented a popup selector for the immunization reason code.
> Openemr fix 5277 immunization reason codes

- interface/forms/procedure_order/common.php
- interface/forms/procedure_order/templates/procedure_reason_row.php
Fixes #5276 
Added to the procedure order UI the reason code, reason status,
reason description, start and end dates for the reasons. Now users can
hit the reason code icon and it will expand to provide the additional
reason code, status, start/end dates.
Refactored the addProcLine to use a template from the HTML dom so we can
also handle the reason code expanded widget. Tested the various ways
addProcLine to make sure it still works in the various ways it is
called.
Changed the Procedure Order Date Ordered to be a datetime selector
instead of just a date selector.
Relevant screenshots are here:
I wasn't able to figure out how to trigger the quest questions that go into the last column before actions.  I'm not sure how that impacts the spacing of everything.  I'm hoping someone who has …
> Openemr fix 5276 procedure order

- _rest_routes.inc.php
- interface/main/finder/document_select.php
- interface/main/messages/trusted-messages-ajax.php
- library/classes/Document.class.php
- src/RestControllers/FHIR/FhirDocumentRestController.php
clarify the can_access() function
Generally, the parameter to choose the user that is being checked in acl calls are the username. The can_access parameter also follows this, so corrected it. And clarified some calls using it.
> clarify the can_access() function

- interface/modules/zend_modules/module/CodeTypes/src/CodeTypes/Listener/CodeTypeEventsSubscriber.php
Fixes #5260 
This should be the last fix on this issue. ugh.  Remove the cpt4_code
table once again and make sure we are only using the codes table.  Also
added a check to make sure we don't have problems with duplicate code
text for our cpt4 code updaters.
> Fixes #5260 code types table

- library/globals.inc.php
- src/Cqm/CqmClient.php
- src/Services/Cda/CdaValidateDocuments.php
- src/Services/Qrda/QrdaReportService.php
- tests/Tests/ECQM/MeasureResultsTest.php
fixes #5340
also removed node_binary global since not used in most service and is a security issue.
TODO (for me):
make it so that it only breaks when the service is needed (for example, Care Coordination module does not need it for import of ccda)
(I am going to work on this TODO in future after get more acquainted with the node services)
> couple optimizations for the node services

- interface/forms/observation/save.php
- interface/patient_file/merge_patients.php
- src/Services/Qdm/Services/AbstractObservationService.php
- src/Services/Qdm/Services/EncounterService.php
- src/Services/Qrda/Helpers/Date.php
Fixes #5364 
This will get us by with testing I believe. I'll know more when I run through all the test patients, again!
> add qrda encounter dedupe merge

- ccdaservice/package-lock.json
- ccdaservice/package.json
bump install version to allow for all future minor and patch level version changes.
Fixes #
change package to include minor and patch level version bumps to our NPM managed packages so we aren't needing to change core lock and json for minor changes to services.
> make oe-schematron-service production ready

- src/Cqm/QrdaControllers/QrdaReportController.php
Manually forces a garbage collection cycle after each cat1 patient is
exported.  We trade cpu cycles for memory usage so that we can run on
low memory environments (such as our default dockers).
> Fixes #5400 cat 1 memory usage

- sites/default/statement.inc.php
This saves hours when printing invoices at the end of the month, so they don't have to be printed one-by-one (otherwise they overlap).
> Insert a page break after each entry

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceRequestModelGenerator.php
- library/globals.inc.php
- src/Services/Cda/CdaValidateDocuments.php
- add functionally to validation service.
- fix referral from direct to be empty
- new globals for validation server
Fixes #5447
> New external MDHT validation

- src/Services/Cda/CdaValidateDocuments.php
- use CURLStringFile is only valid for PHP >= 8.1
- remove unused use
Nuts is about all I have to say about this!:)
> quick fix prior commit

- ccdaservice/oe-blue-button-generate/lib/sectionLevel2.js
Referral document type was failing because we were missing the treatment
plan extension date.
Fixes #5480
> Fixes #5480 treatment plan extension date.

- library/classes/rulesets/Amc/library/AbstractAmcReport.php
AMC was breaking if a numerator test did not pass with the patient fhir credentials being missing.
> Fixes #5464 AMC - pass not defaulted to 0

- interface/forms/care_plan/report.php
Display the human readable careplan type name in the encounter summary
page.
> Fixes #5475 human readable careplan type display

- interface/forms/vitals/report.php
- interface/forms/vitals/templates/vitals/general_new.html
- interface/forms/vitals/templates/vitals/vitals_textbox.tpl
- interface/forms/vitals/templates/vitals/vitals_textbox_conversion.tpl
- interface/forms/vitals/vitals.js
- library/js/CustomTemplateApi.js
Fixes #5496 
Fixes #5500 
kg to lb was throwing an error as we tried calling a Number method on a
string.
Vitals were saving in metric if you had metric set as the main unit and
entered in data that way.
Setting a vitals value to be empty was not emptying out the
corresponding conversion field and the saved input.
I haven't been able to reproduce this typecast error on my version of php but on
some versions of php this was throwing a type conversion error.  We
parse as floats the values before we put them through number_format to
fix the type conversion problem.
Made it so double clicking the vitals form doesn't popup the dialog
template editor.
> Openemr fix #5496 vital form bugs

- ccr/display.php
- controllers/C_Document.class.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncountermanagerController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Listener/CCDAEventsSubscriber.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaDocumentTemplateOids.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaGlobalsConfiguration.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaUserPreferencesTransformer.php
- src/Events/PatientDocuments/PatientDocumentTreeViewFilterEvent.php
Fixes #5455 
After talking this over with @sjpadgett we decided to implement this by having multiple sort order sections for the four document types we support in CCD-A.  Its not ideal, but the alternative will take quite a bit of time to architect.  
I wrote a new preview option for CCD-A that examines the XML document to figure out the correct CCDA Template document type so we can know what sort order to use to display for the correct document.
Added a deprecation notice to the ccr/display.php in case anyone is using it.  We no longer reference it from the documents pages so we can probably remove it at some point.
I also added a new filter event to the patient document tree viewer so people can modify / update the html tree rendering on the documents if they so choose.  This made it …
> Fixes #5455 Document Type Display Order

- portal/patient/libs/Controller/OnsiteDocumentController.php
fixes #5515 
Pid is a string, so can't check the type in the comparison
> portal fix since Pid is a string, otherwise never authorized

- src/Common/ORDataObject/ORDataObject.php
Fixes #5514 
The isObjectModified property was not being set in many forms because
they don't call the default constructor for ORDataObject.  So we need to
setup our properties that are required as default values in the property
assignment instead of handling it inside the constructor.
> Fixes #5514 Form Id Not Populating

- API_README.md
- FHIR_README.md
- _rest_routes.inc.php
- ccdaservice/serveccda.js
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Listener/CCDAEventsSubscriber.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaGenerator.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceDocumentRequestor.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceRequestModelGenerator.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
- src/Common/ORDataObject/ORDataObject.php
- src/Events/PatientDocuments/PatientDocumentCreateCCDAEvent.php
- src/Services/FHIR/FhirDocRefService.php
- src/Services/FHIR/FhirProvenanceService.php
- src/Services/PatientService.php
- src/Services/Search/BasicSearchField.php
- src/Services/Search/DateSearchField.php
- src/Services/Search/SearchFieldComparableValue.php
- swagger/openemr-api.yaml
Fixes #5508 
Fixes #5517
Changes g9 $docref to be a POST api since we generate a new document
every time.
Fixes ISO8601 date problems with php since php's date constant is
incorrect.  Switch to ATOM constant.
Fixed the ORDataObject saving incorrectly on some database instance
types due to the timezone and microsecond formatting.
Added __clone helper methods to the search field classes so we can copy
them and modify properties w/o modifying the references.
Added brief, terse documentation for g9 generation with docref.  Needs
to be fleshed out in the fhir readme file.
Updated the swagger file to point to the g9 documentation.
Removed the remote xsl stuff as I found out chrome actively blocks
remote xsl's from rendering unless everything is in the same folder,
port, origin, and schema. …
> Openemr fix 5508 ccd date ranges

- ccr/transmitCCD.php
- interface/main/messages/trusted-messages-ajax.php
- interface/main/messages/trusted-messages.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncountermanagerTable.php
- library/globals.inc.php
- src/Common/DirectMessaging/ErrorConstants.php
Fixes #5539 
We were not supporting the message disposition notification check with EMRDirect.  This is an ONC requirement in order to support immediate confirmation that a recipient received the message.  I added a globals setting and a flag on the messages page to support this use.
I changed up the transmitCCD and transmitMessages function to use SET FINAL flag for EMR Direct to trigger the message disposition notification check.
The carecoordination will use whatever the globals setting is set to.
@lcmaas you may be interested in reviewing this to make sure we are handling everything your company needs.
From my testing this passes the ONC 2015 (b)(1) MT 46 Disposition Notification Options test.
> Fixes #5539 Toggle Messages Received Confirmation

- FHIR_README.md
- _rest_routes.inc.php
- swagger/openemr-api.yaml
Wanted to make sure I get this in before I forget it since I've had it
stashed for a while.  Updating the ccda documentation for g9.
Fixes #5549 @bradymiller this is just a minor fix.  Hopefully it doesn't mess  up anything you've been doing on the g9 documentation.  Big thing is we dropped filtering on vitals as I found out vitals always just returns the most recent vitals in ccda.  Will be quite a bit of work to change so I'm leaving it be.
> Fixes #5549 ccda documentation

- ccdaservice/oe-blue-button-generate/lib/headerLevel.js
- ccdaservice/serveccda.js
- interface/modules/zend_modules/public/xsl/cda.xsl
Implemented the referral fallback by using the encompassing encounter provider information if we have one in the displayed CCDA, or falling back to the Primary Care Provider (PP) or the Primary Care Physician (PCP) if we have one.
In order to grab the phone and contact information I had to fix up some issues in the care team and provider templates.  Those are still displaying properly in the documentationOf and in the Care Team sections.
Everything is passing in the ETT validator and looking at the xml it looks like everything is populating correctly for care team and the documentationOf.
Fixed up a number of style issues in the cda to make the format a bit more condensed while still preserving readability.  Did this by moving address info all into one line.  Found a couple of places …
> Fixes #5565 referral fallback, style fixes

- interface/forms/LBF/new.php
- interface/forms/sdoh/new.php
- interface/forms/sdoh/patient_portal.php
- interface/forms/sdoh/report.php
- interface/forms/sdoh/save.php
- interface/forms_admin/forms_admin.php
- library/api.inc
- library/registry.inc
- portal/lib/download_template.php
- portal/patient/libs/Controller/OnsitePortalActivityController.php
- portal/patient/scripts/app/onsitedocuments.js
- portal/patient/templates/OnsiteDocumentListView.tpl.php
- src/Common/Forms/CoreFormToPortalUtility.php
@sjpadgett , Have the main plumbing in (can save the form and modify the form form the patient portal).  Plan:
1. Get it working well in portal and in the dashboard where it is saved to chart as pdf etc. **DONE**
2. Streamline the process of how a "patient portal compliant" form can be placed in template (will potentially do this from the Forms->Adminstration gui for forms that are "patient portal compliant") - **DONE - (patient portal compliant forms get a neat icon next to their names in the gui and the template is placed into the document_templates sql table when the form is registered)**
3. Encapsulate things as much as possible to make it as easy as possible for users to make their forms "patient portal compliant" **DONE**
btw, the first commit in this PR is security related bug …
> Native form to patient portal form

- composer.json
- composer.lock
- breaks on windows 5.22.1+
5.22.2 okay on linux!
Fixes #5571
> Revert adodb-php version to 5.22.0

- interface/forms/CAMOS/new.php
- interface/forms/CAMOS/save.php
- interface/forms/newpatient/report.php
- interface/patient_file/encounter/forms.php
- interface/patient_file/summary/add_edit_amendments.php
- interface/patient_file/summary/demographics.php
- interface/patient_file/summary/list_amendments.php
- library/globals.inc.php
- library/patient.inc
- src/Core/Header.php
- src/Menu/MainMenuRole.php
- converted to render in tab instead of dialog.
- remove rx_modal class reference in widget
Fixes #5581
Fixes #5597 
Fixes #5601
Originally Amendments were a dialog. After twig conversion the class event reference to call modal wasn't in scope any longer.
Converted to render in tab as other widget do.
> Bug Fixes Amendments

- _rest_config.php
- library/ESign/views/default/esign_signature_log.php
Fixes #5531 
remove warning from displaying to user
move to log
eventually can follow @bradymiller's advice
>having an esign admin gui that checks the hashes and allows some flexibility towards fixing hashes
> move esign data integrity warning to log

- config/config.yaml
- interface/new/new_comprehensive.php
- interface/patient_file/summary/demographics_full.php
- interface/usergroup/facilities_add.php
- interface/usergroup/facility_admin.php
- interface/usergroup/user_admin.php
- interface/usergroup/usergroup_admin_add.php
- library/js/erx_javascript.js
Fixes #5641 changed out the erx_javascript.inc.php file to be an erx_javascript.js file that can be included in the header.  This fixes some DOM issues where the script tag is placed above the html tag breaking the DOM.  It also makes it easier for users to include the script by just adding 'erx' to the header.  Finally it facilitates a future migration of the user_admin pages to twig.
> Openemr fix 5641 erx javascript

- ccdaservice/serveccda.js
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceDocumentRequestor.php
- CCM chunk send data to service
- add data stacking buffer to service
- honor EOT(file separator character) in service
- replace deprecated js substr with substring
Fixes #5657 
Allows sending ccda content xml array for content larger than 128kb. Theoretically this will allow any array size.
Co-Authored with @adunsulag
> Manage CCDA data transmission to service

- src/Core/ModulesApplication.php
- src/Core/ModulesClassLoader.php
Implemented a modules class loader that allow module writers to register a namespace if its not already been registered.  This makes it so the ModuleWriter doesn't have to use requires everywhere and a module can be just dropped into the filesystem and execute once its been registered and installed from the Manage Modules interface.  
This is a proposed solution to the problem in #5643.  If it looks good to everyone then hopefully we can bring this in.
```php
<?php
// openemr.bootstrap.php
namespace Acme\OpenEMR\Modules\MyUniqueModule;
use OpenEMR\Core\ModulesClassLoader;
// @global ModulesClassLoader $classLoader
$classLoader->registerNamespaceIfNotExists('Acme\\OpenEMR\\Modules\\MyUniqueModule\\', __DIR__ . DIRECTORY_SEPARATOR . 'src');
// run any other custom module code needed here. …
```
> Fixes #5643 ModulesClassLoader autoload module code without composer install

- src/Core/Header.php
- src/Events/Core/TemplatePageEvent.php
Fixes #5681 
Added the ability to inject javascript or css into any page inside
OpenEMR using the Header class specifically the setupHeader method which
is used in smarty, twig, and our regular php files all over the place to
bring in javascript and css assets.  This allows module / event writers
to inject content on every page or on specific pages based on the script
name / page name.
> Fixes #5681 Header events for js/css

- interface/patient_file/report/custom_report.php
- interface/patient_file/summary/stats.php
- library/classes/Prescription.class.php
- templates/patient/card/medical_problems.html.twig
- templates/patient/card/medication.html.twig
Previously, on the patient dashboard, medication would only be listed and it would not have any useful information. Fixes #5621, #5623.
I still need one more part to this change, as described in the issue. Feel free to merge this change individually, or wait for the last part.
I have a feeling I put a few too many conditionals in here and perhaps should just split it out into a separate `.html.twig` page. Thoughts?
(Originally wrote for 6.1.0, rebased onto 7.0 automatically. Tested on Ubuntu 22.04 LTS, which ships PHP 8.1.2.)
> Add medication dosage to the patient dashboard and reports (#5621 #5623)

- interface/main/calendar/modules/PostCalendar/pnuserapi.php
- interface/usergroup/user_admin.php
- interface/usergroup/usergroup_admin_add.php
- src/Core/Header.php
- src/Core/ModulesApplication.php
- src/Core/ModulesClassLoader.php
- src/Events/Core/TemplatePageEvent.php
- src/Events/User/UserEditRenderEvent.php
- src/Services/UserService.php
Fixes https://github.com/openemr/openemr/issues/5643 ModulesClassLoader
Implemented a modules class loader that allow module writers to register a namespace if its not already been registered.  This makes it so the ModuleWriter doesn't have to use requires everywhere and a module can be just dropped into the filesystem and execute once its been registered and installed from the Manage Modules interface.
Style fixes
Fixes https://github.com/openemr/openemr/issues/5681 Added the ability to inject javascript or css into any page inside OpenEMR using the Header class specifically the setupHeader method which is used in smarty, twig, and our regular php files all over the place to bring in javascript and css assets.  This allows module / event writers to inject content on every page or on …
> Rel 610 Bring in  #5643 #5681 #5683 #5685

- interface/main/calendar/modules/PostCalendar/pnuserapi.php
- interface/usergroup/user_admin.php
- interface/usergroup/usergroup_admin_add.php
- src/Core/Header.php
- src/Core/ModulesApplication.php
- src/Core/ModulesClassLoader.php
- src/Events/Core/TemplatePageEvent.php
- src/Events/User/UserEditRenderEvent.php
- src/Services/UserService.php
Fixes https://github.com/openemr/openemr/issues/5643 ModulesClassLoader
Implemented a modules class loader that allow module writers to register a namespace if its not already been registered. This makes it so the ModuleWriter doesn't have to use requires everywhere and a module can be just dropped into the filesystem and execute once its been registered and installed from the Manage Modules interface.
Style fixes
Fixes https://github.com/openemr/openemr/issues/5681 Added the ability to inject javascript or css into any page inside OpenEMR using the Header class specifically the setupHeader method which is used in smarty, twig, and our regular php files all over the place to bring in javascript and css assets. This allows module / event writers to inject content on every page or on …
> Rel 700 bring in #5643 #5681 #5683 #5685

- swagger/index.html
This works with @adunsulag 's ongoing PR at: #5706
Works for both testing of private (works with or without this change) and public (only works with this change) apps.
Note that the not very smart swagger feature that hides the client secret appears to not be in the current version that is used in OpenEMR (using 3.50.2 in OpenEMR where it looks like that change is in the 4.4.0 https://github.com/swagger-api/swagger-ui/releases/tag/v4.4.0 release ).
> switch on PKCE support in swagger

- interface/main/tabs/menu/menus/standard.json
- interface/super/edit_globals.php
- sites/default/documents/custom_menus/Custom.json
Fixes #5560 
Resolves the issue of the page name of "Globals" not having a meaningful name.
I feel like the easiest name would be "Config" as "Globals" is a configuration area for the entire EMR. I have made "Config" the navigation bar name and "Configuration" the long version on the actual page.
> Change Globals Page Name to User-Friendly Name

- interface/drugs/dispense_drug.php
The current encounter was not used in dispensing drugs. Default encounter value of 0 was used. So we take the encounter from the session and use it accordingly.
Fixes #5712
Internal error: the referenced encounter no longer exists. 1 0
Get the current encounter and use this in dispensing a drug via the charges panel
> Fix Drugs dispensing in Charges Panel

- library/classes/Prescription.class.php
- sql/7_0_0-to-7_0_1_upgrade.sql
- sql/database.sql
- version.php
Fixes #5743
Allow string option_id from drug_route list
Modify Prescription class and change table column from int to varchar
> Handle route ids with string values.

- interface/login/login.php
Fixes #5759 
Fixes the right and left login layout not fully showing up as explained in the issue.
NOTE: This also needs to be merged in as a patch to version 7.0.0 and version 6.1.0 as it is affected by this bug. Login layouts will look distorted if this fix isn't implemented.
> Fixes Left and Right Login Layout Color Not Fully Showing

- interface/patient_file/report/custom_report.php
- interface/super/edit_layout_props.php
- library/options.inc.php
- sql/7_0_0-to-7_0_1_upgrade.sql
- sql/database.sql
Fixes: #5744, #5765, #5766
(Throwing the WIP flag back up on this, since we have an up for grabs demo available [here](https://four.openemr.io/c/openemr/interface/login/login.php?site=default). I'll update this PR once it's all ready again.)
- Hide unchecked boxes in reports by default, allowing the user to override this setting per-layout.
- Add a `grp_unchecked` column to `layout_group_properties`
- Use the Unicode reference for checkboxes instead of `[ x ]` / `[   ]`
- Make the patient name larger in printed reports, ensuring the practice information is right-aligned
> Custom patient report cleanup (Fixes: #5744, #5765, #5766)

- interface/billing/sl_eob_invoice.php
Fixes #5837 
Clicking the past encounter button does not go to past encounters. 
Added event handler to the onclick function.
> Bug fix #5837

- src/Services/FHIR/DocumentReference/FhirClinicalNotesService.php
Make the date search work for document reference with onc inferno.
Fixes #5858 where the date search was not working.
> Fixes #5858 DocumentReference date search

- interface/patient_file/summary/create_portallogin.php
- src/Events/Patient/Summary/PortalCredentialsTemplateDataFilterEvent.php
- src/Events/Patient/Summary/PortalCredentialsUpdatedEvent.php
- templates/patient/portal_login/print.html.twig
Add twig and event extensions that can be used by module writers to extend to create_portallogin dialog.
I introduce two new events, one for extending the data sent to the twig templates in the create_portallogin.php and one for triggering when the portal credentials have been updated. Also utilized a new technique that can be used to add a 0..* extension of twig files to add content to an existing twig.  I had to go this route as my module wanted to replace SOME of the twig files but I needed the twig data with some additional field data added.  The fireEvent in twig would not have accomplished this mechanism as I couldn't re-arrange the output in the existing twig file.
Fixes #5875.
> Fixes #5875 portal module extensions

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- interface/patient_file/summary/demographics.php
remove a lone semicolon
sql fix for limit
added document name to labels for patient photographs (to be consistent with the insurance cards which fixed to show the document name label instead of the uuid) in patient summary
> misc fixes

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- src/Services/Cda/XmlExtended.php
fixes #5903 
@sjpadgett , the silent fail was happening at the creation of the instance `$xmltoarray = new XmlExtended();`. No constructor is involved, so figured that the class it extended was bringing in something that XmlExtended didn't. So, if create a dummy Xml class `$dummyXml = new XML();` before creating the XmlExtended() class then it works (gui import of xml and zip with documents and the command line synthea import also works)
:)
I think something that XML brings in at https://github.com/laminas/laminas-config/blob/3.7.0/src/Reader/Xml.php#L5-L21 that is not brought in by XmlExtended is causing the fail, but even if I copy that into the XmlExtended class script, it still fails.
> ccda import fix

- src/Services/Search/DateSearchField.php
- src/Services/Search/SearchFieldStatementResolver.php
Handles the timezone requests on the date search field to parse out the requestor's timezone.
Handles the adjustment of the requestor's timezone on the search field statement resolver to be the local time.
Fixes #5919
> Fix #5919 datetime timezone.

- interface/patient_file/history/encounters.php
Fixes #5926 
Tooltips currently are not useful.
Make the darn thing useful:)
The report tooltip now popover where popover will stay open for 30 seconds             
or if the mouse leaves popover or if the user clicks anywhere in popover.            
This will allow user to enter popover report view and scroll if report 
height is overflowed. Popover will either close when mouse leaves view 
or user clicks anywhere in view. 
Multiple popovers may be opened on hover/focus but closing any one of them, closes all.   
Kind of a nifty solution.
> Fix encounter history hover tooltips

- src/Services/FHIR/FhirLocationService.php
- src/Services/LocationService.php
We were using invalid types in the Location.type field which I've gone ahead and fixed.
Fixes #5933. 
I also call out for future work the fact that we need to support the multiple patient addresses (such as previous address) in FHIR for the Location work here.
> Fixes #5933 Fhir Location Type invalid

- _rest_config.php
- apis/dispatch.php
- src/Common/Auth/OpenIDConnect/SMARTSessionTokenContextBuilder.php
- src/FHIR/SMART/SMARTLaunchToken.php
Fixes #5943 by allowing the **launch** scope context to establish request context information.
> Openemr fix 5943 patient context launch scope

- interface/patient_file/history/encounters.php
- src/Services/ClinicalNotesService.php
- fix query to qualify the list that option ids for a note are selected from.
Fixes #5949
Notes fetch query was fetching notes category and note type using the option_id only which caused duplicates.
The reason is that the same option_id happens to be in another list resulting in the join including result.
Qualify the option_id to the correct list by including list_id in join.
> Clinic notes duplicate notes on fetch

- interface/main/calendar/add_edit_event.php
When selecting the days a calendar event repeats, the label itself is not tied to the input checkbox. This PR ties the label to the input and tidies up the HTML rendering of the elements
> Allow the labels of the repeating days to be clicked

- .github/workflows/manual-build-php-fpm-dockers.yml
- .github/workflows/styling.yml
- .github/workflows/syntax.yml
- .github/workflows/test.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using [secure-workflows](https://github.com/step-security/secure-workflows).
The GitHub Actions workflow has a GITHUB_TOKEN with write access to multiple scopes. Here is an example of the permissions in one of the workflow runs:
https://github.com/openemr/openemr/actions/runs/3166984505/jobs/5157123174#step:1:19
After this change, the scopes will be reduced to the minimum needed for the following workflows:
- manual-build-php-fpm-dockers.yml
- styling.yml
- syntax.yml
- test.yml
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced.
- [GitHub recommends](https://docs.github.com/en/actions/security-guides/automat …
> ci: add minimum GitHub token permissions for workflows

- interface/patient_file/pos_checkout_normal.php
Fixes #6040 
Before and after photos
I'm not sure there's a lot of value add to this particular screen when compared to the Payment screen, fixing the UI discrepancy nonetheless.
> Fix Overflowing UI

- src/OeUI/OemrUI.php
Better wrapping for Page Heading - it is now a flex div and pushes icon to the right, sizing down the icons. Previously, they were nested inside the `h2` element, this puts all the icons in a better place.
(Screenshot has a wrench icon... that is a side effect from some other work, just pretend it is not there)
> Better Page Heading UI

- src/Services/EncounterService.php
There was already a pull request for this issue (#5873) but was never merged.
Fixes #5872
This allows to put the date of the encounter when creating it instead of needing to update it after
> Fix for insertEncounter where creating an encounter always use current date

- library/classes/Installer.class.php
add hooks to support enforcement of ssl/x509 database connection when autoinstalling (really nice to support for dockers and kubernetes)
> add hooks to support enforcement of ssl/x509 database connection when autoinstalling (really nice to support for dockers and kubernetes)

- src/Services/LogoService.php
Now start with an empty paths array - only add `public` if the proper structure exists. If not, `error_log()` the problem and return an empty string. This ensures the rendering can continue (albeit, with no logo).
Fixes #6147
> fix: Quietly report an error if logo cannot be located

- docker/development-easy-arm32/docker-compose.yml
- docker/development-easy-arm64/docker-compose.yml
- docker/development-easy-light/docker-compose.yml
- docker/development-easy/docker-compose.yml
fixes #6147
For the easy development docker environment, allow development/testing in the public folder
> fix: easy development docker environment - allow development and testing in public folder

- src/Services/PatientService.php
- src/Services/Search/StringSearchField.php
Union (OR) searches were broken when using String search fields.
Fixes #6143 
I'll need to check this fix against Inferno and make sure we didn't break anything.
> Fixes #6143 support UNION (,) searches

- library/classes/postmaster.php
Make it so the postmaster throws exceptions by calling the constructor on the parent class.
Fixes #6144
> Fixes #6144 Postmaster throw exceptions

- src/Services/LogoService.php
The fix from yesterday does in fact solve the issue - but this PR actually wraps the risky bits in a proper try/catch block and ensures things just chug along in the event something else may go wrong in the future.
> Better handling of any error Finder may throw

- src/Services/LogoService.php
By default, `findLogo()` will return a file path with a query string `t` with a value of the last modified time of the file. This should bust any caches as files are updated by the administrator.
> Cache-bust logos based on last modified time

- interface/patient_file/summary/create_portallogin.php
- src/Services/PatientAccessOnsiteService.php
Fixes #6158
Fixes #6159
Pulled the portal credentials into its own class so it can be re-used elsewhere.
Added to the validEmail check function the ability to have a + sign in the email address to support email labels like example+label@gmail.com.
> Fixes #6158,#6159 Portal Credentials Refactor

- src/Common/Http/HttpRestRouteHandler.php
Made it so the local api works with the standard and fhir api calls by skipping the scope checks.
Fixes #6171
> Fixes #6171 local api scope checks

- interface/new/new_comprehensive.php
Just remove the second half of the condition, no need to display a non-breaking white space in this situation. Fixes #6194
> fix: Remove unnecessary non-breaking whitespace if not displaying the field label

- portal/get_patient_info.php
- portal/index.php
- portal/verify_session.php
Fixes #6190 
This change allows the portal page to redirect to another page other than the SPA home.php file once a user has authenticated.  In this initial release we only allow this to go to a module page that exists in the OpenEMR directory.  As needed we can open this up to other areas of the application.
The redirect param is retained across password changes and the mfa auth that is handled in the portal/index.php.
I modified the verify_sessions so that the landingpage param can be updated so the script can be used inside of other pages we want to be protected by the portal session (such as inside a module).
> Fixes #6190 Portal Login Redirect

- src/Billing/Claim.php
- src/Billing/X125010837P.php
> fix: Claim.php, loadPayerInfo(), use empty instead of equals null for legacy

- library/sql.inc.php
fixes #6212
fix the generic_sql_affected_rows function
Guessing this is secondary to adodb libary since broken in master but not in prior 7.0.0 release. Changed the function to use a adodb function rather than a native mysqli function and appears to be working.
> fix: fix the generic_sql_affected_rows function

- src/Services/AppointmentService.php
When the POST /api/patient/{pid}/appointment standard api endpoint is called it returns the following error:
ERROR: insert failed: INSERT INTO openemr_postcalendar_events SET uuid=? pc_pid=?, pc_catid=?, pc_title=?, pc_duration=?, pc_hometext=?, pc_eventDate=?, pc_apptstatus=?, pc_startTime=?, pc_endTime=?, pc_facility=?, pc_billing_location=?, pc_informant=1, pc_eventstatus=1, pc_sharing=1, pc_aid=?
Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'pc_pid='1', pc_catid='5', pc_title='Office Visit', pc_duration='9...' at line 1
/var/www/localhost/htdocs/openemr/src/Services/AppointmentService.php at 297:sqlInsert
/var/www/localhost/htdocs/openemr/src/RestControllers/AppointmentRestController.php …
> Fixes #6238

- library/globals.inc.php
- src/Services/PatientAccessOnsiteService.php
- templates/emails/patient/portal_login/message.html.twig
- templates/emails/patient/portal_login/message.text.twig
Fixes #6227 patient portal address link not showing.
Also adds more explanation details to the globals config about patient portal configuration.
This does not address the duplicate portal email address issue yet until I get more clarification on the security fix @bradymiller was addressing in his earlier commits.
> Patient Portal address link Fixes #6227

- interface/globals.php
- interface/modules/zend_modules/config/application.config.php
- src/Core/ModulesApplication.php
Fixes #6254 
Adds a security check in the ModulesApplication system to check if the currently executed script is a module script file (IE its in the module directory or a sub directory).  If it does it grabs the module name and checks if the module is enabled.  If the module is not enabled it throws an AccessDenied exception.  This is caught in the globals.php file.  
So now any script that tries to use the system globals will have this security check.  I believe this is a nice clean way to make limit the attack surface of our core modules.  If they aren't enabled then there are fewer security risks for them to execute.  
I tried to make the code as efficient as possible as this essentially runs two string comparisons on every single request against the current path and the module …
> Fixes #6254 Lock down module script files to enabled modules

- src/Billing/Claim.php
- src/Billing/X125010837P.php
Fixes #6268
correctly outputs line item payer adjustments for secondary claims
> fix: line item adjustments for secondary claims

- .github/stale.yml
Fixes #6201
Nota bene: this requires an additional label `WaitingForInfo` when maintainers decide something should be closed without further input. Feels like a fair tradeoff to me. 
... Hopefully this is the winner. Multi-user git is hard.
> chore: only stale-bot issues that lack info for reproduction or are unassigned

- interface/main/calendar/includes/pnAPI.php
- interface/modules/custom_modules/oe-module-claimrev-connect/src/Billing_Claimrev_Service.php
- interface/modules/custom_modules/oe-module-claimrev-connect/src/Eligibility_ClaimRev_Service.php
- interface/modules/custom_modules/oe-module-prior-authorizations/src/Controller/ListAuthorizations.php
- interface/modules/zend_modules/module/Acl/src/Acl/Controller/AclController.php
- interface/modules/zend_modules/module/Acl/view/acl/acl/acl.phtml
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Form/ModuleconfigForm.php
- interface/modules/zend_modules/module/Carecoordination/view/carecoordination/setup/index.phtml
- interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
- interface/modules/zend_modules/module/Installer/src/Installer/Model/InstModuleTable.php
- interface/modules/zend_modules/module/Installer/view/installer/installer/configure.phtml
fix: php 8.2 fixes
@juggernautsei and @claimrevolution , note I made very minor changes to your modules to clear php 8.2 warnings
> fix: php 8.2 fixes

- library/appointments.inc.php
Fixes #6234 
check to see if consecutive appointments are in office and if so use the previous appointments date and end time as the next appointment
> fix: portal scheduling fix

- API_README.md
Updated the api readme to include information about open id connect including the discovery endpoint and introspection.  Ran into a problem where I was missing the default site in my introspection url and couldn't figure out what was going on.  Decided to update the documentation to clarify the need for the site url.
> Update API_Readme.md for OIDC information

- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Bootstrap.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Controller/TeleconferenceRoomController.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Services/TelehealthConfigurationVerifier.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/TelehealthGlobalConfig.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Util/AuthUtils.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Util/TelehealthAuthUtils.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/templates/comlink/admin/telehealth_footer_box.html.twig
- interface/super/edit_globals.php
- interface/super/templates/field_html_display_section.php
- src/Services/Globals/GlobalSetting.php
Added the ability to verify the telehealth configuration settings to the Telehealth settings.
Also added a new GlobalSetting option to provide html sections to the global settings.  That way information boxes and any other custom large display of code for the settings can be displayed in the GlobalsConfiguration area.
> Fixes #6363 verify telehealth settings button

- interface/main/calendar/add_edit_event.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/public/assets/js/telehealth-appointment.js
- interface/modules/custom_modules/oe-module-comlink-telehealth/public/index-portal.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/public/index.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Controller/TeleHealthCalendarController.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Controller/TeleHealthFrontendSettingsController.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Controller/TeleconferenceRoomController.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/templates/comlink/appointment/add_edit_event.js.twig
- src/Events/Appointments/AppointmentJavascriptEventNames.php
Fixes #6371 
Implemented a generate invite link feature since we have to dynamically
generate an invite link now for the one time login links.  Since the
links are generated on the backend server we have to have a two step
process for grabbing the session link.  First the link is generated and
inserted into the DOM and then the browser can copy the link and the
invitation.  Firefox and safari block the copy feature when the copied
content is generated asynchronously.
Fixed the settings stuff that got lost during the merge conflict.
Added a setting option to configure the expiration time on the the one
time links.  Has a minimum of 1 minute and a maximum of 30 minutes.  If
the setting is missing or invalid it defaults to 15 minutes.
Fixed the display of the request media permissions …
> Feat openemr thirdparty onetime invitations

- src/Services/LogoService.php
replace file path separators to match passed in path
Fixes #6355 
Logo doesn't display on windows.
> Fix LogoService for Windows

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
Fixes #6097 
Makes it so we don't blow up the ccda generation when the uuid doesn't generate.  This only happens when you specify an office contact and the organization uuid is missing or the organization for the office contact is missing.
> fix: #6097 uuid failing on ccda generation

- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Controller/TeleHealthVideoRegistrationController.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Services/TeleHealthRemoteRegistrationService.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Services/TelehealthConfigurationVerifier.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/TelehealthGlobalConfig.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/templates/comlink/admin/telehealth_footer_box.html.twig
- src/Common/Auth/OneTimeAuth.php
Fixes #6389 
Fix telehealth provisioning resume to resume the user not suspend it.
Add debug logging for telehealth resume, suspend, and deactivate actions
in provisioning service.
Add more detailed messages on the verifier to detail whether the config
is not saved vs the portal is not setup.
Made the login time limit setting an optional setting so it doesn't
break the configuration setting.
Fixed a minor issue where if the settings fail validation and then
succeed afterwards, the text color is set to be a success message
instead of a failure.
If the patient's first name changed, isValidPatient would fail.  Fixed
the check so we just verify that there is a valid username and don't try
to match the patient first name with the portal username.
> Bug openemr fix 6389 telehealth bugs

- src/Services/FHIR/FhirLocationService.php
Fixes #6384 
The facility data was being excluded in a patient bound context.  If the access token is bound to a patient context it will return the patient location data when requesting a specific facility location id.  This was due to the OR clause in the patient bound search.
Fixed up the search query binding so patients get their own data or the facility data but it still prevents access to other patient data.
> Fix encounter location to provide facility data

- interface/language/lang_definition.php
- interface/language/lang_manage.php
- interface/language/language.inc.php
> fix: multi language tool fixes

- interface/patient_file/deleter.php
Fixes #6319 
instead of deleting forms we can set the deleted flag to 1 and this also avoids having to manage the different names of the `form_dir` created via the portal
> fix: set deleted flag for forms when delete person

- src/Core/ModulesApplication.php
Fixes #6396
Makes it so the webroot path still functions in the safe filter. Prevents injection of scripts in the header unless the file actually exists in OpenEMR and that its locked down to the module directory.
> Fixes #6396 webroot path for safe filter

- interface/modules/custom_modules/oe-module-comlink-telehealth/moduleConfig.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Bootstrap.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/TelehealthGlobalConfig.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/templates/comlink/admin/telehealth_footer_box.html.twig
- interface/modules/custom_modules/oe-module-comlink-telehealth/welcome.php
Fixed up the verbiage and some problems with the telehealth live payment signup process. It was popping up an alert box with the paypal subscriber id and expected the patient to copy and remember that value for signup.  This is most likely what was causing the multiple signup problems that users of the module were dealing with.
Broke the signup into three steps and provide progress status to the users as they signup.  Better instructions on how to move to the next step are included in each process.
> Openemr fix telehealth signup locale

- interface/modules/custom_modules/oe-module-comlink-telehealth/moduleConfig.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Bootstrap.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/TelehealthGlobalConfig.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/templates/comlink/admin/telehealth_footer_box.html.twig
- interface/modules/custom_modules/oe-module-comlink-telehealth/welcome.php
* Add save and locale telehealth check instructions
Added a check for the locale settings which should be setup to avoid clinic problems.
Added instructions that the user needs to log out and log back in after saving the telehealth settings.
* Fix psr problems.
* Fix telehealth subscription signup.
Include instructions and the subscription id for the user to use when they signup for the credentials.
Add a copy button and switch the alert of the subscription id to actually show up in a success message info box.  Before the change the user had limited understanding on how to proceed to the next steps in the configuration system.
* Improve signup verbiage, add subscription id
To make the signup process easier for users, we break the signup into three steps with instructions.  We also add …
> Openemr fix telehealth signup locale (#6413)

- interface/modules/custom_modules/oe-module-comlink-telehealth/src/TelehealthGlobalConfig.php
Telehealth settings needs to use the UniqueInstallationUuid instead of using the globals.
Fixes #6415.  This should be pretty rare that someone hasn't configured anything in their OpenEMR installation before setting up the telehealth settings, but this fixes that bug.
> Fix institution id to generate if empty

- src/Common/Auth/OpenIDConnect/Entities/ClientEntity.php
- src/Common/Auth/OpenIDConnect/Grant/CustomClientCredentialsGrant.php
- src/Common/Auth/OpenIDConnect/Repositories/ClientRepository.php
- src/FHIR/SMART/ClientAdminController.php
- src/RestControllers/AuthorizationController.php
- src/RestControllers/SMART/SMARTAuthorizationController.php
Made the support for multiple redirect_uri elements in a client registered app actually work.
Also fixed the missing import in the client_credentials grant flow.
Fixes #6444 
Fixes #6419
> Fixes #6444, #6419 oauth2 redirect, imports

- interface/globals.php
- interface/main/tabs/menu/menus/standard.json
- interface/reports/ip_tracker.php
- interface/usergroup/usergroup_admin.php
- library/ajax/login_counter_ip_tracker.php
- library/globals.inc.php
- sites/default/documents/custom_menus/Custom.json
- sql/7_0_1-to-7_0_2_upgrade.sql
- sql/database.sql
- src/Common/Auth/AuthUtils.php
- version.php
fixes #5627 
Basically provides ability to set a timeout (from last failed login) where then ok to login.
Also sets default setting of 20 for failed logins (and 1 hour for the timeout above)
Displayed the failed user login counter and last failed date in the Users display.
Would it also be helpful to have ability to reset the failed login counter in the Users display?
> feat: improve max failed login mechanism

- src/Services/AppointmentService.php
the pc_duration field was missing from the appointment search which breaks the insert event piece for the transfer appointment in telehealth.  Exposing the property ensures its not null.
Fixes #6500
> Fixes #6500 Telehealth Transfer appointment

- _rest_routes.inc.php
- apis/dispatch.php
- src/Common/Http/HttpRestRequest.php
- src/Common/Http/HttpRestRouteHandler.php
Makes the http request object PSR7 compliant so we can use it in other libraries that consume PSR7 requestinterface objects.
Fixes #6503.  By being interoperable with PSR7, module writers can leverage other libraries and pass the request into things such as Guzzle, Symfony, and other components that leverage an interoperable request object.
> Fixes #6503 httprequest PSR7

- interface/globals.php
- src/Common/Http/HttpRestRouteHandler.php
- src/Events/RestApiExtend/RestApiSecurityCheckEvent.php
- src/Services/BaseService.php
I add a new RestApiSecurityCheckEvent that allows module writers to initiate their own security checks or replace the current OpenEMR API security checks.
Fix a minor typo bug on the accessdenied exception in the globals.
I also add methods to the BaseService class to be able to get and set the event dispatcher.
Fixes #6504
> Fixes #6504 Security Api Extension Event

- src/Billing/BillingProcessor/Tasks/GeneratorX12.php
> fix: pass referenced variable instead of integer to genX12837P

- src/Billing/X125010837P.php
* fix: output service facility zip if not 9 digits
* fix log msg
Fixes #
> fix: output service facility zip if not 9 digits (#6489) for rel-701

- src/Services/FHIR/FhirValidationService.php
- src/Services/FHIR/UtilsService.php
- src/Services/PatientService.php
Add helper methods to the UtilsService for parsing and creating canonical urls, for parsing references, and creating operation outcome resources.
Also added two helper methods to retrieve the list of providerIDs for a given list of patients.
Fixes #6505 
Fixes #6509
> Fixes #6505,#6509 fhir,patient helper methods

- admin.php
Fixes #6460 
I added this line of code to admin.php.
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`
The admin page should fit within the display.
> Fit to window patch

- interface/usergroup/addrbook_list.php
- library/options.inc.php
- src/Billing/X125010837P.php
* output payer zip even if not 5 or 9 digits
* fix: username may be null for providers
* look for abook_type external providers in addr book
Fixes #
> username may be null for providers for Rel 701

- src/Common/Auth/OpenIDConnect/Repositories/ClientRepository.php
- src/Common/Utils/HttpUtils.php
- src/RestControllers/AuthorizationController.php
- src/RestControllers/RestControllerHelper.php
- src/Services/FHIR/FhirCodeSystemConstants.php
- src/Services/FHIR/Traits/MappedServiceCodeTrait.php
- src/Services/FHIR/Traits/MappedServiceTrait.php
- src/Services/FHIR/UtilsService.php
- src/Services/QuestionnaireResponseService.php
- src/Services/Search/TokenSearchField.php
Fixes #6574 
The questionnaire response search would fail when searching on things
such as id due to duplicate column names.  In order to make this service
work in a FHIR context we need to fix up the search method and handle
the uuid translations.
Fixes #6575 
Made it possible to save an oauth2 client using the client repository.
This makes it so OpenEMR callers don't need to include the RestConfig
class or deal with the AuthorizationController to generate a smart app
client record if needed.  Module writers can register their own smart
app as needed using this functionality.
Fixes #6576 
made it so the create update flag is set to false so API consumers know
they can't provider their own logical ids when creating a resource.
Also had some minor utility methods added in preparation for …
> Openemr fix 6574 6575 6576 fhir updates

- CONTRIBUTING.md
- ci/apache_82_1011/docker-compose.yml
chore: documentation for flex docker now using alpine 3.18 with php 8.2
> chore: documentation for flex docker now using alpine 3.18 with php 8.2

- interface/patient_tracker/patient_tracker.php
fixes php8 error not showing up in the logs - related to the implode function blocking FlowBoard from proceeding when a patient replies "CALL" indicating they need a callback regarding an appointment reminder they received.
It also removes the ability to add a note about the Callback request.  Instead it is replaced with an icon to directly open the SMS Bot so staff/front desk can directly reply to the patient via SMS, if SMS is allowed and they have a mobile/cell phone listed in demographics.  If not, just the CALL icon is displayed.
Fixes #6596
> fix: Update patient_tracker.php

- .env.example
- interface/main/tabs/main.php
add new environment debug variable to turn off dated reminders and background  service from running.
Fixes #6601 
Decided to keep as separate PR
> Allow repeater services to be turned off

- src/Billing/X125010837P.php
> fix: output other insco zip if not 5 or 9 digits and log if isn't

- src/Billing/X125010837P.php
…600)
* fix: output other insco zip if not 5 or 9 digits and log if isn't
* fix: output other insco payer zip if not 5 or 9 digits and log if isn't
* fix first commit with insuredZip
* fix logic payerZip
* surround conditions
* formatting
Fixes #
> fix: output other insco zip if not 5 or 9 digits and log if isn't for rel-701

- src/Services/BaseService.php
- src/Services/MedicationPatientIssueService.php
> fix: allow a field with date somewhere in it's name to be null in BaseService buildUpdateColumns()

- interface/patient_file/encounter/forms.php
- src/Events/Encounter/EncounterFormsListRenderEvent.php
- src/Services/EncounterService.php
- src/Services/FormService.php
Fixes #6629 add render events to top and bottom of encounter form.
Exposed the table name in the encounters service as well so we can actually use it instead of copying the name elsewhere.
> feat: Fixes #6629 Encounter forms list render event

- interface/patient_file/summary/demographics.php
Move from a flawed flex-based layout to a column based layout to ensure the UI remains usable. Also update the medication card to render the dosage instructions.
Fixes #6651 
Note I copied and pasted a few problem list many times to render a mock PL that is incredibly long as a test that this looks better.
> fix: Better UI of PAM UI

- interface/patient_file/summary/demographics.php
Only render card if enabled in $GLOBALS
fixes #6653
> fix: Only render Portal Card on MRD if Portal is enabled globally

- interface/patient_file/summary/demographics.php
Ensure the portal card is rendered if any of the API options or the portal is enabled, otherwise hide the portal card.
See #6653
> fix: Hide the portal card if the portal is disabled and ALL APIs are disabled

- interface/patient_file/summary/add_edit_issue.php
- interface/patient_file/summary/add_edit_issue_medication_fragment.php
- interface/patient_file/summary/stats_full.php
Resolves #6664 
I still think there's improvements that can be made to the quick-pick list versus title versus code but this is still much improved. By default, only the clinically critical fields are displayed, with a collapsing div to hold everything else. The title field now has a helper button to open the code window. The dialog box opens wide and taller now. Something I couldn't figure out is why we hide the Active checkbox, which seems like it would be a nice little feature. However, since I couldn't determine why it's not shown when it is, I chose not to change the logic.
<details><summary>Before / After</summary>
</details>
> feat: Improve the add/edit Issue UI

- src/Common/Twig/TwigExtension.php
Resolves #6247 
New wrapper for the `getLogo()` function from `LogoService` available in twig.
> feat: new Twig function for getting logo url

- interface/main/messages/messages.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- library/pnotes.inc.php
New portal auth check function
modify get query to include portal users
Fixes #6695 
Allows portal messages to be view by users that are assigned to the portal.
New portal auth check function
modify get query to include portal users
> Allow any flagged portal user to view portal pnotes

- interface/billing/sl_eob_search.php
change button name attribute to form_email from form_download
This should go out in next patch!
Fixes #6711 
Billing invoice email send
> Billing invoice email broken

- library/options.inc.php
> fix: use mb_strlen to check field value length in get_layout_form_value()

- src/Services/Search/DateSearchField.php
- src/Services/Search/SearchFieldStatementResolver.php
Fixes #6669 changed out the regex for the date parsing to handle partial seconds up to milliseconds. Also documented the code a little bit better for the regex.
> Feat openemr fix #6669 date partial seconds

- src/Events/CDA/CDAParseEvent.php
- src/Events/CDA/CDAPostParseEvent.php
- src/Events/CDA/CDAPreParseEvent.php
- src/Services/Cda/CdaTemplateParse.php
Will resolve #6715. Add a new Event allowing hooks into `parseCDAEntryComponents()` for every component that gets parsed. The event dispatches the string of the component (encounter, allergy, medication, problems, etc), the OID, the component array, and the current state of `$templateData`.
`CdaTemplateParse->templateData` is always updated with the results of `$event->getTemplateData()` The event runs __after__ the core parsing function runs
> feat: Hook into the CDA Parsing functions

- src/Common/Http/HttpRestRequest.php
Query params were not being set due to how the http rest request is not being populated.
Fixes #6732
> Fixes #6732 fhir _search query params

- .gitignore
- ccdaservice/data-stack/data-stack.spec.js
- jest.config.js
- package.json
Create script to generate test coverage reports for JS files.
Running `test:js-coverage` will generate the report inside the folder `coverage/js-unit`.
By opening the `index.html` file inside the folder `coverage/js-unit/lcov-report`, you can easily navigate through the project and check statistics for each file:
If there's interest, we could also include the `coverageThreshold` option to discourage people from adding more JS without including tests. The initial value would allow the project to pass as is. As coverage increases over time, we would increase the value of the threshold to prevent coverage from falling. This is a decision to be made by the team, so it's not included in this initial proposal.
> feat(jest): coverage reports for js unit tests

- interface/patient_file/summary/demographics.php
- interface/smart/ehr-launch-client.php
- library/globals.inc.php
- library/js/utility.js
- oauth2/smart/ehr-launch-autosubmit.html.twig
- sql/7_0_1-to-7_0_2_upgrade.sql
- sql/database.sql
- src/Common/Auth/OpenIDConnect/Entities/ClientEntity.php
- src/Common/Auth/OpenIDConnect/Repositories/ClientRepository.php
- src/Common/Auth/OpenIDConnect/SMARTSessionTokenContextBuilder.php
- src/Common/Session/SessionUtil.php
- src/FHIR/SMART/ClientAdminController.php
- src/FHIR/SMART/SMARTLaunchToken.php
- src/FHIR/SMART/SmartLaunchController.php
- src/RestControllers/AuthorizationController.php
- src/RestControllers/SMART/SMARTAuthorizationController.php
First stab at #6525 by allowing the EHR to launch a smart app and reuse the authorization context that the currently logged in user has.  Keeping it as draft for now in order to discuss the security implications and for a followup commit to add the database tracking to prevent replay attacks.
I introduce a global that by default is off to allow OpenEMR administrators to enable smart apps to skip the authorization screen when the smart app is launched inside the EHR.
I refactored the launch sequence now to be an on-demand generation of the launch token using javascript instead of generating the token and stuffing it into the html.
I added a flag on the individual client app to turn on or off the authorization skip flag.  This gives admins control over allowing apps to launch immediately …
> feat: #6525 Use EHR authorization for SMART Apps

- interface/clickmap/C_AbstractClickmap.php
Pain map wasn't saving due to invalid use of a $this->model reference. Changed the reference to be a local variable which then saves fine. I'm assuming this broke as part of the smarty upgrade process.
Fixes #6742
> Fix #6742 Pain Map saving

- tests/api/InternalApiTest.php
- tests/api/InternalFhirTest.php
Fixes #6744
Have made the changes for the internal and fhir apis to work as expected
InternalApiTest.php -
Added setIsLocalApi and setApiType  for the $restRequest, Modified setRequestURI to setRequestPath for the $restRequest
InternalFhirTest.php -
Changed the URL endpoint from '/apis/api/facility' to '/apis/fhir/Patient' in the functions  testFetchApi and testAjaxApi, Added setIsLocalApi and setApiType  for the $restRequest, Modified setRequestURI to setRequestPath for the $restRequest, Changed $routes list from $ROUTE_MAP to $FHIR_ROUTE_MAP to fetch the Fhir endpoints
> Modifications in InternalApiTest and InternalFhirTest files to make it work locally in a new module

- interface/themes/tabs_style_full.scss
Fixes #6746 
The contrast of the navigation bar in dark theme when hovered over was not accessible. 
This commit resolves this issue to match the background of the hovered submenu.
> Increased contrast in navbar hover in dark theme

- interface/patient_file/summary/demographics.php
Resolves #6760 by accounting to the prescription card. Also swaps `.row` for `.form-row` for small gutters on that row. Not a great fix, we could probably add a utility class for smaller gutters but that is outside the scope of this fix
> fix: Ensure proper rendering of top cards

- library/options.inc.php
- src/Services/PatientService.php
- default pid to null if new patient
Needs to go back in patch. May not be able to cherry pick.
Fixes #6769
see issue
null pid if 0
> Prevent previous name fetch on pid = 0

- _rest_routes.inc.php
- interface/super/edit_globals.js
- interface/super/edit_globals.php
- interface/super/templates/globals-address-book.php
- interface/usergroup/addrbook_list.php
- src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
- src/FHIR/Config/ServerConfig.php
- src/Services/Globals/GlobalSetting.php
- swagger/openemr-api.yaml
Fixes #6752 
Fixes #6751 
Allows an address book config data type to be added for the global config.
Adds an endpoint for retrieving users from the system.  If there are users we wish to retrieve that are not practitioners (such as external entities that are in the address book), we can't use the practitioner api.  Instead we expose the users endpoint.
> feat: openemr 6752 6751 address book user rest api

- .stylelintignore
Specifying interface folders with errors, so they can be separately fixed in future changes. This also reincorporates folders without errors in the stylelint analysis, so they can be monitored for errors from now on.
> chore(stylelint): specify interface folders with errors

- interface/main/tabs/js/custom_bindings.js
- oauth2/smart/ehr-launch-autosubmit.html.twig
Fixed the menu item to hide the overlay on the external domain.
I still don't like that it sets the title to unknown but without some heavier refactoring to populate a default label as defined in the menu system there's not a lot that can be done here.
Fixes #6781
> Fixes #6781 hide overlay on external domain

- interface/usergroup/addrbook_list.php
- library/classes/postmaster.php
- sql/7_0_1-to-7_0_2_upgrade.sql
- sql/database.sql
- templates/emails/system/system-notification.html.twig
- templates/emails/system/system-notification.text.twig
Add a new column to the email queue to hold the template name, we use the email message body to store json details for the twig templates.
Add two vanilla system notification templates.
Fixes #6772
> feat: Fixes #6772 adds twig email templates to emails

- ccdaservice/serveccda.js
- ccdaservice/utils/clean-code/clean-code.js
- ccdaservice/utils/clean-code/clean-code.spec.js
- ccdaservice/utils/constants.js
- extract cleanCode function to a separate file
- add tests
- create constant NULL_FLAVOR
The constant allows us to reuse the value without having to type it repeatedly, which is error-prone. It also simplifies the process of updating the value, if needed in the future.
> refactor(ccdaservice): extract and test cleanCode function

- templates/core/about.html.twig
- templates/login/login_core.html.twig
- templates/login/partials/html/product_registration_modal.html.twig
This is a proposal to change the colors of the buttons inside the registration modal:
This change has two purposes:
- provide better differentiation between the buttons
- grab the user's attention and highlight the action we want to encourage
This is a common UI pattern for CTAs
[Update]: following feedback by @robertdown, the "No Thanks" button will keep the `btn-secondary` class.
> refactor(registration-modal): improve button colors

- interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
add custom module pathing
Fixes #6808 
Missing pathing for SQL upgrade checks for custom module.
Fix missing pathing for SQL upgrade checks for custom module.
> Fix Zend module SQL upgrade

- interface/modules/custom_modules/oe-module-faxsms/openemr.bootstrap.php
- interface/modules/custom_modules/oe-module-faxsms/src/Events/NotificationEventListener.php
Fixes #6820 
Fixed it so that if you fire the SendNotificationEvent event inside an API
call it will no longer be silently ignored in the fax/sms module.
Changed the module to use the user_id or pid in the session as a
determinant of the session being populated instead of the
session_database_uuid.
Fixed spelling error in the email subject being sent.
> Bug openemr fix #6820 fax api call

- _rest_routes.inc.php
- src/Common/Database/QueryPagination.php
- src/Common/Database/QueryUtils.php
- src/RestControllers/PatientRestController.php
- src/RestControllers/RestControllerHelper.php
- src/Services/FHIR/FhirPatientService.php
- src/Services/FHIR/FhirServiceBase.php
- src/Services/FHIR/IResourceSearchableServiceWithConfig.php
- src/Services/FHIR/Traits/ResourceServiceSearchTrait.php
- src/Services/PatientService.php
- src/Services/Search/FHIRSearchFieldFactory.php
- src/Services/Search/SearchConfigClauseBuilder.php
- src/Services/Search/SearchFieldOrder.php
- src/Services/Search/SearchQueryConfig.php
- src/Validators/ProcessingResult.php
- swagger/openemr-api.yaml
- tests/Tests/RestControllers/PatientRestControllerTest.php
Fixes #6800 
Fixes #6799 
Add common _sort parameter that can be used in the _rest_routes
Add date,_offset,_limit query parameters to the /api/patient route
Added helper method QueryUtils::escapeLimit for escaping limit parameters in SQL queries.
Changed standard api to return the links parameters if there are paginated responses for the search (someone searched with the _limit/_offset parameters).
Added to FhirPatientService the _lastUpdated search parameter that can be used.
Changed FHIR api to support in the base service the ability to do a searchForOpenEMRRecordsWithConfig method that will allow more customized configuration options in the future in addition to the basic search parameters.  It currently supports pagination and sort order.  Right now only the patient service supports …
> WIP Fixes #6800,#6799 fhir/std api sort/pagination

- interface/patient_file/summary/create_portallogin.php
- src/Services/PatientAccessOnsiteService.php
- templates/patient/portal_login/print.html.twig
Add user setting to persist option for the user setting it in MRD
add checkbox and persist js function to template.
Fixes #6813
> Add disable forced reset credential flag on portal login reset/create

- interface/usergroup/mfa_totp.php
- library/classes/Installer.class.php
- setup.php
In order to use a non-qr type TOTP code we need to show the shared secret when going to add the code.
Fixes #6839
> feat: Fixes #6839 show mfa shared secret

- src/Services/AllergyIntoleranceService.php
> fix: fix AllergyIntoleranceService lookup by pid

- interface/patient_file/summary/demographics.php
- library/options.inc.php
- src/Common/Layouts/LayoutsUtils.php
- src/Common/Twig/TwigExtension.php
- templates/patient/card/allergies.html.twig
fixes to allergy card in patient summary
> fix: fixes to allergy card in patient summary

- interface/themes/color_base.scss
Fixes #6865
Sets highlight according to custom color palette when using styles with customized colors.
Add backgrpund based on color palette to make it contrast (darker background and pale text)
> fix: highlight when using custom theme shows text colored pink  (https://github.com/openemr/openemr/issues/6865)

- ccdaservice/serveccda.js
- ccdaservice/utils/providers/providers.js
- ccdaservice/utils/providers/providers.mock.js
- ccdaservice/utils/providers/providers.spec.js
With this one, we finally reach 1% coverage :partying_face:
> refactor(ccdaservice): test and refactor populateProvider function

- interface/patient_file/download_template.php
Fixes #6868
Textarea fields of forms containing line breaks will shown as they are saved when generating a patient document template.
add a dataFixup that sends text:line-break as required by OpenDocument writer.
> fix: line breaks in textarea fields - when fetching data to a patient document template

- interface/eRxSOAP.php
- interface/eRxXMLBuilder.php
- interface/patient_file/summary/demographics.php
Fixes #
Something changed in PHP, or a package dependency that broke the parsing of allergy and medication responses from NewCrop.
This fixes that, and also prevents sending diags other than ICD10 to NewCrop because NewCrop only supports ICD10.
@bradymiller If possible, this should also be merged into rel-701 and added to next patch.
> fix parsing of response from NewCrop

- src/Services/ClinicalNotesService.php
Resolves both #6907 and #6908 
This changes the default behavior of the two relevant functions in the ClinicalNotesService by assuming the request is for active list options only. Can pass `true` to the function (Setting `$includeInactive`) which will return all options
> fix: Return only active clinical note types and categories by default

- interface/forms/newpatient/common.php
- library/globals.inc.php
Resolves #6909 by creating a new global similar to other options on the Encounter form. The only difference is rendering also accounts for the Hide Billing Widget global.
> fix: In Collection option in Encounter Form configurable

- interface/forms/newpatient/common.php
Fixes #6928 
it's okay for `pos_code` to be `null` since billing will check for that and grab the proper code for the service facility
> fix: encounter pos_code to null to honor config

- interface/orders/receive_hl7_results.inc.php
> fix: use datetime of procedure result to match existing encounter

- interface/orders/single_order_results.inc.php
Fixes #6917
The lab results don't show a date in the specimen column. 
Quest would like a date to be shown there. The specimen column would show the specimen number if one were entered into the results page; however, if one is not entered. Then, the field is blank. Ron at Quest asked that the date be shown in the column under specimen.
> Displaying date in specimen column of lab results.

- interface/forms/procedure_order/common.php
- interface/procedure_tools/libs/labs_ajax.php
- interface/procedure_tools/quest/gen_hl7_order.inc.php
- src/Events/Services/LabTransmitEvent.php
- src/Events/Services/QuestLabTransmitEvent.php
> Quest Lab Hub module support

- interface/login/login.php
- interface/patient_file/encounter/find_code_dynamic_ajax.php
- add modifier to lists search returned array
Fixes #6984 
- see issue
Apparently datatables project is now enforcing all columns from table build has a data object.
In the past we default to the code type header for lists (three columns) however failed to populate the modifier column on search return results.
> Layout editor list dialog error fix

- interface/patient_file/summary/demographics.php
Ensure `$cards` is never less than 1, render proper bootstrap classes. Resolves #6965
> fix: Ensure proper bootstrap classes for PAMI list

- interface/patient_file/summary/demographics.php
- templates/patient/card/card_base.html.twig
* fix: use btn-link instead of a tag for dashboard cards
* remove redundant section classes card mb-2
* change listening element to button
Fixes #
> fix: use btn-link instead of a link for dashboard cards (#6995)

- src/Services/FHIR/Organization/FhirOrganizationInsuranceService.php
Bulk export would fail if a company had an insurance company in the EMR.  Fixed the misnamed variable.
Fixes #7000
> Fixes #7000 bulk export 500 failure

- src/Services/FHIR/FhirProvenanceService.php
Provenance was relying on patient ids for patient/$export and system/$export operation.  This should resolve that issue.
Fixes #7001
> Fixes #7001 Bulk FHIR 500 error patient ids

- src/Services/FHIR/FhirAllergyIntoleranceService.php
- src/Services/FHIR/Observation/FhirObservationSocialHistoryService.php
- src/Services/FHIR/Observation/FhirObservationVitalsService.php
- src/Services/ProcedureService.php
- src/Services/SocialHistoryService.php
Allergy intollerance was failing when the unassigned reaction was given since there are no codes and that threw a warning.
social history was relying on columns that didn't exist that also threw warnings.
Vitals services temp_method was not being set properly and threw a warning.
Procedure service had a number of columns it attempted to populate but the actual data values did not match with the array keys.
Fixes #7002.
> Fixes #7002 FHIR api warnings missing keys

- src/Common/Auth/OpenIDConnect/JWT/JsonWebKeySet.php
- src/Common/Auth/OpenIDConnect/JWT/RsaSha384Signer.php
- src/RestControllers/RestControllerHelper.php
Fixes the export operation name to be 'export' which is the expected name coming from the OperationDefinition.code property for the $export operation for Patient/Group/System export.
Also added a few more debug logs to the json key stuff to help with debugging.
Fixes #7019.
> Fixes #7019 operation name export operation

- interface/login/login.php
fix: login language selector settings for allowed languages and hiding dummy language
> fix: login language selector settings for allowed languages and hiding dummy language

- interface/drugs/add_edit_lot.php
If the lot quantity was a string the script fatally errored.  Fixes the issue.
Fixes #6942
> Fixes #6942 type conversion fatal error.

- sql/7_0_1-to-7_0_2_upgrade.sql
- sql/database.sql
- templates/patient_finder/finder.html.twig
> fix: dob typo in recent patient finder

- interface/main/finder/dynamic_finder.php
- src/Services/PatientService.php
- templates/patient_finder/finder.html.twig
* This version does not preserve the order of recent_patients data.
* This version preserves the order.
* This version is updated to ONLY store the pid values in the recent_patients table.
* Code style cleanup...
* Correctly format date and datetime columns from patient_data in the Recent Patients tab
* Correct PHP styling
* chore: bump db version for prior commit (#7044)
* Chore: change production docker to 7.0.2
* Update docker-compose.yml to 7.0.2
* Make Recent Patients Tab more similar to the Patient List tab -- i.e. clickable rows, etc.
* Use patient_data.pid to uniquely identify patients for Recent Patients list ;  Change twig to xlt the table headers.
* fix SQL statements so SQL commands are capitalized consistently.
* change from xlt to xlListLabel for column titles.
--------- …
> Recent patients fixes rel-702

- interface/forms/eye_mag/a_issue.php
- interface/forms/eye_mag/css/style.css
- interface/forms/eye_mag/php/eye_mag_functions.php
Here are some simple Eye Form styling fixes.
> Eye Form Style fixes

- interface/reports/prescriptions_report.php
Fixes #7057
Fixes `&nbsp;` being visible in rows following parent rows, particularly after a patient is first mentioned.
- Fix visible non-breaking spaces in child rows
> Fix visible non-breaking space in Rx report

- interface/login/login.php
- src/Common/Auth/AuthUtils.php
Fixes #7067 
include in 7.0.2 patch 1
- wrap login twig loader in try/catch so user is notified
- ignore ($GLOBALS['password_expiration_days'] if is set to blank/empty string in password auth validation.
- report password expired to error log as a notice.
> bug fixes password expired global

- library/forms.inc.php
- src/Common/Auth/AuthUtils.php
- query and set global value for test in constructor
Fixes #
Security concerns previous password_expiration_days is blank fix.
> Auth security fix previous PR#7068

- library/forms.inc.php
- src/Common/Auth/AuthUtils.php
* Auth security fix previous PR#7068
- query and set global value for test in constructor
* - annoying warning PHP Warning:  Undefined array key 1 in C:\xampp\htdocs\openemr\library\forms.inc.php on line 163
Fixes #
> Auth security fix previous PR#7068 (#7082) for rel-702

- .github/workflows/syntax.yml
chore: add php 8.4-dev syntax check to ci
> chore: add php 8.4-dev syntax check to ci

- .github/workflows/test.yml
- ci/apache_83_112/docker-compose.yml
chore: updated mariadb testing versions for ci
(dropped mariadb 10.10 version from ci)
(added mariadb 11.2 version to ci)
> chore: updated mariadb testing versions for ci

- src/RestControllers/SMART/SMARTAuthorizationController.php
- templates/api/smart/smart-style_light.json.twig
Fix the 500 url loading error in issue #7133.
Add the logo and modal backdrop color to the twig files in #7134
> Fixes #7133, #7134 SMART on FHIR style fixes

- src/RestControllers/SMART/SMARTAuthorizationController.php
- templates/api/smart/smart-style_light.json.twig
Fix the 500 url loading error in issue #7133.
Add the logo and modal backdrop color to the twig files in #7134
> Backport rel-702 Fixes #7133, #7134 SMART on FHIR style fixes (#7135)

- src/Events/Encounter/EncounterButtonEvent.php
Fixes #7084
Missing print label button
Add print label button
> fix: missing print label file for the quest lab hub

- interface/forms/LBF/printable.php
> fix: add margin defaults to prevent mpdf php8 fatal math error LBF printing

- interface/forms/LBF/printable.php
- library/custom_template/ajax_code.php
> chore: replace htmlspecialchars with escaping functions for recent commit

- library/custom_template/add_context.php
- library/custom_template/delete_category.php
- library/custom_template/personalize.php
> fix: escaping custom templates used with ckeditor

- src/Common/Twig/TwigExtension.php
The twig custom function csrfToken($subject = 'default', $fieldName = "_token") sig arg $subject will not default to arg value unless null is passed in. Quote counts as populated.
Fixes #7167 
Modify twig function to ensure proper subject from csrf token creation is used in verification.
> Fix for opening new tab from picker

- interface/orders/types.php
> fix: use REQUEST global to catch form_order

- interface/super/rules/library/RuleManager.php
> fix: fix cdr gui alert toggles

- interface/globals.php
add routine to set uninitialized user settings not in globals.
Fixes #7194
> Global user settings not set

- interface/main/calendar/add_edit_event.php
> feat: use global default visit category for add edit event

- interface/forms/fee_sheet/new.php
- interface/main/tabs/menu/menus/standard.json
- interface/patient_file/encounter/load_form.php
- interface/super/edit_list.php
- sites/default/documents/custom_menus/Custom.json
Fixes #7165 built off of @sjpadgett #6382
> fix: support multiple modifiers in fee sheet

- interface/modules/custom_modules/oe-module-weno/scripts/file_download.php
- interface/modules/custom_modules/oe-module-weno/scripts/weno_log_sync.php
- interface/modules/custom_modules/oe-module-weno/src/Services/Container.php
- interface/modules/custom_modules/oe-module-weno/src/Services/DownloadWenoPharmacies.php
- interface/modules/custom_modules/oe-module-weno/src/Services/FacilityProperties.php
- interface/modules/custom_modules/oe-module-weno/src/Services/LogDataInsert.php
- interface/modules/custom_modules/oe-module-weno/src/Services/LogImportBuild.php
- interface/modules/custom_modules/oe-module-weno/src/Services/LogProperties.php
- interface/modules/custom_modules/oe-module-weno/src/Services/PharmacyService.php
- interface/modules/custom_modules/oe-module-weno/src/Services/TransmitProperties.php
- interface/modules/custom_modules/oe-module-weno/src/Services/WenoPharmaciesImport.php
- interface/modules/custom_modules/oe-module-weno/src/Services/WenoPharmaciesJson.php
- interface/modules/custom_modules/oe-module-weno/templates/facilities.php
- interface/modules/custom_modules/oe-module-weno/templates/indexrx.php
- interface/modules/custom_modules/oe-module-weno/templates/rxlogmanager.php
- interface/modules/custom_modules/oe-module-weno/templates/synch.php
- interface/super/edit_globals.php
- Improve pharmacy import by using transactional queries. From 4 minutes to 40 seconds.
- improve validation and error reporting.
- some code cleanup for warnings and in general
- fix frame screen output to use the current theme so user always see content.
Fixes #
> Weno fixes and updates

- src/Validators/PatientValidator.php
This allows empty strings to be validated.  Fixes #7219.
> Fixes #7219 email validate allow empty strings.

- src/Services/AddressService.php
- src/Services/InsuranceCompanyService.php
- src/Services/PhoneNumberService.php
We fix #7216 where we populate the plus_four property in the address service.
Fixes #7217 where we allow the record id to be set / saved on insert. We also throw exceptions if the sql command fails. Lastly we skip saving the phone number if there is nothing in the data.
> Fixes #7216,#7217 insurance company saves

- src/Services/InsuranceCompanyService.php
Make it so that we still return records even if there is no corresponding address record.  This happens because city and street if they are empty forces an address record to be skipped in creation.
Fixes #7226
> Fixes #7226 Insurance company address query

- contrib/forms/xmlformgen/xslt/new.php.xslt
- contrib/forms/xmlformgen/xslt/view.php.xslt
- interface/main/calendar/add_edit_event.php
- interface/modules/zend_modules/module/Carecoordination/view/carecoordination/setup/index.phtml
- interface/orders/single_order_results.inc.php
- interface/reports/patient_flow_board_report.php
- portal/report/portal_custom_report.php
- portal/report/portal_patient_report.php
> fix: bug fix

- interface/modules/custom_modules/oe-module-weno/ModuleManagerListener.php
- interface/modules/custom_modules/oe-module-weno/moduleConfig.php
- interface/modules/custom_modules/oe-module-weno/src/Services/ModuleService.php
- interface/modules/custom_modules/oe-module-weno/src/Services/TransmitProperties.php
- interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
- interface/modules/zend_modules/module/Installer/src/Installer/Model/InstModuleTable.php
- interface/modules/zend_modules/module/Installer/view/installer/installer/configure.phtml
- interface/modules/zend_modules/module/Installer/view/installer/installer/index.phtml
- interface/modules/zend_modules/public/js/installer/action.js
- src/Core/AbstractModuleActionListener.php
- src/Core/ModulesApplication.php
Fixes #7247 
Complete refactor of Module Manager to a one page table of all module types.
We now auto register modules to install ready state. You will still get an unregister button that will remove module database entry then will auto reregister to a new registered state. Biggest reason to allow this is so that if the modules action event listener needs to reinstall or other cleanup activities, it can.
If you want or need to use the modules config/settings(for David!:)) script before the module is enabled, you'll need to set the modules table mod_ui_active flag. I added a convenience function to abstract base class to example or use.
- See Wenos or FaxSMS ModuleManagerListener class for examples of  using the new mod_ui_active flag and trapping events.
- To be safe and ensure classes …
> Module Manager Refactor

- src/Billing/Claim.php
- src/Validators/CoverageValidator.php
Fixes #7263 
also removes required ss entry for insurance since is unnecessary
>  fix: skip empty insurance for claim validation in billing manager 

- library/clinical_rules.php
cdr fix to correctly show actions that are due, due soon, past due in expanded listings
Reported by @hanksterr7 
Note that the code change here is very minimal (just ensuring `$dateCounter == 1` before running the code that states it is Not Due). This link will show the code changes without whitespace to show this:
https://github.com/openemr/openemr/pull/7211/files?w=1
Testing well in both reminder and report mode.
> fix: cdr fix to correctly show actions that are due, due soon, past due in expanded listings

- bin/console
- src/Common/Command/CreateAPIDocumentationCommand.php
- src/Common/Command/CreateClientCredentialsAssertionSymfonyCommand.php
- src/Common/Command/Runner/CommandRunner.php
- src/Common/Command/SymfonyCommandRunner.php
- src/Events/Command/CommandRunnerFilterEvent.php
We change up the OpenEMR command runner to be deprecated and add a warning notice for people to use the OpenEMR symfony command runner in bin/console.
Changed up the symfony command runner to use a class that also fires an event to grab module commands if there exist any in the system. Deprecated the create client assertions command since that is used in our FHIR api documentation.  I completely migrated the api documentation creation command into the symfony command runner.
Fixes #7237
> Fixes #7237 allow modules to add CLI commands.

- interface/patient_file/encounter/select_codes.php
- change by adding a search and reset button implemented by datatables search function.
Removes the type ahead feature. Even on a very fast machine search is slow on the large code datasets. 
With type ahead an event fired a search request every character where events would stack in DOM. IMO a no no
Fixes #7276
> Change search behaviour of select codes

- templates/prescription/general_edit.html
Fixes #7314
The `per_refill` field is declared as an `INT` in `sql` (whose maximum possible value is `2147483647`), hence setting the `maxlength` of `per_refill` to `9`, so that the value gets saved correctly.
Reduced `maxlength` of `per_refill` to `9`
> Reduce `maxlength` of `per_refill` to `9`

- interface/code_systems/list_staged.php
- library/standard_tables_capture.inc.php
- sql/7_0_2-to-7_0_3_upgrade.sql
- sql/database.sql
- version.php
> feat: support for loading 2024 reporting cqm valueset

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- src/Common/Command/CcdaImport.php
- src/Common/Command/CcdaNewpatient.php
- src/Common/Command/CcdaNewpatientImport.php
- src/Common/Command/Trait/CommandLineDebugStylerTrait.php
- src/Services/Cda/CdaTemplateImportDispose.php
Fixes #7319 
This fixes the error in the ccda that was creating tons of entries in the drug_entry list options list.  The CCDA was not checking against empty values and would continue to create new list_options for each immunization / prescription drug_unit when the unit was an empty string
I also added some debugging instruments on the prescription and immunization process which makes it easy to compare for a ccda what is being parsed and what is being stored in the database.
Added a debug flag to all of the ccda commands so that these options are available for people needing to do any debugging of the process.
> Fixes #7319 ccda extra drug_unit list options

- library/options.inc.php
- src/Common/Forms/Types/BillingCodeType.php
- src/Common/Layouts/LayoutsUtils.php
Fixes #7323 
This is a billing code selector widget that was used in options.inc.php. I extracted it into its own class file so I can use it in a module as well as use it in options.inc.php.
I also moved the options.inc.php isOption command to the LayoutUtils so it can also be used externally.  I marked the isOption function as deprecated.
> Fixes #7323 Billing Code Widget,deprecate isOption

- library/patient_tracker.inc.php
- src/Services/AppointmentService.php
- src/Services/PatientTrackerService.php
> fix: speed up slow flow board using static methods

- interface/logview/logview.php
Fixes #7335
The OpenEMR logs uses the time format as Hours:Minutes which is inadequate to determine the timeline of events. This fix changes the time format to Hours:Minutes:Seconds
Add the parameter for seconds as true in two echo statements
> fix: inadequate date time format in log viewer

- src/Common/Logging/EventAuditLogger.php
Fixes #7340 
This PR adds a log scrubbing template to mask sensitive details in the log(which is currently exposed in logs). Currently, this template only masks the field "reference" in the table "ar_session" to conceal sensitive payment details in the log. However, if approved, this template can be used to extend the masking of other sensitive details to other tables and fields too. Masking of sensitive information in logs is essential to prevent the stealing of information. (ASVS 7.1.1).
After update: 
1. In "EventAuditLogger.php", add a class constant to keep track of the tables and the fields in each table that contains sensitive information.
2. In "EventAuditLogger.php", for any insert operation, if the current table contains any field containing sensitive information, the value for …
> Fix: OpenEMR logs sensitive information such as payment details

- library/options.inc.php
- src/Common/Forms/Types/LocalProviderListType.php
Fixes #7368
This is a local provider's selector widget that was used in options.inc.php. I extracted it into its own class file so I can use it in a module as well as use it in options.inc.php.
I added options to inject a static list of providers into the widget for caching/performance reasons.  Also added option to inject the query used to retrieve the list of providers into the widget.
> Fixes #7368 local provider's form list type

- src/Services/BaseService.php
- src/Services/EmployerService.php
- src/Services/PractitionerService.php
This changes the getSelectFields method signature to support column and table aliases.
Fixes #7370.
I do have concerns as this would be a breaking change if anyone private fork or custom module extends the BaseService method and override the getSelectFields method.  It doesn't break any logic in core but I wonder if this will have problems.  As this is likely to go into a minor patch I'm not sure if we bring it in or not.
> Fixes #7370 support select-fields alias

- controllers/C_Document.class.php
- library/classes/Document.class.php
- src/Events/PatientDocuments/PatientDocumentStoreOffsite.php
- src/Events/PatientDocuments/PatientDocumentUpload.php
- src/Events/PatientDocuments/PatientRetrieveOffsiteDocument.php
Fixes #7232
* A dispatch will be sent to see if any module is listening for the file upload.
* If a listener is found then the file will be uploaded to the listener and the fiber will be terminated.
* If no listener is found then the file will be stored locally.
Adding fiber class to the documents class to accomplish the tie in between the module and local file storage
> Store documents in remote cloud bucket

- library/clinical_rules.php
fixes #7266
Fixes #7153
Fixes #7157
Fixes #7161
CDR engine fixes for duplicate use of actions across rules in addition to an optimization
The optimization both clarifies the code regarding which $reminder_due status is chosen and also minimizes the calls to reminder_results_integrate, which could get resource intensive if overuse it.
Also brought in fixes from https://github.com/openemr/openemr/pull/7160
> fixes: CDR engine fixes for duplicate use of actions across rules in addition to an optimization

- interface/patient_file/history/encounters.php
Fixes #7270
to print or make a pdf of a visit history report one had to use the browsers print function, with ctrl+p or file/print etc. This only prints what had been displayed on the screen, so for a long history that takes several screens only the first would be printed.
add a 'print' button that prints the complete page of the history being displayed. for page length 'ALL' this is the complete history which will produce a multi page document where necessary
display the patient's details at the top of the history window and on the first page of the print or pdf document.
>  add print button and put patient's details at top of visit history page #7270

- interface/modules/zend_modules/module/Application/src/Application/Plugin/CommonPlugin.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- src/Services/Cda/CdaTemplateParse.php
> fix: check for empty postParseEvent ccda import

- interface/billing/sl_eob_process.php
> fix: use empty array if no cpts when posting era

- interface/usergroup/user_admin.php
- interface/usergroup/usergroup_admin.php
- interface/usergroup/usergroup_admin_add.php
- library/js/utility.js
Fixes https://github.com/openemr/openemr/issues/7355
This PR adds validation on the front-end UI and the backend to ensure that input is validated and sanitized for the google signin email input field. Without the PR, invalid or potentially malicious data can be saved in the field, such as JavaScript or scripts. (ASVS 5.1.3 and CWE-20)
After update:
1. Use an industry standard Regular Expression (RegEx) from the Open Worldwide Application Security Project (OWASP) on the front-end https://owasp.org/www-community/OWASP_Validation_Regex_Repository
2. Use the built in PHP function filter_var to validate the email on the backend https://www.php.net/manual/en/function.filter-var.php or https://www.w3schools.com/php/filter_validate_email.asp
> Fix: Input sanitation on google signin email

- controllers/C_Document.class.php
- interface/modules/custom_modules/oe-module-weno/scripts/weno_log_sync.php
- interface/modules/custom_modules/oe-module-weno/src/Services/LogProperties.php
- interface/modules/custom_modules/oe-module-weno/templates/synch.php
- library/htmlspecialchars.inc.php
- src/Events/PatientDocuments/PatientRetrieveOffsiteDocument.php
> Cherry pick sjp 702

- src/Common/Logging/EventAuditLogger.php
Turns out probably shouldn't mess with log information to ensure remain compatible with ONC certification.
> Fix: Revert "Fix: OpenEMR logs sensitive information such as payment details (#7341)"

- src/Common/Logging/EventAuditLogger.php
rel-702 fix
Revert "Fix: OpenEMR logs sensitive information such as payment details (#7341)" (#7396)
> Fix: Revert "Fix: OpenEMR logs sensitive information such as payment details (#7341)" (#7396)

- interface/billing/ub04_dispose.php
- interface/billing/ub04_form.php
- src/Billing/BillingProcessor/BillingClaimBatch.php
- src/Billing/BillingProcessor/BillingProcessor.php
- src/Billing/BillingProcessor/Tasks/GeneratorUB04Form_PDF.php
- src/Billing/BillingProcessor/Tasks/GeneratorUB04NoForm.php
- src/Billing/BillingProcessor/Tasks/GeneratorUB04X12.php
- src/Billing/X125010837I.php
Fixes #7413 
Many reverts and fixes to project.
Fixed from issues
- Fee Sheet doesn't save revenue codes
- Custom Codes doesn't save or select revenue codes.
- UB04 form doesn't render
- 837i X12 claim doesn't generate due to missing revenue code plus.
> Refactor UB04 837i X12 feature to make work again.

- interface/billing/ub04_dispose.php
- interface/billing/ub04_form.php
- src/Billing/BillingProcessor/BillingClaimBatch.php
- src/Billing/BillingProcessor/BillingProcessor.php
- src/Billing/BillingProcessor/Tasks/GeneratorUB04Form_PDF.php
- src/Billing/BillingProcessor/Tasks/GeneratorUB04NoForm.php
- src/Billing/BillingProcessor/Tasks/GeneratorUB04X12.php
- src/Billing/X125010837I.php
* Refactor UB04 837i feature to make work again.
* fix PHP 8.2 warnings
(cherry picked from commit 14e7854b0922ebe3512a672e25af844a6ebe6b37)
Fixes #
> Refactor UB04 837i X12 feature to make work again. (#7412)

- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CcdController.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
- library/classes/Document.class.php
- src/Services/Cda/CdaTemplateImportDispose.php
- src/Services/Cda/CdaTemplateParse.php
> fix: ccda zip import and php warnings and deprecations

- Documentation/help_files/medical_dashboard_help.php
- interface/patient_file/summary/demographics.php
- interface/super/edit_globals.php
- library/globals.inc.php
- src/Services/Globals/GlobalSetting.php
Fixes #7192 
Hide unutilized dashboard cards
> Hide dashboard card 2

- interface/modules/custom_modules/oe-module-faxsms/messageUI.php
- interface/modules/custom_modules/oe-module-weno/templates/pharmacy_list_form.php
- interface/patient_file/summary/demographics.php
- interface/super/edit_globals.php
- src/Common/Crypto/CryptoGen.php
- Add Prescriptions and Insurance to hide dashboard items
- Fix recent exception in Crypto styling to error log.
Fixes #
Change to previous commits.
> Various changes and fixes

- ccr/createCCR.php
- ccr/createCCRActor.php
- ccr/createCCRAlerts.php
- ccr/createCCRImmunization.php
- ccr/createCCRMedication.php
- ccr/createCCRProblem.php
- ccr/createCCRResult.php
- ccr/display.php
- ccr/transmitCCD.php
- interface/usergroup/facilities_add.php
- interface/usergroup/facility_admin.php
> fix: add missing use statement in facility admin script

- interface/patient_file/summary/demographics.php
- library/specialty_forms.php
- Added an alert disabling the capability in create patient.
Fixes #7437
Because the Previous Name plug in will save name when added and not on form save, the new name gets saved to current patient opened pid because a new pid doesn't get generated until saved.
There are a couple hacky ways to get around this limitation, I chose to turn it off.
forum issue.
> Previous names in New/Search doesn't save.

- interface/main/tabs/menu/menus/standard.json
- sites/default/documents/custom_menus/Custom.json
> fix: batch payments distinct tab

- config/config.yaml
- interface/modules/custom_modules/oe-module-faxsms/library/utility.php
- interface/modules/custom_modules/oe-module-faxsms/messageUI.php
- interface/modules/custom_modules/oe-module-faxsms/src/Controller/EtherFaxActions.php
- package-lock.json
- package.json
Fixes #
- revert jspdf to prior version 2.5.1
- use jspdf UMD version in fax viewers. I misconfigure in my first tries at UMD for this library.
> Some change to prior PR#7429

- config/config.yaml
- interface/modules/custom_modules/oe-module-faxsms/contact.php
- interface/modules/custom_modules/oe-module-faxsms/library/utility.php
- interface/modules/custom_modules/oe-module-faxsms/messageUI.php
- interface/modules/custom_modules/oe-module-faxsms/src/Controller/EtherFaxActions.php
- interface/modules/custom_modules/oe-module-faxsms/src/EtherFax/EtherFaxClient.php
- interface/modules/custom_modules/oe-module-faxsms/version.php
- package.json
- src/Services/ImageUtilities/HandleImageService.php
> Backport etherfax #7429 #7447

- interface/reports/front_receipts_report.php
> total front receipts by payment method

- interface/patient_file/report/custom_report.php
Fixes #7432
Checks the date to see if it is 0 or empty. 
Wraps the date display in an if statement
> Phantom date showing at the top of all reports.

- interface/super/manage_document_templates.php
Fixes #7406
1. As we can see in the test case, we are fixing CWE 409 in the OpenEMR platform which is “Improper Handling of Highly Compressed Data(Data Amplification)”. This is ASVS 12.1.2 in the ASVS document which says that “Verify that compressed files are checked for "zip bombs" - small input files that will decompress into huge files thus exhausting file storage limits.”
2. However, when we try to upload a zip bomb on the OpenEMR platform, it allows it under the Admin->Documents->Document Templates section.
3. The fix was to add code which checks zip bombs on the platform for this particular section of the portal mentioned in the previous point. As you can see in the code diff above, there has been additional code written for .zip extensions and the code performs 2 checks.
4. The …
> Prevent Upload of ZIP bombs

- interface/patient_file/history/encounters.php
Fixes # #7399
@bradymiller 's comment on PR #7359 
escape two strings on line 317 of interface/paitne_file/history/encounters.php
> escape strings - brady's comment on PR #7359

- interface/new/new_comprehensive.php
Fixes https://github.com/openemr/openemr/issues/7378
It would not allow the user to enter a future date of birth in the insurance field which is a basic validation check.
Changes proposed in this pull request:
Just the addition of a word -past that disables any future dates for the user. So that user can only select dates previous to the current date
> Fix: to not allow user to pick future date for DOB

- interface/patient_file/summary/immunizations.php
Added the delete class to the button which is used by the java script function to select the delete button.
Fixes #7345
It fixes the issue with the delete button in the immunization list of a patient. 
Adding delete to the class attribute of the button element solves this issue because this triggers the javascript onclick function responsible for deleting the immunization entry.
> Fix: delete entry in immunization

- interface/forms/note/new.php
- interface/forms/note/print.php
- interface/forms/note/report.php
- interface/forms/note/save.php
- interface/forms/note/view.php
- interface/modules/custom_modules/oe-module-weno/README.md
- interface/modules/custom_modules/oe-module-weno/src/Services/LogImportBuild.php
- interface/modules/custom_modules/oe-module-weno/src/Services/LogProperties.php
- interface/modules/custom_modules/oe-module-weno/src/Services/TransmitProperties.php
- interface/modules/custom_modules/oe-module-weno/src/WenoGlobalConfig.php
- interface/modules/custom_modules/oe-module-weno/templates/setup_facilities.php
- interface/modules/custom_modules/oe-module-weno/templates/weno_fragment.php
- interface/modules/custom_modules/oe-module-weno/templates/weno_setup.php
- interface/modules/custom_modules/oe-module-weno/templates/weno_users.php
- interface/new/new_comprehensive.php
- interface/patient_file/history/encounters.php
- interface/patient_file/report/custom_report.php
- interface/patient_file/summary/immunizations.php
- interface/reports/amc_full_report.php
- interface/reports/amc_tracking.php
- interface/reports/audit_log_tamper_report.php
- interface/reports/cdr_log.php
- interface/reports/clinical_reports.php
- interface/reports/cqm.php
- interface/reports/inventory_list.php
- interface/reports/report_results.php
- interface/super/manage_document_templates.php
- library/forms.inc.php
- library/js/xl/jquery-datetimepicker-2-5-4.js.php
Fixes #
7443
7407
7359 7400
7379
7453
7386
7346
> Patch1 more cherry-picks

- src/Services/DocumentTemplates/DocumentTemplateRender.php
> fix: use temp files dir for htmlpurify serializer path

- library/js/xl/jquery-datetimepicker-2-5-4-translated.js
This fixes #7497 when the DateFormatRead is not defined and the date time picker uses its own internal function the format fails when using the % to do date formatting.
> Fixes #7497 datetimepicker invalid date format

- interface/modules/custom_modules/oe-module-faxsms/src/Controller/EtherFaxActions.php
Fixes #7505
normalize file path from document controller for fax send
> Mangled path fax send

- controllers/C_Document.class.php
Made it so the <br /> tag does not show up in the message statuses when updating document properties.
Fixes #7511
> Fixes #7511 documents stray html tags

- interface/usergroup/usergroup_admin.php
Fixes #7503 by allowing the multiple users to have an empty google sign in email address. If the address is empty it sets the value to null which doesn't trigger the unique constraint.
> Fixes #7503 user admin create empty google sign in

- composer.json
- library/sanitize.inc.php
- src/Validators/CoverageValidator.php
- tests/Tests/Unit/library/SanitizeMultiByteCaseInsensitiveStringEqualsTest.php
This puts in multibyte case insensitive validation on the subscriber previous name fields.  Due to unicode character sets having multiple uppercase characters that correspond to a single lowercase and viceversa with many lowercase to a single uppercase, name identifiers are normalized into unicode NFKC form before comparison.
Fixes #7477
> ins subscriber name validation fixes see #7477

- interface/billing/billing_report.php
> fix: set default X12 partner if only 1 effective insurance

- interface/main/tabs/main.php
Fixes #7493
if configuration > appearance > Search Patient By Any Demographics is set to 'none', my understanding is the search bar should not appear on the main page. It was being displayed.
the configuration item is now checked and if set to 'none' the search field is not displayed
> hide 'search by any demographics ' field if config for this set to 'none'

- interface/patient_file/summary/add_edit_issue.php
Fixes #7563
Type name not displayed next to radio button when choosing which issue type to add from an encounter form
adds Type name to radio button when choosing which issue type to add from an encounter form
> show issue type in 'add issue' form from encounter form

- templates/portal/header.html.twig
- templates/portal/home.html.twig
- templates/portal/partial/_alert_loading.html.twig
- templates/portal/partial/_help_card.html.twig
- templates/portal/partial/_nav_icon.html.twig
- templates/portal/partial/_nav_icon_secure_messaging.html.twig
This fixes #7609.  This work has been sponsored by Open Plan IT and heavily builds upon what @sjpadgett has done with the portal single page app layout.
The issues referenced in the commit comments are for internal issues in the Open Plan IT project. 
Screenshots for the new design:
Desktop version:
Main home screen:
Medical Reports Screen
Settings Screen
Dashboard Help Screen
Medical Reports Help Screen
Surface Pro:
Ipad AIR
iPhone XR
Samsung Galaxy S8
> Feat openemr fix #7609 dashboard cards size consistency

- library/js/utility.js
- portal/home.php
- portal/patient/libs/Controller/OnsiteDocumentController.php
- portal/patient/templates/OnsiteDocumentListView.tpl.php
- src/Services/Utils/TranslationService.php
The translation system was not setup in the OnSiteDocumentController and a bug in utility.js would blow up preventing the questionnaire from saving.  I added more safety checks to the xl translation function. Injected the language translations into the OnSiteDocumentController and abstracted the language definition retrievals into a service utility class.
Fixes #7621
> Fixes #7621 validation save errors w/ translations

- portal/add_edit_event_user.php
- portal/find_appt_popup_user.php
- portal/home.php
- templates/portal/base.html.twig
- templates/portal/home.html.twig
Fixes #7608 appointment localized dates.
This fixes the appointment localized date issue showing in the new
appointment screen. I add the localization js library to the
add_edit_event_user.php script and also handle the localization when it
comes back in the find_appt_popup script.
Also changed default behavior to retain today's date in the date field
if you switch providers in the appointment popup dialog.
Work sponsored by Open Plan IT.
> Fixes #7608 appointment localized dates

- interface/forms/questionnaire_assessments/questionnaire_assessments.php
- library/globals.inc.php
Fixes #7550
adds a configuration/appearance item to specify where the LOINC copywrite statement should be displayed when editing a questionnaire - at the top, at the bottom, neither, both 
option 'Display LOINC note on questionnaires' - in configuration/appearance. Possible values top, bottom, both, don't display - added to globals.inc.php
Modify questionnaire_assessments.php to take account of the configured option when displaying the note
> Questionnaire - configure where LOINC notice should go

- interface/main/tabs/js/user_data_view_model.js
Fixes #7596
if 'search on any demographics' is configured as 'fixed' nothing happens if the search box is empty, 
in this PR if configured as fixed, and search box is empty, it behaves like 'dual' and goes to the patient finder, listing all the patients
> search on demographics configured to 'fixed' uses finder if search box is empty

- interface/forms/LBF/new.php
Fixes #7579
Prevent collisions for newly added services and existing diagnoses, which caused the newly added services to disappear when saving.
Start the line number of existing diagnoses at 1,000, bringing them in line with the code for new diagnoses.
Also separate the line counter from the loop, so that existing services don't increment it and cause gaps in the numbering of existing diagnoses, which could potentially cause collisions with newly added diagnoses.
> Fix #7579: Disappearing services in LBF

- portal/patient/scripts/app/patientdata.js
Made it so the submit changes button always shows but it is disabled until data has changed.
Made it so the data change watch on the submit changes button is based on the input event instead of the change event.  This makes it so we can capture input changes on mobile devices and enable the save button without having the mobile user have to tap somewhere else to enable the button.
Fixes #7656
> Fixes #7656 submit changes button fixes for patient portal demographics profile edit

- portal/add_edit_event_user.php
This fixes #7654 changes the verbiage Openings to be "See Availability" to make it more clear to both US and EU audiences of what this button does.
> Fixes #7654 see appointments availability

- templates/portal/home.html.twig
- templates/portal/partial/_nav_icon.html.twig
Made it so the patient portal will update the page title tag whenever the single page app navigates to a new 'page'. I do this whenever the page is persisted.
If the user comes back to the dashboard page it reverts to the default page title set in the home.php file.
Fixes #7646
> Fixes #7646 portal update page title tag

- gacl/docs/manual.html
This fixes issue [#7590 ](https://github.com/openemr/openemr/issues/7590)
This issue resolves the wrongful use of a break element/tag in line 248 of the file (gacl/docs/manual.html).
Content separation should be done using CSS as it has better semantics, accessibility and responsiveness. 
--
To fix this issue, I removed the break tag on Line 248. I created a new CSS selector called "image-space" and then applied that class to the paragraph tag (now line 250) about the image to achieve the same effect.
> Fixes #7590 wrongful use of break tag

- src/Common/Twig/TwigExtension.php
- src/Patient/Cards/PortalCard.php
- templates/patient/partials/portal.html.twig
Fixes #7670
patient portal card on dashboard mentions 'demographics choices' even if the group has been renamed to something other than choices 
PostalCard.php now looks for the group's name (group 4) in the db and uses the new name - or reverts to 'Choices' if the group name is not returned
> display correct name when 'choices' group name is changed

- portal/messaging/messages.php
Fixed the async loading issues with the secure message details loading after the messsages are displayed allowing the user to click on them.  I put a loading screen in and only display the messages after all the data has loaded (or failed to load).
Fixed the issue where clicking on the checkbox of the secure message would load up the details instead of checking the box.
Fixes #7662
Fixes #7663
> Fixes #7662 #7663 secure messaging bugs

- src/Services/InsuranceService.php
Fixes #7684 
This PR simply adds to the query when searching for coverage to actually pull the associated `insurance_companies` entity, if present.
> Add payor information for FHIR Coverage Endpoint

- portal/account/index_reset.php
- templates/portal/home.html.twig
- templates/portal/portal-credentials-settings.html.twig
Fixes #7650.
Twigified the update credentials page.  Improved the UX and made the username/password updates be independent of each other.
Page now looks like this:
Also added some help instructions as well.
> Feat Fixes #7650 portal credential settings update

- config/config.yaml
- src/Core/Header.php
Made it so the config.yaml file can now have an object syntax to specify
additional attributes to add to the script tag such as the type syntax
that will be output in the HTML.
Fixes https://github.com/openemr/openemr/issues/7698
Added the questionnaire and questionnaire-lforms configuration option
that can be used in the setupHeader syntax to be able to embed
questionnaires into the form.
Fixes https://github.com/openemr/openemr/issues/7699
This work allows the questionnaire to be embedded in the setupHeader twig function
```
{% block header %}
{{ setupHeader(['questionnaires']) }}
{% endblock %}
```
Then the questionnaire can be rendered in the twig fairly easily:
```
{% block contents %}
<div id="formContainer"></div>
<div class="container-fluid">
<div class="row">
<div class="col-12"> …
```
> Feat openemr fix #7699 #7698 setup header

- src/Billing/X125010837P.php
- src/Validators/CoverageValidator.php
- src/Validators/PatientValidator.php
- tests/Tests/Services/PatientServiceTest.php
- tests/Tests/Validators/PatientValidatorTest.php
* feat: allow 1 char first names for insurance subscriber
* change Tests Validators to use empty fname
* update patient service test to use empty fname
Fixes #
> feat: allow 1 char first names for insurance subscriber (#7715) for rel-702

- composer.json
- library/sanitize.inc.php
- src/Validators/CoverageValidator.php
- tests/Tests/Unit/library/SanitizeMultiByteCaseInsensitiveStringEqualsTest.php
* ins subscriber name validation fixes see #7477
This puts in multibyte case insensitive validation on the subscriber previous name fields.  It does not fully fix the issue for all unicode names as apparently some unicode character sets can have multiple uppercase characters that correspond to a single lowercase and viceversa with many lowercase to a single uppercase.  Some research shows we need to normalize the characters and then do a comparison but need to do more research to see if this is an actual valid assumption or not before implementing.
This will almost fix #7477 for nearly all issues, but the edge cases still need to be addressed.
* Implement multi-byte normalization
Did a bunch of research on the unicode normalization process to make sure we were using the correct …
> ins subscriber name validation fixes see #7477 (#7478) for rel-702

- interface/patient_file/report/patient_report.php
- interface/super/edit_globals.php
- portal/home.php
- portal/report/portal_patient_report.php
- src/Controllers/Portal/PortalPatientReportController.php
- src/Events/PatientReport/PatientReportFilterEvent.php
- templates/portal/home.html.twig
- templates/portal/partial/cards/_health_snapshot_allergylist_card.html.twig
- templates/portal/partial/cards/_health_snapshot_card.html.twig
- templates/portal/partial/cards/_health_snapshot_immunization_card.html.twig
- templates/portal/partial/cards/_health_snapshot_labresults_card.html.twig
- templates/portal/partial/cards/_health_snapshot_medicationlist_card.html.twig
- templates/portal/partial/cards/_health_snapshot_prescriptionlist_card.html.twig
- templates/portal/partial/cards/_health_snapshot_problemslist_card.html.twig
- templates/portal/partial/cards/_health_snapshot_scripts.html.twig
- templates/portal/partial/cards/_health_snapshot_scripts_post.html.twig
- templates/portal/partial/reports/patient_report/_body_scripts.html.twig
- templates/portal/partial/reports/patient_report/_documents.html.twig
- templates/portal/partial/reports/patient_report/_head.html.twig
- templates/portal/partial/reports/patient_report/_issues_encounters.html.twig
- templates/portal/partial/reports/patient_report/_issues_encounters_form.html.twig
- templates/portal/partial/reports/patient_report/_procedure_orders.html.twig
- templates/portal/partial/reports/patient_report/_section_list.html.twig
- templates/portal/partial/reports/patient_report/_section_list_item.html.twig
- templates/portal/portal_patient_report.html.twig
Made it so the custom report foudn in patient_report.php uses twig and also has a filter event for customizing the data that gets passed into the report selection system.  This allows module writers to extend the interface and add data or hide sections as needed.
Did the same thing with the health snapshot to allow pieces of the snapshot to be overridden by twig templates.
This work was done to facilitate a module that wanted to have flags to hide/show different parts of the reports and health snapshot as they pilot test these areas with their patients.
Fixes #7707
Fixes #7708
> Fixes #7707, #7708 health snapshot, custom report

- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
- interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
The day, month, and week appointments are showing html entities for things like apostrophes, quotes, ampersands, etc because the data is being double escaped.  We need to make sure we only do a single version escape on the calendar.
The calendar uses the pcVarPrepHTMLDisplay function to escape this and other fields which then get double escaped when passed through OpenEMR's attr function.  We fix this issue by the removing the attr and relying on the pcVarPrepHTMLDisplay.  This makes it so if anyone is using the PostCalendar/pnuserapi.php to grab events it will still work properly.
Fixes #7635
> Fixes #7635 appointment comments double escaped

- docker/library/dockers/dev-php-fpm-8-1-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-8-1/Dockerfile
- docker/library/dockers/dev-php-fpm-8-2-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-8-2/Dockerfile
- docker/library/dockers/dev-php-fpm-8-4-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-8-4/Dockerfile
support nginx based testing ci dockers for testing nodejs stuff
> fix: support nginx based testing ci dockers for testing nodejs stuff

- src/Billing/Claim.php
- src/Billing/X125010837P.php
- src/Services/FormService.php
Fixes #7759 
also fixes an empty array and warning
> fix: x12837 billing 5 or 9 digit zip check

- src/Billing/BillingReport.php
> fix: allow viewing of fee sheet items if billing.billed is null

- src/Controllers/Portal/PortalPatientReportController.php
- templates/portal/partial/reports/patient_report/_procedure_orders.html.twig
Made it so we handle the procedures list if there are no procedures present.
Fixes #7814.  Refactoring of the patient report page exposed a bug where if no procedures are present it blows up the portal.
> Fixes #7814 empty procedures error.

- interface/modules/custom_modules/oe-module-faxsms/messageUI.php
- interface/modules/custom_modules/oe-module-faxsms/openemr.bootstrap.php
- interface/modules/custom_modules/oe-module-faxsms/src/Controller/EmailClient.php
Fixes #7845
Support viewing sent email notifications in the FaxSMS module.
Add a menu item, and adjust messageUI.php to support viewing email details.
> Show an email tab for viewing past notifications.

- ccdaservice/package-lock.json
- interface/patient_file/summary/immunizations.php
This PR addresses Issue #7844 
Updates the "Help" link on the immunization entry form to the current US CDC page: https://www.cdc.gov/vaccines/hcp/vis/current-vis.html
Additional clarifications and changes may be needed to ensure this link is appropriately localized per original issue author's request. 
Does your code include anything generated by an AI Engine? No
> updated US CDC website link to current immunization VIS page

- interface/drugs/add_edit_lot.php
Fixes #7304
Fix type casting error in add_edit_lot.php file.
Add type casting for $drug_id and $lot_id on line 131 and 132 and removed the "+ 0"
> Fix type error in add_edit_lot file

- .github/workflows/build-dev-php-fpm-docker.yml
- .github/workflows/manual-build-php-fpm-dockers.yml
- .github/workflows/test.yml
- .github/workflows/weekly-build-php-fpm-dockers.yml
- ci/apache_83_116/docker-compose.yml
- ci/nginx_85/docker-compose.yml
- ci/nginx_85/php.ini
- docker/development-insane/README.md
- docker/development-insane/docker-compose.yml
- docker/library/dockers/dev-nginx/nginx.conf
- docker/library/dockers/dev-php-fpm-8-4-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-8-5-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-8-5-redis/php.ini
- docker/library/dockers/dev-php-fpm-8-5/Dockerfile
- docker/library/dockers/dev-php-fpm-8-5/php.ini
- docker/library/dockers/dev-php-fpm/Dockerfile
- docker/library/dockers/dev-php-fpm/README
- docker/library/dockers/dev-php-fpm/data/docker-php-entrypoint
- docker/library/dockers/dev-php-fpm/data/docker-php-ext-configure
- docker/library/dockers/dev-php-fpm/data/docker-php-ext-enable
- docker/library/dockers/dev-php-fpm/data/docker-php-ext-install
- docker/library/dockers/dev-php-fpm/data/docker-php-source
- docker/library/dockers/dev-php-fpm/data/php.ini
Added:
- Mechanism to build php-fpm docker nightly from php development codebase.
- Will now auto build the php fpm dockers weekly on sundays.
- PHP 8.5-dev support in ci and insane dev environment
- Added MariaDB rolling 11.6 to ci
TODO:
- add 8.5 testing issue when in codebase
> ci support for php 8.5

- CONTRIBUTING.md
update easy dev docs to ensure have most recent dockers for alternate php versions
> chore: update easy dev docs to ensure have most recent dockers for alternate php versions

- templates/encounter/forms/navbar.html.twig
Fixes #7897
the forms drop down menus in an encounter summary appear behind a clinical notes report. this ensures the menu would always be on the top of other items
the drop down menu's z-index is set to '9999'
no
> Encounter form menu - keep on top of any reports

- sql/7_0_2-to-7_0_3_upgrade.sql
- sql/database.sql
Fixes #7862 
Replaces non-recommended abbreviations in dosage form, route of administration, frequency when entering a prescription.
Changes the file database.sql to remove non-recommended abbreviations and replace with written-out form.
> Replaces non-recommended prescription abbreviations

- src/Billing/X125010837P.php
> fix: edi segment count for ordering provider

- src/FHIR/SMART/ClientAdminController.php
fixes issues #7914 which prevents edit form from loading when contacts is empty
,'value' => is_array($client->getContacts()) ? implode("|", $client->getContacts()) : ''
> #7914 - Fix for contacts being empty or string

- contrib/portal_templates/assessments/SDC FHIR/After_Visit_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/Back_Pain_History_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/Back_Pain_Impact_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/Back_Pain_Severity_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/Follow_Up_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/Full_Assessments.json
- contrib/portal_templates/assessments/SDC FHIR/Impact_of_Back_Pain_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/Medical_History_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/PROMIS_Anxiety_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/PROMIS_Depression_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/PROMIS_Interference_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/PROMIS_Physical_Activity_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/PROMIS_Physical_Function_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/PROMIS_Sleep_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/Pain_Initial_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/Safety_Outcomes_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/Shared_Decision_Making_Assessment.json
- contrib/portal_templates/assessments/SDC FHIR/Social_Factors_Assessment.json
Numerous Questionnaires for pain management.
The three questionnaire set  After_Visit_Assessment.json, Follow_Up_Assessment.json and Pain_Initial_Assessment allows complete pain evaluation. To use import from Portal Dashboard to templates and Questionnaire Resource.
Fixes #7971
All forms need re validation since last SDC release. I've already have done the Pain Initial Assessment.
> SDC FHIR Pain Management Questionnaires

- interface/main/calendar/add_edit_event.php
Fixes #7967 
This pull request extends the recurring appointment options in the calendar to include 7th, 8th, and 9th occurrences.  Previously, recurrence was limited to up to the 6th occurrence.
Added new options "7th every," "8th every," and "9th every" to the "Repeats" frequency drop down.
Key changes:
Extended $repeatOptions: The $repeatOptions array now includes entries for "7th every," "8th every," and "9th every."
Modified form_repeat_freq select: The form_repeat_freq select element is updated to include the new options from $repeatOptions.
Adjusted dateChanged() and Recurrence Logic: The server-side recurrence handling (especially around $my_recurrtype = 2) now considers these new recurrence frequencies. The dateChanged() function will need a bit more sophisticated logic to handle …
> Update add_edit_event.php to allow repeat every 7th, 8th, 9th 

- contrib/util/ccda_import/import_ccda.php
ccda import script mods
1. updated header documentation
2. Added back exit command and put back the command line check (generally put exit command in any scripts not frequently used that bypass globals auth)
3. Note also needed to update/rebuild all the downstream dockers with new argument structure (ie. fun fun :) ): https://github.com/openemr/openemr-devops/pull/407
> ccda import script mods

- interface/patient_file/encounter/forms.php
- interface/patient_file/encounter/load_form.php
- interface/patient_file/encounter/view_form.php
- interface/patient_file/history/encounters.php
- interface/patient_file/history/encounters_ajax.php
- interface/patient_file/report/custom_report.php
- portal/report/portal_custom_report.php
- src/Common/Forms/FormLocator.php
- src/Common/Forms/FormReportRenderer.php
- src/Core/ModulesApplication.php
- src/Events/Encounter/LoadEncounterFormFilterEvent.php
This implements the loading of a form from a module using events.  This allows the module writer to customize the directory of an existing form or to implement their own forms.
It assumes that forms will be added to the registry via the module's table.sql.  It does NOT modify the forms administration piece.  That is still a work in progress.
I implemented also a FormLocator class for finding the paths for a form and caching the file.  Caching is based upon the formdir, page request (visit.php, report,php, new.php), and the current report page.
The report renderer got added everywhere that the LBF / standard forms are rendered.
Also added a safety mechanism to the ModulesApplication to make sure a module can only include files that are inside the module.
Added a new event …
> Fixes #7907 load forms from a module

- interface/patient_file/encounter/forms.php
- interface/patient_file/encounter/load_form.php
- interface/patient_file/encounter/view_form.php
- interface/patient_file/history/encounters.php
- interface/patient_file/history/encounters_ajax.php
- interface/patient_file/report/custom_report.php
- portal/report/portal_custom_report.php
- src/Common/Forms/FormLocator.php
- src/Common/Forms/FormReportRenderer.php
- src/Core/ModulesApplication.php
- src/Events/Encounter/LoadEncounterFormFilterEvent.php
* Fixes #7905 load forms from a module
This implements the loading of a form from a module using events.  This allows the module writer to customize the directory of an existing form or to implement their own forms.
It assumes that forms will be added to the registry via the module's table.sql.  It does NOT modify the forms administration piece.  That is still a work in progress.
I implemented also a FormLocator class for finding the paths for a form and caching the file.  Caching is based upon the formdir, page request (visit.php, report,php, new.php), and the current report page.
The report renderer got added everywhere that the LBF / standard forms are rendered.
Also added a safety mechanism to the ModulesApplication to make sure a module can only include files that are inside the …
> rel-703 Fixes #7907 load forms from a module (#7991)

- interface/reports/appointments_report.php
Fixes #8010
row 1 of the csv file, which contains column headings, now matches the headings used in the report itself
a new array is generated with the csv data and with row 1, the headers, matching the report (rather than db field names)
no
> appointments report csv file header row does not match report headers

- interface/forms/vitals/templates/vitals/vitals.html.twig
- interface/forms/vitals/vitals.js
- src/Services/Traits/ServiceEventTrait.php
- src/Services/VitalsService.php
refactor saveVitalsArray to create new form_vitals first to get new id then create the forms record. Removes the reliance on sequence value. fix doc block entry for event trait.
Fixes #8051 
Fixes #7857 
On new vitals form save and for the sake of pure logic create the form_vital form first to get the record id from table to use in the new encounter forms record.
refactor saveVitalsArray to create new form_vitals first to get new id then create the forms record. Removes the reliance on sequence value. fix doc block entry for event trait.
> Refactor Vitals form save

- library/dicom_frame.php
twig template missing web_root var init
Fixes #8065 
image loading
> Fix Dicom Viewer 404 image load

- custom/code_types.inc.php
- interface/code_systems/list_staged.php
- interface/patient_file/encounter/find_code_dynamic.php
- interface/patient_file/encounter/find_code_dynamic_ajax.php
- interface/patient_file/encounter/select_codes.php
- library/standard_tables_capture.inc.php
- sql/7_0_2-to-7_0_3_upgrade.sql
- version.php
> rel-703 pr #7976 #7276 snomed fixes

- src/Common/Auth/OAuth2KeyConfig.php
- src/Common/Auth/OAuth2KeyMissing.php
Update Oauth2KeyConfig for more logging and removing duplicated code
Prelim testing ok. Still more testing to do.
Here is what the log shows with some of the testing (so can track what is happening to the oauth2 stuff; ideally should only be created once and then set, but if need to autocreate-them for some reason then can follow what is going on in the log to problem solve the issue (since recreating oauth2 stuff will break all api tokens, will be good to know can problem solve from log when this is happening)).
> feat: update Oauth2KeyConfig for more logging and removing duplicated code

- library/js/utility.js
- src/FHIR/SMART/ClientAdminController.php
This fixes #8103 on windows and other browsers that don't like a forward slash in a query parameter. Was missing the encoding of the action.
Fixes #8103
> Fix dsi window launch w/ unescaped action #8103

- src/FHIR/SMART/ClientAdminController.php
- templates/interface/smart/admin-client/edit.html.twig
The token parsing was not being received due to a use of the query param when the request is a POST instead of a GET.
The trustedUsers array was skipped over with the twig refactor as part of the b11 dsi work.
Fixes #8111
Fixes #8110
> Fix token parsing&trusted user display #8111,#8110

- library/js/utility.js
- src/FHIR/SMART/ClientAdminController.php
* Fix dsi window launch w/ unescaped action #8103
This fixes #8103 on windows and other browsers that don't like a forward slash in a query parameter. Was missing the encoding of the action.
Fixes #8103
* Remove leftover button from old cdr implementation
Originally had the external CDR built so you could go to a list of CDR services and see them.  However, I consolidated them into the clients list pieces and we no longer need to go the CDR external list page as that got removed.  The old button was still showing up under the tools so removing that option.
> rel-703 Fix dsi window launch w/ unescaped action #8103 (#8114)

- src/FHIR/SMART/ClientAdminController.php
- templates/interface/smart/admin-client/edit.html.twig
The token parsing was not being received due to a use of the query param when its parameter is posted.
The trustedUsers array was skipped over with the twig refactor as part of the b11 dsi work.
Fixes #8111
Fixes #8110
> rel-703 Fix token parsing&trusted user display #8111,#8110 (#8113)

- library/user.inc.php
Looks like the home dashboard page was not collapsing properly due to a bug in the refactor of cac171e where the wrong function was being called.
Fixes #8105
> rel-703 Fixes #8105 collapsing home dashboard (#8107)

- src/RestControllers/RestControllerHelper.php
- src/Services/FHIR/FhirServiceBase.php
- src/Services/FHIR/Traits/ResourceServiceSearchTrait.php
- src/Services/Search/SearchQueryConfig.php
- src/Validators/ProcessingResult.php
Removed _REWRITE_COMMAND from pagination links as its extraneous information that's not needed.
Fixed bug where FHIR resources were not properly handling the search config parameters.
Fixed a bug where pagination was not actually limiting the results to the specified _limit parameter.  Also added support for FHIR TU _maxresults parameter in addition to supporting experimental clients that use _limit.  Fixes #8128.
Fixed bug where sort fields were always set to be descending (ie search field date treated as search field -date).  Fixes #8127.
Many of these bugs were introduced in the original paging/sorting PR in  #6801
> Fixes api sorting, pagination problems #8127,#8128

- src/RestControllers/RestControllerHelper.php
- src/Services/FHIR/FhirServiceBase.php
- src/Services/FHIR/Traits/ResourceServiceSearchTrait.php
- src/Services/Search/SearchQueryConfig.php
- src/Validators/ProcessingResult.php
Removed _REWRITE_COMMAND from pagination links as its extraneous information that's not needed.
Fixed bug where FHIR resources were not properly handling the search config parameters.
Fixed a bug where pagination was not actually limiting the results to the specified _limit parameter.  Also added support for FHIR TU _maxresults parameter in addition to supporting experimental clients that use _limit.  Fixes #8128.
Fixed bug where sort fields were always set to be descending (ie search field date treated as search field -date).  Fixes #8127.
Many of these bugs were introduced in the original paging/sorting PR in  #6801
> rel-703 Fixes api sorting, pagination problems #8127,#8128 (#8129)

- interface/modules/custom_modules/oe-module-faxsms/library/api_onetime.php
- interface/modules/custom_modules/oe-module-faxsms/src/Events/NotificationEventListener.php
- portal/home.php
- portal/index.php
- sql/7_0_2-to-7_0_3_upgrade.sql
- sql/database.sql
- src/Common/Auth/OneTimeAuth.php
- src/Events/Messaging/SendNotificationEvent.php
- templates/portal/header.html.twig
- templates/portal/home.html.twig
- templates/portal/login/autologin.html.twig
- version.php
* Feature add persist token portal login and Whereto redirect add new session var to track URL landOn query to redirect.
* refactor onetime tokens and wrapper to add an actions array to onetime_auth add new universal onetime event and listener onNotifyUniversalOneTime(SendNotificationEvent $event).
* streamline event and onetime listener handling. add scope and profile for onetime contexts
* implement pin collection for onetime login enforce visit page only. removes Dashboard button so can't goto that page.
* cleanup and set defaults
* update 7.0.2 to 7.0.3 sql.
* More cleanup
* escape
(cherry picked from commit 30af554f207296cfe9429f99bf4a6d0bff048986)
Fixes #
> Feature add persist token portal login and Whereto redirect (#8088)

- interface/forms/eye_mag/php/eye_mag_functions.php
fixes: #8140 
This PR refine the Imp/Plan Builder to search for whole words/phrases in a clinical field.  For example, prior code allowed positive hits for "hole" when the clinical field included "whole" and "wholey" etc.  This Limits it to "hole" by addition a regex to add \b$term\b to the logic.  It also limits searches to fields with activity=1.
> feat: Update eye_mag_functions.php to refine Imp/Plan Builder search

- interface/forms/eye_mag/js/eye_base.php
fixes #8151 
When the Eye Form loads it will display the Form as the authID/current user prefers (based on the last time they used the form) - which panels are open by default, which are closed, minus or plus cylinder, Draw/quick picks panel open, whole sections of exam hidden, etc.  Some people will never use the Neuro section, so it is hidden. Others want the Retina Draw panel to display by default, others will want the Glaucoma Fee Sheet to display on opening the form.  Each time a panel is changed, that UI choice is stored as the current preference and subsequent Eye Forms will open/display the same way for that user.  This change fixes a bug where the RETINA section was not honoring preferences, because it was mis-labelled as POSTSEG.  Now all is well.
> POSTSEG vs RETINA

- src/Services/FHIR/Observation/FhirObservationVitalsService.php
This fixes #8136 by populating the value quantity for the inhaled oxygen flow rate.  Shouldn't impact inferno but punting to patch 1.
> Fixes #8136 value for fhir inhaled oxygen flow rate

- interface/billing/billing_tracker.php
- interface/main/tabs/main.php
- library/js/xl/formatting.js
- portal/home.php
- templates/core/base.html.twig
- templates/patient/insurance/insurance_edit.html.twig
- templates/portal/home.html.twig
Fixes #8173.
Formatting library was missing the time_display_format in the jsGlobals so time formatting was messed up.
Also had a wierd bug where sub-frames that loaded the i18formatting library would end up stomping on the global values of i18formatting but when the script was unloaded the browser appears to go and remove the references to those values so the functions would end up undefined.
I ended up defining the formatting library in the main entry points (main.php and in the portal/home.php) so the functions always exist.  I then removed the library loads from any of the sub-frames to avoid the behavior.  billing_tracker.php, insurance_edit, and the encounter stuff appears to be the only things impacted.
@stephenwaite I don't have any data setup for the x12 auto sftp claim tracking …
> Fixes #8173 date format encounter bug

- library/ESign/Signature.php
Fixes #8205 show the e-sign amendment.
The constructor order for the signature is off due to the addition of the suffix/valedictory tags which throws off the values of everything else.
> Show e-sign amendment. Fixes #8205

- interface/billing/edit_payment.php
- library/payment.inc.php
https://github.com/openemr/openemr/issues/8156
Fixes #8156
It seems that the issue had already been fixed in most places. Applied the same changes to places that might have been missed. 
Made sure that the issue is consistently fixed by changing 'isset' to '!empty' for 'Payment' and 'AdjAmount'
No
> fixing pre-payment bug completely

- interface/main/calendar/includes/pnAPI.php
- interface/main/calendar/modules/PostCalendar/pnuser.php
https://github.com/openemr/openemr/issues/8239
Fixes # 8239
Calendar search Keywords field not working
The Keywords field currently gets cleaned in the **pnVarCleanFromInput** function and since the Keywords field is just a string, it does not get processed properly and returns null. 
I added a new function, **pnStringCleanFromInput**, which properly cleans string inputs. 
No
> fixing keyword processing issue in calendar search

- interface/main/about_page.php
Fixes https://github.com/openemr/openemr/issues/8204
Fixes issue where the global setting "Display the Review link on the About page" controls the visibility of the "Donate" link and the global setting "Display the Donations link on the About page" controls the visibility of the "Write a Review" link.
Simple typo correction
No
> Correct mismatched Review and Donate globals on About page

- interface/forms/newpatient/C_EncounterVisitForm.class.php
- library/globals.inc.php
Brought back in the default facility in order to respect the Set Service Facility care team setting.
Fixed the care team setting so it uses the first care team setting in the patient demographics.  Before it would break if there were multiple care team settings.
Relabeled the Set Service Facility care team setting label so it is more clear of what is happening.
Fixes #8262
> Fixes #8262 default facility to respect care team

- src/Services/DocumentService.php
Fixes #8304
Return the filename as it is stored in the database in the documents api.
Don't use the file path basename but get the name field from the documents table.
I also added the hash field to the api, this makes preventing duplicate uploads a lot easier.
> alter document api response body to include file name and hash

- tests/Tests/Api/ApiTestClient.php
API testing is a little tricky because you have to determine whether to debug the client (tests) or the server. In my current case, it is useful to be able to distinguish getting an HTTP status code indicating failure from a successful one that still fails.
Provides a little more debugging context when registration fails during api testing.
No
N/A
> check registration status before continuing tests

- _rest_routes.inc.php
- apis/dispatch.php
- interface/main/about_page.php
- interface/main/tabs/js/tabs_view_model.js
- interface/main/tabs/main.php
- interface/product_registration/product_registration_controller.js
- interface/product_registration/product_registration_controller.php
- library/ajax/track_events.php
- library/telemetry_reporting_service.php
- portal/lib/track_portal_events.php
- src/Services/ProductRegistrationService.php
- src/Telemetry/TelemetryService.php
- version.php
fixes #8334
~~(prob gonna do a little more work to make it clear what getProductStatus() is for by renaming it to getProductStatusDialog() and then offshooting the call from the about page to a small new function for collecting the email adress)~~ DONE
> fix: registration modal fix to ensure complete decoupling

- interface/main/dated_reminders/dated_reminders_add.php
- interface/main/dated_reminders/dated_reminders_log.php
https://github.com/openemr/openemr/issues/8307
Fixes #8307 
The bad usability of the two forms in Reminders
1. Use consistent colored top cards, make each card the same width
2. Added Reset buttons
3. Added “No Messages Found” text in place of the existing table header
4. Separated filters into sections:
* Dated Message Log form:
* Message Date Range
* Message Participants
* Message Status
* Send a Reminder form:
* Message Recipients
* Due Date & Priority
* Message Content
5. Added muted help text / made existing help text muted
No
> Improving reminder forms

- interface/patient_file/summary/demographics_full.php
https://github.com/openemr/openemr/issues/8315
Fixes #8315
The label and buttons will now stay at where they should be regardless of display size:
Changed container-xl to container-fluid so the label, buttons, and demographics form each take up the entire width of the viewport
No
> Fixing UI For Demographics Form On Big Screens

- src/Common/ORDataObject/ORDataObject.php
- Swap out `REPLACE INTO` (which issues DELETE+INSERT) for `INSERT … ON DUPLICATE KEY UPDATE` (in-place UPSERT)
- Introduce `$setClause` accumulator to build the column-value list once and replace manual `substr` trimming with `rtrim()`
Fixes [8333](https://github.com/openemr/openemr/issues/8333)
This patch fixes the unintended deletion/re-insertion cycle in all `ORDataObject` subclasses (e.g. InsuranceCompany) by replacing the `REPLACE INTO` logic with an in-place upsert (`INSERT … ON DUPLICATE KEY UPDATE`), thereby preserving the original `uuid` on every save.
- Swap out the existing `REPLACE INTO` statement for an `INSERT … ON DUPLICATE KEY UPDATE` in the `ORDataObject::save()` method.
- Introduce a `$setClause` string accumulator to build the `column = value` list once, rather than …
> Switch REPLACE INTO with INSERT … ON DUPLICATE KEY UPDATE

- setup.php
Fixes #8344
Ensures that the values checked in the config check in setup.php aren't just the ones that were set earlier in the same file.
Capture the original ini values before setting them.
> fix(setup.php): use unchanged values in config check

- src/Telemetry/TelemetryService.php
for rel-703,  do not send usage report if telemetry is turned off
> fix: do not send usage report if telemetry is turned off (#8371)

- sql/database.sql
s/decission/decision/
Fixes #8352
Note that this typo also exists in sql/7_0_2-to-7_0_3_upgrade.sql, but since that appears to be a migration, I left it alone.
> fix(sql/database.sql): typo

- package.json
Fixes #8383
Makes it a bit easier and faster to npm install, and prevents unintended consequences from upstream updating their repo.
- removes the reference to summernotes-plugins, which is obsolete.
> chore: remove summernote-plugins

- src/Events/Core/SQLUpgradeEvent.php
- src/Services/Utils/Interfaces/ISQLUpgradeService.php
- src/Services/Utils/SQLUpgradeService.php
Fixes #8380
Resolves a circular dependency between SQLUpgradeService and SQLUpgradeEvent.
Opens the door to dependency injection.
- Create `ISQLUpgradeService`, an interface 
- Reference the interface instead of the implementation in `SQLUpgradeEvent`
> refactor: decouple SQLUpgradeService and SQLUpgradeEvent

- .github/workflows/test.yml
- ci/apache_82_114/docker-compose.yml
- ci/apache_83_1011/docker-compose.yml
- ci/apache_83_105/docker-compose.yml
- ci/apache_83_106/docker-compose.yml
- ci/apache_83_114/docker-compose.yml
- ci/apache_83_116/docker-compose.yml
- ci/apache_83_57/docker-compose.yml
- ci/apache_83_80/docker-compose.yml
- ci/apache_83_84/docker-compose.yml
- ci/nginx_82/docker-compose.yml
- ci/nginx_83/docker-compose.yml
- ci/nginx_84/docker-compose.yml
- ci/nginx_85/docker-compose.yml
Fixes #8399
Add healthchecks to ci docker-compose so tests can know when mysql is ready to go, and don't have to sleep for 60 seconds.
- add healthchecks to the mysql service in the docker-compose files in ci/, when the image is mariadb.
- remove the sleep 60 in .github/workflows/tests.yml when the healthcheck will do the same thing.
> fix(ci docker-compose): healthchecks in lieu of sleep 60

- .github/workflows/test.yml
- ci/ciLibrary.source
- composer.json
- composer.lock
- tests/Tests/Api/FacilityApiTest.php
- tests/Tests/Api/PatientApiTest.php
- tests/Tests/Api/PractitionerApiTest.php
- tests/Tests/Common/Uuid/UuidRegistryTest.php
- tests/Tests/Fixtures/FixtureManagerTest.php
- tests/Tests/Services/FHIR/FhirAllergyIntoleranceServiceQueryTest.php
- tests/Tests/Services/FHIR/FhirOrganizationServiceCrudTest.php
Fixes #8403
Coverage reporting for tests (other than e2e and api).
When the environment variable `ENABLE_COVERAGE=true`, each testsuite (besides e2e and api) will produce a coverage report in the form of both terminal output and php-style coverage in `./coverage/coverage.${testsuite}.cov`.
At the end of that test configuration run, all the `./coverage/coverage.${testsuite}.cov` files are merged by phpcov into coverage.clover.xml, an htmlcov directory and again on standard output for a comprehensive view of the coverage.
Then those artifacts are stored for viewing in the test run's summary.
The htmlcov artifact can be downloaded, unpacked and viewed in a browser for a nice visualization of coverage.
The coverage.clover.xml is suitable for providing to a tool such as codecov.io for further …
> ci: coverage reporting

- ccdaservice/README.md
- ccdaservice/package-lock.json
- ccdaservice/package.json
support nodejs 24
Fixes #8418
Fix that `npm install` fails in ccdaservice when the node version is 24.
Update libxmljs2 to 0.37.0, which works with node 24.
> chore(ccdaservice): bump libxmljs2 to 0.37.0

- src/FHIR/SMART/ExternalClinicalDecisionSupport/DecisionSupportInterventionEntity.php
- src/FHIR/SMART/ExternalClinicalDecisionSupport/PredictiveDSIServiceEntity.php
- tests/Tests/Api/FacilityApiTest.php
- tests/Tests/Api/PatientApiTest.php
- tests/Tests/Api/PractitionerApiTest.php
- tests/Tests/Fixtures/BaseFixtureManager.php
> fix: php unit deprecations

- .github/dependabot.yml
Fixes #8438
Configure/activate Dependabot for Github Actions
Add a .github/dependabot.yml so that dependabot aids OpenEMR in keeping Github Actions up-to-date.
> ci(dependabot): enable for github actions

- contrib/forms/dap/FormDAP.class.php
- contrib/forms/evaluation/FormEvaluation.class.php
- contrib/forms/hand/FormHand.class.php
- contrib/forms/hp_tje_primary/FormHpTjePrimary.class.php
- contrib/forms/soap2/FormSOAP.class.php
- interface/forms/ros/FormROS.class.php
- interface/forms/soap/FormSOAP.class.php
- library/classes/Company.class.php
- library/classes/Document.class.php
- library/classes/InsuranceCompany.class.php
- library/classes/Note.class.php
- library/classes/Pharmacy.class.php
- library/classes/PhoneNumber.class.php
- library/classes/Prescription.class.php
- src/Common/Forms/FormVitals.php
- src/Common/ORDataObject/Address.php
Fixes #8449
phpstan found that $string wasn't always being initialized because we were appending to it on the first use. This change ensures that all implementations of toString are consistent.
Mainly, replace `$string .=` with `$string =` in toString implementations in cases where `$string` was not previously initialized.
> fix(toString): consistently initialize $string

- contrib/forms/evaluation/C_FormEvaluation.class.php
Fixes #8454
Fix a typo that references an object that doesn't exist because the object it means to reference is spelled differently.
s/BillingUtilites/BillingUtilities/ in contrib/forms/evaluation/C_FormEvaluation.class.php.
> fix(C_FormEvaluation): typo

- admin.php
Fixes #8464
Fixes the conflict between the two sqlQuery function definitions in the codebase.
- rename `sqlQuery` to `adminSqlQuery` in admin.php
> fix(admin.php): rename sqlQuery to avoid naming conflict

- docker/library/dockers/dev-php-fpm-8-5-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-8-5/Dockerfile
> fix: dev-php-fpm-8-5 docker build which is used by the ci for PHP 8.5 (php dev version) testing

- phpunit.xml
- tests/Tests/Api/FacilityApiTest.php
- tests/Tests/Fixtures/BaseFixtureManager.php
- tests/Tests/Fixtures/EncounterFixtureManager.php
- tests/Tests/Services/CarePlanServiceTest.php
- tests/Tests/Services/EncounterServiceTest.php
- tests/Tests/Services/FHIR/FhirAllergyIntoleranceServiceQueryTest.php
- tests/Tests/Services/FHIR/FhirOrganizationServiceCrudTest.php
- tests/Tests/Services/FHIR/FhirPatientServiceCrudTest.php
- tests/Tests/Services/FHIR/FhirPatientServiceMappingTest.php
- tests/Tests/Services/FHIR/FhirPatientServiceQueryTest.php
- tests/Tests/Services/FHIR/FhirPractitionerServiceCrudTest.php
- tests/Tests/Services/FacilityServiceTest.php
- tests/Tests/Services/PatientServiceTest.php
- tests/Tests/Services/PractitionerServiceTest.php
Fixes #8485 
PHPUnit 10 deprecated docblock comments and annotations in favor of attributes (php8 feature), prepares for migration to PHPUnit 12 maybe
use attributes instead of annotations
> chore: PHPUnit deprecations

- CONTRIBUTING.md
- DOCKER_README.md
- docker/development-insane/README.md
- docker/development-insane/docker-compose.yml
Fixes #8515
Use `docker compose` directly instead of `docker ... $(docker compose ps)` to run commands in compose services.
- doc: s/docker-compose/docker compose/ for command guidance
- doc(CONTRIBUTING): use docker compose syntax directly
> doc(CONTRIBUTING): use docker compose syntax directly

- interface/main/backuplog.sh
Fix all the shellcheck complaints in this file and some other cleanup.
1. Use a correct shebang.
2. Name the positional parameters.
3. Create a function to reduce duplication.
4. Quote the parameters.
5. Use long shell options for clarity.
6. Use curly-braces around parameter expansions.
> fix(backuplog.sh): fix all shellcheck complaints

- tests/Tests/E2e/HhMainMenuLinksTest.php
- tests/Tests/E2e/IiPatientContextMainMenuLinksTest.php
> fix: phpunit dataprovider defaults

- docker/development-easy-light/docker-compose.yml
The couchdb service is missing from this setup but openemr still depends on the volume being present for an rsync command.
Fixes #8593
Starting the development-easy-light setup using docker-compose currently causes an rsync error in the openemr container, preventing a successful startup.
This solution provides an (easy to understand) quick fix by just re-adding the volume to the container (as in the development-easy setup), although there is no couchdb service present in the easy-light setup.
Another solution, of course, would be to remove the rsync command that represents the broken dependency. But my guess is this would cause container images to diverge, so just adding the volume might be an easier and cleaner solution for the dev setup.
No
> Re-add couchdb volume to openemr service in development-easy-light setup

- .github/workflows/inferno-test.yml
Still part of #8632
Pin the runner for inferno tests the same as the other runners.
Change the alias for the runner in inferno tests from "latest" to 24.04
> ci(inferno): pin ubuntu runner to 24.04

- docker/library/dockers/dev-php-fpm-5-6-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-5-6/Dockerfile
- docker/library/dockers/dev-php-fpm-7-0-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-7-0/Dockerfile
- docker/library/dockers/dev-php-fpm-7-1-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-7-1/Dockerfile
- docker/library/dockers/dev-php-fpm-7-2-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-7-2/Dockerfile
- docker/library/dockers/dev-php-fpm-7-3-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-7-3/Dockerfile
- docker/library/dockers/dev-php-fpm-7-4-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-7-4/Dockerfile
- docker/library/dockers/dev-php-fpm-8-0-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-8-0/Dockerfile
- docker/library/dockers/dev-php-fpm-8-1-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-8-1/Dockerfile
- docker/library/dockers/dev-php-fpm-8-2-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-8-2/Dockerfile
- docker/library/dockers/dev-php-fpm-8-3-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-8-3/Dockerfile
- docker/library/dockers/dev-php-fpm-8-4-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-8-4/Dockerfile
- docker/library/dockers/dev-php-fpm-8-5-redis/Dockerfile
- docker/library/dockers/dev-php-fpm-8-5/Dockerfile
Fixes #8635
Prevent cache stale problems and follow Dockerfile best practices by ensuring that apt-get install is always preceded by apt-get update in the same RUN step.
Refactor Dockerfiles…
- apt-get install always follows apt-get update in the same RUN step
- alphabetize things to install
- break compound commands on lines
- COPY commands come as late as possible to avoid spurious cache invalidation
> fix(docker): apt-get install with update

- composer.json
- composer.lock
Fixes #8682
Requires #8683 
Some phpstan errors made me suspect that the missing phpunit extension might be responsible for a bunch of problems, but testing locally doesn't show me what I need to know, so trying it in CI...
> ci(phpstan): add phpstan-phpunit extension

- custom/qrda_functions.php
- interface/billing/ub04_dispose.php
- interface/eRx_xml.php
- interface/forms/CAMOS/content_parser.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Exception/TeleHealthProviderSuspendedException.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Exception/TelehealthProviderNotEnrolledException.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Exception/TelehealthProvisioningServiceRequestException.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Exception/TelehealthValidationException.php
- interface/modules/custom_modules/oe-module-faxsms/src/EtherFax/EtherFaxClient.php
- interface/modules/zend_modules/module/Application/src/Application/Model/ApplicationTable.php
- interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Factory/SetupControllerFactory.php
- interface/reports/pat_ledger.php
- library/classes/CouchDB.class.php
- library/spreadsheet.inc.php
- phpstan.github.neon
- phpstan.local.neon
- src/Common/Acl/AccessDeniedException.php
- src/Common/Auth/OpenIDConnect/JWT/JWKValidatorException.php
- src/Common/Csrf/CsrfInvalidException.php
- src/Common/Database/SqlQueryException.php
- src/Common/Http/Psr17Factory.php
- src/Cqm/Qdm/BaseTypes/AbstractType.php
- src/FHIR/Export/ExportException.php
- src/Services/FHIR/FhirProvenanceService.php
- src/Services/FHIR/FhirValueSetService.php
- src/Services/Search/SearchFieldException.php
- src/Telemetry/TelemetryService.php
Fixes #8688
Fixes all 44 PHP deprecation notices in the OpenEMR codebase related to implicit nullable parameters, deprecated variable syntax, and parameter order issues.
**1. Fixed Implicit Nullable Parameters (33+ instances)**
- Added explicit `?` nullable type declarations to function parameters with `= null` defaults
- Updated exception constructors across telehealth, fax/SMS, and core modules
- Fixed method signatures in FHIR services, HTTP factories, and other core classes
**2. Fixed Deprecated Variable Syntax (11 instances)**
- Changed `${var}` syntax to `{$var}` in string interpolation
- Updated files: `library/classes/CouchDB.class.php`, `library/spreadsheet.inc.php`, `src/Cqm/Qdm/BaseTypes/AbstractType.php`
**3. Fixed Parameter Order Issues (9 instances)**
- Added default values …
> fix(php): deprecated syntax

- composer.lock
- phpstan.github.neon
- phpstan.local.neon
Fixes #8695
Removes the error phpstan raises when updating to phpstan 2.1.20 due to an ignored error no longer being found.
- chore(deps-dev): bump phpstan/phpstan in the development group
- ci(phpstan): remove resolved ignored errors
> chore(deps-dev): bump phpstan/phpstan from 2.1.18 to 2.1.20 in the development group

- tests/Tests/Unit/Common/Crypto/CryptoGenTest.php
Fixes #8721
Adds comprehensive test coverage for the CryptoGen class to improve code quality and ensure cryptographic functionality works as expected.
- test(CryptoGen): coverage for CryptoGen
> test(CryptoGen): coverage for cryptogen

- src/Services/Qdm/QdmBuilder.php
Fixes #8728
Address `Variable $qdmModel on left side of ?? always exists and is not nullable.`
Remove the null coalescing operator.
> fix(QdmBuilder): phpstan complaint

- custom/code_types.inc.php
- library/sql.inc.php
Fixes #8753
`exit(1)` instead of `exit` in sql.inc.php so the OS can correctly interpret them as failure conditions.
> fix(sql.inc.php): exit(1) on query error

- .github/workflows/test.yml
By limiting the parallelism we might avoid the sporadic timeout that impacts the e2e tests. It won't hurt much to try it.
Set max-parallel for the test matrix.
> ci: max-parallel in tests

- src/Common/Crypto/CryptoGen.php
- src/Common/Crypto/KeyVersion.php
- tests/Tests/Unit/Common/Crypto/CryptoGenTest.php
Fixes #8782
Simplify CryptoGen by making its versions an enum, which will cause impossible values to fail at the type checker instead of requiring manual checking.
- refactor(CryptoGen): add KeyVersion enum
> refactor(cryptogen): Validate KeyVersion via Enum

- .github/workflows/test.yml
Fixes #8810 
The max-parallel setting is not doing any good, so let's remove it.
> ci(test): remove max-parallel setting

- phpstan.github.neon
- portal/patient/fwk/libs/verysimple/String/VerySimpleStringUtil.php
Fixes #8823
- Use `;` for the delimiter so we can use `/` in the expression.
> fix(VerySimpleStringUtil): regex delimiter

- interface/forms/newpatient/C_EncounterVisitForm.class.php
- phpstan.github.neon
Fixes #8825
Removes unused closure variables from `use`.
Removes unused closure variables from `use`.
> fix(C_EncounterVisitForm): remove unused closure variables

- interface/therapy_groups/therapy_groups_controllers/therapy_groups_controller.php
- library/classes/thumbnail/Thumbnail.class.php
- phpstan.github.neon
- src/Common/Logging/EventAuditLogger.php
- src/Cqm/Qdm/Traits/PatientExtension.php
- src/Services/BaseService.php
- src/Services/DocumentTemplates/DocumentTemplateService.php
- src/Services/PatientService.php
- src/Services/QuestionnaireResponseService.php
- src/Services/QuestionnaireService.php
- src/Services/Search/BasicSearchField.php
Fixes #8829
Fix cases where phpstan is misled by annotations saying a parameter is `null` or a function returns `false` when the type can be other things.
> fix: remove only-null annotations

- rector.php
> chore: rector ignore smarty dir for openemr-cmd

- .github/workflows/validate-codecov.yml
- codecov.yml
Fixes #8900
Make codecov wait to report until the slower tests have reported, so it doesn't fail a PR just because of one set of tests.
> ci(codecov): report after two builds

- codecov.yml
- src/Common/Crypto/CryptoGen.php
> fix: crypto encrypt fix to maintain behavior of encryption of empty string when empty string or null

- templates/portal/home.html.twig
Fix for - https://github.com/openemr/openemr/issues/8922
Describe the bug
The Patient Portal logout functionality is currently not working as expected. When a user attempts to log out, instead of being redirected to the login page, the system displays a "Requested URL not found" error.
Its reproduced in the live demo server also.
Steps to reproduce the behavior:
Login to Patient portal
Click on ' Logout' option
It will show 'Not Found
The requested URL was not found on this server.'
>  Updated Patient Portal logout URL point to portal/logout - for bug 8922

- src/RestControllers/AuthorizationController.php
- src/RestControllers/SMART/SMARTAuthorizationController.php
- src/RestControllers/Subscriber/SessionCleanupListener.php
- src/RestControllers/Subscriber/SiteSetupListener.php
- templates/oauth2/patient-select.html.twig
The OAuth2 Authorization Code grant flow was not working properly due to changes with the session handling / management.  Needed to fix the issue with the session being cleaned up on every request if it wasn't a local api request (launched within the GUI application in OpenEMR).
Also discovered that the launch/patient scope was not working with the patient selector due to the CSRF token not properly populating due to the session changes so fixed that issue also.
Fixes #8958
> Fixes #8958 oauth2 session

- portal/patient/fwk/libs/verysimple/Phreeze/QueryBuilder.php
Fixes #8980
Phreeze\QueryBuilder::RemoveWherePrefix wants to strip parentheses around the query, but doesn't correctly look for parentheses at the end of the query string.
> fix(Phreeze\QueryBuilder): actually strip parens

- controllers/C_InsuranceCompany.class.php
- controllers/C_InsuranceNumbers.class.php
- controllers/C_Pharmacy.class.php
- controllers/C_Prescription.class.php
Fixes #8998
Remove dead code and unused parameters.
Replace wrong-case class name comparisons with instanceof.
> fix(C_controllers): clean up dead code and wrong-case comparisons

- interface/billing/edi_271.php
- interface/billing/ub04_dispose.php
- interface/forms/newGroupEncounter/report.php
- interface/forms/newpatient/report.php
- interface/patient_file/report/custom_report.php
- interface/reports/custom_report_range.php
- portal/lib/download_template.php
- portal/report/portal_custom_report.php
- rector.php
Fixes #8988
Use `__DIR__` instead of dirname
> refactor(php): use __DIR__ instead of dirname

- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Repository/TeleHealthPersonSettingsRepository.php
- interface/modules/custom_modules/oe-module-comlink-telehealth/src/Repository/TeleHealthProviderRepository.php
- src/Common/Twig/TwigExtension.php
- src/Controllers/Interface/Forms/Observation/ObservationController.php
- src/Services/ObservationService.php
- src/Services/PatientService.php
- src/Services/Qdm/ResultsCalculator.php
- tests/Tests/Services/FHIR/FhirAllergyIntoleranceServiceQueryTest.php
- tests/Tests/Unit/Common/Crypto/CryptoGenTest.php
Fixes #9028
Reduces the overhead from a wrapper that only calls a function with an identical signature.
I used the rector rule
https://getrector.com/rule-detail/function-like-to-first-class-callable-rector
to apply this change, but on the advice of rector folks, am not putting
this in rector.php right now. It's safe enough if you manually review
each change, but we don't want it to apply to everything without careful
consideration.
> refactor(php): wrappers to first class callables

- library/classes/smtp/smtp.php
- phpstan.github.neon
- portal/patient/fwk/libs/verysimple/HTTP/FormValidator.php
- rector.php
Fixes #8992
Replace deprecated `ereg` functions.
> refactor(php): prefer preg_match to ereg

- .github/workflows/rector.yml
Makes the list of applied rector rules visible in the CI job. This gives us important debugging information when dealing with rector.
> ci(rector): list applied rules

- interface/modules/zend_modules/module/Installer/src/Installer/Model/InstModuleTable.php
- rector.php
- src/Cqm/CqmClient.php
Fixes #9011
Change multiple catch statements of the same exception to a single one <code>|</code> separated
> refactor(php): Use multi-catch syntax

- interface/billing/billing_report.php
- interface/billing/payment_pat_sel.inc.php
- interface/billing/sl_receipts_report.php
- interface/reports/collections_report.php
- interface/reports/daily_summary_report.php
- interface/reports/insurance_allocation_report.php
- phpstan.github.neon
Fixes #9037
Fix places where variables were initialized to null and then immediately used in a non-nullable context, such as addition. Also, tried to initialize counter variables outside the loop, avoiding the need to check them inside the loop.
> fix: Initialize numeric variables to 0 instead of null
