openemr/openemr

interface/forms/LBF/new.php, interface/super/edit_list.php, library/options.js.php
- selected search list was being overwritten to first list item
Fixes #5527 
Fixes #5390 
List to be search was not being handled and overwritten to default list when paginating.
=> Fix selected display items range in Lists

interface/themes/colors/utilities/default_variables.scss, interface/themes/default-variables.scss, interface/themes/oe-styles/style_light.scss, library/templates/address_list_display.php, library/templates/address_list_form.php
=> light styling fix and use of gray300 in address datatype

docker/production-arm/docker-compose.yml, docker/production/docker-compose.yml
update versions in the production docker compose scripts
=> update versions in the production docker compose scripts

.github/workflows/test.yml, CONTRIBUTING.md, ci/apache_81_103/docker-compose.yml, ci/apache_81_104/docker-compose.yml, ci/apache_81_105/docker-compose.yml, ci/apache_81_107/docker-compose.yml, ci/apache_81_108/docker-compose.yml, ci/apache_81_57/docker-compose.yml, ci/apache_81_8/docker-compose.yml
update easy dev, flex docker, ci for alpine 3.16 and php 8.1
=> update easy dev, flex docker, ci for alpine 3.16 and php 8.1

interface/forms/misc_billing_options/new.php, interface/forms/misc_billing_options/report.php, library/classes/rulesets/Amc/library/AmcItemizedActionData.php, src/Billing/BillingProcessor/BillingClaim.php, src/Billing/Claim.php, src/Common/ORDataObject/Address.php, src/Common/ORDataObject/ContactAddress.php, src/Cqm/Qdm/BaseTypes/AbstractType.php, src/Cqm/Qdm/BaseTypes/DateTime.php
=> fix #5632 and #5634, send voided claim electronically, suppress deprecated jsonSerialze, psr12 visibility warnings

interface/main/finder/dynamic_finder.php, interface/main/finder/dynamic_finder_ajax.php
Bug:  
AJAX Error when searching all fields when using search box at top right of main (not patient finder).  It was created when multiple address datatype was introduced to the demographic layout form.
I'm surprised no one caught this minor bug of a big core feature before 7.0 release.  This might warrant a quick patch to the release.
Really simple fix.
=> Dynamic Finder AJAX Fix

.github/SECURITY.md
=> security reporting updates

interface/forms/misc_billing_options/new.php, interface/forms/misc_billing_options/report.php, interface/main/finder/dynamic_finder_ajax.php, library/classes/rulesets/Amc/library/AmcItemizedActionData.php, src/Billing/BillingProcessor/BillingClaim.php, src/Billing/Claim.php, src/Common/ORDataObject/Address.php, src/Common/ORDataObject/ContactAddress.php, src/Cqm/Qdm/BaseTypes/AbstractType.php, src/Cqm/Qdm/BaseTypes/DateTime.php
=> dynamic finder fix and void elec claim

portal/get_pro.php, portal/home.php, templates/portal/home.html.twig
- add My Assessments to menu
- logic to collapse table view to show assessment only
- fix screen render
Fixes #5631
Fix assessment rendering and some restyle
=> Portal EASIPRO bug fixes

interface/main/messages/messages.php, interface/patient_file/summary/demographics.php
=> fixes #5647, setting msg status to done and show all messages

package.json, portal/import_template.php, portal/import_template_ui.php, portal/lib/download_template.php, portal/questionnaire_template.php, sql/7_0_0-to-7_0_1_upgrade.sql, sql/database.sql, src/Common/Uuid/UuidRegistry.php, src/Services/DocumentTemplates/DocumentTemplateService.php, src/Services/QuestionnaireService.php, version.php
- add lform-30.4.1 napa install
- core rendering template
- new class QuestionnaireService
- add questionnaire directive hooks for template rendering `{QuestionnaireURLLoinc|name|https://clinicaltables.nlm.nih.gov/loinc_form_definitions|loinc code} and {Questionnaire:name or id}`
Fixes #5638 
Database items to come.
Up For Grabs demo (which includes the standard demo data) for this PR is at: http://www.open-emr.org/wiki/index.php/Development_Demo#Epsilon_-_Up_For_Grabs_Demo
=> Portal FHIR Questionnaire implementation

portal/patient/scripts/app/onsitedocuments.js, portal/patient/templates/OnsiteDocumentListView.tpl.php
=> bug fix e6

interface/forms/vitals/templates/vitals/general_new.html
=> fix #5651, use assigned webroot variable from vitals class

interface/forms/vitals/templates/vitals/general_new.html
=> use assigned webroot variable from vitals class (#5652)

CONTRIBUTING.md, docker/development-insane/docker-compose.yml
insane dev docker update to default to alpine 3.16
=> insane dev docker update to default to alpine 3.16

portal/patient/fwk/libs/verysimple/Phreeze/Criteria.php, portal/patient/fwk/libs/verysimple/Phreeze/DataPage.php, portal/patient/fwk/libs/verysimple/Phreeze/DataSet.php, portal/patient/fwk/libs/verysimple/Phreeze/Phreezable.php, portal/patient/fwk/libs/verysimple/Phreeze/Reporter.php, portal/patient/libs/Controller/PortalPatientController.php, portal/patient/templates/OnsiteActivityViewListView.tpl.php, portal/patient/templates/ProviderHome.tpl.php, portal/report/portal_patient_report.php, portal/sign/lib/save-signature.php, portal/sign/lib/show-signature.php, src/Gacl/Gacl.php
=> bug fix and php8.1 fixes

portal/patient/fwk/libs/verysimple/Phreeze/Criteria.php, portal/patient/fwk/libs/verysimple/Phreeze/DataPage.php, portal/patient/fwk/libs/verysimple/Phreeze/DataSet.php, portal/patient/fwk/libs/verysimple/Phreeze/Phreezable.php, portal/patient/fwk/libs/verysimple/Phreeze/Reporter.php, portal/patient/libs/Controller/PortalPatientController.php, portal/patient/templates/OnsiteActivityViewListView.tpl.php, portal/patient/templates/ProviderHome.tpl.php, portal/report/portal_patient_report.php, portal/sign/lib/save-signature.php, portal/sign/lib/show-signature.php, src/Gacl/Gacl.php
* bug fix and php8.1 fixes
* styling
Fixes #
=> bug fix and php8.1 fixes (#5664)

interface/forms/gad7/gad7.inc.php, interface/forms/gad7/gad7_javasrc.js, interface/forms/gad7/new.php, interface/forms/gad7/report.php, interface/forms/gad7/view.php
* gad7.inc.php: improve close without saving button, move q8 strings into this file, require_once patient.inc
* improve layout a little, better close without saving button legend, improved style such as more strings in included files, default for q8 set as no answer, changes-made flag
Fixes #
=> Gad7 (#5660)

src/Billing/BillingProcessor/Tasks/GeneratorHCFA_PDF_IMG.php, src/Billing/Claim.php
=> fix for multiple hcfa pdfs on form

interface/patient_tracker/patient_tracker.php, src/Services/PatientTrackerService.php
Fixes #5675 
future proofing
php8.1 warnings
=> php8.1 fixes for patient tracker aka flow board

src/Billing/BillingProcessor/Tasks/GeneratorHCFA_PDF_IMG.php, src/Billing/Claim.php
=> rel-700 fix for multiple hcfa pdfs on form (#5680)

interface/usergroup/user_admin.php, interface/usergroup/usergroup_admin_add.php, src/Events/User/UserEditRenderEvent.php
Fixes #5683 adds events to user_admin and usergroup_admin_add page in
order to be able to render content on those pages from a module.
=> Fixes #5683 user admin events

interface/main/calendar/modules/PostCalendar/pnuserapi.php, src/Services/UserService.php
Add methods to the user service and have the calendar api use those methods to grab the calendar providers.
=> Fixes #5685 add provider calendar methods

interface/billing/edit_payment.php, library/payment.inc.php
=> php8 fixes for batch payments

interface/billing/edit_payment.php, interface/patient_tracker/patient_tracker.php, library/payment.inc.php, portal/add_edit_event_user.php, src/Services/PatientTrackerService.php
bring back  #5676, #5689, and #5674 to rel-700
=> bring back  #5676, #5689, and #5674 to rel-700

version.php
=> Update patch version to patch 2

version.php
=> Bump version for patch 2

src/Billing/Hcfa1500.php, src/Billing/X125010837P.php
=> Accept assign fix

interface/main/calendar/modules/PostCalendar/common.api.php, interface/main/calendar/modules/PostCalendar/pnadmin.php, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
=> fix php8.1 warnings, deprecation for calendar

.github/workflows/manual-build-php-fpm-dockers.yml, .github/workflows/test.yml, ci/apache_81_109/docker-compose.yml
=> some ci and workflow stuff

docker/library/dockers/dev-php-fpm-8-2-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-2/Dockerfile
=> fix php-fpm-82 docker

sql/7_0_0-to-7_0_1_upgrade.sql, sql/database.sql
=> Add By Mouth to prescription list options (Fixes #5714)

sql/7_0_0-to-7_0_1_upgrade.sql, version.php
minor adjustment to prior commit
=> minor adjustment to prior commit

interface/forms/vitals/templates/vitals/vitals.html.twig, templates/core/about.html.twig, templates/login/login_core.html.twig, templates/portal/home.html.twig
=> minor escaping fix

interface/forms/vitals/C_FormVitals.class.php, interface/modules/zend_modules/public/index.php, interface/orders/receive_hl7_results.inc.php, interface/patient_file/summary/demographics_save.php, interface/super/edit_layout.php, library/classes/Controller.class.php, library/options.inc.php, src/Common/Http/HttpRestRequest.php, src/PatientPortal/Chat/ChatController.php, src/Rx/RxList.php, src/Services/Cda/CdaValidateDocuments.php, src/Services/Qdm/Services/ImmunizationAdministeredService.php
fixes #5728
fixes for php 7.4 in rel-700
=> fixes for php 7.4 in rel-700

interface/forms/questionnaire_assessments/questionnaire_assessments.php, interface/forms/questionnaire_assessments/report.php, interface/forms/questionnaire_assessments/save.php, src/Services/QuestionnaireResponseService.php, src/Services/QuestionnaireService.php, src/Services/QuestionnaireTraits.php
- two versions of reports. Column and flex row reports. Column is default
- fix if missing lForm form data then it is created from the questionnaire json or visa versa.
- encounter can now create new form from just a FHIR questionnaire.
Fixes #5677 
See issue for example of reports
=> Questionnaire encounter report

interface/usergroup/facility_admin.php
=> fix #5780, add eRx condition to primary business entity checkbox disable

templates/insurance_numbers/general_edit.html
=> practice settings insurance numbers minor smarty fix

library/ajax/graphs.php
Fixes #5783
As described in the issue.
=> Fix for graphing of LBF data entered retroactively.

portal/account/register.php
fixes #5768 
@tywrenn , let me know if this fixes your issue. If so, then will bring this in and get it into the next 7.0.0 patch.
=> registration fix

portal/import_template_ui.php, sql/7_0_0-to-7_0_1_upgrade.sql
minor adjustments to questionnaire code
=> minor adjustments to questionnaire code

templates/patient/partials/portal.html.twig
=> check for allow portal in choices before displaying create creds

library/classes/X12Partner.class.php
=> Update X12Partner.class.php to pad spaces for 2 ISA fields

interface/patient_file/summary/demographics.php, templates/patient/card/photo.html.twig
Fixes #5802 
Fixes #5804 
twig template was missing render for the id card photo
=> Fix missing patient Id in demograhics widget

.stylelintrc.json
=> ignore temporary css file for patch

interface/forms/questionnaire_assessments/lform_webcomponents.php, interface/forms/questionnaire_assessments/questionnaire_assessments.php, interface/patient_file/history/encounters.php, library/dialog.js, library/js/ajtooltip.js, portal/import_template.php, portal/import_template_ui.php, portal/questionnaire_render.php, src/Services/DocumentTemplates/DocumentTemplateService.php
- cleanup portal categories
Fixes #5815
=> Questionnaire import utility

templates/login/login_core.html.twig
Fixes #5776
OpenEMR Google Sign-On with new libraries
Added Google new library changes
=> Google Sign-On with new libraries

ccdaservice/package-lock.json
quick fix for the easy dev environment
=> quick fix for the easy dev environment

composer.json, composer.lock, interface/main/calendar/modules/PostCalendar/plugins/function.pc_date_format.php, interface/main/calendar/modules/PostCalendar/plugins/modifier.pc_date_format.php, interface/main/calendar/modules/PostCalendar/pnincludes/Date/Calc.php, library/smarty_legacy/smarty/Smarty_Compiler_Legacy.class.php, library/smarty_legacy/smarty/internals/core.write_compiled_include.php, library/smarty_legacy/smarty/plugins/function.html_select_date.php, library/smarty_legacy/smarty/plugins/function.html_select_time.php, library/smarty_legacy/smarty/plugins/modifier.date_format.php, portal/patient/fwk/libs/savant/Savant3/resources/Savant3_Plugin_date.php
=> fix #5749, use function PHP81_BC\strftime; 

interface/billing/sl_eob_invoice.php
=> edit billing note in invoice, fix #5842

interface/billing/sl_eob_search.php, interface/forms/newpatient/common.php, interface/forms/newpatient/save.php, interface/reports/collections_report.php, sql/7_0_0-to-7_0_1_upgrade.sql, sql/database.sql
=> fix #5842, move in collection to encounter based

interface/forms/vitals/C_FormVitals.class.php, interface/forms/vitals/growthchart/chart.php, interface/forms/vitals/templates/vitals/vitals.html.twig, library/clinical_rules.php, src/Common/Twig/TwigExtension.php
=> fix #5849, handle all zeroes from old form_vitals date field; display date at top of table

interface/patient_file/summary/demographics.php, library/MedEx/API.php
- cast pid in demographics
- PHP 8 errors in MedEx API
Fixes #5861 
Fix various PHP 8 errors preventing view from rendering.
=> Reported issue fix Recall Board view details not displaying.

interface/forms/questionnaire_assessments/questionnaire_assessments.php
- add a dialog alert to show validation errors
Fixes #5867 
Add form validation
=> Missing form validation Questionnaires

interface/forms/track_anything/create.php, interface/forms/track_anything/history.php, interface/forms/track_anything/new.php, interface/patient_file/summary/track_anything_fragment.php
=> fixes for track anything

sql/database.sql, sql/patch.sql
add missing sql stuff from 758a42b3fe421b9854bd8907c05e57e06fa39727
=> fix prior commit

interface/reports/insurance_allocation_report.php
Fixes #5889
remove old CSS to have the columns and data to line up properly
=> Removing the outdated CSS to let bootstrap align the report.

interface/patient_file/summary/create_portallogin.php, src/Events/Patient/Summary/PortalCredentialsTemplateDataFilterEvent.php, src/Events/Patient/Summary/PortalCredentialsUpdatedEvent.php, templates/patient/portal_login/print.html.twig
Bring back the pr to fix #5875.
@stephenwaite I had a conflict on the create_portallogin.php.  Can you look this over and make sure I didn't stomp on anything you did?
=> Fixes #5875 portal module extensions (#5876)

portal/import_template.php
=> quick fix for recent commit: fix null coalesce in import_template.php

interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncountermanagerTable.php, src/Services/Cda/CdaTemplateImportDispose.php
@sjpadgett , also gotta remember to bring this into rel-700 after your ccda fixes go there
=> minor adjustments

interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php, src/Services/Cda/CdaValidateDocuments.php
Fixes #
Not too sure but looks like a prior commit change got by me.
=> CCDA Testing fixes and prior commit conflicts

interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php, src/Services/Cda/XmlExtended.php
=> fix XML new extended class for Linux

library/patient.inc.php, portal/patient/fwk/libs/verysimple/DB/DataDriver/MySQLi.php
=> fix #5907, policy types need to be global 

library/patient.inc
=> bring back global fix for policy types to rel-700

sql/database.sql
=> database fix for patch 2 prep

library/classes/InsuranceNumbers.class.php
=> fixes #5310, add ZZ to provider number arrays

interface/super/manage_document_templates.php, interface/super/manage_site_files.php
=> better display of mime names

interface/code_systems/dataloads_ajax.php, interface/super/manage_document_templates.php, interface/super/manage_site_files.php, library/classes/InsuranceNumbers.class.php, library/standard_tables_capture.inc
=> More patch2 prep

interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php, src/Services/Cda/CdaTemplateImportDispose.php, src/Services/Cda/CdaTemplateParse.php
- mostly procedure import
Fixes #
=> Back port of PR #5917

src/RestControllers/FHIR/FhirDocumentRestController.php
Fixes #5931 Make the patient uuid optional for provider/system requests.
=> Fix #5931 FHIR Binary Download

src/Services/FHIR/Traits/FhirBulkExportDomainResourceTrait.php
Makes it so we don't die w/ a 500 when there are no patients in a group to export.  It just returns on the request.
Fixes #5932
=> Fixes #5932 don't fail on empty group export

src/Services/SurgeryService.php
This fixes #5940 where the recorder_uuid was failing.
=> Fixes #5940 convert uuid for surgery recorder

interface/super/edit_globals.php, library/ajax/billing_tracker_ajax.php, src/Billing/BillingProcessor/Tasks/GeneratorX12.php, src/Billing/BillingProcessor/X12RemoteTracker.php, src/Billing/BillingReport.php, src/Billing/X125010837P.php
=> fix #5938, save sftp global correctly, php8 fixes, don't download 835

interface/patient_file/history/encounters.php
- backport from master
Fixes #
=> Change internal tooltip to BS4 popover

interface/orders/single_order_results.inc.php, interface/patient_file/history/encounters.php, src/Services/ClinicalNotesService.php
- encounter history popover changes
- php error single orders and table restyle
- Clinical Notes duplicating
Fixes #
From PR #5950 #5951
=> Backports to v7

interface/orders/single_order_results.inc.php
- fix php error
- restyle single orders report
Fixes #
=> Fix php typing errors

interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php, src/Services/BaseService.php, src/Services/Cda/CdaTemplateImportDispose.php
- ensure only unstructured is merged  to existing pid
=> Prevent duplicate merge CCDA

interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php, src/Services/BaseService.php, src/Services/Cda/CdaTemplateImportDispose.php
- qualify existing pid for unstructured only.
=> Don't allow auto merge openemr ccda import port PR #5957

interface/main/messages/save.php, library/MedEx/API.php
Remove a MedEx Preference.
Reset background_services on Preference change.
=> Medex9.28.22

ccdaservice/oe-blue-button-generate/lib/translate.js, ccdaservice/serveccda.js, interface/code_systems/list_staged.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncountermanagerController.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php, interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml, interface/modules/zend_modules/module/Ccr/view/ccr/ccr/index.phtml, src/Services/BaseService.php, src/Services/Cda/CdaTemplateImportDispose.php, src/Services/Cda/CdaTemplateParse.php, src/Services/PatientService.php
- default export search from current date to current - 3months
- fix search to date with adding time to get today encounters
- fix import emai
- change import patient match messages for clarity
- set encounter cda template code using encounter type code in encounter form.
- import/export all vitals history
- some more users and facility import work
Fixes #5962 
Fixes #5963
=> CCDA  Additions

ccdaservice/oe-blue-button-generate/lib/translate.js, ccdaservice/serveccda.js, interface/code_systems/list_staged.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncountermanagerController.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php, interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml, src/Services/BaseService.php, src/Services/Cda/CdaTemplateImportDispose.php, src/Services/Cda/CdaTemplateParse.php, src/Services/PatientService.php
- default export search from current date to current - 3months
- fix search to date with adding time to get today encounters
- fix import emai
- change import patient match messages for clarity
- set encounter cda template code using encounter type code in encounter form.
- import/export all vitals history
- some more users and facility import work
- create new calendar category if encounter imported category doesn't exist
Bring back from master
=> Back port PR #5964 CCDA updates v7

interface/forms/care_plan/report.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php, interface/patient_file/deleter.php, src/Services/Cda/CdaTemplateImportDispose.php
- ensure if unstructured and CDA then combine/merge
- fix deleter to auto close after 2 sec or immediate for encounters.
Fixes https://github.com/openemr/openemr/issues/5977
Fixes https://github.com/openemr/openemr/issues/5976
=> port PR #5978 CCDA import merge duplicate fix

interface/forms/care_plan/report.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php, interface/patient_file/deleter.php, src/Services/Cda/CdaTemplateImportDispose.php
- ensure if unstructured and CDA then combine/merge
- fix deleter to auto close after 2 sec or immediate for encounters.
Fixes #5977 
Fixes #5976 
Fixes #5980
=> CCDA import merge duplicate fix

sql/7_0_0-to-7_0_1_upgrade.sql, sql/database.sql
=> change procedure orderform to Orders category and menu item

interface/usergroup/addrbook_edit.php
Improvement for the address book form;
Previously "State" is written from a label
Now "State" can be selected from the lists that we have
=> state can now be selected/generated from the lists that we have

interface/patient_file/summary/demographics.php, src/Events/PatientDemographics/RenderEvent.php
Fixes #5986
allows the ability to inject java script into the demographics 
adding java event to demographics page
=> Render event java demographics

docker/library/dockers/dev-php-fpm-8-2-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-2/Dockerfile
=> php82 ci docker update

.github/workflows/test.yml, ci/apache_81_1010/docker-compose.yml
add yet another mariadb short term release to ci
=> add yet another mariadb short term release to ci

src/Billing/BillingUtilities.php
=> add new remit and claim advice remark codes

interface/modules/custom_modules/oe-module-comlink-telehealth/src/Models/UserVideoRegistrationRequest.php
Send the user role in the telehealth registration request.
Fixes #6009
=> Fix #6009 send telehealth user role

portal/import_template.php, portal/lib/doc_lib.php, portal/lib/download_template.php, portal/questionnaire_render.php
- added a HTMLPurifier config option for base64 data in img src
- reconfiged template editor to use `<br>` tag instead of auto `<p>` on enter. Works much better.
Fixes #6017 
allow images in pdf
=> Signature in portal pdf fix and Template import changes

interface/billing/sl_eob_invoice.php, interface/reports/receipts_by_method_report.php
=> fixes #5996, clarifies method of payment in Pmt method financial report

.github/workflows/manual-build-php-fpm-dockers.yml, .github/workflows/test.yml, ci/nginx_83/docker-compose.yml, ci/nginx_83/php.ini, docker/library/dockers/dev-php-fpm-8-3-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-3-redis/php.ini, docker/library/dockers/dev-php-fpm-8-3/Dockerfile, docker/library/dockers/dev-php-fpm-8-3/php.ini
=> add php8.3-dev to ci

interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml, interface/modules/zend_modules/module/Documents/src/Documents/Controller/DocumentsController.php, interface/modules/zend_modules/public/css/drag_and_drop_uploader.css, src/Services/Cda/CdaTemplateImportDispose.php, src/Services/Cda/CdaTemplateParse.php
improved appt event category create
Fixes #6038
=> fix ccda import dupl category

admin.php
Improvements to admin page.
Add a link to the patient portal for easy access.
(This PR may be ignored, I am following Brady's video tutorial)
=> add patient portal link to admin page

docker/development-insane/README.md, docker/development-insane/docker-compose.yml, docker/library/dockers/dev-nginx/nginx.conf
added php 8.3-dev to insane docker dev environment
=> added php 8.3-dev to insane docker dev environment

interface/reports/appointments_report.php, library/appointments.inc.php, library/htmlspecialchars.inc.php, src/Services/SpreadSheetService.php
=> add csv export to appt report

interface/main/dated_reminders/dated_reminders.php, interface/main/messages/messages.php, library/dated_reminder_functions.php
This moves the UI of the MRR page closer to bootstrap standards, including replacing lots of javascript with Bootstrap's Tab functionality. The PR is ready, though the UI could still be improved even further. The refactoring was more than I anticipated so I want to go ahead and move forward now and make the next rounds of improvements separately. No before and after this time, but a screencapture of the new UI
=> UI improvements to Message, Reminder, Recall Board

interface/drugs/add_edit_drug.php, interface/drugs/add_edit_lot.php, interface/drugs/destroy_lot.php, interface/drugs/drug_inventory.php, interface/forms/fee_sheet/new.php, interface/forms_admin/forms_admin.php, templates/login/login_core.html.twig
Removing excess font-weight-bold, slowly.
=> 4739 excessive use of font weight bold throughout the UI

portal/lib/doc_lib.php, portal/lib/download_template.php, portal/patient/libs/Controller/OnsiteDocumentController.php, portal/patient/scripts/app/onsitedocuments.js, portal/patient/templates/OnsiteDocumentListView.tpl.php
- type cast pids to same type, int.
Fixes #6063
=> Portal document delete exception and New Print button

src/Services/FacilityService.php
=> string cast facility id in getByID FacilityService

templates/pharmacies/general_list.html
=> practice settings datatable warning fix for pharmacies, fixes #6065

interface/patient_file/summary/demographics.php, interface/patient_file/summary/demographics_full.php, interface/patient_file/summary/demographics_save.php, library/patient.inc.php, sql/7_0_0-to-7_0_1_upgrade.sql, sql/database.sql, src/Billing/Claim.php, templates/patient/card/billing.html.twig, templates/patient/card/insurance.html.twig, version.php
=> add insurance effective date end

ccdaservice/README.md, ccdaservice/oe-blue-button-generate/package.json, ccdaservice/package-lock.json, ccdaservice/package.json, ccdaservice/serveccda.js, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceDocumentRequestor.php, src/Services/Cda/CdaValidateDocuments.php
Fixes #6093 
rebuild using node v18.12.1
I will prob test to later versions
=> Update CCDA srvice for Node version 18+

interface/new/new_comprehensive.php, interface/patient_file/summary/demographics_full.php, interface/practice/ins_list.php
=> fix #6085, ins search fixes

templates/insurance_companies/general_list.html
Fixes #6082
After the page loads allow the data to be searchable.
=> Adding Datatables to insurance page

interface/modules/custom_modules/oe-module-comlink-telehealth/Readme.md
=> Telehealth comlink update add price

interface/orders/find_order_popup.php
=> fix php8 math in find_order_popup

library/formatting.inc.php, library/formatting_DateToYYYYMMDD_js.js.php, library/js/xl/jquery-datetimepicker-2-5-4.js.php
=> handle pm times when locale set to 12 hrs

src/RestControllers/AllergyIntoleranceRestController.php, src/Services/AllergyIntoleranceService.php, src/Validators/AllergyIntoleranceValidator.php
Dear Community,  I am representing the project of a Digital health platform developed by Cardo Health AB ( [www.cardohealth.com](http://www.cardohealth.com/)),  through the support of my current employer ( NearForm ). We are pleased to contribute some fixes in OpenEMR on behalf of Cardo Health and look forward to continuing to do so in the future.
In this PR we are exposing `comments` fields for the allergies entity. It's editable in UI and we thought that we can also use it in the API. Thanks!
=> feat: allergy comments fields in REST API

ccdaservice/README.md, ccdaservice/oe-blue-button-generate/package.json, ccdaservice/package-lock.json, ccdaservice/package.json, ccdaservice/serveccda.js, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceDocumentRequestor.php, sql/database.sql, sql/patch.sql, src/Services/Cda/CdaValidateDocuments.php
Fixes #
missing date field for ccda author in CCM settings for auther
=> Fix a missed date in ccda module and others

sql/7_0_0-to-7_0_1_upgrade.sql
=> quick upgrade fix

interface/super/edit_layout.php
=> check if column is reserved and delete field from layout editor

library/classes/Installer.class.php
better use of getenv in prior commit to add hooks to support enforcement of ssl/x509 database connections
=> better use of getenv in prior commit to add hooks to support enforcement of ssl/x509 database connections

interface/main/backup.php, interface/patient_file/summary/demographics_full.php, interface/practice/ins_search.php, interface/super/edit_layout.php, library/classes/Installer.class.php, portal/lib/doc_lib.php, portal/messaging/messages.php, portal/patient/templates/OnsiteDocumentListView.tpl.php, src/Services/AddressService.php, src/Services/Cda/CdaTemplateImportDispose.php, src/Services/InsuranceCompanyService.php, src/Services/PhoneNumberService.php
Fixes #
Backports so I can do a hot patch.
=> Backport master PR's to v7

interface/main/backup.php, portal/messaging/messages.php
- make first admin default portal user if none defined in users
Fixes #6086
=> Secure messaging default portal user and windows backup lists

interface/forms/newpatient/common.php, library/globals.inc.php
=> feat: set service facility based on care team in demo choices

library/classes/Installer.class.php
fix: quick fix to enforce support of x509 database connection on install
=> fix: quick fix to enforce support of x509 database connection on install

interface/modules/custom_modules/oe-module-prior-authorizations/openemr.bootstrap.php, interface/modules/custom_modules/oe-module-prior-authorizations/public/deleter.php, interface/modules/custom_modules/oe-module-prior-authorizations/public/index.php, interface/modules/custom_modules/oe-module-prior-authorizations/table.sql, interface/modules/zend_modules/module/Installer/src/Installer/Model/InstModuleTable.php, library/ajax/graphs.php
=> fix: minor prior auth bugs and some php8 warns in graphs

interface/super/edit_layout.php
Pretty straight forward, just add `form-control-sm` to the LBF Edit page
=> Make input elements on LBF edit page smaller for an input-dense page

src/Services/PatientAccessOnsiteService.php
Fix the password generating.
Fixes #6178 
Return statements are important!
=> Fixes #6178 patient access credential fix password

interface/patient_file/summary/demographics.php
=> fix: fix effective date end fatal error from prior commit

Documentation/INSTALL
Fixes #
No ticket
Misspelled words
Misspelled words
=> Misspelled words

src/Common/Auth/AuthUtils.php
=> reset fail user fail counter on password update

interface/forms/questionnaire_assessments/questionnaire_assessments.php, templates/documents/general_list.html
Fixes #6205 
Fixed where selection is by the table id
=> Wrong form fetch pid for questionnaires from auditing

interface/modules/zend_modules/module/Installer/view/installer/installer/configure.phtml, interface/modules/zend_modules/module/Installer/view/installer/installer/index.phtml, interface/modules/zend_modules/module/Installer/view/layout/layout.phtml, interface/modules/zend_modules/public/css/emr.css, interface/modules/zend_modules/public/js/installer/action.js, interface/patient_file/report/custom_report.php
Fixes #6218 
Fixes #6219 
Above issues
=> fix: Custom report exception and installer UI improvements

interface/reports/external_data.php
Remove unnecessary javascript, use data-attributes to manage the toggling, overall better usage of Bootstrap.
Fixes #6210
=> fix: Use data-attributes and proper nav semantics in External Data

interface/forms/newpatient/common.php
=> fix: Ensure a Facility ID is always sent to a new encounter save event

interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
=> feat: Improved calendar facility UI

interface/forms/vitals/C_FormVitals.class.php, interface/forms/vitals/growthchart/chart.php, interface/forms/vitals/templates/vitals/vitals.html.twig, interface/forms/vitals/templates/vitals/vitals_growthchart_actions.html.twig
=> fix: fix growth chart issues

.github/workflows/test.yml
=> fix: Turn off PHP 8.2 Apache MariaDB 10.6 until upstream fix

interface/themes/patientportal-base.scss, interface/themes/patientportal-register.scss, portal/index.php
=> fix: Better UI of language selection on patient portal

interface/reports/pat_ledger.php
=> fix: use primary business entity if no facility in ledger form

interface/forms/newpatient/common.php
=> fix: set viewmode to true if incoming form id for encounter form editing

.github/workflows/test.yml
fix: More focused turn off PHP 8.2 Apache MariaDB 10.6 until upstream
=> fix: More focused turn off PHP 8.2 Apache MariaDB 10.6 until upstream

.github/workflows/test.yml, CONTRIBUTING.md, ci/apache_80_1011/docker-compose.yml, ci/apache_81_1011/docker-compose.yml, ci/apache_82_1011/docker-compose.yml, ci/nginx_80/docker-compose.yml, ci/nginx_81/docker-compose.yml, ci/nginx_82/docker-compose.yml, ci/nginx_83/docker-compose.yml, docker/development-easy-light/docker-compose.yml, docker/development-easy/docker-compose.yml, docker/development-insane/README.md, docker/development-insane/docker-compose.yml
feat: migrate ci and dev dockers to mariadb 10.11 long term release
=> feat: migrate ci and dev dockers to mariadb 10.11 long term release

portal/messaging/handle_note.php
=> fix: bug fix

interface/billing/sl_eob_process.php, sql/7_0_0-to-7_0_1_upgrade.sql, sql/database.sql, src/Billing/ParseERA.php, src/Billing/SLEOB.php, version.php
=> feat: add payer claim number to ar activity table

src/OeUI/OemrUI.php
=> fix: check if OemrUI element exists before accessing classList

templates/insurance_companies/general_list.html
Fixes #6282 
see comment in code
testing well
=> fix: appease datatables table header requirements smarty insurance cos template

library/ajax/execute_cdr_report.php, library/classes/rulesets/library/RsPopulation.php
=> fix: adjust RsPopulation class to be compatible with Iterator class

interface/forms/fee_sheet/new.php, interface/main/calendar/includes/pnAPI.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php, interface/orders/receive_hl7_results.inc.php, interface/orders/types_edit.php, interface/patient_file/printed_fee_sheet.php, interface/patient_file/summary/stats.php, interface/reports/pat_ledger.php, interface/super/rules/base/library/BaseController.php, interface/super/rules/controllers/edit/helper/common.php, interface/super/rules/include/common.php, interface/super/rules/library/ReminderIntervals.php, interface/super/rules/library/RuleCriteriaDatabaseBucket.php, interface/super/rules/library/RuleCriteriaTargetFactory.php, interface/super/rules/library/RuleManager.php, library/FeeSheet.class.php, library/ajax/execute_cdr_report.php, library/clinical_rules.php, library/options.inc.php, library/smarty_legacy/smarty/Smarty_Compiler_Legacy.class.php, library/smarty_legacy/smarty/Smarty_Legacy.class.php, library/sql.inc.php, library/templates/address_list_display.php, src/Common/Logging/EventAuditLogger.php, src/Gacl/Gacl.php, src/Services/ContactService.php
This is a quick walk through of all the scripts I was able to run through.
Note that the more complicated/timeconsuming places in the codebase were not completed and have been reported as separate issues.
=> fix: php 8.2 fixes

interface/orders/procedure_stats.php
=> fix: ignore additional addresses in procedure statistics report

interface/patient_file/summary/demographics.php, library/appointments.inc.php
Function to retrieve past recurring and non-recurring appts
=> Function to retrieve past recurring and non-recurring appts

interface/patient_file/summary/demographics.php, library/appointments.inc.php
=> fix: psr12 fixes

acl_upgrade.php, src/Common/Acl/AclMain.php
=> fix: update acl documentation

interface/forms/vitals/C_FormVitals.class.php, interface/forms/vitals/templates/vitals/vitals.html.twig, interface/forms/vitals/templates/vitals/vitals_textbox_conversion.html.twig
Had a bug where the localization of the vitals unit was throwing things off.  Broke out the label from the unit translation which fixes this for international users.
Fixes #6303 
Fixes #6292
=> Fixes #6292, #6303 localization bug vitals unit conv.

interface/patient_file/summary/demographics_full.php, interface/patient_file/summary/demographics_save.php
Fixes #6312 
improves previous swapping of primary and secondary by bringing tertiary into the mix
enables swapping 2nd and 3rd
=> feat: allow full swapping of insurances

interface/main/calendar/modules/PostCalendar/pnadmin.php, interface/main/calendar/modules/PostCalendar/pntemplates/default/admin/submit_category.html
=> fix: Smarty cal php82 warnings

interface/forms/LBF/new.php, interface/patient_file/deleter.php, portal/patient/fwk/libs/verysimple/Phreeze/Phreezable.php, portal/patient/fwk/libs/verysimple/Phreeze/Phreezer.php
=> fix: ignore history data form name via portal for delete, some deprecation fixes

interface/main/messages/messages.php, interface/main/messages/templates/linked_documents.php, interface/modules/custom_modules/oe-module-faxsms/README.md, interface/modules/custom_modules/oe-module-faxsms/contact.php, interface/modules/custom_modules/oe-module-faxsms/library/rc_sms_notification.php, interface/modules/custom_modules/oe-module-faxsms/library/utility.php, interface/modules/custom_modules/oe-module-faxsms/messageUI.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/AppDispatch.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/EtherFaxActions.php, interface/new/new_search_popup.php
restyle message areas
Fixes #6294
=> allow pnote attachment from fax

templates/core/about.html.twig
This code improvement shortens the 'Donate Now' button to only display the word 'Donate', which helps to improve the load time of the 'About' page. By removing unnecessary text, the button loads faster, providing a smoother user experience for visitors. This change has been made with the goal of improving the overall performance and usability of the OpenEMR platform.
=> reduced text on donate button

interface/modules/custom_modules/oe-module-faxsms/contact.php, interface/modules/custom_modules/oe-module-faxsms/messageUI.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/EtherFaxActions.php
- Validate inform that email smtp is configured.
Just some quick clean up
=> Some faxsms module changes.

interface/forms/fee_sheet/review/fee_sheet_classes.php, interface/forms/vitals/C_FormVitals.class.php, library/classes/Installer.class.php, setup.php, src/Billing/BillingProcessor/BillingClaimBatch.php, src/Billing/BillingProcessor/BillingLogger.php, src/Billing/Claim.php
=> fix: suppress php deprecation notices installer class and few other classes

interface/orders/find_order_popup.php, interface/orders/single_order_results.inc.php
=> fix: minor deprecation and warning in procedure order

sql/7_0_1-to-7_0_2_upgrade.sql, version.php
=> chore: prep master for 7.0.2-dev

library/appointments.inc.php
=> fix: backport portal scheduling fix (#6335) to rel-701

interface/modules/custom_modules/oe-module-faxsms/README.md
=> Install module faxsms README

interface/forms/eye_mag/js/eye_base.php, interface/main/finder/dynamic_finder.php, interface/main/finder/dynamic_finder_ajax.php, library/custom_template/share_template.php
=> fixes: couple more misc fixes

interface/modules/custom_modules/oe-module-comlink-telehealth/src/TelehealthGlobalConfig.php
Fixes #6342 add debug flag as optional setting
=> Fixes #6342 add debug flag as optional setting

src/RestControllers/AuthorizationController.php
=> Fix checkstyle bugs

library/appointments.inc.php
=> fix: portal scheduling fix take 2

interface/main/calendar/add_edit_event.php, library/appointments.inc.php
=> fix: portal scheduling fix take 3

interface/forms/newpatient/save.php, interface/main/finder/patient_select.php
=> fix: fixes #6350 enc_service_date

library/formatting.inc.php
Fixes #6306 
thanks for pointing out the case issue @growlingflea
=> fix: encounter datetime for 12 hr locale

interface/forms/vitals/C_FormVitals.class.php, interface/forms/vitals/growthchart/chart.php, interface/forms/vitals/templates/vitals/vitals_growthchart_actions.html.twig, interface/patient_file/encounter/trend_form.php, library/globals.inc.php
Fixes #6365 which was previously fixed but was missing these
=> fix: plot multiple points on growthchart

interface/forms/vitals/C_FormVitals.class.php, interface/forms/vitals/growthchart/chart.php, interface/forms/vitals/templates/vitals/vitals_growthchart_actions.html.twig, interface/patient_file/encounter/trend_form.php, library/globals.inc.php
* php8 math errors
* another
* cpl more
* fix: plot multiple datapoints on growth charts
* remove int casts
* use latest vitals for demographics dashboard, global for graphing data warning
Fixes #
=> fix: plot multiple points on growthchart (#6360) for rel-701

library/js/calendarDirectSelect.js
validate attribute
clean up syntax
Fixes #6367 
See issue for details
=> Calendar javascript error on scroll hover

interface/modules/custom_modules/oe-module-comlink-telehealth/src/Services/TeleHealthProvisioningService.php, interface/modules/custom_modules/oe-module-comlink-telehealth/src/Services/TelehealthConfigurationVerifier.php
Need to check for config changes with existing provisioned users. Fixes #6376
=> Fixes #6376 verify existing users check

composer.json, composer.lock
=> fix: update adodb package

interface/patient_file/deleter.php
=> fix: update formdir to HIS for delete patient with portal history form

portal/patient/libs/Controller/OnsiteDocumentController.php, portal/patient/scripts/app/onsitedocuments.js
* fix: bug fix
* use attr instead
Fixes #
=> fix: bug fix (#6354) for rel-701

interface/forms/fee_sheet/new.php, interface/patient_file/encounter/find_code_dynamic.php, interface/patient_file/encounter/find_code_dynamic_ajax.php, interface/super/edit_list.php
Fixes #6361 
modify code selectors to pass around the code modifier if available
forum issue https://community.open-emr.org/t/modifier-handling-in-fee-sheet-list/20289
=> Fix feesheet option list to include modifier if available.

interface/modules/custom_modules/oe-module-comlink-telehealth/src/Controller/TeleHealthVideoRegistrationController.php, interface/modules/custom_modules/oe-module-comlink-telehealth/src/Services/TeleHealthRemoteRegistrationService.php, interface/modules/custom_modules/oe-module-comlink-telehealth/src/Services/TelehealthConfigurationVerifier.php, interface/modules/custom_modules/oe-module-comlink-telehealth/src/TelehealthGlobalConfig.php, interface/modules/custom_modules/oe-module-comlink-telehealth/templates/comlink/admin/telehealth_footer_box.html.twig, src/Common/Auth/OneTimeAuth.php, src/Services/FHIR/FhirLocationService.php
Fixes #6389 in rel-701
Fixes #6384 in rel-701
Had to cherry-pick the individual commits because I did a merge into master on the PRs instead of squash and merge like I should have done.
=> Rel 701 backport 6389 6384

library/auth.inc.php, library/classes/Installer.class.php
=> fix: installer class properties public visibility

library/auth.inc.php, library/classes/Installer.class.php
* fix: installer class properties public visibility
* suppress php warnings for click login icon from admin.php page
Fixes #
=> fix: installer class properties public visibility, pr 6387 for rel 701

interface/patient_file/deleter.php
* fix: set deleted flag for forms when delete person
* sql escape
Fixes #
=>  fix: set deleted flag for forms when delete person (#6383) rel 701

version.php
=> chore: increment v_js_includes

interface/modules/custom_modules/oe-module-comlink-telehealth/moduleConfig.php
- Create an iframe to serve the welcome home page for signup.
- Accept and process a postMessage of credential data from signup application server.
- Auto save credentials to globals to save user from having to copy/pasted.
Fixes #6401
=> Telehealth signup credential auto save convience feature.

src/Core/ModulesApplication.php
=> Rel 701 backport 6396

interface/forms/vitals/C_FormVitals.class.php
narrow focus on #6399 and forgot to check for people with no prior vitals
=> fix: check vitals history are countable

portal/patient/scripts/app.js, portal/patient/scripts/app/onsitedocuments.js, portal/patient/scripts/app/patientdata.js, portal/patient/templates/OnsiteDocumentListView.tpl.php, src/Services/DocumentTemplates/DocumentTemplateService.php, templates/portal/header.html.twig
- style nav bar logo to be responsive
- change Top Nav menu toggle to indicate menu state in button.
- fix profile save alert to show in correct alert box.
- add Dismiss Form button to top and bottom of editor
- change edited document in select list to blue from red to indicated form is active.
- change My Documents to Document Actions to be clearer with instructions.
Fixes #6410 
Fixes #6411
=> Some portal fixes and changes

Documentation/Direct_Messaging_README.txt, Documentation/INSTALL, Documentation/README.phpgacl
Fixes #
I did not create an issue for something this minor but I can if it is required.
Fixed typos in the following files:
- Documentation/Direct_Messaging_README.txt
- Documentation/INSTALL
- Documentation/README.phpgacl
Fixed typos in documentation. No further action required.
=> Fixed typos in the help documentation

docker/production-arm/docker-compose.yml, docker/production/docker-compose.yml
=> chore: minor docker updates

interface/forms/vitals/growthchart/chart.php
=> fix: growth chart graphing for metric locale

interface/forms/eye_mag/js/eye_base.php, interface/forms/eye_mag/php/eye_mag_functions.php, interface/main/calendar/add_edit_event.php, library/ajax/addlistitem.php, library/patient.inc.php
=> fix: eye form bug and other php8 fatal errors and deprecations

interface/forms/newpatient/common.php
=> fix: use correct cancel create encounter function based on viewmode

src/Common/Database/QueryUtils.php, src/Services/UserService.php
Fixes #6446
Fixes #6447
Adds transaction methods to the QueryUtils class.
Adds a toggleSensitiveFields method to the UserService for returning data such as the username.
=> Fixes #6446, #6447, query helpers

library/formatting.inc.php
=> fix: Update formatting.inc.php to format 12 hr time for am

library/classes/X12Partner.class.php, sql/7_0_1-to-7_0_2_upgrade.sql, sql/database.sql, src/Billing/Claim.php, templates/x12_partners/general_edit.html, version.php
=> feat: add billing service submitter to x12 partner

sql/7_0_1-to-7_0_2_upgrade.sql, sql/database.sql
=> fix: sql syntax alter table x12_partners Update 7_0_1-to-7_0_2_upgrade.sql

interface/forms/newpatient/common.php, library/classes/Controller.class.php, library/formatting.inc.php
=> most recent commits for rel-701 patch 1

interface/billing/billing_report.php, interface/billing/get_claim_file.php, interface/billing/sl_eob_process.php, interface/billing/ub04_dispose.php, src/Billing/BillingProcessor/Tasks/GeneratorUB04X12.php, src/Billing/BillingProcessor/Tasks/GeneratorX12.php, src/Billing/BillingProcessor/Tasks/GeneratorX12Direct.php, src/Billing/Claim.php, src/Billing/Hcfa1500.php, src/Billing/X125010837I.php, src/Billing/X125010837P.php
=> fix: set x12 partner in Claim class, misc 837 institutional fixes

interface/globals.php, library/classes/postmaster.php, library/email_service_run.php, sql/7_0_1-to-7_0_2_upgrade.sql, sql/database.sql, src/Common/Auth/AuthUtils.php, version.php
email background service
Added for sending emails when blocking users/ip addresses. Can be also leveraged by all other places that send emails, if wish.
=> feat: email background service

interface/patient_file/summary/demographics.php, src/Billing/BillingProcessor/Tasks/GeneratorX12.php, src/Billing/BillingProcessor/Tasks/GeneratorX12Direct.php, src/Billing/Claim.php, src/Billing/X125010837P.php
=> fix: 837 professional HL count

src/Billing/Claim.php
=> fix: provider number sql error in Claim.php

src/Patient/Cards/PortalCard.php
=> fix: typo for demographics acl in patient portal card

library/ajax/addlistitem.php
=> fix: fix add to list feature

src/Patient/Cards/PortalCard.php
=> fix: typo for demographics acl in patient portal card (#6483)

src/Billing/X125010837P.php
=> fix: output service facility zip if not 9 digits

interface/patient_file/front_payment.php
=> fix: fix invoice payment total

src/Services/QuestionnaireResponseService.php
Add hooks to execute code whenever the questionnaire response is saved or updated.
Added a helper search method to make querrying the repository easier, and a method to grab a questionnaire by its id.
Fixes #6506
=> Fixes #6506 QuestionnaireResponse hooks,search

interface/main/main_screen.php, library/globals.inc.php
=> Remove frames related globals

interface/patient_file/front_payment.php, src/Billing/BillingProcessor/Tasks/GeneratorX12.php
=> invoice total and 837P fix for Rel 701

interface/usergroup/addrbook_list.php, library/options.inc.php, src/Billing/X125010837P.php
=> fix: username may be null for providers

interface/globals.php, interface/themes/oe-styles/style_solar.scss
- fix solar nav background style
- force theme to style_light if missing in globals
- add portal theme to globals
Fixes #
=> Missed globals prior PR.

interface/billing/billing_report.php, interface/patient_file/history/encounters.php, interface/patient_file/summary/demographics.php, library/patient.inc.php
=> fix: implements insurance date_end for billing

interface/billing/billing_report.php, interface/patient_file/history/encounters.php, interface/patient_file/summary/demographics.php, library/patient.inc.php
* use insurance date end on encounters page
* check insurance end date first for demographics old insurance display
* check insurance end date in billing report
* update comment
* formatting
* formatting
* formatting
Fixes #
=> implements insurance date_end for billing for Rel 701

interface/reports/appointments_report.php
=> fix: do not list canceled appts in report by default

src/Billing/X125010837P.php
=> fix: use claim referrer in X125010837P

interface/reports/appointments_report.php, src/Billing/X125010837P.php
=> couple recent fixes for Rel 701

interface/themes/oe-styles/style_dark.scss, portal/messaging/secure_chat.php, portal/patient/templates/OnsiteActivityViewListView.tpl.php, portal/patient/templates/OnsiteDocumentListView.tpl.php, portal/patient/templates/OnsitePortalActivityListView.tpl.php, portal/patient/templates/_FormsHeader.tpl.php, portal/patient/templates/_Header.tpl.php, portal/quickstart_page.php
=> - Fix dependencies for core portal apps

interface/forms/questionnaire_assessments/questionnaire_assessments.php, interface/themes/oe-styles/style_dark.scss, portal/index.php, portal/patient/scripts/app/onsitedocuments.js, portal/patient/templates/OnsiteDocumentListView.tpl.php, portal/quickstart_page.php
- restyle main portal login to be responsive in portrait
- add select to auto save
- alert patient for unsaved edits if in edit and refresh page
Fixes #
=> More portal

interface/forms/requisition/new.php, library/lab.inc.php
Fixes #6433
Fixes bugs in the order deletion and the requisition deletion. 
Updates styling to bootstrap x
=> Fix styling and bug

interface/patient_file/front_payment.php, interface/patient_file/pos_checkout_normal.php
=> fix: default payment method for checkout

portal/patient/scripts/app/onsiteactivityviews.js
Add a custom event for allowing module writers to add custom audit handling logic.
Fixes #6568
=> Fixes #6568 Portal Audit JS Event

src/Common/Forms/BaseForm.php, src/Common/Forms/FormQuestionnaireAssessment.php, src/Services/FormService.php
Add classes for dealing with the encounter forms table and the form_questionnaire_assessments table.
Fixes #6571
=> Fixes #6571 Form OOP Fixes

portal/lib/doc_lib.php, src/Pdf/PatientPortalPDFDocumentCreator.php, src/Services/DocumentTemplates/DocumentTemplateService.php
Pulls the portal pdf document logic from doc_lib.php into a class so we can use it / consume it in OpenEMR.
Fixes #6570
=> Fixes #6570 portal pdf document creator class

interface/modules/custom_modules/oe-module-prior-authorizations/public/patient_menu/custom_patient_menu.json
=> fix: change acl_req in prior auth module for custom patient menu

sql/7_0_1-to-7_0_2_upgrade.sql
=> fix: typo in 701 to 702 upgrade

sql/7_0_1-to-7_0_2_upgrade.sql
fix: minor fix in upgrade script
=> fix: minor fix in upgrade script

interface/billing/billing_report.php, sql/7_0_1-to-7_0_2_upgrade.sql
=> fix: topatient call in billing report load encounter dropdown

interface/main/calendar/add_edit_event.php, src/Events/Appointments/AppointmentRenderEvent.php, src/Events/Services/ServiceDeleteEvent.php, src/Events/Services/ServiceSaveEvent.php, src/RestControllers/AppointmentRestController.php, src/Services/AppointmentService.php
Added a ServiceDeleteEvent and refactored the add_edit_event script to fire off both the pre and post service delete events.
Added an event to add content at the bottom of the add_edit_event page.
Did some minor documentation cleanup on the service save event.
Fixes #6591
=> feat: Fixes #6591 Appointment Event Firing

interface/super/templates/field_multi_sorted_list_selector.php
Use bootstrap's list-group on the sortable list.
=> fix: Use bootstrap for list items on multi sorted list options

interface/main/calendar/add_edit_event.php, interface/main/calendar/find_appt_popup.php, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
=> fix: cast start minutes to int for calendar view math

interface/forms/eye_mag/js/eye_base.php, interface/forms/eye_mag/php/eye_mag_functions.php, interface/forms/eye_mag/report.php, interface/forms/eye_mag/save.php, interface/forms/eye_mag/view.php
=>  fix: prevent form_eye_ros from overwriting values on form exit that were previously saved plus php8 warnings 

interface/forms/eye_mag/php/eye_mag_functions.php, interface/forms/eye_mag/report.php, interface/forms/eye_mag/view.php, interface/forms/fee_sheet/new.php
=> fix: better handling of PMSFH mentions in eye exam edit and report

library/classes/Document.class.php, src/Pdf/PatientPortalPDFDocumentCreator.php
Return the document object in the PatientPortalPDFDocumentCreator class.
Also type defined the document uuid method in the Document class.
Fixes #6610
=> feat: Fixes #6610 pdf refactor return document

src/Common/Http/HttpRestRouteHandler.php
Adds content-encoding to allowed CORS headings
Fixes #6634
=> feat: Fixes #6634 CORS content-encoding

interface/forms/eye_mag/js/eye_base.php, interface/forms/eye_mag/php/eye_mag_functions.php, interface/forms/eye_mag/report.php, interface/forms/eye_mag/save.php, interface/forms/eye_mag/view.php, interface/forms/fee_sheet/new.php, interface/main/calendar/add_edit_event.php, interface/main/calendar/find_appt_popup.php, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html, src/Billing/BillingProcessor/BillingProcessor.php, src/Billing/BillingProcessor/Tasks/AbstractGenerator.php, src/Billing/BillingProcessor/Tasks/AbstractProcessingTask.php, src/Billing/BillingProcessor/Tasks/TaskReopen.php, src/Services/BaseService.php, src/Services/MedicationPatientIssueService.php
=> Rel 701 last 5 commits from master

interface/main/finder/dynamic_finder.php, interface/patient_file/summary/demographics.php, library/globals.inc.php, sql/7_0_1-to-7_0_2_upgrade.sql, sql/database.sql, src/Common/Session/PatientSessionUtil.php, src/Common/Twig/TwigExtension.php, src/Services/PatientService.php, templates/patient_finder/finder.html.twig
This creates a new session array item for the 10 most recent patients that have been opened. The actual user interface is still to be completed, but the underlying functionality now exists.
I know some may argue this should be it's own module, but the overhead of putting it in a new module versus the slim addition to core I feel warrants just putting it in core.
New global to set the max number of Recent Patient, new List to allow admins to customize which fields are set in the session.
=> feat: Recent patient list

interface/drugs/drug_inventory.php
=> fix: bump generateEmptyTd() for inventory management datatables

templates/patient/card/allergies.html.twig
=> fix: Alarm on the 3 most critical allergic reactions

interface/billing/sl_eob_process.php, library/patient.inc.php
=> fix: era posting display floatval fix and typo in patient.inc

src/Services/QuestionnaireResponseService.php, src/Services/QuestionnaireService.php
Made it so the source_url for questionnaire imports is properly formatted.
Also fixed the questionnaire reponse to be ordered by date and exposed the questionnaire uuid in the sql query.
Fixes #6672
=> Fixes #6672 source_url and order QRs by date

interface/usergroup/facilities.php
=> fix: Add missing style from inactive toggler button

interface/billing/sl_eob_process.php, library/patient.inc.php
=> fix for rel-701: era posting display floatval fix and typo in patient.inc (#6675)

interface/usergroup/facilities.php
=> fix: updateUsersFacility bug in prior commit

library/pnotes.inc.php
=> fix: check assigned_to user for pnote access

templates/error/general_function_argument.html, templates/error/general_function_arguments.html
=> fix(templates): fix typos in error html files

.github/workflows/styling.yml
=> ci(stylelint): simultaneously check css and scss files

interface/forms/care_plan/new.php, interface/forms/care_plan/templates/careplan_actions.php
Put the metadata on it's own row, allowing for the description to be wider
=> feat: Care Plan UI Wider Textbox

portal/index.php
=> fix: Typo and translation

.stylelintignore, .stylelintrc.json, contrib/forms/example2/print.php, contrib/forms/example2/style.css, contrib/forms/example2/view.php, swagger/index.css
=> fix(stylelint): correct stylelint "extends" configuration

.eslintignore, package.json
fix: add vendor directory to .eslintignore
feat: add lint-js fix support for the devtools
=> Lint js updates

.eslintrc.json, .github/workflows/js-test.yml, ccdaservice/data-stack/data-stack.js, ccdaservice/data-stack/data-stack.spec.js, ccdaservice/package-lock.json, ccdaservice/serveccda.js, jest.config.js, package-lock.json, package.json
Some improvements for the DataStack class of ccdaservice:
- extract it to separate file
- encapsulate properties
- create tests for class
Tested changes by running the OpenEMR app and generating 10 random patients:
=> refactor(ccdaservice): improve DataStack class

interface/patient_file/summary/demographics.php
=> fix: send lists.pid into allergy Service for dashboard allergies

interface/main/finder/dynamic_finder.php
=> fix: add webroot + Add New Patient

interface/main/calendar/add_edit_event.php, interface/smart/ehr-launch-client.php, src/Common/Auth/OpenIDConnect/SMARTSessionTokenContextBuilder.php, src/Events/Appointments/AppointmentDialogCloseEvent.php, src/FHIR/SMART/SMARTLaunchToken.php, src/FHIR/SMART/SmartLaunchController.php
Made it so we can launch a smart app with a specific appointment context as well as hook into the appointment close dialog.
Also added in an ehr-launch-client.php file so we can quickly do an ehr initiated app launch.
Fixes #6720
=> Fixes #6720 appointment dialog hooks

library/pnotes.inc.php
=> check assigned_to user for pnote access for rel-701

interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
addition that Fixes #6621 so will display minutes properly
=> fix: format minutes integer for calendar

interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
=> fix: format minutes integer for calendar for rel-701

templates/patient/card/allergies.html.twig
=> bug: Render Nothing Recorded indicator on Allergy card

interface/patient_file/summary/demographics.php
=> fix: Check if we have recorded no known allergies

interface/patient_file/summary/demographics.php
=> fix: Render demographics in MRD

library/options.inc.php
- for patch from master-7.0.2
Fixes #
=> Previous name errant data on add new patient

.eslintrc.json, interface/main/tabs/js/menu_analysis.js, interface/patient_file/report/custom_report.js, library/dialog.js, library/js/ajax_functions_writer.js, library/js/calendarDirectSelect.js, library/js/erx_javascript.js, portal/sign/assets/signer_api.js
This rule flags escapes that can be safely removed without changing behaviour.
Docs: https://eslint.org/docs/latest/rules/no-useless-escape
=> fix(eslint): fix no-useless-escape error

.stylelintignore
fix openemr-cmd ltr after running openemr-cmd jrb
=> fix openemr-cmd ltr after running openemr-cmd jrb

.stylelintignore, gacl/admin/admin.css
phpGACL - ACL Admin page after changes:
Error fixed: [no-descending-specificity](https://stylelint.io/user-guide/rules/no-descending-specificity/)
This stylelint error enforces an order of specificity for selectors, from lower to higher. This helps keeping the CSS code more logical, predictable and maintainable.
=> fix(gacl): fix stylelint errors in admin.css

src/RestControllers/UserRestController.php
Didn't see this until I tried an external server.  Ouch.
Fixes #6783
=> Fixes #6783 missing user rest controller

interface/patient_file/encounter/forms.php
A bit better styling of the Encounter page. Still need to add a bunch of forms to test.
=> Add container, better rendering of header, space buttons

interface/modules/custom_modules/oe-module-claimrev-connect/table.sql, interface/modules/custom_modules/oe-module-claimrev-connect/templates/eligibility.php
if more than one come back on a check.
Increased table column size too, truncation was happening
Fixes #6778
this will display the missing insurances that should of been presented.  Also the text data column was to small and data was being truncated, so more data could be missing.
Just looping the data and using the correct property. Also changing the column types on the table the module uses.
=> added ability to see multiple eligibilities if

interface/forms/fee_sheet/new.php
Add button classes to the radio inline
=> feat: Better spacing of additional code buttons on fee sheet

interface/forms/newpatient/report.php, interface/forms/newpatient/templates/report.html.twig
Move the encounter report.php to twig, make some minor UI improvements
Will resolve #6748
=> feat: Better UI and Code for encounter report

interface/forms/newpatient/templates/report.html.twig
Had the tags reversed, this runs the text then converts to newlines properly
=> fix: Quickfix to reverse the text and nl2br tags

interface/patient_file/encounter/forms.php, library/ESign/views/form/esign_button.php
Some more improvements on the encounter page. Add a chevron to form titles, reduce the context buttons
=> feat: More encounter UI improvements

interface/forms/newpatient/report.php, interface/forms/newpatient/templates/report.html.twig
=> fix: For prior PR #6749

interface/forms/newpatient/common.php, interface/forms/newpatient/report.php, interface/patient_file/encounter/forms.php, interface/usergroup/user_admin.php, interface/usergroup/usergroup_admin.php, interface/usergroup/usergroup_admin_add.php, library/ESign/DbRow/Signable.php, library/ESign/Signature.php, library/ESign/SignatureIF.php, library/ESign/views/default/esign_signature_log.php, library/patient.inc.php
=> provider credentials for rel-701

library/globals.inc.php
Allow user admin to determine how portal credential force reset is handled
options are allow disallow or user selectable from dialog
=> Add force credential reset option to globals

interface/patient_file/summary/create_portallogin.php, library/globals.inc.php, src/Services/PatientAccessOnsiteService.php, templates/patient/portal_login/print.html.twig
See issue #6813 
Port from master dev
=> Backport of force rest credentials option from PR #6817

interface/forms/clinical_notes/new.php, interface/forms/clinical_notes/templates/report.html.twig, interface/patient_file/encounter/forms.php, src/Common/Twig/TwigExtension.php, src/Services/ClinicalNotesService.php
1. Sql query fix (grabbing of the category stuff from list_options was broken)
2. Translation fixes
3. Escaping fix
=> fix: several clinical_notes form fixes

portal/patient/scripts/app/onsitedocuments.js
Forgot to refactor full URL's that includes static domain from when testing a session issue.
=> fix static domain included in URL

.github/workflows/test.yml, ci/apache_82_111/docker-compose.yml
chore: ci mariadb stuff - added 11.1 and removed 10.9
=> chore: ci mariadb stuff - added 11.1 and removed 10.9

interface/billing/search_payments.php, src/Events/Billing/Payments/DeletePayment.php
Fixes #6841
Add class for billing event when payments are deleted
Edits to search_payment.php
New class added to the Events folder.
=> Adding event to billing deleting of payment

src/Common/Database/QueryPagination.php
Fixes the fatal error with the totalCount not being defined.
Fixes #6848
=> feat: Fixes #6848 pagination fatal error.

src/Services/FHIR/FhirPatientService.php, src/Services/FHIR/FhirServiceBase.php, src/Services/FHIR/UtilsService.php, src/Services/PatientService.php
Fixes #6851 change sort order of title field
Fixes #6849 add extension url lookup FHIR utility method 
Fixes #6827 add patient provider/general practitioner to api
=> feat: Fixes #6851,#6849,#6827 api changes.

interface/patient_file/summary/demographics.php
=> bug: No custom function call in "btnLink"

interface/patient_file/summary/stats_full.php
fix: fix none mechanism in issues gui
=> fix: fix none mechanism in issues gui

interface/patient_file/summary/demographics.php
fix: fix none issue mechanism in the patient summary screen
=> fix: fix none issue mechanism in the patient summary screen

interface/patient_file/summary/demographics.php
fix: patient summary screen fix for receptionist
=> fix: patient summary screen fix for receptionist

interface/forms/newpatient/common.php, interface/forms/newpatient/report.php, interface/patient_file/encounter/forms.php, library/patient.inc.php
=> fix: save pos_code with new encounter

interface/patient_file/front_payment.php, src/Events/Billing/Payments/PostFrontPayment.php
=> Module needs to add feature to payment screen

interface/patient_file/summary/demographics.php, templates/patient/card/card_base.html.twig
Restyle cards
Fixes #6883 
- Change column sizes
=> Dashboard card repositioning

composer.json, composer.lock, interface/orders/gen_hl7_order.inc.php, interface/orders/receive_hl7_results.inc.php, interface/procedure_tools/gen_universal_hl7/gen_hl7_order.inc.php, interface/procedure_tools/labcorp/gen_hl7_order.inc.php, library/edihistory/test_edih_sftp_files.php, src/Billing/BillingProcessor/X12RemoteTracker.php, src/Common/Auth/OpenIDConnect/JWT/RsaSha384Signer.php
chore: upgrade phpseclib from version 2 to version 3
=> chore: upgrade phpseclib from version 2 to version 3

interface/forms/newGroupEncounter/common.php, interface/forms/newpatient/common.php
Fixes a potential issue from b5663de where the strict comparison might fail
=> fix: fix to prior commit, use int to compare facility id

interface/patient_file/front_payment.php
=> feat: add billing event to front payment

controllers/C_InsuranceCompany.class.php, interface/billing/edi_270.php, interface/patient_file/summary/demographics.php, library/classes/X12Partner.class.php, library/globals.inc.php, sql/7_0_1-to-7_0_2_upgrade.sql, sql/database.sql, src/Billing/EDI270.php, templates/patient/card/insurance.html.twig, templates/x12_partners/general_edit.html, version.php
couldn't help myself @juggernautsei  :sweat_smile: 
Fixes #6914
=> feat: minor refactor x12 insurance eligibility api

templates/login/base.html.twig, templates/login/layouts/vertical_box.html.twig
Fixes the hard coded background styles in the login page.
Fixes #6920
=> fix: Variable background styles on login screen

interface/forms/clinical_notes/new.php
=> feat: New Clinical Note defaults to today

sql/7_0_1-to-7_0_2_upgrade.sql
=> bug: remove semicolon typos

docker/development-insane/README.md, docker/development-insane/docker-compose.yml
chore: insane dev environment updates
=> chore: insane dev environment updates

interface/billing/indigent_patients_report.php, interface/billing/sl_eob_invoice.php, interface/billing/sl_eob_search.php, interface/billing/sl_receipts_report.php, interface/patient_file/encounter/superbill_custom_full.php, interface/patient_file/front_payment.php, interface/reports/appt_encounter_report.php, interface/reports/collections_report.php, interface/reports/front_receipts_report.php, interface/reports/inventory_transactions.php, interface/reports/receipts_by_method_report.php, interface/reports/sales_by_item.php, interface/reports/services_by_category.php, library/formatting.inc.php, library/report.inc.php, portal/portal_payment.php, src/Billing/InvoiceSummary.php, src/Common/Utils/FormatMoney.php
=> refactor: refactor bucks function with new class based on oeFormatMoney

interface/billing/sl_eob_invoice.php, interface/patient_file/encounter/forms.php, src/Billing/Claim.php, src/Billing/InvoiceSummary.php, src/Common/Utils/FormatMoney.php
=> fix: round small billing invoice amounts for better comparison and display

interface/billing/payment_master.inc.php, library/payment_jav.inc.php
=> fix: remove allocate alert

interface/forms/newpatient/save.php, library/encounter.inc.php, src/Services/EncounterService.php
Fixes 6952
Default POS code not being saved to the encounter.
=> Bug Fix - default pos code

interface/eRxStore.php, interface/eRxXMLBuilder.php
We should only be sending active diagnosis to newcrop, not all
=> Newcrop diagnois only active

interface/usergroup/mfa_totp.php
=> Fix typo in interface/usergroup/mfa_totp.php

templates/super/facilities/form.html.twig
=> fix: update label for facility code

interface/modules/custom_modules/oe-module-ehi-exporter/CHANGELOG.md, interface/modules/custom_modules/oe-module-ehi-exporter/info.txt, interface/modules/custom_modules/oe-module-ehi-exporter/public/assets/js/ehi-exporter.js, interface/modules/custom_modules/oe-module-ehi-exporter/public/index.php, interface/modules/custom_modules/oe-module-ehi-exporter/src/Bootstrap.php, interface/modules/custom_modules/oe-module-ehi-exporter/src/Models/EhiExportJobTask.php, interface/modules/custom_modules/oe-module-ehi-exporter/src/Models/ExportResult.php, interface/modules/custom_modules/oe-module-ehi-exporter/src/Models/ExportState.php, interface/modules/custom_modules/oe-module-ehi-exporter/src/Models/ExportTableResult.php, interface/modules/custom_modules/oe-module-ehi-exporter/src/Services/EhiExportJobService.php, interface/modules/custom_modules/oe-module-ehi-exporter/src/Services/EhiExportJobTaskService.php, interface/modules/custom_modules/oe-module-ehi-exporter/src/Services/EhiExporter.php, interface/modules/custom_modules/oe-module-ehi-exporter/src/TableDefinitions/ExportTableDefinition.php, interface/modules/custom_modules/oe-module-ehi-exporter/table.sql, interface/modules/custom_modules/oe-module-ehi-exporter/templates/oe-module-ehi-exporter/ehi-exporter-tasks.html.twig, interface/modules/custom_modules/oe-module-ehi-exporter/templates/oe-module-ehi-exporter/ehi-exporter.html.twig
This change adds progress indicators to the export process.  It will loop through each batch individually and process the batch while reporting progress in 5 second intervals on the currently processed batch.  If a batch fails it can be retried.
Added a new column to the task to hold the current result progress.
Changed up the index page to function as both the main index and an ajax controller.  Probably could break this apart but for expediency did it this way.
=> Asynchronous Export Progress Updates.

_rest_routes.inc.php, composer.json, sql/7_0_2-to-7_0_3_upgrade.sql, swagger/openemr-api.yaml, version.php
chore: prep for after rel-702 branch (will bring this in after branch rel-702)
=> chore: prep for after rel-702 branch

.github/workflows/js-test.yml, .github/workflows/styling.yml, .github/workflows/syntax.yml, .github/workflows/test.yml, README.md, _rest_routes.inc.php, swagger/openemr-api.yaml
chore: kick off the rel-702 branch
=> chore: kick off the rel-702 branch

_rest_routes.inc.php, swagger/openemr-api.yaml
Fixes #6967
Corrected field name on /api/patient/{pid}/message/{mid}
Added parameters to /fhir/Group/{id}/$export
=> Edit openemr-api.yaml to to pass validation

interface/patient_file/summary/demographics.php, templates/patient/card/card_base.html.twig
=> fix: use btn-link instead of a tag for dashboard cards

.github/workflows/test.yml, ci/apache_82_80/docker-compose.yml, ci/apache_82_82/docker-compose.yml, docker/development-insane/README.md, docker/development-insane/docker-compose.yml
chore: bit of mysql cleanup in ci and dev environments
=> chore: bit of mysql cleanup in ci and dev environments

docker/production-arm/docker-compose.yml, docker/production/docker-compose.yml, library/globals.inc.php, version.php
=> chore: prepping for release

interface/patient_file/summary/demographics.php, interface/themes/colors/utilities/default_variables.scss, interface/themes/core/oe-mobile.scss, interface/themes/core/therapy-groups.scss, interface/themes/default-variables.scss, interface/themes/misc/bootstrap_navbar.scss, interface/themes/misc/edi_history_v2.scss, interface/themes/misc/encounters.scss, interface/themes/misc/rules.scss, templates/documents/general_list.html, templates/patient/card/card_base.html.twig, templates/patient/card/medication.html.twig
- Change themes default font size to BS defaults 1rem.
- add card class to center cards class list
- fix Medications card list font weight to normal from bold.
Fixes #7027
=> Some last minute changes

composer.lock
fix: composer lock was out of date
=> fix: composer lock was out of date

composer.json
=> fix: composer fix

interface/orders/orders_results.php
=> fix: bug rel-702

sql/7_0_1-to-7_0_2_upgrade.sql, sql/database.sql, templates/patient_finder/finder.html.twig
=> fix: dob typo in recent patient finder (#7036)

src/Services/AllergyIntoleranceService.php
=> fix: prevent dupe allergies returning from service

src/Services/AllergyIntoleranceService.php
* fix: prevent dupe allergies returning from service
* move array push
Fixes #
=> fix: prevent dupe allergies returning from service (#7041) for rel-702

version.php
Fixes #
bump db version counter for 5f8e933
=> chore: bump db version for prior commit

sql/patch.sql
=> fix: recent pt dob to DOB in patch.sql

docker/production-arm/docker-compose.yml, docker/production/docker-compose.yml
Fixes #7047
Updates docker/production/docker-compose.yml to for 7.0.2.
=> Chore: change production docker to 7.0.2

interface/patient_file/report/custom_report.php, interface/patient_file/summary/demographics_print.php
=> fix: mpdf necessary config for patient custom report pdf download

interface/forms/eye_mag/a_issue.php, interface/forms/eye_mag/css/style.css, interface/forms/eye_mag/php/eye_mag_functions.php, interface/patient_file/report/custom_report.php, interface/patient_file/summary/demographics_print.php
=> last 2 commits from master for rel-702

interface/forms/note/new.php
=> Add bootstrap to modernize work school note form

interface/forms/note/new.php
* Add bootstrap to modernize
* removing short tags
Fixes #
=> Add bootstrap to modernize work school note form (#6947) for rel-702

library/classes/thumbnail/ThumbnailGenerator.php, portal/patient/fwk/libs/util/parsecsv.lib.php, portal/patient/fwk/libs/verysimple/Phreeze/DataAdapter.php, portal/patient/fwk/libs/verysimple/Phreeze/DataSet.php, portal/patient/fwk/libs/verysimple/Phreeze/ObserveToSmarty.php, portal/patient/fwk/libs/verysimple/Phreeze/QueryBuilder.php, tests/Tests/Unit/Common/Auth/OpenIDConnect/Repositories/ScopeRepositoryTest.php, version.php
* chore: bump db version for prior commit
* styling fixes for new version of squizz
Fixes #
=> chore: bump db version for prior commit (#7083) and php styling fixes for rel-702

version.php
=> undo v_db increment for rel-702

interface/reports/collections_report.php
Fixes #7099
Adding the option for group number to the collection report
adding columns for the group report
=> feat: Adding the option to include group numbers in the collection report

portal/patient/templates/OnsiteActivityViewListView.tpl.php, portal/patient/templates/_FormsHeader.tpl.php, portal/portal_payment.php, portal/verify_session.php
Fixes #7102 
- for windows fix file path to globals.php in verify_session
- php 8.2 warning
=> Portal fixups

package-lock.json, package.json
=> fix: pin ckeditor4.22.1

interface/reports/collections_report.php
…port (#7100)
* Adding the option to include group numbers in the collection report
* expected at least 8 spaces, found 4
Fixes #
=> pr7100 for rel-702

interface/modules/custom_modules/oe-module-faxsms/contact.php, interface/modules/custom_modules/oe-module-faxsms/messageUI.php, interface/modules/custom_modules/oe-module-faxsms/setup.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/AppDispatch.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/EtherFaxActions.php
* SMS Fax module updates
- fix dialog in SMS reminders reply
- fix PHP 8 warnings
* - more php warnings
Fixes #
=> SMS Fax module updates (#7096) for rel-702

portal/patient/templates/OnsiteActivityViewListView.tpl.php, portal/patient/templates/_FormsHeader.tpl.php, portal/portal_payment.php, portal/verify_session.php
* Portal fixups
- for windows fix file path
- php 8.2 warning
* - remove extraneous characters from html
Fixes #
=> Portal fixups (#7103) for rel-702

src/Services/FHIR/FhirPatientService.php
Adds email_direct to the FHIR Patient Service.  
This commit maps the "Trusted Email" to (system)email, (use)mobile, both for output and input. It avoids the pre-existing mapping conflict/collision for home/work email -> email.  Justification of the mapping comes from the FHIR ContactPointUse spec for "mobile" (for urgent matters, not routine ones):
> A telecommunication device that moves and stays with its owner.  May have characteristics of all other use codes, suitable for urgent matters, not the first choice for routine business."
Fixes #7113.
=> Implement email_direct in the FHIR Patient api.

.github/workflows/manual-build-php-fpm-dockers.yml, docker/library/dockers/dev-php-fpm-8-3/Dockerfile, docker/library/dockers/dev-php-fpm-8-4-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-4-redis/php.ini, docker/library/dockers/dev-php-fpm-8-4/Dockerfile, docker/library/dockers/dev-php-fpm-8-4/php.ini
chore: ci add build for nginx dockers php84
=> chore: ci add build for nginx dockers php84

docker/library/dockers/dev-php-fpm-8-4-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-4/Dockerfile
fix: php 8.4-dev nginx builds for ci
=> fix: php 8.4-dev nginx builds for ci

.github/workflows/test.yml, ci/nginx_84/docker-compose.yml, ci/nginx_84/php.ini, docker/development-insane/README.md, docker/development-insane/docker-compose.yml, docker/library/dockers/dev-nginx/nginx.conf
chore: add php 8.4-dev to ci and insane dev environment
=> chore: add php 8.4-dev to ci and insane dev environment

.github/workflows/js-test.yml, .github/workflows/styling.yml, .github/workflows/test.yml, CONTRIBUTING.md, README.md, ci/apache_83_1010/docker-compose.yml, ci/apache_83_1011/docker-compose.yml, ci/apache_83_104/docker-compose.yml, ci/apache_83_105/docker-compose.yml, ci/apache_83_106/docker-compose.yml, ci/apache_83_110/docker-compose.yml, ci/apache_83_111/docker-compose.yml, ci/apache_83_57/docker-compose.yml, ci/apache_83_80/docker-compose.yml, ci/apache_83_82/docker-compose.yml
chore: integrate new flex docker into ci
(main php to 8.3 and main nodejs to 20)
=> chore: integrate new flex docker into ci

interface/reports/criteria.tab.php
=> fix: billing manager date select options syntax error

interface/forms/LBF/new.php, library/ajax/template_context_search.php, library/custom_template/ajax_code.php, library/custom_template/custom_template.php, library/custom_template/personalize.php
- add preventdefault to keep form from submitting on button
- fix numerous php warnings
- fix sql query error for orphan query
- some restyle for colors
This picks up from PR #7130
Fixes #7129
=> fix: Fix Nation Notes unable to share templates

src/Events/Patient/Summary/Card/SectionEvent.php
Fixes #7171 so that the section event order of operations is done correctly.
=> Fix #7171 section event append

controllers/C_Document.class.php, portal/patient/libs/Controller/OnsiteDocumentController.php, portal/patient/scripts/app/onsitedocuments.js, portal/patient/templates/OnsiteDocumentListView.tpl.php, src/Services/DocumentTemplates/DocumentTemplateService.php, templates/documents/general_list.html, templates/documents/general_upload.html
Since portal refactor the render portal documents from patient documents has been broken. Nuts on me!
Figured I'd do a bit of restyle while here.
Fixes #7173 
refactor controller to call new portal document menu fix calling requested document render from patient documents restyle documents to be cleaner
=> Fix render Document Temples from Documents

library/custom_template/ajax_code.php, library/custom_template/quest_popup.php, library/js/ajax_functions_writer.js
Render build for component list needed refactor.
Fixes #7176
=> Fix for Nation Notes

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/security_report.md, .github/SECURITY.md
chore: update security reporting documentation and some funding documentation
=> chore: update security reporting documentation and some funding documentation

interface/modules/custom_modules/oe-module-weno/scripts/file_download.php, interface/modules/custom_modules/oe-module-weno/scripts/weno_pharmacy_search.php, interface/modules/custom_modules/oe-module-weno/src/Services/LogImportBuild.php, interface/modules/custom_modules/oe-module-weno/src/Services/PharmacyService.php, interface/modules/custom_modules/oe-module-weno/src/Services/WenoPharmaciesImport.php, interface/modules/custom_modules/oe-module-weno/templates/facilities.php, interface/modules/custom_modules/oe-module-weno/templates/pharmacy_list_form.php
- rename class file because of case difference. windows doesn't care but linux does
weird how I had to rename for git prob a windows thing.
=> Weno bug fixes

interface/modules/custom_modules/oe-module-weno/src/Services/LogProperties.php, interface/modules/custom_modules/oe-module-weno/src/Services/TransmitProperties.php, interface/modules/custom_modules/oe-module-weno/src/Services/WenoPharmaciesImport.php, interface/modules/custom_modules/oe-module-weno/templates/indexrx.php, interface/modules/custom_modules/oe-module-weno/templates/rxlogmanager.php, interface/modules/custom_modules/oe-module-weno/templates/synch.php
Fixes #
Weno module fixup.
- fix transaction for pharmacy download
- refactor user default fac to include select from user facility when user is not logged into facility.
- convert error to interface style helper to static
- create static styler for echo to interface.
- refactor all show errors to include a style compatible with themes.
=> Weno module changes

src/Billing/X125010837P.php
Fixes #7206 
these changes will get the claim on file at the clearinghouse who would then expect to receive a medical claim attachment sent electronically, that's to be done later :)
=> feat: support worker's comp electronic claims

interface/main/tabs/menu/menus/standard.json, interface/reports/rwt_2024_report.php, sites/default/documents/custom_menus/Custom.json
add Real World Testing Report for 2024
=> feat: add Real World Testing Report for 2024

interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
Action status was not being passed in the listener. Fixes #7214
=> Fixes #7214 pass action status to listener

interface/logview/logview.php, interface/usergroup/usergroup_admin.php
- restyle logs view
- code standards usergroup_admin
Fixes #
log view needed a restyle.
Looks like Users edit could have some discrete bugs.
Issue I haven't found yet for entries are duplicating.
=> Various Bug fixes.

library/js/xl/jquery-datetimepicker-2-5-4-translated.js
possible fix of logic in jquery-datetimepicker-2-5-4-translated.js
hi @adunsulag , noted that the logic in this script may be incorrect (unless i am missing something; perhaps this setting is already set somewhere by default). This is a blind fix since not sure how to test it.
=> fix: possible fix of logic in jquery-datetimepicker-2-5-4-translated.js

controllers/C_InsuranceCompany.class.php, library/classes/InsuranceCompany.class.php, src/Services/InsuranceCompanyService.php, templates/insurance_companies/general_list.html.twig
Fixed the list loading taking forever on the insurance company list. This fixes #7224.
Had a bug in the fix for #7217 so this fixes that as well. Wasn't actually replacing the insurance id.
=> Fixes #7224, #7217 insurance company changes

contrib/forms/xmlformgen/xslt/new.php.xslt, contrib/forms/xmlformgen/xslt/view.php.xslt, interface/main/calendar/add_edit_event.php, interface/modules/zend_modules/module/Carecoordination/view/carecoordination/setup/index.phtml, interface/orders/single_order_results.inc.php, interface/reports/patient_flow_board_report.php, portal/report/portal_custom_report.php, portal/report/portal_patient_report.php
* fix: bug fix
* js context
Fixes #
=> fix: bug fix (#7230) rel-702

src/Billing/X125010837P.php
=> fix: bug in service facility logic

interface/forms/LBF/new.php
=> fix: add space to fix broken LBF sql query

interface/patient_file/front_payment.php
=> fix: remove formatting when calculating front payment balance

interface/patient_file/front_payment.php
=> fix: remove formatting when calculating front payment balance (#7261)

library/clinical_rules.php
for rel-702
cdr fix to correctly show actions that are due, due soon, past due in expanded listings
=> fix: cdr fix to correctly show actions that are due, due soon, past due in expanded listings

.github/workflows/manual-build-php-fpm-dockers.yml
chore: update github actions for docker builds to prevent deprecations
=> chore: update github actions for docker builds to prevent deprecations

.github/workflows/manual-build-php-fpm-dockers.yml
quick fix to prior pull request #7271
=> chore: commit 2 that updates github actions for docker builds to prevent deprecations

.github/workflows/test.yml, ci/apache_83_113/docker-compose.yml, ci/apache_83_83/docker-compose.yml
chore: ci add mariadb 11.3, change mysql 8.2 to mysql 8.3
=> chore: ci add mariadb 11.3, change mysql 8.2 to mysql 8.3

interface/patient_file/encounter/forms.php, library/ESign/Encounter/Controller.php, library/ESign/Form/Controller.php, library/ESign/views/encounter/esign_form.php, library/ESign/views/form/esign_form.php, library/js/gSignIn.js
for rel-702
fix: Support google single sign on mode for esign of encounters and forms
=> fix: Support google single sign on mode for esign of encounters and forms

ccr/createCCR.php, interface/modules/zend_modules/module/Acl/view/acl/acl/acl.phtml, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncountermanagerController.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Listener/CCDAEventsSubscriber.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceRequestModelGenerator.php, interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml, interface/modules/zend_modules/module/Carecoordination/view/carecoordination/setup/index.phtml, interface/modules/zend_modules/module/CodeTypes/src/CodeTypes/Listener/CodeTypeEventsSubscriber.php, interface/usergroup/facilities_add.php, interface/usergroup/facility_admin.php, portal/add_edit_event_user.php
=> bug: fix bug

ccr/createCCR.php, interface/modules/zend_modules/module/Acl/view/acl/acl/acl.phtml, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncountermanagerController.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Listener/CCDAEventsSubscriber.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceRequestModelGenerator.php, interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml, interface/modules/zend_modules/module/Carecoordination/view/carecoordination/setup/index.phtml, interface/modules/zend_modules/module/CodeTypes/src/CodeTypes/Listener/CodeTypeEventsSubscriber.php, interface/usergroup/facilities_add.php, interface/usergroup/facility_admin.php, portal/add_edit_event_user.php
* bug: fix bug
* fix bugs
* fix bug
Fixes #
=> bug: fix bug (#7231) for rel-702

interface/smart/register-app.php, src/Common/Auth/OpenIDConnect/Entities/ClientEntity.php
=> fix: cast empty contacts string to empty array

interface/billing/sl_eob_invoice.php
=> fix: int cast statement count saving invoice

interface/billing/sl_eob_invoice.php, interface/smart/register-app.php, src/Common/Auth/OpenIDConnect/Entities/ClientEntity.php
=> Rel 702 fixins

interface/billing/billing_report.php
=> fix: patient select bug from billing manager

interface/reports/appointments_report.php
=> fix: add canceled appts counter

interface/billing/sl_eob_invoice.php
=> fix: separate out pt and enc billing note

templates/patient/insurance/_insurance_edit_screen_edit.html.twig
Fixes https://github.com/openemr/openemr/pull/7269#discussion_r1541177345
=> fix: missing attr _insurance_edit_screen_edit.html.twig

src/Services/AppointmentService.php
Fixes #7301 
Add title to select query
=> Resolve #7301: Add title to appointment

src/Services/AppointmentService.php
Fixes #7300 
A bug that was accidentally introduced.
Fix bug
=> Resolve #7300: Resolve bug accidentally introduced in API

src/Common/Crypto/CryptoGen.php, src/Common/Crypto/CryptoGenException.php
minor CryptoGen class updates (#7365) for rel-702
=> feat: minor CryptoGen class updates (#7365)

interface/modules/custom_modules/oe-module-weno/scripts/weno_pharmacy_search.php, interface/modules/custom_modules/oe-module-weno/templates/indexrx.php
- restrict NCPDP to 7 digits per spec
=> weno changes

interface/main/messages/messages.php
Fixes #6070
select2 dropdown width on SMS Zone tab in Message Center
- set dropdown width via appropriate select2 options
- add tooltip for fontawesome action icon
=> fix: SMS Zone patient search dropdown

interface/forms/group_attendance/functions.php, interface/forms/group_attendance/new.php, interface/forms/group_attendance/report.php, interface/reports/collections_report.php
* expected at least 8 spaces, found 4
* adding attendance to encounter summary page
* PSR fixes
* fixing translation
Bringing #7127 into rel-702.
=> rel-702 feat: Group attendance display encounter (#7128)

controllers/C_Document.class.php, interface/billing/sl_eob_process.php, interface/main/messages/messages.php, interface/modules/custom_modules/oe-module-weno/scripts/weno_pharmacy_search.php, interface/modules/custom_modules/oe-module-weno/templates/indexrx.php, interface/modules/zend_modules/module/Application/src/Application/Plugin/CommonPlugin.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php, interface/patient_file/history/encounters.php, interface/reports/patient_list_creation.php, interface/usergroup/user_admin.php, interface/usergroup/user_info.php, interface/usergroup/usergroup_admin_add.php, library/classes/Document.class.php, library/clinical_rules.php, library/js/utility.js, library/options.inc.php, src/Common/Forms/Types/LocalProviderListType.php, src/Events/PatientDocuments/PatientDocumentStoreOffsite.php, src/Events/PatientDocuments/PatientRetrieveOffsiteDocument.php, src/Services/BaseService.php, src/Services/Cda/CdaTemplateParse.php, src/Services/EmployerService.php, src/Services/PractitionerService.php
Cherry picks to current
Fixes #
See commit
=> Jerry 702 picks

library/clinical_rules.php
=> Rel702 fixes cdr 10

interface/main/messages/messages.php
Brings #6070 into release 702 branch.
=> rel-702 fix SMS Zone patient search dropdown (#7307)

controllers/C_Document.class.php, library/htmlspecialchars.inc.php, src/Events/PatientDocuments/PatientRetrieveOffsiteDocument.php
=> fix: check for empty array before looking for offsite document

interface/modules/custom_modules/oe-module-weno/scripts/weno_log_sync.php, interface/modules/custom_modules/oe-module-weno/src/Services/LogProperties.php, interface/modules/custom_modules/oe-module-weno/templates/synch.php
- this needs a rewrite but maybe later
Making some errors easier to understand.
=> Weno better error handling from fetches

interface/forms/newpatient/common.php, interface/forms/newpatient/save.php, library/globals.inc.php, sql/7_0_2-to-7_0_3_upgrade.sql, sql/database.sql, src/Billing/Claim.php, src/Billing/MiscBillingOptions.php, src/Billing/X125010837P.php, src/Services/EncounterService.php
=> feat: support loop 2420E

interface/forms/newpatient/common.php, interface/forms/newpatient/save.php, library/globals.inc.php, sql/database.sql, sql/patch.sql, src/Billing/Claim.php, src/Billing/MiscBillingOptions.php, src/Billing/X125010837P.php, src/Services/EncounterService.php
=> Bring into patch 1 2420E #7405

interface/billing/billing_report.php
=> fix: billing manager To Encounter button to load proper person

ccr/createCCR.php, ccr/createCCRActor.php, ccr/createCCRAlerts.php, ccr/createCCRImmunization.php, ccr/createCCRMedication.php, ccr/createCCRProblem.php, ccr/createCCRResult.php, ccr/display.php, ccr/transmitCCD.php, interface/billing/billing_report.php, interface/main/messages/messages.php, interface/usergroup/facilities_add.php, interface/usergroup/facility_admin.php, library/MedEx/API.php
=> Rel 702 picks

Documentation/help_files/medical_dashboard_help.php, interface/modules/custom_modules/oe-module-faxsms/messageUI.php, interface/modules/custom_modules/oe-module-weno/templates/pharmacy_list_form.php, interface/patient_file/summary/demographics.php, interface/super/edit_globals.php, library/globals.inc.php, library/specialty_forms.php, src/Common/Crypto/CryptoGen.php, src/Services/Globals/GlobalSetting.php
=> Gap cherry-picks

interface/modules/custom_modules/oe-module-claimrev-connect/ModuleManagerListener.php, interface/modules/custom_modules/oe-module-claimrev-connect/moduleConfig.php, interface/modules/custom_modules/oe-module-claimrev-connect/openemr.bootstrap.php, interface/modules/custom_modules/oe-module-claimrev-connect/version.php
Module uninstall
(cherry picked from commit 4e8432afbaf3ce0f20aa045561fb82a99856402a)
Fixes #
=> Pull request #7442 backport Cleanup Background tasks

interface/reports/front_receipts_report.php, library/patient.inc.php, src/Patient/Cards/BillingViewCard.php, templates/patient/card/billing.html.twig
=> couple billing commits for rel-702

interface/modules/custom_modules/oe-module-weno/README.md, interface/modules/custom_modules/oe-module-weno/src/Services/LogImportBuild.php, interface/modules/custom_modules/oe-module-weno/src/Services/LogProperties.php, interface/modules/custom_modules/oe-module-weno/src/Services/TransmitProperties.php, interface/modules/custom_modules/oe-module-weno/src/WenoGlobalConfig.php, interface/modules/custom_modules/oe-module-weno/templates/setup_facilities.php, interface/modules/custom_modules/oe-module-weno/templates/weno_fragment.php, interface/modules/custom_modules/oe-module-weno/templates/weno_setup.php, interface/modules/custom_modules/oe-module-weno/templates/weno_users.php, interface/super/manage_document_templates.php
- missed calc age bug
- nomenclature changes replace all weno provider with weno user
Fixes #
This just continues the Weno project. Will back port
=> Weno changes from documentation critique

interface/main/messages/messages.php
=> bug: fix variable typo in messages.php

interface/main/messages/messages.php, src/Billing/X125010837I.php
=> Bug fixes rel 702

templates/portal/home.html.twig
=> fix: webroot typo documents-go portal home

interface/orders/gen_hl7_order.inc.php, interface/procedure_tools/gen_universal_hl7/gen_hl7_order.inc.php, interface/procedure_tools/quest/gen_hl7_order.inc.php, library/patient.inc.php
=> fix: add date_end to query for getEffectiveInsurances

interface/modules/custom_modules/oe-module-weno/scripts/weno_pharmacy_search.php, interface/modules/custom_modules/oe-module-weno/sql/1_0_0-to-2_0_0_upgrade.sql, interface/modules/custom_modules/oe-module-weno/src/Services/DownloadWenoPharmacies.php, interface/modules/custom_modules/oe-module-weno/src/Services/TransmitProperties.php, interface/modules/custom_modules/oe-module-weno/src/Services/WenoValidate.php, interface/modules/custom_modules/oe-module-weno/table.sql, interface/modules/custom_modules/oe-module-weno/templates/indexrx.php, interface/modules/custom_modules/oe-module-weno/templates/pharmacy_list_form.php, interface/modules/custom_modules/oe-module-weno/templates/weno_fragment.php, interface/modules/custom_modules/oe-module-weno/templates/weno_setup.php, interface/modules/custom_modules/oe-module-weno/templates/weno_users.php
- trigger persisted filters on form entry
- add refresh button to widget
=> Weno Search Tuning

interface/billing/billing_report.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/EtherFaxActions.php, interface/modules/custom_modules/oe-module-weno/scripts/weno_pharmacy_search.php, interface/modules/custom_modules/oe-module-weno/sql/1_0_0-to-2_0_0_upgrade.sql, interface/modules/custom_modules/oe-module-weno/src/Services/DownloadWenoPharmacies.php, interface/modules/custom_modules/oe-module-weno/src/Services/TransmitProperties.php, interface/modules/custom_modules/oe-module-weno/src/Services/WenoValidate.php, interface/modules/custom_modules/oe-module-weno/table.sql, interface/modules/custom_modules/oe-module-weno/templates/indexrx.php, interface/modules/custom_modules/oe-module-weno/templates/pharmacy_list_form.php, interface/modules/custom_modules/oe-module-weno/templates/weno_fragment.php, interface/modules/custom_modules/oe-module-weno/templates/weno_setup.php, interface/modules/custom_modules/oe-module-weno/templates/weno_users.php, interface/orders/gen_hl7_order.inc.php, interface/procedure_tools/gen_universal_hl7/gen_hl7_order.inc.php, interface/procedure_tools/quest/gen_hl7_order.inc.php, library/js/xl/jquery-datetimepicker-2-5-4-translated.js, library/patient.inc.php
=> Weno cherry to 7.0.2

interface/billing/billing_report.php
let's try this again :)
Fixes #7501
=> fix: set default x12 partner for item in billing manager

.github/workflows/test.yml, ci/apache_83_84/docker-compose.yml, docker/development-insane/README.md, docker/development-insane/docker-compose.yml
add mysql 8.4 to ci and insane dev environment
=> add mysql 8.4 to ci and insane dev environment

docker/development-insane/docker-compose.yml
chore: add support for alpine 3.20 to insane dev environment
=> chore: add support for alpine 3.20 to insane dev environment

docker/development-insane/README.md
chore: small doc change for alpine 3.20 in insane dev env
=> chore: small doc change for alpine 3.20 in insane dev env

src/Services/DocumentTemplates/DocumentTemplateRender.php
=> fix: create custom temp directory for html purify serializer

ccdaservice/oe-blue-button-generate/index.js, ccdaservice/package-lock.json, ccdaservice/package.json, ccdaservice/serveccda.js, ccdaservice/utils/date/date.js
- refactor formatDate() to include an ISO 8106 reformat causing a moment() warning.
- turn debug off
- bump moment version
- remove unneeded node module directory
Fixes #7528
=> CCDA Service fixes

interface/procedure_tools/labcorp/ereq_form.php, interface/procedure_tools/labcorp/gen_hl7_order.inc.php
Made it so the date collected issue works when doing the manual ereq for labcore.
Fixes #7526
=> Fixes #7526 labcore fix date collected issues

ci/apache_83_1011/docker-compose.yml, ci/apache_83_105/docker-compose.yml, ci/apache_83_106/docker-compose.yml, ci/apache_83_111/docker-compose.yml, ci/apache_83_112/docker-compose.yml, ci/apache_83_114/docker-compose.yml, ci/apache_83_57/docker-compose.yml, ci/apache_83_80/docker-compose.yml, ci/apache_83_84/docker-compose.yml
chore: complete integration of flex-3.20 (alpine 3.20) into ci
=> chore: complete integration of flex-3.20 (alpine 3.20) into ci

.github/workflows/test.yml, CONTRIBUTING.md, ci/apache_81_114/docker-compose.yml, ci/apache_82_114/docker-compose.yml, ci/ciLibrary.source, ci/nginx_81/docker-compose.yml, ci/nginx_82/docker-compose.yml, ci/nginx_83/docker-compose.yml, ci/nginx_84/docker-compose.yml, docker/development-easy-arm/docker-compose.yml, docker/development-easy-light/docker-compose.yml, docker/development-easy/docker-compose.yml, docker/development-insane/README.md, docker/development-insane/docker-compose.yml, docker/production-arm/docker-compose.yml, docker/production/docker-compose.yml
update ci and dev environments to use mariadb 11.4
=> update ci and dev environments to use mariadb 11.4

library/js/nncustom_config.js
- prevent version check.
Fixes #7540 
See issue
=> Annoying CKEditor4 security warning

interface/main/calendar/modules/PostCalendar/pnuser.php, src/Gacl/GaclApi.php
=> Rel 702 bugs

src/Services/Utils/SQLUpgradeService.php
=> fix: migrate table engine array binds

src/Services/Utils/SQLUpgradeService.php
=> fix: migrate table engine array binds (#7566)

src/Services/EncounterService.php
Fixes #7569 where a bug was messing up the form_encounter data.
=> Fix encounter save bug on therapy_group_id #7569

src/Services/ListService.php
Fixes #7570 search for an option by the codes column
=> Fixes #7570 list service search by codes

interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php, library/ajax/specialty_form_ajax.php, library/options.inc.php, src/Services/PatientNameHistoryService.php, src/Services/PatientService.php
Fixes #7568 by refactoring the patient previous name into its own class.
=> Refactor previous name into dedicated service

interface/modules/custom_modules/oe-module-comlink-telehealth/welcome.php
Fixes #7560
Update the support email to contact for telehealth support.
=> Change support desk contact information

docker/development-easy/docker-compose.yml, library/auth.inc.php, sql/7_0_2-to-7_0_3_upgrade.sql, sql/database.sql, src/Common/Session/SessionTracker.php
=> throttling down mechanism

library/auth.inc.php, sql/database.sql, sql/patch.sql, src/Common/Session/SessionTracker.php
=> feat: throttle down mechanism for rel-702 (#7587)

sql/7_0_2-to-7_0_3_upgrade.sql
fix: quick fix upgrade for throttle down feature
=> fix: quick fix upgrade for throttle down feature

interface/modules/custom_modules/oe-module-prior-authorizations/public/reports/list_report.php
=> bug fix #7558

portal/account/index_reset.php, portal/account/register.php, portal/get_patient_documents.php, portal/index.php, templates/portal/home.html.twig, templates/portal/registration/portal_register.html.twig
- missed validation for username length change.
- PHP warnings
Fixes #7599
=> Portal bug fixes and features update

ci/apache_81_114/docker-compose.yml, ci/apache_82_114/docker-compose.yml, ci/apache_83_1011/docker-compose.yml, ci/apache_83_105/docker-compose.yml, ci/apache_83_106/docker-compose.yml, ci/apache_83_111/docker-compose.yml, ci/apache_83_112/docker-compose.yml, ci/apache_83_114/docker-compose.yml, ci/apache_83_57/docker-compose.yml, ci/apache_83_80/docker-compose.yml, ci/apache_83_84/docker-compose.yml, ci/ciLibrary.source, ci/nginx_81/docker-compose.yml, ci/nginx_82/docker-compose.yml, ci/nginx_83/docker-compose.yml, ci/nginx_84/docker-compose.yml
fix: attempt to fix docker compose in ci
=> fix: attempt to fix docker compose in ci

ci/apache_81_1011/docker-compose.yml, ci/apache_82_1010/docker-compose.yml, ci/apache_82_1011/docker-compose.yml, ci/apache_82_104/docker-compose.yml, ci/apache_82_105/docker-compose.yml, ci/apache_82_106/docker-compose.yml, ci/apache_82_110/docker-compose.yml, ci/apache_82_111/docker-compose.yml, ci/apache_82_57/docker-compose.yml, ci/apache_82_80/docker-compose.yml, ci/apache_82_82/docker-compose.yml, ci/ciLibrary.source, ci/nginx_81/docker-compose.yml, ci/nginx_82/docker-compose.yml, ci/nginx_83/docker-compose.yml
fix: fix ci (#7614) in rel-702
=> fix: fix ci (#7614)

templates/portal/home.html.twig
Made it so the payment scripts are disabled if the patient portal Make Online Payment feature is turned off.
Fixes #7620
=> Fixes #7620 disable payment scripts

portal/add_edit_event_user.php
Error in first patient appointment due to php casting errors.
Fixes #7633
=> Fixes #7633 appointment error for first appt

ci/ciLibrary.source
=> bit of future proofing to ci

interface/main/calendar/add_edit_event.php
Typecasting done to avoid "string+integer"
solved #7304
=> solved issue #7304

portal/add_edit_event_user.php, src/Services/AppointmentService.php
Made it so the No Show category type for the calendar is hidden when requesting a new appointment on the patient portal.
Fixes #7640
=> Fixes #7640 patient port no show appt

API_README.md, FHIR_README.md
Fixes #7631 
Update the API_README.md file to match the current menu layout.
Changed every use of the word 'Global' to 'Config'.
=> Fix to 7631 - Update API_README

Documentation/help_files/cms_1500_help.php
=> fixes #7612

interface/globals.php, library/sql.inc.php, sql_upgrade.php, src/Services/Utils/SQLUpgradeService.php
=> fix: Upgrade to v702 fails for really old version

portal/get_patient_documents.php
Changes up get patient documents to do the following. Change verbiage from "Select All Toggle" to "Select All Documents".
Add info message to say zip file will be downloaded
Change category path structure to use folder separator instead of hyphens and fix display if files stored in root category
Fixes #7660
=> Fixes #7660 Download Medical Documents UX fixes

interface/main/messages/messages.php, portal/messaging/messages.php
Made the main clinician messages screen clickable for the entire row. Made it so the entire row shows a cursor icon that its clickable when you hover over it
Portal secure messaging - made the compose message a primary button. Moved the refresh button to the very end of the portal message bar and changed its title to be more descriptive.
Added text to the compose message button to make it more clear what should be done here for better discoverability.
Made the sender/receiver and subject name clickable.
Fixes #7648
=> Fixes #7648 secure messaging

interface/main/messages/messages.php, library/htmlspecialchars.inc.php
I fixed the message casing on the messages so it doesn't look like a SQL statement.  Also saw we were using xls which is deprecated so I cleaned it up everywhere it was being used in the messages.php file.
Fixes #7644
=> Fixes #7644 message casing

interface/billing/sl_receipts_report.php
=> columns need to align left easier to read

interface/reports/custom_report_range.php
=> fix: Custom Reports-Superbill not showing Billing Information

.github/workflows/test.yml, tests/Tests/E2e/CreateStaffTest.php
=> fix: update couple packages in ci

templates/portal/home.html.twig, templates/portal/partial/cards/_appointment_card.html.twig
Changed up the appointments text when there are no appointments.
Also twigify the appointments card list.
Fixes #7652
=> Fixes #7652 portal twigify appointments and no appointments font update

interface/forms/newpatient/templates/report.html.twig, interface/modules/custom_modules/oe-module-faxsms/library/rc_sms_notification.php, library/encounter_events.inc.php, library/globals.inc.php, portal/add_edit_event_user.php, portal/get_patient_documents.php, portal/home.php, src/Services/AppointmentService.php, src/Services/DocumentTemplates/DocumentTemplateRender.php, templates/portal/appointment-item.html.twig, templates/portal/home.html.twig, templates/portal/partial/cards/_appointment_card.html.twig
Fixes #7680
Fixes #7688 
Fixes #7692 
A forum issue brought up by user to restore a legacy use case.
remove purifier global property
new global in Config Calendar `Prevent Appointment Comment as Visit Reason` to prevent using appointment comment as new visit reason.
refactor encounter report twig to have visit reason on it's own line instead of header.
=> Auto-create encounter reason flag and some forgotten fixes.

interface/forms/newpatient/save.php
=> fix: save encounter, hidden visit category

templates/core/about.html.twig
=> update review page

interface/modules/custom_modules/oe-module-ehi-exporter/Readme.md, interface/modules/custom_modules/oe-module-ehi-exporter/openemr.bootstrap.php
=> fix: remove 2015 reference from ehi export

Documentation/EHI_Export/docs/index.html, Documentation/help_files/cqm_amc_help.php
=> fix: remove cpl 2015 references

Documentation/EHI_Export/docs/index.html, Documentation/help_files/cqm_amc_help.php
=> fix: remove cpl 2015 references (#7720) for rel-702

library/globals.inc.php
minor translation constant fix
=> fix: minor translation constant fix

interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php, library/ajax/specialty_form_ajax.php, library/options.inc.php, src/Services/PatientNameHistoryService.php, src/Services/PatientService.php
for rel-702, here's one that has to come back for our billing module, thanks @adunsulag 
Fixes #7568 by refactoring the patient previous name into its own class.
Fixes #
=> Refactor previous name into dedicated service (#7571) for rel-702

src/Billing/X125010837P.php, src/Validators/CoverageValidator.php, src/Validators/PatientValidator.php, tests/Tests/Services/PatientServiceTest.php, tests/Tests/Validators/PatientValidatorTest.php
Fixes #7714 
also fixes a minor but potential php fatal error with int + string
=> feat: allow 1 char first names for insurance subscriber

interface/modules/custom_modules/oe-module-weno/templates/download_log_viewer.php, interface/modules/custom_modules/oe-module-weno/templates/weno_fragment.php, portal/import_template_ui.php, src/Services/DocumentTemplates/DocumentTemplateService.php
=> Some Module Updates

interface/modules/custom_modules/oe-module-weno/templates/download_log_viewer.php, interface/modules/custom_modules/oe-module-weno/templates/weno_fragment.php, portal/import_template_ui.php, src/Services/DocumentTemplates/DocumentTemplateService.php
* Some Module Updates Fix from weno review
* wrong syntax
* add search to portal template maintenance to prevent browser lock up. Max of 5K
* persist selected patients regardless of search term. Must unselect.
(cherry picked from commit 786fe8bc15fd6f6e2c9f3bdf49614490284e566a)
Fixes #
=> Some Module Updates (#7732)

src/Services/AppointmentService.php
In PR 7303 (https://github.com/openemr/openemr/pull/7303) title was added to only the search function, but now it is added to all queries.
Title is added to all queries.
=> Add title to all appointment sql queries

docker/library/dockers/dev-php-fpm-8-1-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-1/Dockerfile, docker/library/dockers/dev-php-fpm-8-2-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-2/Dockerfile, docker/library/dockers/dev-php-fpm-8-3-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-3/Dockerfile, docker/library/dockers/dev-php-fpm-8-4-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-4/Dockerfile
support ccda in nginx ci dockers
=> fix: support ccda in nginx ci dockers

docker/library/dockers/dev-php-fpm-8-3-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-3/Dockerfile, docker/library/dockers/dev-php-fpm-8-4-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-4/Dockerfile
another fix for nginx based testing ci dockers
=> fix: another fix for nginx based testing ci dockers

docker/library/dockers/dev-php-fpm-8-3-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-3/Dockerfile, docker/library/dockers/dev-php-fpm-8-4-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-4/Dockerfile
hopefully last fix for nginx containers
=> fix: hopefully last fix for nginx containers

docker/library/dockers/dev-php-fpm-8-3-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-3/Dockerfile, docker/library/dockers/dev-php-fpm-8-4-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-4/Dockerfile
=> fix: one more fix for nginx ci

docker/library/dockers/dev-php-fpm-8-4-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-4/Dockerfile
=> fix: another nginx ci fix

interface/billing/billing_report.php, interface/modules/custom_modules/oe-module-faxsms/library/rc_sms_notification.php, interface/patient_file/history/encounters.php
fix billing managers toencounter and topatient.
check and set if passed in pid not current for encounter history
Minor stuff but thought provoking when looking into our tabs and patient view models!
Fixes #7752
=> Billing Manager and Some Module fixes

.github/workflows/test.yml, ci/ciLibrary.source, ci/nginx/nginx.conf, interface/reports/unique_seen_patients_report.php, tests/Tests/E2e/CheckMainMenuLinksTest.php, tests/Tests/E2e/CheckUserMenuLinksTest.php, tests/Tests/E2e/CreateStaffTest.php, tests/Tests/E2e/LoginTest.php, tests/Tests/E2e/Pages/LoginPage.php, tests/Tests/E2e/Pages/MainPage.php, tests/Tests/E2e/Pages/UsersTab.php
feat: add e2e testing for both menu links. Also fixed some e2e stuff.
=> feat: add e2e testing for both menu links. Also fixed some e2e stuff.

interface/forms/questionnaire_assessments/questionnaire_assessments.php, interface/forms/questionnaire_assessments/save.php, interface/modules/custom_modules/oe-module-faxsms/library/rc_sms_notification.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/AppDispatch.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/RCFaxClient.php, interface/modules/custom_modules/oe-module-weno/src/Services/LogDataInsert.php, interface/modules/custom_modules/oe-module-weno/src/Services/LogImportBuild.php, interface/modules/custom_modules/oe-module-weno/src/Services/TransmitProperties.php, interface/modules/custom_modules/oe-module-weno/templates/weno_fragment.php, interface/modules/custom_modules/oe-module-weno/templates/weno_users.php, interface/patient_file/summary/demographics.php, interface/super/edit_list.php, interface/usergroup/user_admin.php, portal/import_template.php, portal/index.php, portal/lib/doc_lib.php, portal/lib/download_template.php, portal/patient/libs/Controller/AppBasePortalController.php, portal/patient/libs/Controller/OnsiteDocumentController.php, portal/patient/scripts/app/onsiteactivityviews.js, portal/patient/scripts/app/onsitedocuments.js, portal/patient/scripts/view.js, portal/patient/templates/OnsiteActivityViewListView.tpl.php, portal/patient/templates/OnsiteDocumentListView.tpl.php, portal/patient/templates/PatientListView.tpl.php, portal/report/pat_ledger.php, src/Services/DocumentTemplates/DocumentTemplateService.php, src/Services/QuestionnaireService.php, templates/login/base.html.twig, templates/login/partials/input/password.html.twig
- add update to log sync for erx changes
- rename Weno Provider ID to  Weno User ID in Users
Fixes #7758 
for patch 2
=> More Changes and Fixes Modules

tests/Tests/E2e/IiPatientContextMainMenuLinksTest.php, tests/Tests/E2e/User/UserAddTrait.php
=> fix: couple e2e ci fixes

interface/patient_file/encounter/forms.php, library/options.inc.php, src/Billing/EDI270.php, templates/x12_partners/general_edit.html
This is actually a pretty nice and still useful feature. 
Thanks for the help @stephenwaite 
Fixes #7773 
Fixes #7308 
Fixes #7776 
Change eligibility password and login to use SFTP inputs. 
Rework MIME parsing.
Fix conditional preventing any request calls.
Fix default unassigned for multi select if not empty.
=> Eligibility Fixes

interface/patient_file/encounter/forms.php, library/options.inc.php, src/Billing/EDI270.php, templates/x12_partners/general_edit.html
* Eligibility Fixes Change eligibilty password and login to use SFTP inputs. Rework MIME parsing.
Fix conditional preventing any request calls.
* Prevent auto select unassigned for multiselect if other items are selected. i.e only select for empty selects.
* add title for review encounters
* refactor out oeHttp
(cherry picked from commit 13d17525381c29bb567ad9ca8f25af44564fbcba)
Fixes #
=> Patch 2 rel-702

version.php
=> prepare for patch2

CHANGELOG.md
=> feat: update CHANGELOG for 7.0.2.2

tests/Tests/E2e/GgUserMenuLinksTest.php, tests/Tests/E2e/HhMainMenuLinksTest.php, tests/Tests/E2e/IiPatientContextMainMenuLinksTest.php, tests/Tests/E2e/JjEncounterContextMainMenuLinksTest.php, tests/Tests/E2e/Patient/PatientAddTrait.php, tests/Tests/E2e/User/UserAddTrait.php
=> fix: e2e ci misc fixes

interface/patient_file/summary/demographics.php
=> fix: firefox close dialog from cdr edit source

library/js/utility.js
related to prev closed issue #7787
=> fix: firefox close dialog from smart dsi edit source

index.php, library/dialog.js, portal/sign/assets/signer_api.js, src/Services/LogoService.php, templates/portal/partial/reports/patient_report/_head.html.twig
Add style to dialog Alert and Confirm
Fixes #7792 
Fixes #7800 
Fix questionnaires dialog alert styles defaults
Fix portal theme using main theme
=> Dialog styles

interface/modules/custom_modules/oe-module-prior-authorizations/public/patient_menu/custom_patient_menu.json
=> fix: correct link to patient report in prior auth module

interface/usergroup/addrbook_edit.php
=> fix: allow delete from addr book when username is null

interface/main/onotes/office_comments.php, interface/main/onotes/office_comments_full.php, src/Services/ONoteService.php
have dates include as time stamps
restyle tables and add modals for delete and edit.
Fixes #7811
=> Add new actions delete and edit to Office Notes

controllers/C_Document.class.php, library/ajax/document_helpers.php, portal/import_template_ui.php, portal/patient/libs/Controller/OnsiteDocumentController.php, portal/patient/templates/OnsiteDocumentListView.tpl.php, portal/report/portal_patient_report.php, templates/documents/general_list.html, tests/Tests/E2e/HhMainMenuLinksTest.php
refactor the patient id select
add logic to controller
ensure presistence when using Document Templates.
add a flag to note if portal is called from New Documents
Fixes #7812
=> New Documents Update and fix

interface/patient_file/transaction/print_referral.php, sites/default/referral_template.html
Fixes #7824
Add the date of birth to the referral form, as it is expected by many providers.
=> Include DOB in referral template.

src/Controllers/Portal/PortalPatientReportController.php, templates/portal/partial/reports/patient_report/_procedure_orders.html.twig
Made it so we handle the procedures list if there are no procedures present.
Fixes #7814.
=> Fixes #7814 empty procedures error. (#7816)

src/ClinicalDecisionRules/Interface/Controller/ControllerReview.php
Was using the wrong class if the CSRF was invalid.
Fixes #7832
=> Fix invalid CSRF exception class.

src/ClinicalDecisionRules/Interface/Controller/ControllerReview.php
Was using the wrong class if the CSRF was invalid.
Fixes #7832
=> Fix invalid CSRF exception class. (#7833)

portal/sign/assets/signer_api.js, portal/sign/assets/signer_modal.php, templates/portal/home.html.twig
fix anchor syntax
fix audience name in dialog
Fixes #7835
=> Fix Portal Default Signer

CHANGELOG.md
fixes #7842 
add 7.0.2.3 patch
=> change log patch 3

interface/modules/custom_modules/oe-module-prior-authorizations/openemr.bootstrap.php, src/Menu/PatientMenuRole.php
=> fix: broken patient menu dashboard links prior auth module

ccdaservice/package-lock.json, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
=> fix: calendar event edit provider out of office php math error

interface/main/calendar/find_patient_popup.php, interface/modules/custom_modules/oe-module-faxsms/contact.php, interface/modules/custom_modules/oe-module-faxsms/messageUI.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/ClickatellSMSClient.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/EmailClient.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/EtherFaxActions.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/TwilioSMSClient.php, interface/modules/custom_modules/oe-module-faxsms/src/Events/NotificationEventListener.php, src/Events/Messaging/SendNotificationEvent.php, src/Events/Messaging/SendSmsEvent.php
status needs to preserve html for display
missed endings for refactor escaping and translations.
Fixes #7876
=> Quick escape issues fix

.github/workflows/build-dev-php-fpm-docker.yml, .github/workflows/weekly-build-php-fpm-dockers.yml
=> minor ci update fix

.github/workflows/build-dev-php-fpm-docker.yml
ci minor fix to avoid conflicts with automated docker builds
=> ci minor fix to avoid conflicts with automated docker builds

interface/billing/billing_report.php, interface/main/tabs/js/frame_proxies.js, interface/main/tabs/main.php, library/ajax/set_pt.php
Fixes #7874 
- create async/await functionality to make bit more synchronous
- new async loadtab function.
- added javascript function in top to fetch session key/value pairs.
=> The toencounter and toinsurance issue.

CONTRIBUTING.md
=> chore: add testing 8.4 to contributing guide

controllers/C_Document.class.php, custom/code_types.inc.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Factory/EncounterccdadispatchControllerFactory.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceRequestModelGenerator.php, interface/modules/zend_modules/module/Installer/src/Installer/Model/InstModuleTableGateway.php, interface/modules/zend_modules/module/Syndromicsurveillance/src/Syndromicsurveillance/Controller/SyndromicsurveillanceController.php, interface/patient_file/encounter/forms.php, library/ESign/Abstract/Model.php, library/ESign/ButtonIF.php, library/ESign/Encounter/Button.php, library/ESign/Form/Button.php, library/ESign/Viewer.php, library/classes/InsuranceCompany.class.php, library/classes/Pharmacy.class.php, library/clinical_rules.php, library/dicom_frame.php, portal/lib/appsql.class.php, portal/patient/fwk/libs/verysimple/Phreeze/DataAdapter.php, portal/patient/fwk/libs/verysimple/Phreeze/PortalController.php, src/Billing/BillingUtilities.php, src/Common/Session/SessionUtil.php, src/Common/Twig/TwigContainer.php, src/Cqm/CqmClient.php, src/Events/RestApiExtend/RestApiSecurityCheckEvent.php, src/Services/PatientService.php, tests/old_unit_dir/code_types/MultipleTests.php
=> fix: fixes for php 8.4

src/Services/AppointmentService.php
Multiple provider feature appointment delete issue
Fixes #
=> Multiple provider feature appointment delete issue

contrib/forms/scanned_notes/new.php, library/js/utility.js, library/sanitize.inc.php
mostly refactor form and add correct form actions. remove empty check in sanitize check_file_dir_name() method. Caused string '0' label to fail also empty string which is acceptable.
Fixes #7888
=> Fix and refactor contrib form scanned_notes.

src/Reports/RealWorldTesting.php
fix direct message log reporting
=> fix: fix direct message log reporting

composer.json, composer.lock
=> feat: package upgrade phpspreadsheet

interface/forms/eye_mag/php/eye_mag_functions.php, interface/forms/eye_mag/save.php, interface/forms/eye_mag/view.php
=> fix: php8 errors in eye form

interface/forms/questionnaire_assessments/questionnaire_assessments.php
Follow forms admin acl settings
Fixes #7942
=> Questionnaire Permission fix

library/patient.inc.php
Fixes #
Added a fax number to the report at Patient --> Dashboard --> Report 
When printing /faxing report it is nice to have the facility fax number present with the phone and address
Add a fax number on the top of the report
=> Update patient.inc.php to add fax number to the first page of the report

sql/7_0_3-to-7_0_4_upgrade.sql, version.php
change dev version to 7.0.4-dev
=> change dev version to 7.0.4-dev

CONTRIBUTING.md, docker/library/dockers/dev-php-fpm/README
documentation for dev stuff update
=> documentation for dev stuff update

config/config.yaml, interface/billing/billing_tracker.php, library/ajax/billing_tracker_ajax.php, templates/patient/insurance/insurance_edit.html.twig, templates/portal/base.html.twig
=> fix: format the billing tracker dates with js in datatables display

library/patient.inc.php
=> fix: remove stmt count from get_patient_balance()

package-lock.json, package.json
=> feat: ckeditor5 upgrade

docker/development-insane/README.md, docker/development-insane/docker-compose.yml
insane dev env support for alpine 3.21
=> insane dev env support for alpine 3.21

interface/forms/newpatient/save.php, interface/patient_file/summary/add_edit_issue.php, src/Services/EncounterService.php, src/Services/MedicationPatientIssueService.php, src/Services/PatientIssuesService.php, src/Services/SocialHistoryService.php, src/Services/Traits/ServiceEventTrait.php, src/Services/VitalsService.php
Fixes #7982 allow module writers to hook into new/update encounter operations on both form and from encounter service
Fixes #7983 fix issues not being removed when all de-selected in encounter screen gui
Fixes #7984 fix encounter issue not being linked when first creating issue.
I added a new ServiceEventTrait that can be used to quickly add in the dispatchSaveEvent method to services so module writers can hook into it.
=> Feat openemr #7982 #7983 #7984 newpatient encounter save refactors and bug fixes.

interface/reports/sales_by_item.php
=> fix: default units to 1 for sales by item report

interface/billing/billing_report.php, library/ajax/set_pt.php
=> fix: whitelist session pid setting pt from billing manager

interface/reports/appointments_report.php
Fixes #7977
add provider name to csv file on appointments report
add the providers first name and last name (ufname, ulname) to the list of fields  to put into the cvs file
No
=> add provider to csv file

interface/patient_file/manage_dup_patients.php
adjust data set weights
Fixes #7966
=> Refactor and improve Manage Duplicates

contrib/portal_templates/assessments/SDC FHIR/After_Visit_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/Back_Pain_History_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/Back_Pain_Impact_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/Back_Pain_Severity_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/Follow_Up_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/Full_Assessments.json, contrib/portal_templates/assessments/SDC FHIR/Impact_of_Back_Pain_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/Medical_History_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/PROMIS_Anxiety_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/PROMIS_Depression_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/PROMIS_Interference_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/PROMIS_Physical_Activity_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/PROMIS_Physical_Function_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/PROMIS_Sleep_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/Pain_Initial_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/Safety_Outcomes_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/Shared_Decision_Making_Assessment.json, contrib/portal_templates/assessments/SDC FHIR/Social_Factors_Assessment.json, contrib/util/ccda_import/import_ccda.php, interface/patient_file/manage_dup_patients.php, library/dupscore.inc.php, src/Services/Cda/CdaComponentParseHelpers.php, src/Services/Cda/CdaTemplateImportDispose.php
=> Rel 703 jerry

library/user.inc.php, src/OeUI/OemrUI.php, src/Services/Globals/UserSettingsService.php, templates/core/base.html.twig
Make it so the expandable_files setting works properly by calling into
the new UserSettingsService.
Deprecated the functions in user.inc.php and made those functions call
into the new class so there'd be no disruption in the system.
Fixes #7990
Implemented a helper base file that everything can use to implement the
OemrUI settings piece for expand/collapse and formatting.
Provided a default settings page.
=> Bug openemr #7990 oemr UI

src/Common/Forms/FormReportRenderer.php
Fixes #8007 by using include_once instead of just include.
=> Fixes #8007 duplicate fatal error

interface/forms/newpatient/C_EncounterVisitForm.class.php
Fixes #8005 javascript uuid encoding issue with new encounter.
This will also need to be backported into rel-703.
=> Fix javascript uuid encoding issue with encounter

interface/patient_file/encounter/superbill_custom_full.php
Fixes #7946
The issue with adding multiple payers and being able to see all of them
The related column was missing. 
Made the header sticky.
See Issue for before and after pictures.
No
=> Beautification project codes page

interface/patient_file/encounter/superbill_custom_full.php
Beautification project codes page for rel-703
=> Beautification project codes page (#7947)

tests/Tests/E2e/HhMainMenuLinksTest.php
=> ci e2e fixup for php 8.1

tests/Tests/E2e/HhMainMenuLinksTest.php
ci e2e fixup for php 8.1/8.2 on rel-703
=> ci e2e fixup for php 8.1/8.2 (#8019)

tests/Tests/E2e/Base/BaseTrait.php, tests/Tests/E2e/User/UserAddTrait.php, tests/Tests/E2e/Xpaths/XpathsConstantsUserAddTrait.php
=> fix ci e2e for add user test

tests/Tests/E2e/Base/BaseTrait.php, tests/Tests/E2e/User/UserAddTrait.php, tests/Tests/E2e/Xpaths/XpathsConstantsUserAddTrait.php
fix ci e2e for add user test and add patient test
=> fix ci e2e for add user test and add patient test (#8021)

interface/forms/newpatient/templates/newpatient/partials/common/_head.html.twig
=> fix missing webroot

interface/billing/billing_report.php, interface/forms/newpatient/templates/newpatient/partials/common/_head.html.twig, interface/reports/sales_by_item.php, library/ajax/set_pt.php
=> fix webroot, sales item report, set pt for rel-703

.github/workflows/test.yml, composer.lock, tests/Tests/E2e/Patient/PatientAddTrait.php, tests/Tests/E2e/Xpaths/XpathsConstantsPatientAddTrait.php
another e2e ci fix
WORK IN PROGRESS
=> another e2e ci fix

.github/workflows/test.yml, composer.lock, tests/Tests/E2e/Patient/PatientAddTrait.php, tests/Tests/E2e/Xpaths/XpathsConstantsPatientAddTrait.php
=> More ci e2e fixes 

interface/code_systems/list_staged.php
Update to support the 2024 file naming convention for us snomed-ct
Fixes #7976
=> Fixes #7976 snomed us edition file format change

interface/forms/eye_mag/css/style.css, interface/forms/eye_mag/report.php, src/Common/Forms/FormReportRenderer.php
=> fix: global eye form folder

interface/forms/eye_mag/view.php
=> quick styling fix

interface/forms/eye_mag/css/style.css, interface/forms/eye_mag/report.php, interface/forms/eye_mag/view.php, library/MedEx/API.php
=> Ray's fixes for eye form and MedEx for rel 703

tests/Tests/E2e/Patient/PatientAddTrait.php
=> fix: e2e ci fix for patient add

package-lock.json, package.json
chore(deps): bump dompurify from 3.2.3 to 3.2.4 (#8036) for rel-703
=> chore(deps): bump dompurify from 3.2.3 to 3.2.4 (#8036)

src/Common/Auth/OAuth2KeyConfig.php
- Add methods to support keys verification and creations
Fixes #8069
validate api key creation
- Add methods to support keys verification and creations
=> FHIR and API's auth keys verification

src/Reports/RealWorldTesting.php
fix broken real world testing report 2025 if certain module not installed
=> fix: broken real world testing report 2025 if certain module not installed

interface/forms/vitals/templates/vitals/vitals.html.twig, interface/forms/vitals/vitals.js, library/dicom_frame.php, src/Common/Auth/OAuth2KeyConfig.php, src/Services/Traits/ServiceEventTrait.php, src/Services/VitalsService.php
* Refactor Vitals form save refactor saveVitalsArray to create new form_vitals first to get new id then create the forms record. Removes the reliance on sequence value. fix doc block entry for event trait.
* style booboo
* fix save details to return correct array
* fix some id names for usa fix validation error on save to a clean return back to form.
* fix mislabeled id names
(cherry picked from commit a568481c31964e737caa8abaffc5b5a769d414f0)
Fixes #
=> Refactor Vitals form save (#8052)

src/Reports/RealWorldTesting.php
fix: broken real world testing report 2025 if certain module not installed for rel-703
=> fix: broken real world testing report 2025 if certain module not installed (#8071)

interface/reports/appointments_report.php, library/appointments.inc.php
Fixes #8061
In the report->visits->appointments
optionally display the patients' address in the report
select more than one provider, or all and display all their appointments
have a checkbox which when ticked displays patients' address in the report
in the provider drop down menu, be able to select more than one provider, or all providers, and display all their appointments
no
=> Improve appointment report

interface/globals.php, library/globals.inc.php, src/Common/Logging/EventAuditLogger.php
Log http requests and additional data.
=> Bug Fixes, Log Improvements

interface/billing/sl_receipts_report.php
Fixes #8044 
adds entry date as another option
=> feat: add entry date option to cash receipts

interface/billing/sl_receipts_report.php
=> feat: add entry date option to cash receipts (#8080) for rel-703

library/user.inc.php
Looks like the home dashboard page was not collapsing properly due to a bug in the refactor of cac171e where the wrong function was being called.
Fixes #8105
=> Fixes #8105 collapsing home dashboard

interface/forms/newpatient/C_EncounterVisitForm.class.php, src/Common/Logging/EventAuditLogger.php
=> fix: encounter edit referring provider selection

sql/7_0_3-to-7_0_4_upgrade.sql, sql/database.sql, version.php
- three new columns.
- bump version
Fixes #8097
=> Update onetime_auth table and database for new onetime features

library/globals.inc.php
OAuth2 EHR-Launch Authorization Flow Skip Enable App Setting - set default to On
=> OAuth2 EHR-Launch Authorization Flow Skip Enable App Setting - set default to On

library/globals.inc.php
rel-703 OAuth2 EHR-Launch Authorization Flow Skip Enable App Setting - set default to On (#8119)
=> OAuth2 EHR-Launch Authorization Flow Skip Enable App Setting - set default to On (#8119)

library/classes/postmaster.php, src/Common/Auth/AuthUtils.php
update postmaster and AuthUtils for deprecated code and class structure.
Fixes #8082 
Sending email notifications for user password issues.
cleanup some existing classes for deprecated code and class structure
add a hook to add to email queue.
- Still testing to verify these changes.
=> Schedule email notifications

ccdaservice/package-lock.json, composer.json, composer.lock
=> feat: bump ring central package

interface/forms/CAMOS/new.php, library/htmlspecialchars.inc.php
fix: camos related fixes
Testing well.
=> fix: camos related fixes

interface/forms/CAMOS/new.php, library/htmlspecialchars.inc.php
fix: camos related fixes (#8144)
=> fix: camos related fixes (#8144)

interface/billing/sl_receipts_report.php, interface/forms/eye_mag/js/eye_base.php, interface/forms/eye_mag/save.php, interface/forms/eye_mag/view.php
=> fix: eye form IOP times

interface/forms/eye_mag/SpectacleRx.php, interface/forms/eye_mag/js/eye_base.php, interface/forms/eye_mag/php/eye_mag_functions.php, interface/forms/eye_mag/save.php, interface/forms/eye_mag/view.php
=> Eye form commits rel 703

_rest_routes.inc.php, composer.json, swagger/openemr-api.yaml
=> chore: 7.0.4-dev updates

interface/globals.php
fix: login language menu selector was not showing up
fixes #8158
=> fix: login language menu selector was not showing up

interface/globals.php
for rel-703
fix: login language menu selector was not showing up
=> fix: rel-703 login language menu selector was not showing up

CHANGELOG.md
=> update changelog for 7.0.3

docker/production-arm/docker-compose.yml, docker/production/docker-compose.yml
update production docker compose for rel-703
=> update production docker compose for rel-703

docker/production-arm/docker-compose.yml, docker/production/docker-compose.yml
update production docker compose
=> update production docker compose

config/config.yaml, interface/billing/billing_tracker.php, interface/main/tabs/main.php, library/ajax/billing_tracker_ajax.php, library/js/xl/formatting.js, portal/home.php, templates/core/base.html.twig, templates/patient/insurance/insurance_edit.html.twig, templates/portal/base.html.twig, templates/portal/home.html.twig
Release for 7.0.3.1
Brings in #7955 billing tracker dates
Brings in #8174 which fixes date usage of encounters that aren't YYYY-MM-DD format.
=> Rel 703 pr backport of #7955 and #8174

interface/reports/pat_ledger.php
=> fix: pt ledger ins co name detail

version.php
rel-703
chore: increment v_js_includes
=> chore: increment v_js_includes for rel-703

controllers/C_Document.class.php
=> fix: fix code styling issues

controllers/C_Document.class.php
rel-703
fix: fix code styling issues
=> fix: fix code styling issues (#8198)

version.php
=> chore: prep 7.0.3.1

CHANGELOG.md
=> chore: changelog for 7.0.3.1

interface/reports/pat_ledger.php, library/js/oeUI/insurance/EditPolicyScreenController.js
=> rel-703 backport for PRs #8181 #8175 #8171

library/ESign/Signature.php
rel-703
Show e-sign amendment.
=> Show e-sign amendment. Fixes #8205 (#8206) for rel-703

interface/modules/custom_modules/oe-module-faxsms/messageUI.php, package-lock.json, package.json
tested jspdf library version update to 3.0.1
Fixes #8209 
Replaced and testing well
=> replace tiff.js with utif2 for fax

version.php
=> chore : prep 7.0.3.2

interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
rel-703
adding minimum height for all appts under 15 minutes for all categories (#8171)
=> adding minimum height for all appts under 15 minutes for all categories (#8171)

docker/production/docker-compose.yml
=> restore docker compose yml version for rel-703 production

version.php
=> chore : prep 7.0.3.3

CHANGELOG.md
=> chore: changelog for 7.0.3.3

templates/portal/home.html.twig
rel-703
fixes #8178
fixing issue of allow_custom_report being treated as a string instead of global
=> fixing issue of allow_custom_report being treated as a string instead of global (#8223)

src/Services/VitalsService.php
Fixes the duplicate entry problem in the vital sign services.
Fixes #8207
=> Fixes #8207 vital sign api duplicates

.gitignore, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day_print/outlook_ajax_template.html, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month_print/outlook_ajax_template.html, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html, interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week_print/outlook_ajax_template.html, interface/main/calendar/modules/PostCalendar/pnuserapi.php, library/globals.inc.php
Fixes #8228
show a patient's address in the appointment information on the calendar view and in the print out if requested
a new configuration value for 'config_>calendar->appointment display style' which displays 'last name, first name, address (Comments
This has value '5' in the GLOBAL config field calendar_appt_style
when this value is set the patient's address is displayed along side their full name, and also on the print out if requested
No
=> show a patient's address in the appointment information on the calendar view

interface/main/calendar/modules/PostCalendar/pntemplates/default/user/ajax_search.html
https://github.com/openemr/openemr/issues/8241
Fixes #8241
The calendar search form is generally quite confusing and not intuitive. Could definitely use some work on usability. 
1. Added help text for the Keywords and AND/OR fields
2. Moved the AND/OR field next to Keywords field so it's clearer what it's for
3. Disabled the AND/OR field until user inputs two or more words in the Keywords field
4. Added 'Enter' to search feature
5. Added Reset/Clear button feature
6. Added hover effect to search results to show that it's clickable
No
=> Improving calendar search UI

docker/development-easy-arm/docker-compose.yml, docker/development-easy-light/docker-compose.yml, docker/development-easy/docker-compose.yml, docker/development-insane/docker-compose.yml, docker/production/docker-compose.yml
=> fix: remove docker-compose attribute version

interface/modules/custom_modules/oe-module-faxsms/library/rc_sms_notification.php, interface/modules/custom_modules/oe-module-faxsms/library/run_notifications.php, interface/modules/custom_modules/oe-module-faxsms/library/setup_services.php, interface/modules/custom_modules/oe-module-faxsms/messageUI.php, interface/modules/custom_modules/oe-module-faxsms/setup_rc.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/AppDispatch.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/NotificationTaskManager.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/RCFaxClient.php, interface/modules/custom_modules/oe-module-faxsms/src/Controller/TwilioSMSClient.php, interface/modules/custom_modules/oe-module-faxsms/version.php
Fix the SMS call log fetch
Fix actions i.e. show text message and reply
error handling
Fixes #8311 
Fixes #8312 
Fix SMS for RC
Fix login auth
Fix message reply option
=> Ring Central faxsms update

apis/dispatch.php, portal/home.php, portal/lib/track_portal_events.php, src/Services/ProductRegistrationService.php, src/Telemetry/BackgroundTaskManager.php, src/Telemetry/TelemetryRepository.php, src/Telemetry/TelemetryService.php, templates/portal/home.html.twig
add portal dashboard card click events for tracking 
fix allowTelemetry logic
Fixes #8332
=> Telemetry portal tracking events

interface/main/calendar/add_edit_event.php, library/validation/validation_script.js.php
https://github.com/https://github.com/openemr/openemr/issues/8182
https://github.com/https://github.com/openemr/openemr/issues/8185
**This pull request combines pull requests #8183 and #8186 to fix the conflicts**
Fixes #8182 and #8185 
See above
See above
No
=> Adding validation and disabling duration for in office events

interface/patient_file/summary/stats_full.php
button had wrong closing tag of anchor
fix input endings
Fixes #8341
=> Syntax error in stats_full script

src/Core/ModulesApplication.php
Disable in table after 3 attempts.
Fixes #8349
=> Disable unruly modules on start

interface/forms/procedure_order/common.php
Going to leave open for a bit in case I run into something else.
Fixes #
=> quick escape fix DORN

sql/7_0_3-to-7_0_4_upgrade.sql, sql/database.sql, version.php
add additional col event_url to unique key. key is now event_label, event_url
Fixes #8354 
sql duplicate errors.
=> Fix sql error track events

apis/dispatch.php, interface/patient_file/encounter/load_form.php, sql/7_0_3-to-7_0_4_upgrade.sql, sql/database.sql, version.php
add user role in place of scopes for api tracking
Fixes #8354
=> Reindex, Remove scopes, Add encounter forms

apis/dispatch.php, interface/patient_file/encounter/load_form.php, sql/database.sql, sql/patch.sql, version.php
Fixes #
Separate PR for 7.0.3 database mods from master.
=> patch 4 backport of telemetry fix for track event duplication error

setup.php, src/Core/ModulesApplication.php
Staging for patch 4, PART 2
--- 
TODO:
EMPTY
---
MILESTONE:
https://github.com/openemr/openemr/milestone/21
---
CRITICAL TAGS THAT USING TO TRACK (ie. please do not modify these while patch build ongoing):
- https://github.com/openemr/openemr/issues?q=label%3A%22Status%3A%20Needs%20Release%20Merge%22
- https://github.com/openemr/openemr/issues?q=%20label%3ASTAGED
- https://github.com/openemr/openemr/issues?q=%20label%3A%22MERGE%20CONFLICT%22
- https://github.com/openemr/openemr/issues?q=%20label%3A%22DATABASE%20CHANGES%22
- https://github.com/openemr/openemr/issues?q=%20label%3ABUMP-NEXT-PATCH
---
UP FOR GRABS demo:
not planned
---
=> Staging for patch 4, PART 2

src/Telemetry/TelemetryService.php
=> fix: do not send usage report if telemetry is turned off

CHANGELOG.md
=> changelog for 7.0.3.4

interface/forms/procedure_order/common.php, interface/modules/custom_modules/oe-module-dorn/public/lab_setup.php, interface/modules/custom_modules/oe-module-dorn/public/orders.php, interface/modules/custom_modules/oe-module-dorn/src/DornGenHl7Order.php, interface/modules/custom_modules/oe-module-dorn/src/ReceiveHl7Results.php, interface/orders/types.php, interface/patient_file/encounter/load_form.php
Using wrong return log for transmit response.
DORN requires GT1 for third party.
Fixes #8347
poor logging causing wrong status info.
insurance GT1 segment missing for third party. spec says optional but DORN wants. Still need to test if required for bill clinic.
=> DORN logging and insurance issues continues issue coverage.

interface/modules/custom_modules/oe-module-prior-authorizations/public/deleter.php, interface/modules/custom_modules/oe-module-prior-authorizations/public/index.php, interface/modules/custom_modules/oe-module-prior-authorizations/public/reports/list_report.php, interface/modules/custom_modules/oe-module-prior-authorizations/src/Controller/AuthorizationService.php, interface/modules/custom_modules/oe-module-prior-authorizations/src/Controller/ListAuthorizations.php
=> chore: Advance Prior Auth - Code enhancements to  meet PHP coding standards. 

interface/patient_tracker/patient_tracker.php
=> fix: bad date format for pt tracker

interface/billing/sl_eob_process.php
=> fix: EOB posting php8 fatal error

interface/patient_file/encounter/trend_form.php
Fixes #
Vitals Graph Issue - raised in OpenEMR Forum link - https://community.open-emr.org/t/amount-in-vitals-charts/25581
=> Vitals Graph Fix

.github/workflows/test.yml, ci/README.md, ci/apache_82_114/docker-compose.yml, ci/apache_83_114/docker-compose.yml, ci/apache_84_1011/docker-compose.yml, ci/apache_84_105/docker-compose.yml, ci/apache_84_106/docker-compose.yml, ci/apache_84_114/docker-compose.yml, ci/apache_84_116/docker-compose.yml, ci/apache_84_57/docker-compose.yml, ci/apache_84_80/docker-compose.yml, ci/apache_84_84/docker-compose.yml, ci/ciLibrary.source, ci/compose-shared-apache.yml, ci/compose-shared-mariadb.yml, ci/compose-shared-mysql.yml, ci/compose-shared-nginx.yml, ci/nginx_82/docker-compose.yml, ci/nginx_83_no-e2e/docker-compose.yml, ci/nginx_84_no-e2e/docker-compose.yml, ci/nginx_85/docker-compose.yml
fixes #8426
This is more of a "see what happens" PR. Just seeing if using include in the docker-compose stuff for ci is possible. Good chance I have done this all wrong and all testing will fail :)
=> feat: incorporate multi-file composition with ci docker test environments

CONTRIBUTING.md
=> doc(CONTRIBUTING): simplify rector compose commands

.github/workflows/rector.yml, interface/forms/eye_mag/php/eye_mag_functions.php, interface/main/finder/dynamic_finder.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php, interface/patient_file/front_payment.php, library/custom_template/personalize.php, portal/import_template_ui.php, src/Gacl/GaclApi.php, tests/Tests/Fixtures/FixtureManagerTest.php
=> chore: remove perms on rector workflow

tests/Tests/Unit/Services/LogoServiceTest.php
=> fix: rector fix in tests/Tests/Unit/Services/LogoServiceTest.php

.github/workflows/build-dev-php-fpm-docker.yml
=> fix(ci): fix openemr/dev-php-fpm:pre-build-dev-85 docker

interface/main/calendar/includes/pnHTML.php, interface/modules/zend_modules/module/Application/src/Application/Model/ApplicationTable.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php, portal/lib/appsql.class.php
Fixes #8595
Fix typo: retrive -> retrieve
Just typo fixes
=> fix(spelling): s/retrive/retrieve/

.github/workflows/inferno-test.yml, tests/Tests/E2e/User/UserAddTrait.php
=> fix(ci):fix edge case in functional testing when adding user and fix inferno skipping logic

interface/modules/custom_modules/oe-module-weno/ModuleManagerListener.php, interface/modules/custom_modules/oe-module-weno/info.txt, interface/modules/custom_modules/oe-module-weno/scripts/weno_log_sync.php, interface/modules/custom_modules/oe-module-weno/scripts/weno_pharmacy_search.php, interface/modules/custom_modules/oe-module-weno/src/Bootstrap.php, interface/modules/custom_modules/oe-module-weno/templates/indexrx.php, interface/modules/custom_modules/oe-module-weno/templates/weno_fragment.php, interface/modules/custom_modules/oe-module-weno/version.php
Fixes #8530
fix when to show widget in dashboard and give alert on how to enable.
ensure module is enabled on background tasks
Remove naughty datetime query in search pharmacies
=> Weno Fixes Enhancements.

.gitmodules
=> chore: migrated onc-certification-g10-test-kit repo to openemr org

library/calendar.inc.php, library/edihistory/edih_835_html.php
=> fix: couple function void fixes

rector.php, tests/Tests/Unit/Common/Auth/OpenIDConnect/Grant/CustomClientCredentialsGrantTest.php
- **chore(rector): set to level 3**
- **refactor(rector): apply level 3**
=> refactor(rector): apply level 3

contrib/util/de_identification_upgrade.php, interface/forms/eye_mag/php/taskman_functions.php, interface/forms/eye_mag/view.php, interface/patient_tracker/patient_tracker.php, interface/usergroup/facility_user_admin.php, library/options.inc.php, portal/import_template.php, src/Common/Logging/EventAuditLogger.php
=> fix(phpstan): don't use the return value of void

interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php, interface/patient_file/history/edit_billnote.php, interface/patient_file/history/encounters.php, library/classes/php-barcode.php, library/edihistory/edih_segments.php, library/patient.inc.php, library/smarty_legacy/smarty/Smarty_Legacy.class.php, rector.php, src/Services/Cda/CdaTemplateImportDispose.php, src/Services/UserService.php, tests/Tests/Unit/ClinicalDecisionRules/ControllerEditTest.php, tests/Tests/Unit/FHIR/SMART/ClientAdminControllerTest.php, tests/Tests/Unit/FHIR/SMART/ExternalClinicalDecisionSupport/RouteControllerTest.php
Bump rector to level 4 and apply changes.
- refactor(rector): set rector level to 4
- refactor(rector): apply level 4
=> refactor(rector): apply level 4

library/classes/Installer.class.php
Run phpstan --level 1 on the installer and fix the found issues.
=> fix(Installer): phpstan level 1

interface/modules/custom_modules/oe-module-weno/src/Services/DownloadWenoPharmacies.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php, rector.php, src/Common/Forms/Types/LocalProviderListType.php
Update rector settings to level 5, and set php version to 8.2, which is the same php version as is in composer.json.
- rector level 5, php 8.2
- rector apply changes
=> refactor(rector): apply level 5

.github/workflows/inferno-test.yml, .github/workflows/js-test.yml, .github/workflows/styling.yml, .github/workflows/test.yml, README.md
=> chore: update readme and ci to nodejs 22

.github/workflows/inferno-test.yml, .github/workflows/js-test.yml, .github/workflows/rector.yml, .github/workflows/styling.yml, .github/workflows/syntax.yml
Fixes #8625
Enable caching for php, node actions
- Enable caching for php, node actions
- Remove redundant storage of result when it's the natural behavior of the shell
- Replace find with git ls-files.
=> ci(actions): enable caching

interface/modules/custom_modules/oe-module-faxsms/library/setup_services.php, interface/modules/zend_modules/module/Carecoordination/config/module.config.php, interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php, phpstan.github.neon, phpstan.local.neon
=> fix: couple phpstan fixes

docker/library/dockers/dev-nginx/Dockerfile, docker/library/dockers/dev-php-fpm-5-6-redis/Dockerfile, docker/library/dockers/dev-php-fpm-5-6/Dockerfile, docker/library/dockers/dev-php-fpm-7-0-redis/Dockerfile, docker/library/dockers/dev-php-fpm-7-0/Dockerfile, docker/library/dockers/dev-php-fpm-7-1-redis/Dockerfile, docker/library/dockers/dev-php-fpm-7-1/Dockerfile, docker/library/dockers/dev-php-fpm-7-2-redis/Dockerfile, docker/library/dockers/dev-php-fpm-7-2/Dockerfile, docker/library/dockers/dev-php-fpm-7-3-redis/Dockerfile, docker/library/dockers/dev-php-fpm-7-3/Dockerfile, docker/library/dockers/dev-php-fpm-7-4-redis/Dockerfile, docker/library/dockers/dev-php-fpm-7-4/Dockerfile, docker/library/dockers/dev-php-fpm-8-0-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-0/Dockerfile, docker/library/dockers/dev-php-fpm-8-1-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-1/Dockerfile, docker/library/dockers/dev-php-fpm-8-2-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-2/Dockerfile, docker/library/dockers/dev-php-fpm-8-3-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-3/Dockerfile, docker/library/dockers/dev-php-fpm-8-4-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-4/Dockerfile, docker/library/dockers/dev-php-fpm-8-5-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-5/Dockerfile, docker/library/dockers/dev-php-fpm/Dockerfile, docker/library/ldap-ssl-certs-keys/easy/Dockerfile, docker/library/ldap-ssl-certs-keys/insane/Dockerfile
Fixes #8686
Add syntax declaration to Dockerfiles.
=> build(Dockerfile): add syntax declaration

interface/patient_tracker/patient_tracker.php
add back parameters to search
Fixes #8699
=> Restore Flow Board Filter

phpstan.github.neon, phpstan.local.neon, src/Common/Logging/EventAuditLogger.php, tests/Tests/Common/Logging/EventAuditLoggerBreakglassTest.php, tests/Tests/Fixtures/EventAuditLoggerFixturesTest.php, tests/Tests/Fixtures/GaclFixtureManager.php, tests/Tests/Fixtures/gacl-breakglass.json, tests/Tests/Unit/Common/Logging/EventAuditLoggerTest.php
Fixes #8678
Adds comprehensive tests for the EventAuditLogger.
The tests are Claude Generated
=> test(EventAuditLogger): comprehensive coverage

interface/billing/print_daysheet_report_num1.php, interface/billing/print_daysheet_report_num2.php, interface/billing/print_daysheet_report_num3.php
Fixes #8716
Remove redundant assignment in switch/case.
=> fix(print_daysheet): redundant assignment

src/Common/Crypto/CryptoGen.php, src/Common/Crypto/CryptoInterface.php
Fixes #8744
Create an interface for CryptoGen to enable future improvements.
=> feat(CryptoInterface): for cryptogen

src/Common/Crypto/CryptoGen.php, tests/Tests/Unit/Common/Crypto/CryptoGenTest.php
Fixes #8762
Wrappers around unstubbable calls in CryptoGen to enable testing
Wrappers around unstubbable calls in CryptoGen to enable testing -- update tests so they pass.
Used Claude to generate the wrappers and tweak the tests.
=> test(CryptoGen): wrappers to enable testing

phpstan.github.neon, phpstan.local.neon, src/Cqm/Qdm/BaseTypes/AbstractType.php, src/Cqm/QrdaControllers/QrdaReportController.php
controller implements zip download for qrda 3 reports rather than store in file system.
Fixes #8783 
fix missing class for previous PR.
=> Wrong file version QRDA III controller

Documentation/EHI_Export/docs/index.html
=> chore: remove 2015 reference for b10

Documentation/EHI_Export/docs/index.html
=> chore: remove 2015 reference for b10 (#8842) for rel-703

library/sql.inc.php, phpstan.github.neon
Fixes #8853
Fixes an issue setting db options when the db connection has not been successfully made.
Move the dbh check to just when it's assigned, before any queries are made.
=> fix(sql.inc.php): check connection when setting

src/Common/Crypto/CryptoGen.php, src/Common/Crypto/KeyVersion.php, tests/Tests/Unit/Common/Crypto/CryptoGenTest.php
=> chore: increment crypto to version 7 and pertinent testing changes

phpstan.github.neon, src/Common/Http/oeHttpRequest.php
Fixes #8473
Fix instance call to static property.
=> fix(oeHttpRequest): client is static

package-lock.json, package.json
Reverts openemr/openemr#8870
It's broken/breaks the DICOM viewer. We need to circle back to get it working.
=> Revert "chore(deps): bump jszip and dwv"

custom/export_labworks.php, custom/export_xml.php, phpstan.github.neon
Fixes #8883 
Rename the global `Add` function so it doesn't conflict with other global `Add` functions.
=> fix(export_labworks): rename Add to avoid conflict

.github/workflows/test.yml
Fixes #8670
Add codecov.io coverage reporting
=> ci(test.yml): codecov reporting

.github/workflows/isolated-tests.yml
Fixes #8895
Add code coverage reporting to codecov to isolated-tests.yml
=> ci(isolated-tests): codecov coverage

.github/workflows/build-dev-php-fpm-docker.yml, .github/workflows/weekly-build-php-fpm-dockers.yml, docker/library/dockers/dev-php-fpm-8-5-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-6-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-6-redis/php.ini, docker/library/dockers/dev-php-fpm-8-6/Dockerfile, docker/library/dockers/dev-php-fpm-8-6/php.ini, docker/library/dockers/dev-php-fpm/Dockerfile
=> chore: prep ci for php 8.5-rc and now 8.6-dev

docker/library/dockers/dev-php-fpm-8-5-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-5/Dockerfile, docker/library/dockers/dev-php-fpm-8-6-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-6/Dockerfile
=> chore: more work on php85 and php86 for ci

docker/library/dockers/dev-php-fpm-8-5-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-5/Dockerfile, docker/library/dockers/dev-php-fpm-8-6-redis/Dockerfile, docker/library/dockers/dev-php-fpm-8-6/Dockerfile
=> chore: even more work on php85 and php86 for ci

ci/nginx_86/docker-compose.yml
=> chore: add php8.6-dev to ci testing

docker/development-insane/README.md, docker/development-insane/docker-compose.yml, docker/library/dockers/dev-nginx/nginx.conf
=> chore: support php 8.6-dev in insane dev environment

gacl/profiler.inc.php, phpstan.github.neon, rector.php
Fixes #9050
Update syntax, removing deprecated while each form.
=> refactor(php): change while each to foreach

interface/main/calendar/index.php, interface/main/main_screen.php, rector.php
Fixes #9052
Apply `SetCookieRector` rule
=> refactor(php): modernize setcookie calls
